const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { html, appSource: source } = require('./helpers/read-index-bundle');
const adminUserRoutesSource = fs.readFileSync(path.join(__dirname, '../server/admin-users-routes.js'), 'utf8');
const coachSidebar = source.match(/<div id="sbCoachView"[\s\S]*?<\/div>\s*<!-- 管理员视角 -->/);
const adminSidebar = source.match(/<div id="sbAdminView">[\s\S]*?<\/div>\s*<\/div>\s*<div class="sb-bottom">/);
assert.ok(coachSidebar, 'coach sidebar should exist');
assert.ok(adminSidebar, 'admin sidebar should exist');
assert.match(html, /id="sidebarHost"/, 'index should only keep the sidebar mount host');
assert.doesNotMatch(html, /id="sbAdminView"|id="sbCoachView"/, 'sidebar markup should live in shared components');
assert.match(source, /function renderSidebarShell\(/, 'sidebar should render from the shared components entry');
assert.match(source, /function normalizeClientPermissionProfile\(/, 'frontend permission helpers should be loaded before account page logic');

function fnBody(name){
  const start = source.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = source.indexOf('\nfunction ', start + 1);
  const nextAsync = source.indexOf('\nasync function ', start + 1);
  const candidates = [nextFunction, nextAsync].filter(i => i !== -1);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return source.slice(start, next === -1 ? source.length : next);
}

assert.doesNotMatch(coachSidebar[0], /goPage\('admin-users',this\)[\s\S]*?账号管理/, 'coach sidebar should not expose account management');
assert.match(adminSidebar[0], /goPage\('admin-users',this\)[\s\S]*?账号管理/, 'admin sidebar should expose account management');
assert.match(source, /goPage\('admin-users',this\)[\s\S]*?账号管理/, 'sidebar should provide account management entry');
assert.match(source, /id="page-admin-users" data-standard-list-shell="admin-users"[\s\S]*function renderStandardToolbarHtml/, 'account page should use the shared toolbar shell');
assert.match(source, /'admin-users':\['campuses','coaches'\]/, 'account page should load campuses and coaches for coach binding');
assert.doesNotMatch(fnBody('globalTopFilterPages'), /'admin-users'/, 'account page should not be hidden by global top filters');
assert.match(source, /function renderStandardSearchHtml\(\{id='',placeholder='搜索姓名、手机号'[\s\S]*key:'admin-users'[\s\S]*search:\{id:'adminUserSearch'/, 'account page should provide the unified search field');
assert.match(source, /<button class="tms-btn tms-btn-primary" onclick="openAdminUserModal\(null\)"/, 'account page should provide add button');
assert.match(source, /function renderStandardTableShellHtml\([\s\S]*key:'admin-users'/, 'account page should use the shared table shell');
assert.match(source, /key:'admin-users'[\s\S]*账号名[\s\S]*姓名[\s\S]*手机号[\s\S]*角色[\s\S]*绑定教练[\s\S]*微信绑定[\s\S]*服务号绑定[\s\S]*状态[\s\S]*权限说明[\s\S]*操作/, 'account table headers should follow the standardized account columns');
assert.match(source, /infoId:'adminUserPagerInfo'/, 'account page should include standard pagination info');
assert.match(source, /pageSizeId:'adminUserPageSize'/, 'account page should include standard page size control');
assert.match(source, /buttonsId:'adminUserPagerBtns'/, 'account page should include standard page buttons');
assert.match(fnBody('renderAdminUsers'), /adminUserTbody/, 'account page should render rows into adminUserTbody');
assert.doesNotMatch(fnBody('getFilteredAdminUsers'), /adminUserMatchesCampus\(u\)|globalDateWithinRange/, 'account rows should not be hidden by global campus or time filters');
assert.match(fnBody('getFilteredAdminUsers'), /u\.id!=='pkgmergeadmin'/, 'account list should hide the package merge test admin account');
assert.match(fnBody('adminUserPhoneText'), /return user\.phone\|\|'-'/, 'empty phone should render as dash');
assert.match(fnBody('setCampus'), /if\(currentPage==='admin-users'\)renderAdminUsers\(\)/, 'campus tab changes should refresh account list');
assert.match(fnBody('renderAdminUsers'), /绑定教练/, 'account rows should show coach binding text');
assert.match(fnBody('renderAdminUsers'), /手机号/, 'account rows should show phone text');
assert.match(fnBody('renderAdminUsers'), /微信绑定/, 'account rows should show wechat binding text');
assert.match(fnBody('renderAdminUsers'), /服务号绑定/, 'account rows should show official account binding text');
assert.doesNotMatch(fnBody('adminUserOfficialAccountText'), /role!=='editor'/, 'admin accounts should also show official account binding status');
assert.match(fnBody('renderAdminUsers'), /openAdminUserDetailDrawer/, 'account rows should open the account drawer');
assert.doesNotMatch(fnBody('renderAdminUsers'), /unbindAdminUserWechat|unbindAdminUserOfficialAccount|openAdminUserModal\('\$\{u\.id\}'\)/, 'account rows should keep only view and status actions');
assert.match(fnBody('renderAdminUsers'), /停用|启用/, 'account rows should expose enable and disable actions');
assert.match(fnBody('renderAdminUsers'), /adminUserEmptyStateHtml\(\)/, 'account empty state should use the standard empty state');
assert.match(fnBody('renderAdminUsers'), /renderAdminUserPagerControls\(total,pages\)/, 'account list should render standard pagination controls');
assert.match(fnBody('loadAdminUsers'), /apiCall\('GET','\/admin\/users'\)/, 'account page should load users from admin api');
assert.match(fnBody('openAdminUserModal'), /openAdminUserDrawerCreate\(\)/, 'account add action should open the shared drawer');
assert.doesNotMatch(fnBody('openAdminUserModal'), /openStandardModal/, 'account add action should no longer use the old modal');
assert.match(fnBody('openAdminUserDetailDrawer'), /openStandardDetailDrawer/, 'account detail should use the global drawer shell');
assert.match(fnBody('openAdminUserDetailDrawer'), /renderDetailDrawerTabs\(adminUserDetailActiveTab,\[\['account','账号信息'\],\['binding','绑定关系'\]\]/, 'account drawer should use account and binding tabs');
assert.match(fnBody('adminUserAccountTabHtml'), /openAdminUserDrawerEdit/, 'account info tab should expose edit action inside drawer');
assert.match(fnBody('adminUserAccountTabHtml'), /账号ID[\s\S]*姓名[\s\S]*手机号[\s\S]*角色[\s\S]*绑定教练[\s\S]*数据范围[\s\S]*当前状态/, 'account view should match edit account fields');
assert.doesNotMatch(fnBody('adminUserAccountTabHtml'), /服务号绑定|约球权限/, 'account info tab should not show service binding or standalone match permission fields');
assert.match(fnBody('adminUserAccountFormCardHtml'), /账号ID[\s\S]*姓名[\s\S]*手机号[\s\S]*角色[\s\S]*绑定教练[\s\S]*数据权限[\s\S]*当前状态/, 'account create and edit should share the same account fields');
assert.doesNotMatch(fnBody('adminUserAccountFormCardHtml'), /au_match_ops|au_match_finance|约球运营|约球财务/, 'match permissions should not render as separate account fields');
assert.doesNotMatch(fnBody('adminUserDataPermissionText'), /约球/, 'data permission display should not append match permission text');
assert.doesNotMatch(fnBody('toggleAdminUserScopeFields'), /role==='editor'[\s\S]*setStandardDropdownValue\('au_dataScope','coach'/, 'coach accounts should be able to select campus scope');
assert.match(fnBody('toggleAdminUserScopeFields'), /wrap\.style\.display=scope==='campus'\?'':'none'/, 'campus selector should open whenever data scope is campus');
assert.match(fnBody('openAdminUserDrawerCreate'), /openStandardDetailDrawer/, 'account create should use the global drawer shell');
assert.match(fnBody('openAdminUserDrawerCreate'), /adminUserAccountFormCardHtml/, 'account create should reuse the shared account form');
assert.match(fnBody('openAdminUserDrawerCreate'), /adminUserPasswordCardHtml\(\{isCreate:true\}\)/, 'account create should put initial password in a separate card');
assert.match(fnBody('adminUserPasswordCardHtml'), /isCreate\?'初始密码':'重置密码'[\s\S]*renderDetailDrawerFormCard\(title,form\)/, 'account password cards should share one helper');
assert.match(fnBody('openAdminUserDrawerEdit'), /adminUserAccountFormCardHtml/, 'account edit should reuse the shared account form');
assert.match(fnBody('openAdminUserDrawerEdit'), /adminUserPasswordCardHtml\(\)/, 'account drawer edit should put password reset in a separate card');
assert.doesNotMatch(fnBody('openAdminUserDrawerEdit'), /const officialBindingRow|服务号绑定|<div class="tms-section-header">约球权限<\/div>/, 'account drawer edit should not show service binding or standalone match permission sections');
assert.match(fnBody('adminUserBindingTabHtml'), /unbindAdminUserWechat[\s\S]*unbindAdminUserOfficialAccount/, 'binding tab should expose unbind actions inside drawer');
assert.doesNotMatch(fnBody('openAdminUserDrawerCreate'), /请用这里的账号ID登录，不是姓名/, 'account create drawer should not force account-id-only wording');
assert.match(fnBody('saveAdminUser'), /phone/, 'account save should submit phone');
assert.match(fnBody('saveAdminUser'), /role:roleValue/, 'account edit should submit the selected role');
assert.match(fnBody('saveAdminUser'), /dataScope/, 'account save should submit data scope');
assert.match(fnBody('saveAdminUser'), /campusIds/, 'account save should submit campus ids');
assert.doesNotMatch(fnBody('saveAdminUser'), /officialAccountOpenId/, 'account save should not submit manual official account openid');
assert.match(fnBody('saveAdminUser'), /matchPermissions/, 'account save should submit match permissions');
assert.match(fnBody('collectAdminUserMatchPermissions'), /\['match_ops','match_finance'\]/, 'match permissions should be enabled for every account by default');
assert.match(fnBody('saveAdminUser'), /\/admin\/create-user/, 'account create should call create-user api');
assert.match(fnBody('saveAdminUser'), /\/admin\/update-user/, 'account edit should call update-user api');
assert.match(fnBody('saveAdminUser'), /账号创建成功 ✓/, 'account create should keep the success toast');
assert.doesNotMatch(fnBody('saveAdminUser'), /请用账号ID/, 'account create success toast should not force account-id wording');
assert.match(fnBody('toggleAdminUserStatus'), /\/admin\/update-user/, 'account status toggle should reuse update-user api');
assert.match(fnBody('toggleAdminUserStatus'), /status/, 'account status toggle should send status field');
assert.match(fnBody('unbindAdminUserWechat'), /clearWechat/, 'wechat unbind should send clearWechat flag');
assert.match(fnBody('unbindAdminUserOfficialAccount'), /clearOfficialAccount/, 'official account unbind should send clearOfficialAccount flag');
assert.match(fnBody('resetAdminUserPassword'), /\/admin\/reset-user-password/, 'password reset should call the admin reset password api');
assert.match(adminUserRoutesSource, /path==='\/admin\/reset-user-password'&&method==='POST'/, 'api should provide admin password reset endpoint');
assert.match(adminUserRoutesSource, /const nextRole=String\(body\.role\|\|u\.role\|\|'editor'\)/, 'api update-user should accept role changes');
assert.doesNotMatch(source, /function defaultLandingPageForUser/, 'admin login flow should no longer force a landing page before shell bootstrap');

console.log('admin users page tests passed');
