const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: html } = require('./helpers/read-index-bundle');
const courseSource = [
  fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'scripts', 'pages', 'products.js'), 'utf8'),
  fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'scripts', 'pages', 'packages.js'), 'utf8')
].join('\n');
const apiSource = fs.readFileSync(path.join(__dirname, '..', 'api', 'index.js'), 'utf8');
const pagesCss = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'pages.css'), 'utf8');
const purchaseSectionStart = html.indexOf('id="page-purchases"');
const purchaseSectionEnd = html.indexOf('id="page-entitlements"', purchaseSectionStart);
const purchaseSection = html.slice(purchaseSectionStart, purchaseSectionEnd === -1 ? html.length : purchaseSectionEnd);

function fnBody(name){
  const start = html.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = html.indexOf('\nfunction ', start + 1);
  const nextAsync = html.indexOf('\nasync function ', start + 1);
  const candidates = [nextFunction, nextAsync].filter(i => i !== -1);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return html.slice(start, next === -1 ? html.length : next);
}

assert.match(html, /<div class="sb-sec">教学中心<\/div>/, 'sidebar should group teaching pages');
assert.match(html, /<div class="sb-sec">场地运营<\/div>/, 'sidebar should group court operation pages');
assert.match(html, /<div class="sb-sec">资源管理<\/div>/, 'sidebar should group resource pages');

assert.match(html, /goPage\('products',this\)[\s\S]*?课程产品/, 'sidebar should keep products page');
assert.match(html, /goPage\('packages',this\)[\s\S]*?售卖课包/, 'sidebar should add packages page');
assert.doesNotMatch(html, /<div class="sb-item" onclick="goPage\('purchases',this\)">[\s\S]*?购买记录<\/div>/, 'sidebar should remove purchases as a standalone first-level nav entry');
assert.match(html, /goPage\('admin-users',this\)[\s\S]*?账号管理/, 'sidebar should add account management page');
assert.doesNotMatch(html, /goPage\('entitlements',this\)[\s\S]*?权益账户/, 'sidebar should hide the old entitlement page entry');

assert.match(html, /id="page-packages"/, 'should have packages page section');
assert.match(html, /id="pkgTimeBandFilterHost"/, 'package page should expose a time band filter');
assert.match(html, /id="pkgCoachFilterHost"/, 'package page should expose a coach filter');
assert.match(html, /id="pkgAudienceFilterHost"/, 'package page should expose an adult/youth filter');
assert.match(html, /id="page-purchases"/, 'should have purchases page section');
assert.match(html, /course-showcase/, 'course product page should use the new showcase container');
assert.match(html, /course-package-showcase/, 'package page should use the new showcase container');
assert.match(html, /product-card-shell/, 'product page should render the gemini-style product cards');
assert.match(html, /package-card-shell/, 'package page should render the gemini-style package cards');
assert.match(html, /function packageSortValue\(/, 'package list should expose a persisted sort value helper');
assert.match(html, /function renderPackages[\s\S]*packageSortValue\(a\)-packageSortValue\(b\)[\s\S]*String\(b\.createdAt\|\|''\)\.localeCompare\(String\(a\.createdAt\|\|''\)\)/, 'package list should sort by persisted package order before falling back to newer records first');
assert.match(fnBody('packageBoardCardHtml'), /draggable="true"[\s\S]*onDragStart="startPackageDrag/, 'package cards should be draggable');
assert.match(html, /async function savePackageOrder\([\s\S]*\/packages\/order/, 'package drag order should save through a dedicated endpoint');
assert.match(apiSource, /path==='\/packages\/order'&&method==='PUT'[\s\S]*sortOrder/, 'package order should have a dedicated backend endpoint');
assert.match(apiSource, /const id=decodeURIComponent\(pkgM\[1\]\)/, 'package update route should decode URL-encoded package ids before reading TableStore');
assert.match(html, /function packageDisplayTitle\([\s\S]*packageCoreClassLabel[\s\S]*课时[\s\S]*packageTimeBandShortLabel/, 'package cards should build titles from structured fields');
assert.match(html, /function packageTimeBandBadgeClass\([\s\S]*黄金[\s\S]*非黄金[\s\S]*全天/, 'package time band badge should expose three visual states');
assert.match(fnBody('packageBoardCardHtml'), /package-sales-title-row[\s\S]*packageTimeBandBadgeHtml\(p\)/, 'package cards should show the time band tag next to the title');
assert.match(html, /package-card-meta[\s\S]*packageCreatedDate\(p\)[\s\S]*package-order-link/, 'package cards should keep created date and order link without labels');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /\$\{esc\(p\.id\|\|'-'\)\}/, 'package cards should not render the full raw package id');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /packageDisplayShortId\(p\)|package-meta-id/, 'package cards should not show package id in the footer');
assert.doesNotMatch(html, /package-card-meta[^`]*创建/, 'package card footer should not show the created label');
assert.doesNotMatch(html, /showcase-kv-label">创建时间/, 'package cards should not show created time as a normal field row');
assert.match(html, /归属教练[\s\S]*可用校区[\s\S]*可用时段/, 'package card should show owner coach, campus, and time rules');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /活动期|使用期/, 'package cards should not show sale or usage ranges');
assert.doesNotMatch(fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'scripts', 'pages', 'purchases.js'), 'utf8'), /主归属教练/, 'purchase records should use 归属教练 wording');
assert.match(html, /归属教练[\s\S]*可上课教练/, 'purchase records should expose owner coach and teachable coaches');
assert.match(html, /系统价格[\s\S]*实收金额[\s\S]*改价原因/, 'purchase modal should expose system price, actual paid amount and override reason');
assert.doesNotMatch(html, /tms-pill-tabs/, 'sidebar navigation should replace the demo top tabs');
assert.doesNotMatch(html, /const t=\{students:[\s\S]*?\n\s*const t=\{students:/, 'page title map should not be declared twice after merge');
assert.match(html, /workbench:'工作台'/, 'page title map should include coach workbench');
assert.doesNotMatch(html, /function syncPackageProductMeta/, 'package modal should not sync product metadata anymore');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_productId|课程产品|课程类型跟随课程产品/, 'package modal should no longer require course product selection');
assert.match(fnBody('openPackageModal'), /基础属性[\s\S]*学员类型[\s\S]*课程类型[\s\S]*上课人数[\s\S]*状态[\s\S]*规格与价格[\s\S]*课时[\s\S]*价格[\s\S]*上课时间与效期[\s\S]*活动时间[\s\S]*可用时间[\s\S]*时段类型[\s\S]*可用时段[\s\S]*教练和场地[\s\S]*归属教练[\s\S]*可用校区[\s\S]*可上课教练[\s\S]*备注/, 'package modal should follow the standardized package creation layout');
assert.doesNotMatch(fnBody('openPackageModal'), /有效天数|pkg_validDays/, 'package modal should hide valid days');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_type'/, 'package modal should allow direct course type selection');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_audience'/, 'package modal should allow adult or youth selection');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_ownerCoach'/, 'package modal should allow direct main coach selection');
assert.match(fnBody('openPackageModal'), /pkg_experienceType/, 'package modal should expose a second-level selector for experience courses');
assert.match(fnBody('openPackageModal'), /pkg_smallClassType/, 'package modal should expose a second-level selector for small group packages');
assert.match(courseSource, /function applySmallClassPackagePreset\(/, 'package modal should define small group package presets');
assert.match(fnBody('applySmallClassPackagePreset'), /bootcamp:\{price:1999,lessons:10,timeBand:'黄金时段',maxStudents:'4'\}/, 'small group bootcamp preset should default to 10 lessons');
assert.match(fnBody('openPackageModal'), /data-lessons="10"[\s\S]*10课时[\s\S]*data-lessons="20"[\s\S]*20课时/, 'package modal should expose 10 and 20 lesson shortcuts');
assert.doesNotMatch(fnBody('openPackageModal'), /data-lessons="6"[\s\S]*6课时/, 'package modal should not force six lesson packages');
assert.match(fnBody('savePackage'), /freeAbsenceLimit[\s\S]*smallClassType==='bootcamp'\?1:0/, 'small group bootcamp package should persist one free absence');
assert.match(fnBody('packageExperienceTypeLabel'), /p=p\|\|\{\}/, 'package experience label should tolerate creating a package without existing row data');
assert.match(fnBody('openProductModal'), /p_experienceType/, 'course product modal should expose a second-level selector for experience courses');
assert.match(fnBody('saveProduct'), /experienceType:/, 'course product save should persist the selected experience subtype');
assert.match(fnBody('savePackage'), /const audience=document\.getElementById\('pkg_audience'\)\.value[\s\S]*const data=\{[\s\S]*audience,type:audience/, 'package save should persist the selected adult or youth type');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_type'/, 'package modal course type should use the shared custom dropdown');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_maxStudents'/, 'package modal class size should use the shared custom dropdown');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_timeBand'/, 'package modal time band should use the shared custom dropdown');
assert.doesNotMatch(fnBody('openPackageModal'), /适用日期|pkg_timeScope/, 'package modal should not expose applicable-day selectors');
assert.match(html, /function courseSurchargePayMethodOptions\(\)[\s\S]*payMethodOptions\(\)\.filter/, 'schedule surcharge payment should reuse shared payment methods');
assert.match(fnBody('courseSurchargePayMethodOptions'), /\['储值扣款','课包划扣','大众点评券码','抖音券码','其他'\]\.includes\(option\.value\)/, 'schedule surcharge payment should hide non-cash payment methods');
assert.match(fnBody('openScheduleModal'), /renderCourtDropdownHtml\('sch_fieldFeePayMethod','支付方式',courseSurchargePayMethodOptions\(\)/, 'schedule surcharge field should use filtered shared payment methods');
assert.match(fnBody('openScheduleModal'), /schedule-settlement-row[\s\S]*课程类型[\s\S]*结算方式[\s\S]*扣减课包/, 'schedule modal should order course type, settlement type, then package deduction');
assert.match(fnBody('openScheduleModal'), /schedule-course-type-item[\s\S]*schedule-settlement-type-item[\s\S]*schedule-entitlement-item/, 'schedule modal should give course and settlement compact columns and package a wide column');
assert.match(fnBody('openScheduleModal'), /schedule-field-fee-section[\s\S]*schedule-field-fee-main-row[\s\S]*是否收补差[\s\S]*补差金额[\s\S]*支付方式[\s\S]*schedule-field-fee-note-row[\s\S]*补差说明/, 'schedule surcharge fields should split main fields and note into separate rows');
assert.match(fnBody('openScheduleModal'), /textarea class="finput tms-form-control schedule-field-fee-note" id="sch_fieldFeeNote"/, 'schedule surcharge note should use a readable full-width textarea');
assert.match(pagesCss, /schedule-course-type-item[\s\S]*flex:0 0 120px[\s\S]*max-width:120px/, 'schedule modal course type should use a compact 120px column');
assert.match(pagesCss, /schedule-settlement-type-item[\s\S]*flex:0 0 120px[\s\S]*max-width:120px/, 'schedule modal settlement type should use a compact 120px column');
assert.match(pagesCss, /schedule-entitlement-item[\s\S]*flex:1 1 0[\s\S]*min-width:0[\s\S]*max-width:100%/, 'schedule modal package deduction should take the remaining width without overflowing');
assert.match(pagesCss, /schedule-field-fee-note[\s\S]*min-height:54px/, 'schedule surcharge note should have readable height');
assert.match(html, /packageTimeBandPresetWindows[\s\S]*工作日[\s\S]*周六日/, 'package modal should derive applicable days from time band presets');
assert.match(fnBody('applyPackageTimeBandPreset'), /pkg_timeStart\$\{suffix\}[\s\S]*getScheduleTimeOptions/, 'package modal start time should use the schedule custom time picker');
assert.match(fnBody('applyPackageTimeBandPreset'), /pkg_timeEnd\$\{suffix\}[\s\S]*getScheduleTimeOptions/, 'package modal end time should use the schedule custom time picker');
assert.doesNotMatch(fnBody('openPackageModal'), /type="time"/, 'package modal should not use native time inputs');
assert.doesNotMatch(fnBody('packageTimeScopeOptions'), /value:'custom'|自定义/, 'package time window scope should not include custom');
assert.match(fnBody('openPackageModal'), /tms-checkbox-matrix purchase-coach-picker package-coach-picker[\s\S]*packageCoachChecks/, 'package allowed coaches should use purchase modal checkbox matrix style');
assert.match(fnBody('packageCoachChecks'), /pkg-coach-cb/, 'package allowed coach checks should keep the save selector class');
assert.match(html, /function applyPackageTimeBandPreset/, 'package modal should apply simple default windows for time band presets');
assert.match(html, /function setPackageLessonShortcut\(/, 'package modal should provide lesson shortcuts');
assert.match(html, /10课时[\s\S]*20课时/, 'package modal should expose lesson shortcut chips');
assert.doesNotMatch(html, /50课时/, 'package modal should leave non-standard lesson counts to manual input');
assert.match(html, /黄金时段'[\s\S]*16:00[\s\S]*22:00[\s\S]*09:00[\s\S]*22:00/, 'prime preset should be weekday evening plus weekend daytime');
assert.match(html, /非黄金时段'[\s\S]*09:00[\s\S]*16:00/, 'non-prime preset should be weekday daytime');
assert.match(fnBody('savePackage'), /presetWindows\.map[\s\S]*daysOfWeek:preset\.daysOfWeek/, 'package save should persist preset applicable days');
assert.doesNotMatch(fnBody('savePackage'), /windowRow|secondWindow/, 'package save should not depend on modal-local time window variables');
assert.doesNotMatch(fnBody('savePackage'), /pkg_validDays/, 'package save should not read hidden valid days field');
assert.match(fnBody('savePackage'), /experienceType:/, 'package save should persist the selected experience subtype');
assert.match(fnBody('savePackage'), /validDays:\s*packagePersistedValidDays/, 'package save should preserve valid days without showing it');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_type'[\s\S]{0,120}\$\{locked\?' disabled'/, 'sold package course type should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_ownerCoach'[\s\S]{0,160}pointer-events:none/, 'sold package owner coach should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /id="pkg_timeBand"[\s\S]{0,120}\$\{locked\?' disabled'/, 'sold package time band should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /id="pkg_timeStart"[\s\S]{0,120}\$\{locked\?' readonly'/, 'sold package available time should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_saleStartDate_btn[\s\S]{0,180}\$\{locked\?' disabled'/, 'sold package sale start date should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_usageStartDate_btn[\s\S]{0,180}\$\{locked\?' disabled'/, 'sold package usage start date should stay editable');
assert.match(html, /function productHasReferences/, 'product modal should know whether product is referenced');
assert.match(html, /function packageHasPurchases/, 'package modal should know whether package is sold');
assert.match(html, /onclick="openPackageMergeModal\(\)"[\s\S]*合并课包/, 'package page should expose a package merge entry');
assert.match(html, /function mergePackage\(\)[\s\S]*\/packages\/merge/, 'package merge should call the dedicated merge endpoint');
assert.match(html, /openPackageMergeModal[\s\S]*renderCourtDropdownHtml\('pkg_merge_master'[\s\S]*renderCourtDropdownHtml\('pkg_merge_source'/, 'package merge modal should use the shared custom dropdown');
assert.match(html, /setCourtModalFrame\('合并课包'[\s\S]*modal-merge-package/, 'package merge modal should use the dedicated overflow class');
assert.doesNotMatch(html, /<select class="fselect tms-form-control" id="pkg_merge_/, 'package merge modal should not use native select controls');
assert.doesNotMatch(html, /只支持规则一致的课包合并。并入课包会在后台隐藏，购买记录和课包余额会显示为保留课包。/, 'package merge notice should remove the unreadable yellow hint');
assert.doesNotMatch(html, /课程产品定义上什么课；售卖课包定义怎么卖、什么时候能买、什么时候能用。创建售卖课包时会直接绑定一个课程产品。/, 'package page should remove the long banner description');
assert.doesNotMatch(html, /id="page-packages"[\s\S]*搜索课包名称、课程产品、时段/, 'package search should no longer mention course products');
assert.match(html, /openPackageModal\(null\)">＋ 创建课包/, 'package page primary action should say create package');
assert.match(html, /setCourtModalFrame\(id\?'编辑课包':'创建课包'/, 'package modal title should use create package copy');
assert.match(fnBody('openPackageModal'), /deactivatePackage\('\$\{p\.id\}'\)[\s\S]*下架/, 'package edit modal should use deactivate copy');
assert.doesNotMatch(html, /id="page-purchases"[\s\S]*搜索学员、课包、课程产品/, 'purchase search should no longer mention course products');
assert.doesNotMatch(html, /id="page-packages"[\s\S]*还没有课程产品|id="page-packages"[\s\S]*先创建课程产品，再基于课程产品创建售卖课包。/, 'package page should not require course products to create a package');
assert.doesNotMatch(html, /关联产品:/, 'package cards should not show linked product subtitle');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /showcase-status-tag[\s\S]*启用/, 'package cards should not show the redundant active status tag');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /packageCardTags/, 'package cards should not show duplicate course type tags');
assert.match(fnBody('packageStatusBadge'), /packageListStatusValue[\s\S]*已停售/, 'package stopped sale state should render from package status');
assert.match(fnBody('renderPackages'), /document\.getElementById\('pkgTimeBandFilter'\)/, 'package cards should filter by time band');
assert.match(fnBody('renderPackages'), /document\.getElementById\('pkgCoachFilter'\)/, 'package cards should filter by coach');
assert.match(fnBody('renderPackages'), /document\.getElementById\('pkgAudienceFilter'\)/, 'package cards should filter by adult or youth');
assert.match(fnBody('renderPackages'), /packageAudienceLabelFromText\(\[p\.audience,p\.type,p\.productName,p\.name,p\.packageName,p\.notes\]\)!==af/, 'package audience filter should use the structured audience label');
assert.match(html, /function packageBoardColumns\([\s\S]*青少年 · 私教课[\s\S]*青少年 · 小班课[\s\S]*成人 · 私教课[\s\S]*成人 · 小班课/, 'package board should render the four agreed teaching columns');
assert.match(html, /function packageBoardColumnKey\([\s\S]*小班体验课[\s\S]*小班课[\s\S]*私教课[\s\S]*other/, 'package board should classify experience packages by private or small-group subtype and keep an other fallback');
assert.match(fnBody('renderPackages'), /package-board-column[\s\S]*package-board-title[\s\S]*package-board-count[\s\S]*packageBoardCardHtml/, 'package page should render a Notion-style board with column counts and package cards');
assert.match(fnBody('buildCampusTabs'), /currentPage==='packages'[\s\S]*renderPackageTopFilters/, 'package page should reuse the coach ops top campus dropdown');
assert.match(html, /function selectPackageTopCampus\([\s\S]*refreshPackageTopFilters\(\)[\s\S]*renderPackages\(\)[\s\S]*closeCourtTopDropdowns\(\)/, 'package top campus dropdown should refresh label and package board');
assert.match(fnBody('dropPackageCard'), /packageBoardColumnKey\(dragged\)!==packageBoardColumnKey\(target\)[\s\S]*return/, 'package drag sorting should stay within the same board column');
assert.match(fnBody('syncPackageFilterOptions'), /const typeOptions=withStandardFilterCounts[\s\S]*packageMatchesCourseType/, 'package type filter should show per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /const audienceOptions=withStandardFilterCounts[\s\S]*packageMatchesAudience/, 'package audience filter should show per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /const coachOptions=withStandardFilterCounts[\s\S]*packageMatchesCoach/, 'package coach filter should show per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /const statusOptions=withStandardFilterCounts[\s\S]*packageMatchesStatus/, 'package status filter should show per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /const timeBandOptions=withStandardFilterCounts[\s\S]*packageMatchesTimeBand/, 'package time-band filter should show per-option package counts');
assert.match(fnBody('packageBoardCardHtml'), /package-rule-line[\s\S]*packageRuleIcon[\s\S]*package-rule-tooltip/, 'package cards should show icon rules with hover tooltip');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /packageRuleIcon\('time'\)/, 'package cards should move time band out of the rules area');
assert.match(fnBody('packageBoardCardHtml'), /package-order-link[\s\S]*package-order-chevron/, 'package order count should show a hover chevron affordance');
assert.match(fnBody('packageBoardCardHtml'), /deactivatePackage\('\$\{p\.id\}'/, 'package card should use deactivate instead of delete');
assert.match(html, /currentPage==='packages'\)renderPackages\(\)/, 'global campus tabs should refresh packages page');
assert.match(html, /campusTabs'\)\.style\.display=\[[^\]]*'packages'/, 'global campus tabs should show on packages page');
assert.doesNotMatch(html, /查看课程产品/, 'package toolbar should remove the product shortcut button');
assert.match(html, /价格、课时、人数、校区和可上课教练已锁定/, 'locked core fields should show operator-facing hint');
assert.match(html, /function openPurchaseDetailModal/, 'purchase page should have detail modal');
assert.match(html, /function openPurchaseEditModal/, 'purchase page should have edit modal');
assert.match(fnBody('openPurchaseEditModal'), /packages\.filter\(pkg=>\(pkg\.status!=='inactive'&&pkg\.status!=='merged'\)\|\|pkg\.id===p\.packageId\)/, 'purchase edit package picker should hide merged packages except the current saved package');
assert.match(html, /function savePurchaseEdit/, 'purchase page should save purchase edits');
assert.match(html, /function openPurchaseModal/, 'purchase page should provide the unified purchase modal');
assert.match(fnBody('openPurchaseModal'), /packages\.filter\(p=>p\.status!=='inactive'&&p\.status!=='merged'\)/, 'purchase create package picker should hide merged packages');
assert.match(html, /function purchasePackagePickerLabel/, 'purchase package picker should have a dedicated display label');
assert.match(fnBody('purchasePackagePickerLabel'), /standardPackageLabel\(p,true\)[\s\S]*Number\(p\.price\)[\s\S]*\$\{price\}元[\s\S]*coachName\(p\.ownerCoach\)/, 'purchase package picker label should include package price and bound owner coach');
assert.match(fnBody('openPurchaseModal'), /label:purchasePackagePickerLabel\(p\)/, 'purchase create package picker should show price and bound owner coach');
assert.match(fnBody('openPurchaseEditModal'), /label:purchasePackagePickerLabel\(pkg\)/, 'purchase edit package picker should show price and bound owner coach');
assert.match(fnBody('refreshPurchaseFilters'), /label:purchasePackagePickerLabel\(p\)/, 'purchase record package filter should show price and owner coach');
assert.match(html, /function purchaseStudentPickerHtml\(/, 'purchase modal should expose a searchable student picker helper');
assert.match(html, /function selectPurchaseStudent\(/, 'purchase modal should allow selecting a student from search results');
assert.match(html, /id="pur_studentSearch"/, 'purchase modal should provide a student search input');
assert.match(html, /id="purchaseSaveBtn"[\s\S]*onclick="savePurchase\(\)"/, 'purchase create save button should have a stable id used by the save handler');
assert.match(html, /id="purchaseEditSaveBtn"[\s\S]*onclick="savePurchaseEdit/, 'purchase edit save button should have a stable id used by the edit save handler');
assert.doesNotMatch(fnBody('savePurchase'), /document\.querySelector\('\.btn-save'\)/, 'purchase create save should not depend on the legacy btn-save class');
assert.doesNotMatch(fnBody('savePurchaseEdit'), /document\.querySelector\('\.btn-save'\)/, 'purchase edit save should not depend on the legacy btn-save class');
assert.match(html, /function getFilteredPurchases[\s\S]*String\(b\.purchaseDate\|\|b\.createdAt\|\|''\)\.localeCompare\(String\(a\.purchaseDate\|\|a\.createdAt\|\|''\)\)/, 'purchase list should sort newer payment dates first');
assert.match(html, /function isMeaningfulPurchaseRecord/, 'purchase list should filter worthless empty purchase rows');
assert.match(fnBody('getFilteredPurchases'), /isMeaningfulPurchaseRecord\(p\)/, 'purchase filters should skip worthless empty rows before rendering');
assert.match(html, /function packagePurchaseCount/, 'package card should calculate purchase order count');
assert.match(fnBody('purchaseMatchesPackage'), /purchaseIdsByEntitlement[\s\S]*String\(p\.packageId\|\|''\)===String\(packageId\)/, 'package order count should use exact package id and entitlement-linked purchases');
assert.doesNotMatch(fnBody('packagePurchaseCount'), /packageName|productName|originalPackageName/, 'package order count should not count by package or product names');
assert.match(html, /function purchaseMatchesPackage\(/, 'purchase filtering should share the package matching rule used by package order counts');
assert.match(fnBody('getFilteredPurchases'), /purchaseMatchesPackage\(p,packageId\)/, 'purchase package filter should include the same purchases counted on package cards');
assert.match(fnBody('getFilteredPurchases'), /purchaseMatchesCampus\(p,campus\)/, 'purchase filters should follow the top campus selector');
assert.match(fnBody('getFilteredPurchases'), /activePurchaseDateRange\(\)[\s\S]*purchaseDateWithinRange/, 'purchase filters should follow the top time selector');
assert.match(html, /let purPackageFilterValue=''/, 'purchase package filter should keep a page-level value before the dropdown exists');
assert.match(html, /let purDateRangeFilterValue='全部'/, 'purchase page should keep a top time filter value');
assert.match(html, /function renderPurchaseTopFilters\([\s\S]*purchaseTopCampus[\s\S]*purchaseTopDate/, 'purchase page should render top campus and time filters');
assert.match(fnBody('buildCampusTabs'), /currentPage==='purchases'[\s\S]*renderPurchaseTopFilters/, 'purchase page should show top campus and time filters');
assert.match(html, /function selectPurchaseTopCampus\([\s\S]*refreshPurchaseTopFilters\(\)[\s\S]*renderPurchases\(\)/, 'purchase top campus selector should refresh orders');
assert.match(html, /function onPurchaseDateRangeFilterChange\([\s\S]*purDateRangeFilterValue=value[\s\S]*renderPurchases\(\)/, 'purchase top time selector should refresh orders');
assert.match(fnBody('getFilteredPurchases'), /purchaseSelectedPackageFilter\(\)/, 'purchase filtering should not depend only on the rendered dropdown input');
assert.match(fnBody('focusPurchaseByPackage'), /purPackageFilterValue=String\(packageId\|\|''\)[\s\S]*clearPurchasePageFiltersForPackageFocus\(\)[\s\S]*goPage\('purchases'/, 'package order drilldown should set the package filter before navigating');
assert.match(fnBody('renderPackages'), /const courseType=normalizeCourseType\(p\.courseType\)/, 'package card should normalize legacy course type labels');
assert.match(html, /function packageCoreClassLabel\([\s\S]*体验课[\s\S]*experienceType[\s\S]*私教体验课[\s\S]*小班体验课/, 'shared package label should show both experience-course names');
assert.match(html, /const PAY_METHODS=\['微信','支付宝','现金','转账','大众点评券码','抖音券码','其他'\]/, 'package purchase pay method should use the shared pay method source with coupon codes');
assert.match(fnBody('openPurchaseModal'), /PAY_METHODS\.map/, 'purchase create modal should use shared pay methods');
assert.match(fnBody('openPurchaseEditModal'), /PAY_METHODS\.map/, 'purchase edit modal should use shared pay methods');
assert.match(fnBody('packageBoardCardHtml'), /\$\{packagePurchaseCount\(p\.id\)\} 笔订单/, 'package card order button should show order count');
assert.match(pagesCss, /#page-packages \.course-package-showcase \.tms-search-wrapper\{width:280px/, 'package search should use 280px width');
assert.match(pagesCss, /#pkgTypeFilterHost \.tms-dropdown:not\(\.has-value\) \.tms-dropdown-display[\s\S]*width:60px/, 'package type filter should default to 60px');
assert.match(pagesCss, /#pkgCoachFilterHost \.tms-dropdown:not\(\.has-value\) \.tms-dropdown-display[\s\S]*width:60px/, 'package coach filter should default to 60px');
assert.match(pagesCss, /#pkgStatusFilterHost \.tms-dropdown:not\(\.has-value\) \.tms-dropdown-display[\s\S]*width:60px/, 'package status filter should default to 60px');
assert.match(pagesCss, /#pkgTimeBandFilterHost \.tms-dropdown:not\(\.has-value\) \.tms-dropdown-display[\s\S]*width:60px/, 'package time band filter should default to 60px');
assert.match(pagesCss, /package-board-column\{[^}]*border:1px solid rgba\(255,255,255,\.05\)[^}]*border-radius:12px[^}]*background:rgba\(0,0,0,\.05\)[^}]*padding:12px/, 'package board columns should use the subtle dark slot style');
assert.match(pagesCss, /package-board-title\{[^}]*color:#FFFFFF[^}]*font-size:15px[^}]*font-weight:600[^}]*letter-spacing:\.025em/, 'package board title should use white semibold tracking');
assert.match(pagesCss, /package-board-count\{[^}]*background:rgba\(255,255,255,\.2\)[^}]*color:#FFFFFF[^}]*font-size:12px[^}]*font-weight:400/, 'package board count should use white 12px regular text');
assert.match(pagesCss, /package-card-shell\{[^}]*background:#FFFFFF[^}]*border-radius:12px[^}]*box-shadow:0 1px 2px 0 rgba\(0,0,0,\.05\)/, 'package cards should use white rounded shadow-sm style');
assert.match(pagesCss, /package-card-shell\.is-inactive\{[^}]*opacity:\.9[^}]*border-color:#F3F4F6/, 'inactive package cards should be visually de-emphasized');
assert.match(pagesCss, /package-sales-card-body\{gap:12px[\s\S]*padding:6px/, 'package cards should use 6px internal spacing');
assert.match(pagesCss, /package-sales-subtitle\{[^}]*font-size:11px/, 'package audience and lesson text should use 11px');
assert.match(pagesCss, /package-rule-line\{[^}]*font-size:11px/, 'package campus and coach text should use 11px');
assert.match(pagesCss, /package-sales-footer \.showcase-action-btn\{[^}]*font-size:11px/, 'package edit and deactivate buttons should use 11px');
assert.match(pagesCss, /package-card-meta\{[^}]*font-size:10px/, 'package created date and order count should use 10px');
assert.match(pagesCss, /package-time-band-badge\{[^}]*border-radius:6px[^}]*font-size:10px[^}]*font-weight:500/, 'package time band tag should use 10px medium rounded style');
assert.match(pagesCss, /package-time-band-badge\.is-prime\{background:#FEF9E7;color:#D4AF37;border-color:#FBEBA7/, 'package prime tag should use the gold design');
assert.match(pagesCss, /package-time-band-badge\.is-offpeak\{background:#F3F4F6;color:#6B7280;border-color:#E5E7EB/, 'package off-peak tag should use the gray design');
assert.match(pagesCss, /package-time-band-badge\.is-all\{background:#E6F0FA;color:#4A90E2/, 'package all-day tag should use the blue design');
assert.match(fnBody('packageTimeBandBadgeHtml'), /package-time-band-crown[\s\S]*packageTimeBandBadgeClass/, 'prime package badge should include a small crown icon');
assert.match(pagesCss, /package-status-badge\{[^}]*border:1px solid transparent[^}]*font-size:11px[^}]*font-weight:500/, 'package sale status should use 11px medium rounded style');
assert.match(pagesCss, /package-status-badge\.is-on\{background:#F0FDF4;color:#16A34A;border-color:#DCFCE7/, 'active package status should use green badge styling');
assert.match(pagesCss, /package-status-badge\.is-off\{background:#F9FAFB;color:#9CA3AF;border-color:#E5E7EB/, 'inactive package status should use gray badge styling');
assert.match(pagesCss, /package-sales-footer\{[^}]*justify-content:space-between[^}]*border-top:1px dashed #E5E7EB[^}]*padding:8px 12px/, 'package footer should use dashed divider and two-side alignment');
assert.match(pagesCss, /package-sales-title\{font-size:13px[^}]*font-weight:700[^}]*color:#111827/, 'package title should use 13px bold gray-900');
assert.match(pagesCss, /package-sales-price\{[^}]*color:#E87A5D[^}]*letter-spacing:-\.025em/, 'package price should use brand orange-red and tight tracking');
assert.match(pagesCss, /package-card-shell\.is-inactive \.package-sales-price\{color:#9CA3AF/, 'inactive package price should be gray');
assert.match(pagesCss, /package-sales-core\{[^}]*align-items:center/, 'package price and rule block should vertically align in the middle');
assert.match(pagesCss, /package-sales-footer \.showcase-action-btn\{[^}]*color:#4B5563[^}]*border:1px solid #E5E7EB[^}]*border-radius:4px/, 'package edit button should use gray ghost styling');
assert.match(pagesCss, /package-sales-footer \.showcase-action-btn\.is-danger\{[^}]*color:#EF4444[^}]*border-color:#FEE2E2/, 'package deactivate button should use red ghost styling');
assert.doesNotMatch(purchaseSection, /导出/, 'purchase page should remove export button');
assert.doesNotMatch(purchaseSection, /导入/, 'purchase page should remove import button');
assert.doesNotMatch(purchaseSection, /purDateFrom/, 'purchase page should remove start date filter');
assert.doesNotMatch(purchaseSection, /purDateTo/, 'purchase page should remove end date filter');
assert.match(html, /function openPurchaseModal[\s\S]*支付方式[\s\S]*margin-bottom:0[\s\S]*可上课教练/, 'purchase modal should put pay method and allowed coach fields on separate rows to avoid layout overlap');
assert.match(html, /＋ 课包购买/, 'purchase page should expose a direct package purchase entry button');
assert.match(html, /<th style="width:100px;padding-left:20px">支付日期<\/th><th style="width:80px">学员<\/th><th style="width:110px">课包<\/th><th style="width:90px">实收<\/th><th style="width:105px">余额<\/th><th style="width:80px">状态<\/th><th style="width:95px">归属教练<\/th><th style="width:90px">支付方式<\/th>/, 'purchase table should narrow student and package columns');
assert.doesNotMatch(html, /购买记录用于查账和追溯/, 'purchase page should remove the long audit explanation');
assert.doesNotMatch(fnBody('purchasePackageListLabel'), /replace\(\s*\/\^1v\\d私教课/, 'purchase package column should keep the 1v1/1v2 prefix');
assert.match(fnBody('purchasePackageListLabel'), /replace\([^)]*已停售/, 'purchase package column should only remove stopped-sale copy from the package label');
assert.doesNotMatch(html, /先选择学员[\s\S]*下一步/, 'purchase modal should not require a separate first-step student gate');
assert.match(html, /购买时规则快照/, 'purchase detail should show package snapshot');
assert.match(html, /系统价格[\s\S]*成交金额[\s\S]*改价原因/, 'purchase detail should show price snapshot fields');
assert.match(html, /支付日期[\s\S]*系统录入时间/, 'purchase detail should show business date and system recorded time');
assert.match(html, /function openPurchaseVoidModal/, 'purchase page should use dedicated void modal');
assert.match(html, /function voidPurchase/, 'purchase page should send void reason');
assert.match(html, /作废原因/, 'void modal should require reason');
assert.match(html, /function resolveUniqueStudentIdByText/, 'purchase import should resolve students uniquely');
assert.match(html, /function resolveUniquePackageIdByText/, 'purchase import should resolve packages uniquely');
assert.match(html, /匹配到多个/, 'purchase import should warn duplicate matches');
assert.doesNotMatch(html, /真正消课的是课包余额/, 'purchase page should remove the old package balance explanation');
assert.match(html, /私教课/, 'course pages should expose 私教课 as a fixed type');
assert.match(html, /体验课/, 'course pages should expose 体验课 as a fixed type');
assert.match(html, /训练营/, 'course pages should expose 训练营 as a fixed type');
assert.match(html, /大师课/, 'course pages should expose 大师课 as a fixed type');
assert.doesNotMatch(html, /课程性质/, 'course pages should not mention the removed 课程性质 field');
assert.doesNotMatch(courseSource, /正式课/, 'course pages should not keep the old 正式课 wording');
assert.doesNotMatch(courseSource, /半私教课/, 'course pages should not show the old half-private lesson wording');

console.log('course management nav tests passed');
