const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: html } = require('./helpers/read-index-bundle');
const pagesCss = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'pages.css'), 'utf8');
const tablesCss = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'components', 'tables.css'), 'utf8');

function fnBody(name){
  const start = html.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const next = html.indexOf('\nfunction ', start + 1);
  return html.slice(start, next === -1 ? html.length : next);
}

assert.match(fnBody('scheduleTimeRangeControls'), /refreshScheduleTimeDerivedFields/, 'schedule time range controls should refresh lesson hours when date or time changes');
assert.match(fnBody('renderSchedule'), /scheduleRepeatDisplayText\(s\)/, 'schedule table should expose repeat status beside course type');
assert.match(fnBody('toggleStandardDropdown'), /const container=dropdown\.closest\('\.mbody'\)/, 'dropdown opening direction should account for modal body clipping');
assert.match(fnBody('toggleStandardDropdown'), /containerRect\.bottom/, 'dropdown should compare available space against the modal scroll body');
assert.match(fnBody('toggleStandardDropdown'), /spaceBelow<menuHeight\+12&&spaceAbove>spaceBelow/, 'dropdown should open upward when modal space below is too small');
assert.match(pagesCss, /\.tms-stats-row\s*\{/, 'court page should define scoped tms stats styles');
assert.match(tablesCss, /\.tms-table-card\s*\{/, 'court page should use shared table card styles');
assert.match(pagesCss, /\.tms-mini-bar\s*\{/, 'court page should define scoped tms mini bar styles');
assert.match(pagesCss, /\.tms-record-add-box\s*\{/, 'court page should define scoped modal form layout styles');
assert.match(pagesCss, /\.tms-toolbar\s*\{/, 'court page should define scoped toolbar styles');
assert.match(pagesCss, /\.tms-pagination\s*\{/, 'court page should define scoped pagination styles');
assert.match(fnBody('renderCourtStatsCards'), /document\.getElementById\('courtStatsRow'\)/, 'court page should use the standard stats row host');
assert.match(html, /<div class="tms-table-card">[\s\S]*<div class="tms-table-wrapper">[\s\S]*<table class="tms-table">/, 'court page should use the upgraded tms table wrapper');
assert.match(html, /姓名[\s\S]*手机号[\s\S]*校区[\s\S]*账户类型[\s\S]*会员类型[\s\S]*会员余额[\s\S]*最近订场[\s\S]*会员订场[\s\S]*累计订场[\s\S]*累计消费[\s\S]*跟进人[\s\S]*储值态度[\s\S]*备注[\s\S]*操作/, 'court table should use the standardized booking account columns in the expected order');
assert.doesNotMatch(html, /账户状态|熟悉程序/, 'court table should remove old account status and familiarity columns');
assert.doesNotMatch(html, /label:'处置态度'/, 'court table should not keep the old disposition attitude label');
assert.match(html, /courtAccountTypeFilter/, 'court toolbar should provide account type filter');
assert.match(html, /courtOwnerFilter/, 'court toolbar should provide owner filter');
assert.match(html, /courtMoreActions/, 'court toolbar should provide more actions menu');
assert.match(html, /批量选择[\s\S]*导入CSV[\s\S]*财务迁移预览[\s\S]*备份/, 'court more actions should include batch select, import, finance migration preview, and backup');
assert.doesNotMatch(html, /courtMoreActionValue_dropdown[\s\S]*class="tms-dropdown-item[^"]*">更多操作</, 'court more actions menu should not include a redundant self option');
assert.match(html, /data-court-sort="lastBookingDate"[\s\S]*最近订场/, 'court table should support sorting by latest booking date');
assert.match(html, /data-court-sort="memberBookingCount"[\s\S]*会员订场/, 'court table should support sorting by member booking count');
assert.match(html, /data-court-sort="bookingCount"[\s\S]*累计订场/, 'court table should support sorting by booking count');
assert.match(html, /data-court-sort="bookingAmount"[\s\S]*累计消费/, 'court table should support sorting by booking amount');
assert.match(html, /data-court-sort="balance"[\s\S]*会员余额/, 'court table should keep balance sorting');
assert.match(html, /courtSortKey='lastBookingDate',courtSortDir='desc'/, 'court table should default to latest booking descending');
assert.match(fnBody('setCourtSort'), /courtSortKey='';courtSortDir='desc'/, 'court sorting should cycle back to no sort');
assert.match(tablesCss, /\.tms-sort-header\{[^}]*display:inline-flex[^}]*cursor:pointer/, 'court sort header should reuse the shared sort button style');
assert.match(tablesCss, /\.tms-sort-icon\{[^}]*width:14px[^}]*height:14px/, 'court sort icon should reuse the shared svg icon');
assert.match(html, /<th class="tms-sticky-r"[\s\S]*操作/, 'court table should freeze the action header');
assert.match(html, /会员账户[\s\S]*查看[\s\S]*订场/, 'court row actions should use shorter copy');
assert.doesNotMatch(html, /courtCampusFilterBtn|courtCampusFilterMenu/, 'court table should no longer expose campus header filter');
assert.match(html, /courtPageSize/, 'court table should support page size selection');
assert.match(html, /renderPageSizeSelectorHtml\('courtPageSizeValue',courtPageSize,'setCourtPageSize'\)/, 'court page size selector should reuse the shared numeric page-size dropdown');
assert.match(html, /function renderCourtPagerControls\(/, 'court page should use the standard pager renderer');
assert.match(fnBody('renderCourtPagerControls'), /renderStandardPaginationButtonsHtml\(courtPage,pages,'setCourtPage'\)/, 'court pager should render page buttons through the global standard pager');
assert.doesNotMatch(fnBody('renderCourtPagerControls'), /jumpCourtPage|跳至/, 'court pager should not keep jump-to-page controls');
assert.match(fnBody('renderCourtAccountListView'), /renderStandardTooltipText\(cleanNotes,'tms-text-remark tms-text-remark-1 court-note-cell'\)/, 'court read-model notes should clamp to one line like lead notes');
assert.match(fnBody('renderCourts'), /renderCourtAccountListView\(\)/, 'court page should delegate list rendering to the unified read-model view');
assert.match(fnBody('renderCourtAccountListView'), /renderStandardTooltipText\(cleanNotes,'tms-text-remark tms-text-remark-1 court-note-cell'\)/, 'court list notes should clamp to one line like lead notes');
assert.match(html, /function openCourtFinanceModal\(/, 'court page should expose a dedicated finance modal');
assert.match(html, /记一笔流水/, 'court page should expose the standalone finance entry label');
assert.doesNotMatch(html, /<th[^>]*>充值\/消费记录<\/th>/, 'court table should not keep a separate finance history column');
assert.doesNotMatch(fnBody('renderCourtAccountListView'), /openCourtHist\('\$\{u\.id\}'\)/, 'court rows should not open finance history from a separate list column');
assert.doesNotMatch(fnBody('courtProfileFormHtml'), /加入日期|末次跟进日期|下次跟进日期|熟悉程度|f_joinDate|f_recentFollowUpDate|f_nextFollowUpDate|f_familiarity/, 'court edit drawer should remove deprecated profile fields');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*充值\/消费记录[\s\S]*add-rec-row/, 'court edit modal should no longer contain the inline finance entry area');
assert.match(html, /function renderCourtMiniBar\(/, 'court page should expose a dedicated mini bar renderer');
assert.match(html, /class="tms-sticky-l"/, 'court page should freeze the left name column');
assert.match(html, /class="tms-sticky-r"/, 'court page should freeze the right action column');
assert.match(pagesCss, /#page-courts \.tms-table th\.tms-sticky-l\s*\{[^}]*top:0[^}]*left:0[^}]*z-index:140/s, 'court left header should stay fixed on both horizontal and vertical scroll');
assert.match(pagesCss, /#page-courts \.tms-table th\.tms-sticky-r\s*\{[^}]*top:0[^}]*right:0[^}]*z-index:140/s, 'court right header should stay fixed on both horizontal and vertical scroll');
assert.match(tablesCss, /\.tms-table th\{[^}]*background-color:#F1E9E2/s, 'court sticky and normal headers should share the standard header background');
assert.match(pagesCss, /#page-courts \.tms-table tbody tr:hover td\.tms-sticky-l[\s\S]*#page-courts \.tms-table tbody tr:hover td\.tms-sticky-r/s, 'court sticky columns should join whole-row hover');
assert.match(html, /class="tms-action-link"/, 'court page should render action links with the scoped visual style');
assert.match(html, /function openCourtModal[\s\S]*tms-section-header[\s\S]*tms-form-row/, 'court edit modal should use the upgraded local form layout');
assert.doesNotMatch(fnBody('courtProfileFormHtml'), /placeholder="13800138000"/, 'court phone input should not look prefilled with an example number');
assert.match(fnBody('courtProfileFormHtml'), /id="f_phone"[^>]*placeholder="请输入手机号"/, 'court phone input should use neutral placeholder copy');
assert.match(fnBody('courtProfileFormHtml'), /id="f_studentIds"[\s\S]*id="f_studentSearch"[\s\S]*placeholder="搜索姓名、手机号"[\s\S]*updateCourtStudentSearch\(\)[\s\S]*id="f_studentSuggest"[\s\S]*id="f_selectedStudentTags"/, 'court linked students should use the searchable student picker');
assert.match(html, /function renderCourtStudentTags\(/, 'court linked student picker should render selected student tags');
assert.match(html, /function selectCourtStudent\(/, 'court linked student picker should support selecting a student from search results');
assert.match(html, /function removeCourtStudent\(/, 'court linked student picker should support removing selected students');
assert.match(fnBody('saveCourt'), /parseArr\(document\.getElementById\('f_studentIds'\)\?\.value\|\|'\[\]'\)/, 'court save should read linked students from the picker state');
assert.doesNotMatch(fnBody('courtProfileFormHtml'), /tms-panel-tip|累计充值|当前余额|累计消费|累计实收/, 'court profile edit form should not include readonly finance summary');
assert.doesNotMatch(fnBody('courtProfileFormHtml'), /tms-panel-tip[\s\S]*tms-form-readonly/, 'court readonly finance summary should not look like input fields');
assert.doesNotMatch(fnBody('courtProfileFormHtml'), /来源线索摘要|线索来源/, 'court profile edit form should not include readonly lead summary');
assert.doesNotMatch(fnBody('courtProfileFormHtml'), /来源线索摘要[\s\S]*finput tms-form-control tms-readonly-text/, 'court lead source should not look like an input');
assert.match(fnBody('courtProfileFormHtml'), /姓名 \*[\s\S]*手机号[\s\S]*关联学员[\s\S]*f_campus[\s\S]*f_owner[\s\S]*f_attitude[\s\S]*备注/, 'court profile edit form should keep the simplified field order as readonly profile');
assert.match(fnBody('courtProfileFormHtml'), /id="f_notes"[\s\S]*courtCleanUserNotes\(rv\(r,'notes'\)\)/, 'court profile edit notes should show cleaned user-facing notes');
assert.match(fnBody('courtProfileFormHtml'), /关联学员[\s\S]*linkedStudentPicker[\s\S]*校区/, 'court profile edit form should place linked students beside campus like readonly profile');
assert.match(fnBody('courtProfileFormHtml'), /跟进人[\s\S]*f_owner[\s\S]*储值态度[\s\S]*f_attitude/, 'court profile edit form should use standard follower and deposit attitude fields');
assert.match(fnBody('renderCourtRecentBookingCell'), /daysAgoText\(raw\)/, 'court recent booking cell should show date plus days-ago text');
assert.doesNotMatch(fnBody('renderCourtRecentBookingCell'), /raw\?`\$\{raw\} · \$\{daysAgoText\(raw\)\}`/, 'court recent booking cell should not prepend the date twice');
assert.match(pagesCss, /\.modal\.modal-court \.tms-form-control[^}]*height:38px[^}]*font-size:13px[^}]*font-weight:400/s, 'court modal inputs should use 38px height with normal 13px text');
assert.match(pagesCss, /\.modal\.modal-court \.tms-form-label[^}]*font-size:11px[^}]*font-weight:400/s, 'court modal labels should use normal 11px text');
assert.match(pagesCss, /\.modal\.modal-court \.tms-checkbox-matrix[^}]*font-size:10px/s, 'court linked student selector should use 10px student text');
assert.match(fnBody('courtProfileFormHtml'), /renderStandardDropdownHtml\('f_campus','校区',\[\{value:'',label:'-'\},\.\.\.campusList\],rv\(r,'campus'\),true\)/, 'court modal should allow blank campus');
assert.match(html, /function openCourtFinanceModal[\s\S]*tms-record-add-box/, 'court finance modal should use the upgraded local record card layout');
assert.match(html, /function openCourtFinanceModal[\s\S]*历史记录[\s\S]*tms-history-list/, 'court finance modal should keep the Gemini-style history list under the entry form');
assert.match(fnBody('renderCourtHistoryItems'), /const meta=\[h\.category,h\.payMethod,recordedText\]/, 'court history rows should show concise category, payment, and recorded time only');
assert.match(fnBody('openCourtFinanceModal'), /court-finance-summary-grid[\s\S]*当前余额[\s\S]*累计充值[\s\S]*累计消费[\s\S]*累计实收[\s\S]*确认订场收入[\s\S]*本次实收\/现金流入[\s\S]*待确认\/代用户订场[\s\S]*内部占用次数/, 'court finance summary should show 8 readonly fields in one grid');
assert.doesNotMatch(fnBody('openCourtFinanceModal'), /财务摘要(?:(?!流水录入)[\s\S])*<input[^>]+readonly/, 'court finance summary should not render readonly values as inputs');
assert.match(pagesCss, /\.modal\.modal-court \.court-finance-summary-grid\{display:grid;grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/, 'court finance summary should render four columns per row');
assert.match(pagesCss, /\.modal\.modal-court \.tms-record-add-box \.tms-dropdown-display[^}]*font-size:12px/s, 'court finance entry row should use smaller dropdown text to avoid overlapping');
assert.match(html, /function openCourtFinanceModal[\s\S]*flex:0 0 110px[\s\S]*renderStandardDropdownHtml\('nrType','交易类型'[\s\S]*flex:0 0 128px[\s\S]*renderStandardDropdownHtml\('nrCategory','业务类型'[\s\S]*flex:0 0 128px[\s\S]*renderStandardDropdownHtml\('nrPayMethod','支付方式'/s, 'court finance modal should keep the first three selectors compact enough to avoid stacking');
assert.match(html, /function getCourtDuplicateCandidates\(/, 'court save flow should detect duplicates');
assert.match(html, /发现可能重复的订场用户：/, 'court save flow should warn about possible duplicates');
assert.match(html, /手机号优先，若无手机号则按姓名\+校区/, 'court duplicate reminder should prioritize phone and then name plus campus');
assert.match(fnBody('getCurrentCourtAccountRows'), /searchHit\(q,item\.displayName,item\.phone,item\.campusName,item\.owner,item\.depositAttitude,item\.notesSummary[\s\S]*item\.linkedStudentSummary,item\.membershipTierLabel,item\.membershipStatus\)/, 'court search should cover standard follow-up fields');
assert.match(fnBody('courtFollowOwnerText'), /leadForCourtSummary\(court\?\.id\)\?\.owner[\s\S]*court\?\.owner/, 'court follow owner should fall back from lead owner to the old court owner field');
assert.match(html, /search:\{id:'courtSearch',oninput:'onCourtFilterChange\(\)'/, 'court search should reset to the first page before rendering');
assert.match(html, /courtPageSize=\d+/, 'court page should keep its own page size state');
assert.match(html, /function setCourtPageSize\(/, 'court page should expose page size switching');
assert.match(html, /function courtDisplayName\(/, 'court page should expose a display-name helper for blank court names');
assert.match(fnBody('courtDisplayName'), /courtStudentNames\(court\)\|\|String\(court\?\.phone\|\|''\)\.trim\(\)\|\|'未命名订场用户'/, 'court blank names should fall back to linked student, phone, then default copy');
assert.match(html, /function courtSortMetric\(/, 'court page should centralize sortable metrics');
assert.match(html, /function courtBookingSummary\(/, 'court page should centralize booking count and amount metrics');
assert.match(html, /function isCourtBookingHistoryRow\(/, 'court page should centralize booking row detection');
assert.match(fnBody('courtBookingSummary'), /h\.type==='消费'/, 'court booking summary should count consumption rows');
assert.match(fnBody('courtBookingSummary'), /isCourtBookingHistoryRow\(h\)/, 'court booking summary should reuse booking row detection');
assert.match(fnBody('isCourtBookingHistoryRow'), /category\.includes\('订场'\)[\s\S]*!isStoredValuePayMethod\(payMethod\)/, 'booking row detection should include categorized bookings and legacy direct booking rows');
assert.match(fnBody('courtSortMetric'), /if\(!raw\|\|raw==='-'\|\|raw==='—'\)return \{empty:true,value:0\};/, 'court date sorting should treat dash placeholders as empty values');
assert.match(fnBody('renderCourtAccountListView'), /const sortedList=\[\.\.\.list\];/, 'court page should sort the full filtered list before paging');
assert.match(fnBody('renderCourtAccountListView'), /else\{[\s\S]*updatedAt\|\|b\.createdAt[\s\S]*updatedAt\|\|a\.createdAt/, 'court rows should use a deterministic default sort when no explicit sort is selected');
assert.match(html, /function handleCourtMoreAction\(/, 'court page should expose more action handler');
assert.match(html, /id="courtBatchToolbar"[^>]*style="display:none"/, 'court batch toolbar should stay hidden before entering batch mode');
assert.match(html, /function setCourtBatchMode\(/, 'court page should expose explicit batch mode toggling');
assert.match(html, /function updateCourtBatchButton\([\s\S]*toolbar\.style\.display=courtBatchMode\?'flex':'none'/, 'court batch toolbar should only show in batch mode');
assert.match(html, /function updateCourtBatchButton\([\s\S]*btn\.style\.display=courtBatchMode\?'inline-flex':'none'/, 'court batch delete button should follow batch mode visibility');
assert.match(html, /function renderStandardEmptyText\(/, 'court page should centralize empty dash rendering');
assert.match(html, /return raw&&raw!=='—'\?raw:'-';/, 'court list empty cells should convert long dashes to short dashes');
assert.match(html, /renderStandardDropdownHtml\('nrPayMethod'[\s\S]*'储值卡',true,'onCourtFinanceSceneChange'\)/, 'court booking payment should default to stored-value card');
assert.doesNotMatch(fnBody('saveCourt'), /confirm\(/, 'court save should not use browser confirm');
assert.doesNotMatch(fnBody('saveCourtFinanceRecord'), /confirm\(/, 'court finance save should not use browser confirm');
assert.doesNotMatch(fnBody('renderCourtAccountListView'), /低余额/, 'court stats should not show low balance text');
assert.match(html, /function renderCourtStatsCards\(/, 'court stats should render through one shared card helper');
assert.match(fnBody('renderCourtStatsCards'), /总订场用户[\s\S]*会员用户[\s\S]*客群次数对比[\s\S]*订场总金额[\s\S]*散客消费/, 'court stats should show the requested five dashboard cards');
assert.match(html, /function renderStandardSearchHtml[\s\S]*placeholder='搜索姓名、手机号'[\s\S]*id:'courtSearch'/, 'court user search should use the unified placeholder');
assert.match(html, /court-stat-percent/, 'court stats should render percentages with a smaller muted style');
assert.match(pagesCss, /#courtStatsRow\.court-dashboard-stats\{[^}]*display:grid[^}]*grid-template-columns:repeat\(auto-fit,minmax\(200px,1fr\)\)/, 'court stats should use the shared adaptive card grid');
assert.match(pagesCss, /#page-courts \.court-split-value>span:not\(\.court-stat-slash\)\{font-size:21px/, 'court stat main numbers should use the shared stat number size');
assert.match(pagesCss, /#page-courts \.court-stat-slash\{[^}]*font-size:10px[^}]*font-weight:400/, 'court stat slash should match caption slash weight and size');
assert.match(pagesCss, /#page-courts \.court-stat-percent\{[^}]*font-size:10px[^}]*color:#A19080/, 'court stat percentages should use the shared small metric color');
assert.match(pagesCss, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-field\.full-width\{grid-column:1\/-1;width:492px;max-width:492px\}/, 'court drawer full-width readonly fields should span two columns');
assert.match(html, /function courtMembershipTierLabel\(/, 'court membership display should use membership tier label');
assert.match(html, /function courtMembershipTierTagClass\(/, 'court member tier should use tier-specific tag colors');
assert.match(fnBody('renderCourtAccountListView'), /item\.membershipTierLabel&&item\.membershipTierLabel!=='-'\?`<span class="tms-tag \$\{memberTagClass\}">/, 'current membership should render empty state without a tag');
assert.doesNotMatch(fnBody('renderCourtAccountListView'), /const memberTagClass=m\.accountType==='会员'\?'tms-tag-green':'';/, 'current membership tag color should not reuse account type tag color');
assert.match(fnBody('renderAll'), /renderPageData\(currentPage\)/, 'initial load should render only the current page instead of every module');
assert.match(html, /function renderCourtFinanceFields\(/, 'court finance modal should render fields by selected scene');
assert.match(html, /function onCourtFinanceSceneChange\(/, 'court finance modal should update visible fields when scene changes');
assert.match(html, /data-finance-field="booking"/, 'court booking-only fields should be scoped');
assert.match(html, /data-finance-field="course"/, 'court course-only fields should be scoped');
assert.match(html, /内部占用/, 'court finance modal should support internal occupancy records');
assert.match(html, /领导打球[\s\S]*活动[\s\S]*测试教学[\s\S]*其他/, 'internal occupancy should provide reason options');
assert.match(html, /data-finance-field="internal"/, 'court finance modal should scope internal-only fields');
assert.match(fnBody('renderCourtFinanceFields'), /const isInternal=type==='消耗'&&\['内部使用','领导订场'\]\.includes\(category\);/, 'court finance field visibility should recognize internal occupancy');
assert.match(fnBody('courtFinanceLocal'), /const isInternal=String\(h\.category\|\|''\)\.includes\('内部占用'\);/, 'court finance summary should detect internal occupancy rows');
assert.match(fnBody('courtFinanceLocal'), /else if\(h\.type==='消费'\)\{if\(isInternal\)return;/, 'internal occupancy should not count as direct income or spending totals');
assert.match(fnBody('courtFinanceLocal'), /const hist=currentHistory\.length\?currentHistory:courtBaseHistoryForSave\(c\);/, 'court finance summary should reuse legacy opening history when old records have no explicit history');
assert.match(fnBody('courtFinanceConfirmText'), /内部占用/, 'court finance confirm copy should explain internal occupancy');
assert.match(html, /function courtFinanceRevenueSummaryLocal\(/, 'court page should expose local booking income confirmation summary');
assert.match(fnBody('courtFinanceRevenueSummaryLocal'), /confirmedRevenue=t\.storedValueBooking\+t\.onsiteBooking/, 'court finance summary should separate confirmed booking revenue');
assert.match(fnBody('courtFinanceRevenueSummaryLocal'), /pendingRevenue=t\.proxyBooking/, 'court finance summary should separate proxy booking as pending revenue');
assert.match(fnBody('courtFinanceRevenueSummaryLocal'), /matchBooking/, 'court finance summary should expose match booking revenue');
assert.match(fnBody('openCourtFinanceModal'), /确认订场收入[\s\S]*本次实收\/现金流入[\s\S]*待确认\/代用户订场[\s\S]*内部占用次数/, 'court finance modal should show booking income confirmation buckets');
assert.match(fnBody('runBatchDeleteCourts'), /隐藏/, 'batch delete result should explain hidden archived courts');
assert.match(fnBody('renderCourtAccountListView'), /class="tms-court-row-main"[\s\S]*class="tms-checkbox court-row-cb"/, 'court name cell should separate checkbox and name for easier text selection');
assert.match(fnBody('renderCourtAccountListView'), /\$\{esc\(item\.displayName\)\}/, 'court rows should render the unified display name instead of raw names');
assert.doesNotMatch(fnBody('renderCourtAccountListView'), /<label class="tms-checkbox-wrap"[\s\S]*\$\{esc\(u\.name\)\}/, 'court name text should no longer be wrapped by a clickable label');
assert.match(html, /function openCourtFinanceModal[\s\S]*renderStandardDropdownHtml\('nrStudentId','关联学员'/, 'court finance modal should use a shorter linked-student label');
assert.match(html, /function openCourtFinanceModal[\s\S]*renderStandardDropdownHtml\('nrCompanionCoach','陪打教练'/, 'court finance modal should allow selecting a companion coach for bookings');
assert.match(html, /function saveCourtFinanceRecord[\s\S]*scheduleSource:'订场陪打'/, 'court booking with companion coach should generate a linked coach schedule source');
assert.match(html, /function saveCourtFinanceRecord[\s\S]*courseType:'陪打'/, 'companion coach booking should create a companion schedule type');
assert.match(fnBody('openCourtModal'), /openCourtMergeModal\('/, 'court edit modal should expose a merge entry for existing users');
assert.match(html, /function openCourtMergeModal\(/, 'court page should expose a manual merge modal');
assert.match(html, /function renderCourtMergeTargetOptions\(/, 'court page should expose merge target filtering by search');
assert.match(html, /id="mergeCourtSearch"[^>]*placeholder="搜索姓名、手机号"[^>]*oninput="renderCourtMergeTargetOptions\(\)"/, 'merge modal should support searching target users by name and phone');
assert.match(html, /function mergeCourtUsers\(/, 'court page should expose a merge submit handler');
assert.match(html, /function applyCourtMergeResult\(/, 'court merge should apply API result to local page state immediately');
assert.match(fnBody('mergeCourtUsers'), /const result=await apiCall\('POST','\/courts\/merge'/, 'court merge should keep the API result');
assert.match(fnBody('mergeCourtUsers'), /applyCourtMergeResult\(result,sourceCourtId,targetCourtId\)/, 'court merge should patch local state before refreshing cached page data');
assert.match(fnBody('mergeCourtUsers'), /renderCourts\(\);[\s\S]*loadPageDataAndRender\('courts',\{quiet:true,force:true\}\)\.catch/, 'court merge should redraw immediately and refresh cached data in the background');
assert.match(fnBody('applyCourtMergeResult'), /courtAccountListViewData\.items=courtAccountListViewData\.items/, 'court merge should patch read-model items as well as raw courts');
assert.match(fnBody('applyCourtMergeResult'), /removedCourtId\|\|sourceCourtId/, 'court merge should hide the source row even when the backend archives instead of deletes');

console.log('court page view tests passed');
