const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: html } = require('./helpers/read-index-bundle');
const courseSource = [
  fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'scripts', 'pages', 'products.js'), 'utf8'),
  fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'scripts', 'pages', 'packages.js'), 'utf8')
].join('\n');

function fnBody(name){
  const start = html.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = html.indexOf('\nfunction ', start + 1);
  const nextAsync = html.indexOf('\nasync function ', start + 1);
  const candidates = [nextFunction, nextAsync].filter(i => i !== -1);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return html.slice(start, next === -1 ? html.length : next);
}

assert.match(html, /<div class="sb-sec">教学中心<\/div>/, 'sidebar should group teaching pages');
assert.match(html, /<div class="sb-sec">场地运营<\/div>/, 'sidebar should group court operation pages');
assert.match(html, /<div class="sb-sec">资源管理<\/div>/, 'sidebar should group resource pages');

assert.match(html, /goPage\('products',this\)[\s\S]*?课程产品/, 'sidebar should keep products page');
assert.match(html, /goPage\('packages',this\)[\s\S]*?售卖课包/, 'sidebar should add packages page');
assert.doesNotMatch(html, /<div class="sb-item" onclick="goPage\('purchases',this\)">[\s\S]*?购买记录<\/div>/, 'sidebar should remove purchases as a standalone first-level nav entry');
assert.match(html, /goPage\('admin-users',this\)[\s\S]*?账号管理/, 'sidebar should add account management page');
assert.doesNotMatch(html, /goPage\('entitlements',this\)[\s\S]*?权益账户/, 'sidebar should hide the old entitlement page entry');

assert.match(html, /id="page-packages"/, 'should have packages page section');
assert.match(html, /id="pkgTimeBandFilterHost"/, 'package page should expose a time band filter');
assert.match(html, /id="pkgCoachFilterHost"/, 'package page should expose a coach filter');
assert.match(html, /id="pkgAudienceFilterHost"/, 'package page should expose an adult/youth filter');
assert.match(html, /id="page-purchases"/, 'should have purchases page section');
assert.match(html, /course-showcase/, 'course product page should use the new showcase container');
assert.match(html, /course-package-showcase/, 'package page should use the new showcase container');
assert.match(html, /product-card-shell/, 'product page should render the gemini-style product cards');
assert.match(html, /package-card-shell/, 'package page should render the gemini-style package cards');
assert.match(html, /function renderPackages[\s\S]*String\(b\.createdAt\|\|''\)\.localeCompare\(String\(a\.createdAt\|\|''\)\)/, 'package list should sort newer package records first');
assert.match(html, /function packageDisplayTitle\([\s\S]*packageCoreClassLabel[\s\S]*课时[\s\S]*packageTimeBandShortLabel/, 'package cards should build titles from structured fields');
assert.match(html, /function packageDisplayShortId\(/, 'package cards should expose a short display-only package id helper');
assert.match(html, /package-card-meta">\$\{esc\(packageDisplayShortId\(p\)\)\}<span><\/span>\$\{esc\(packageCreatedDate\(p\)\)\}<span><\/span>/, 'package cards should show a compact display id and created date without labels');
assert.doesNotMatch(fnBody('renderPackages'), /\$\{esc\(p\.id\|\|'-'\)\}/, 'package cards should not render the full raw package id');
assert.doesNotMatch(html, /package-card-meta[^`]*创建/, 'package card footer should not show the created label');
assert.doesNotMatch(html, /showcase-kv-label">创建时间/, 'package cards should not show created time as a normal field row');
assert.match(html, /归属教练[\s\S]*可用校区[\s\S]*可用时段/, 'package card should show owner coach, campus, and time rules');
assert.doesNotMatch(fnBody('renderPackages'), /活动期|使用期/, 'package cards should not show sale or usage ranges');
assert.doesNotMatch(fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'scripts', 'pages', 'purchases.js'), 'utf8'), /主归属教练/, 'purchase records should use 归属教练 wording');
assert.match(html, /归属教练[\s\S]*可上课教练/, 'purchase records should expose owner coach and teachable coaches');
assert.match(html, /系统价格[\s\S]*实收金额[\s\S]*改价原因/, 'purchase modal should expose system price, actual paid amount and override reason');
assert.doesNotMatch(html, /tms-pill-tabs/, 'sidebar navigation should replace the demo top tabs');
assert.doesNotMatch(html, /const t=\{students:[\s\S]*?\n\s*const t=\{students:/, 'page title map should not be declared twice after merge');
assert.match(html, /workbench:'工作台'/, 'page title map should include coach workbench');
assert.doesNotMatch(html, /function syncPackageProductMeta/, 'package modal should not sync product metadata anymore');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_productId|课程产品|课程类型跟随课程产品/, 'package modal should no longer require course product selection');
assert.match(fnBody('openPackageModal'), /基础信息[\s\S]*课程类型[\s\S]*上课人数[\s\S]*课时[\s\S]*价格[\s\S]*状态[\s\S]*上课时间[\s\S]*时段类型[\s\S]*可用时段[\s\S]*活动时间[\s\S]*可用时间[\s\S]*教练和场地[\s\S]*归属教练[\s\S]*可用校区[\s\S]*可上课教练[\s\S]*备注/, 'package modal should follow the standardized package creation layout');
assert.doesNotMatch(fnBody('openPackageModal'), /有效天数|pkg_validDays/, 'package modal should hide valid days');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_type'/, 'package modal should allow direct course type selection');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_ownerCoach'/, 'package modal should allow direct main coach selection');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_type'/, 'package modal course type should use the shared custom dropdown');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_maxStudents'/, 'package modal class size should use the shared custom dropdown');
assert.match(fnBody('openPackageModal'), /renderCourtDropdownHtml\('pkg_timeBand'/, 'package modal time band should use the shared custom dropdown');
assert.doesNotMatch(fnBody('openPackageModal'), /适用日期|pkg_timeScope/, 'package modal should not expose applicable-day selectors');
assert.match(html, /packageTimeBandPresetWindows[\s\S]*工作日[\s\S]*周六日/, 'package modal should derive applicable days from time band presets');
assert.match(fnBody('applyPackageTimeBandPreset'), /pkg_timeStart\$\{suffix\}[\s\S]*getScheduleTimeOptions/, 'package modal start time should use the schedule custom time picker');
assert.match(fnBody('applyPackageTimeBandPreset'), /pkg_timeEnd\$\{suffix\}[\s\S]*getScheduleTimeOptions/, 'package modal end time should use the schedule custom time picker');
assert.doesNotMatch(fnBody('openPackageModal'), /type="time"/, 'package modal should not use native time inputs');
assert.doesNotMatch(fnBody('packageTimeScopeOptions'), /value:'custom'|自定义/, 'package time window scope should not include custom');
assert.match(fnBody('openPackageModal'), /tms-checkbox-matrix purchase-coach-picker package-coach-picker[\s\S]*packageCoachChecks/, 'package allowed coaches should use purchase modal checkbox matrix style');
assert.match(fnBody('packageCoachChecks'), /pkg-coach-cb/, 'package allowed coach checks should keep the save selector class');
assert.match(html, /function applyPackageTimeBandPreset/, 'package modal should apply simple default windows for time band presets');
assert.match(html, /function setPackageLessonShortcut\(/, 'package modal should provide lesson shortcuts');
assert.match(html, /10课时[\s\S]*20课时[\s\S]*50课时/, 'package modal should expose lesson shortcut chips');
assert.match(html, /黄金时段'[\s\S]*16:00[\s\S]*22:00[\s\S]*09:00[\s\S]*22:00/, 'prime preset should be weekday evening plus weekend daytime');
assert.match(html, /非黄金时段'[\s\S]*09:00[\s\S]*16:00/, 'non-prime preset should be weekday daytime');
assert.match(fnBody('savePackage'), /presetWindows\.map[\s\S]*daysOfWeek:preset\.daysOfWeek/, 'package save should persist preset applicable days');
assert.doesNotMatch(fnBody('savePackage'), /windowRow|secondWindow/, 'package save should not depend on modal-local time window variables');
assert.doesNotMatch(fnBody('savePackage'), /pkg_validDays/, 'package save should not read hidden valid days field');
assert.match(fnBody('savePackage'), /validDays:\s*packagePersistedValidDays/, 'package save should preserve valid days without showing it');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_type'[\s\S]{0,120}\$\{locked\?' disabled'/, 'sold package course type should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_ownerCoach'[\s\S]{0,160}pointer-events:none/, 'sold package owner coach should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /id="pkg_timeBand"[\s\S]{0,120}\$\{locked\?' disabled'/, 'sold package time band should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /id="pkg_timeStart"[\s\S]{0,120}\$\{locked\?' readonly'/, 'sold package available time should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_saleStartDate_btn[\s\S]{0,180}\$\{locked\?' disabled'/, 'sold package sale start date should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_usageStartDate_btn[\s\S]{0,180}\$\{locked\?' disabled'/, 'sold package usage start date should stay editable');
assert.match(html, /function productHasReferences/, 'product modal should know whether product is referenced');
assert.match(html, /function packageHasPurchases/, 'package modal should know whether package is sold');
assert.match(html, /onclick="openPackageMergeModal\(\)"[\s\S]*合并课包/, 'package page should expose a package merge entry');
assert.match(html, /function mergePackage\(\)[\s\S]*\/packages\/merge/, 'package merge should call the dedicated merge endpoint');
assert.match(html, /openPackageMergeModal[\s\S]*renderCourtDropdownHtml\('pkg_merge_master'[\s\S]*renderCourtDropdownHtml\('pkg_merge_source'/, 'package merge modal should use the shared custom dropdown');
assert.match(html, /setCourtModalFrame\('合并课包'[\s\S]*modal-merge-package/, 'package merge modal should use the dedicated overflow class');
assert.doesNotMatch(html, /<select class="fselect tms-form-control" id="pkg_merge_/, 'package merge modal should not use native select controls');
assert.doesNotMatch(html, /只支持规则一致的课包合并。并入课包会在后台隐藏，购买记录和课包余额会显示为保留课包。/, 'package merge notice should remove the unreadable yellow hint');
assert.doesNotMatch(html, /课程产品定义上什么课；售卖课包定义怎么卖、什么时候能买、什么时候能用。创建售卖课包时会直接绑定一个课程产品。/, 'package page should remove the long banner description');
assert.doesNotMatch(html, /id="page-packages"[\s\S]*搜索课包名称、课程产品、时段/, 'package search should no longer mention course products');
assert.match(html, /openPackageModal\(null\)">＋ 创建课包/, 'package page primary action should say create package');
assert.match(html, /setCourtModalFrame\(id\?'编辑课包':'创建课包'/, 'package modal title should use create package copy');
assert.match(fnBody('openPackageModal'), /deactivatePackage\('\$\{p\.id\}'\)[\s\S]*下架/, 'package edit modal should use deactivate copy');
assert.doesNotMatch(html, /id="page-purchases"[\s\S]*搜索学员、课包、课程产品/, 'purchase search should no longer mention course products');
assert.doesNotMatch(html, /id="page-packages"[\s\S]*还没有课程产品|id="page-packages"[\s\S]*先创建课程产品，再基于课程产品创建售卖课包。/, 'package page should not require course products to create a package');
assert.doesNotMatch(html, /关联产品:/, 'package cards should not show linked product subtitle');
assert.doesNotMatch(fnBody('renderPackages'), /showcase-status-tag[\s\S]*启用/, 'package cards should not show the redundant active status tag');
assert.doesNotMatch(fnBody('renderPackages'), /packageCardTags/, 'package cards should not show duplicate course type tags');
assert.match(fnBody('packageStatusBadge'), /packageListStatusValue[\s\S]*已停售/, 'package stopped sale state should render from package status');
assert.match(fnBody('renderPackages'), /document\.getElementById\('pkgTimeBandFilter'\)/, 'package cards should filter by time band');
assert.match(fnBody('renderPackages'), /document\.getElementById\('pkgCoachFilter'\)/, 'package cards should filter by coach');
assert.match(fnBody('renderPackages'), /document\.getElementById\('pkgAudienceFilter'\)/, 'package cards should filter by adult or youth');
assert.match(fnBody('renderPackages'), /packageAudienceLabelFromText\(\[p\.audience,p\.type,p\.productName,p\.name,p\.packageName,p\.notes\]\)!==af/, 'package audience filter should use the structured audience label');
assert.match(fnBody('syncPackageFilterOptions'), /const typeOptions=withStandardFilterCounts[\s\S]*packageMatchesCourseType/, 'package type filter should show per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /const audienceOptions=withStandardFilterCounts[\s\S]*packageMatchesAudience/, 'package audience filter should show per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /const coachOptions=withStandardFilterCounts[\s\S]*packageMatchesCoach/, 'package coach filter should show per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /const statusOptions=withStandardFilterCounts[\s\S]*packageMatchesStatus/, 'package status filter should show per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /const timeBandOptions=withStandardFilterCounts[\s\S]*packageMatchesTimeBand/, 'package time-band filter should show per-option package counts');
assert.match(fnBody('renderPackages'), /package-rule-line[\s\S]*packageRuleIcon[\s\S]*package-rule-tooltip/, 'package cards should show icon rules with hover tooltip');
assert.match(fnBody('renderPackages'), /package-order-link[\s\S]*package-order-chevron/, 'package order count should show a hover chevron affordance');
assert.match(fnBody('renderPackages'), /deactivatePackage\('\$\{p\.id\}'/, 'package card should use deactivate instead of delete');
assert.match(html, /currentPage==='packages'\)renderPackages\(\)/, 'global campus tabs should refresh packages page');
assert.match(html, /campusTabs'\)\.style\.display=\[[^\]]*'packages'/, 'global campus tabs should show on packages page');
assert.doesNotMatch(html, /查看课程产品/, 'package toolbar should remove the product shortcut button');
assert.match(html, /价格、课时、人数、校区和可上课教练已锁定/, 'locked core fields should show operator-facing hint');
assert.match(html, /function openPurchaseDetailModal/, 'purchase page should have detail modal');
assert.match(html, /function openPurchaseEditModal/, 'purchase page should have edit modal');
assert.match(fnBody('openPurchaseEditModal'), /packages\.filter\(pkg=>\(pkg\.status!=='inactive'&&pkg\.status!=='merged'\)\|\|pkg\.id===p\.packageId\)/, 'purchase edit package picker should hide merged packages except the current saved package');
assert.match(html, /function savePurchaseEdit/, 'purchase page should save purchase edits');
assert.match(html, /function openPurchaseModal/, 'purchase page should provide the unified purchase modal');
assert.match(fnBody('openPurchaseModal'), /packages\.filter\(p=>p\.status!=='inactive'&&p\.status!=='merged'\)/, 'purchase create package picker should hide merged packages');
assert.match(html, /function purchaseStudentPickerHtml\(/, 'purchase modal should expose a searchable student picker helper');
assert.match(html, /function selectPurchaseStudent\(/, 'purchase modal should allow selecting a student from search results');
assert.match(html, /id="pur_studentSearch"/, 'purchase modal should provide a student search input');
assert.match(html, /id="purchaseSaveBtn"[\s\S]*onclick="savePurchase\(\)"/, 'purchase create save button should have a stable id used by the save handler');
assert.match(html, /id="purchaseEditSaveBtn"[\s\S]*onclick="savePurchaseEdit/, 'purchase edit save button should have a stable id used by the edit save handler');
assert.doesNotMatch(fnBody('savePurchase'), /document\.querySelector\('\.btn-save'\)/, 'purchase create save should not depend on the legacy btn-save class');
assert.doesNotMatch(fnBody('savePurchaseEdit'), /document\.querySelector\('\.btn-save'\)/, 'purchase edit save should not depend on the legacy btn-save class');
assert.match(html, /function getFilteredPurchases[\s\S]*String\(a\.purchaseDate\|\|a\.createdAt\|\|''\)\.localeCompare\(String\(b\.purchaseDate\|\|b\.createdAt\|\|''\)\)/, 'purchase list should sort older purchase records first');
assert.match(html, /function isMeaningfulPurchaseRecord/, 'purchase list should filter worthless empty purchase rows');
assert.match(fnBody('getFilteredPurchases'), /isMeaningfulPurchaseRecord\(p\)/, 'purchase filters should skip worthless empty rows before rendering');
assert.match(html, /function packagePurchaseCount/, 'package card should calculate purchase order count');
assert.match(fnBody('purchaseMatchesPackage'), /purchaseIdsByEntitlement[\s\S]*String\(p\.packageId\|\|''\)===String\(packageId\)/, 'package order count should use exact package id and entitlement-linked purchases');
assert.doesNotMatch(fnBody('packagePurchaseCount'), /packageName|productName|originalPackageName/, 'package order count should not count by package or product names');
assert.match(html, /function purchaseMatchesPackage\(/, 'purchase filtering should share the package matching rule used by package order counts');
assert.match(fnBody('getFilteredPurchases'), /purchaseMatchesPackage\(p,packageId\)/, 'purchase package filter should include the same purchases counted on package cards');
assert.match(fnBody('renderPackages'), /const courseType=normalizeCourseType\(p\.courseType\)/, 'package card should normalize legacy course type labels');
assert.match(fnBody('renderPackages'), /\$\{packagePurchaseCount\(p\.id\)\} 笔订单/, 'package card order button should show order count');
assert.match(html, /function openPurchaseModal[\s\S]*支付方式[\s\S]*margin-bottom:0[\s\S]*可上课教练/, 'purchase modal should put pay method and allowed coach fields on separate rows to avoid layout overlap');
assert.match(html, /＋ 课包购买/, 'purchase page should expose a direct package purchase entry button');
assert.match(html, /<th style="width:100px;padding-left:20px">支付日期<\/th><th style="width:120px">学员<\/th><th style="width:170px">课包<\/th><th style="width:90px">实收<\/th><th style="width:105px">余额<\/th><th style="width:80px">状态<\/th><th style="width:95px">归属教练<\/th><th style="width:90px">支付方式<\/th>/, 'purchase table should use the standardized purchase record columns');
assert.doesNotMatch(html, /先选择学员[\s\S]*下一步/, 'purchase modal should not require a separate first-step student gate');
assert.match(html, /购买时规则快照/, 'purchase detail should show package snapshot');
assert.match(html, /系统价格[\s\S]*成交金额[\s\S]*改价原因/, 'purchase detail should show price snapshot fields');
assert.match(html, /支付日期[\s\S]*系统录入时间/, 'purchase detail should show business date and system recorded time');
assert.match(html, /function openPurchaseVoidModal/, 'purchase page should use dedicated void modal');
assert.match(html, /function voidPurchase/, 'purchase page should send void reason');
assert.match(html, /作废原因/, 'void modal should require reason');
assert.match(html, /function resolveUniqueStudentIdByText/, 'purchase import should resolve students uniquely');
assert.match(html, /function resolveUniquePackageIdByText/, 'purchase import should resolve packages uniquely');
assert.match(html, /匹配到多个/, 'purchase import should warn duplicate matches');
assert.match(html, /真正消课的是课包余额/, 'purchase page should explain package balance purpose');
assert.match(html, /私教课/, 'course pages should expose 私教课 as a fixed type');
assert.match(html, /体验课/, 'course pages should expose 体验课 as a fixed type');
assert.match(html, /训练营/, 'course pages should expose 训练营 as a fixed type');
assert.match(html, /大师课/, 'course pages should expose 大师课 as a fixed type');
assert.doesNotMatch(html, /课程性质/, 'course pages should not mention the removed 课程性质 field');
assert.doesNotMatch(courseSource, /正式课/, 'course pages should not keep the old 正式课 wording');
assert.doesNotMatch(courseSource, /半私教课/, 'course pages should not show the old half-private lesson wording');

console.log('course management nav tests passed');
