const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: html } = require('./helpers/read-index-bundle');
const courseSource = [
  fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'scripts', 'pages', 'products.js'), 'utf8'),
  fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'scripts', 'pages', 'packages.js'), 'utf8')
].join('\n');
const standardSource = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'scripts', 'standard', 'components.js'), 'utf8');
const apiSource = fs.readFileSync(path.join(__dirname, '..', 'api', 'index.js'), 'utf8');
const packageRoutesSource = fs.readFileSync(path.join(__dirname, '..', 'server', 'packages-routes.js'), 'utf8');
const packageBoardRoutesSource = fs.readFileSync(path.join(__dirname, '..', 'server', 'package-board-routes.js'), 'utf8');
const readModelSource = fs.readFileSync(path.join(__dirname, '..', 'server', 'read-models', 'unified-page-views.js'), 'utf8');
const pagesCss = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'pages.css'), 'utf8');
const buttonsCss = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'components', 'buttons.css'), 'utf8');
const filtersCss = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'components', 'filters.css'), 'utf8');
const packageShellConfigStart = standardSource.indexOf("{key:'packages'");
const packageShellConfigEnd = standardSource.indexOf("{key:'purchases'", packageShellConfigStart);
const packageShellConfig = standardSource.slice(packageShellConfigStart, packageShellConfigEnd === -1 ? standardSource.length : packageShellConfigEnd);
const purchaseShellConfigStart = standardSource.indexOf("{key:'purchases'");
const purchaseShellConfigEnd = standardSource.indexOf("{key:'prices'", purchaseShellConfigStart);
const purchaseShellConfig = standardSource.slice(purchaseShellConfigStart, purchaseShellConfigEnd === -1 ? standardSource.length : purchaseShellConfigEnd);

function fnBody(name){
  const start = html.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = html.indexOf('\nfunction ', start + 1);
  const nextAsync = html.indexOf('\nasync function ', start + 1);
  const candidates = [nextFunction, nextAsync].filter(i => i !== -1);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return html.slice(start, next === -1 ? html.length : next);
}
const openPackageModalBody = fnBody('openPackageModal');

assert.match(html, /<div class="sb-sec">教学中心<\/div>/, 'sidebar should group teaching pages');
assert.match(html, /<div class="sb-sec">客户中心<\/div>[\s\S]*?goPage\('leads',this\)[\s\S]*?线索池[\s\S]*?goPage\('trial-students',this\)[\s\S]*?历史学员[\s\S]*?goPage\('package-students',this\)[\s\S]*?在期学员[\s\S]*?goPage\('courts',this\)[\s\S]*?订场用户[\s\S]*?goPage\('memberships',this\)[\s\S]*?会员管理[\s\S]*?goPage\('matches',this\)[\s\S]*?约球活动/, 'customer center should order leads, historical students, active students, courts, memberships, then matches');
assert.match(html, /<div class="sb-sec">教学中心<\/div>[\s\S]*?goPage\('schedule',this\)[\s\S]*?排课管理[\s\S]*?goPage\('coachschedule',this\)[\s\S]*?排课日历[\s\S]*?<div class="sb-sec">产品与定价<\/div>/, 'teaching center should only keep schedule management and schedule calendar');
assert.doesNotMatch(html, /goPage\('coachops',this\)[\s\S]*?教练课时统计/, 'coach workload stats should no longer be a standalone left-menu page');
assert.match(html, /<div class="sb-sec">产品与定价<\/div>[\s\S]*?goPage\('packages',this\)[\s\S]*?课包产品[\s\S]*?goPage\('membership-plans',this\)[\s\S]*?会员方案/, 'product pricing should order package products then membership plans');
assert.match(html, /<div class="sb-sec">基础设置<\/div>[\s\S]*?goPage\('coaches',this\)[\s\S]*?教练管理[\s\S]*?goPage\('campusmgr',this\)[\s\S]*?校区管理[\s\S]*?goPage\('admin-users',this\)[\s\S]*?账号管理/, 'basic settings should order coaches, campus, then accounts');
assert.match(html, /const SHELL_THEME=\{[\s\S]*brandName:'网球兄弟'[\s\S]*brandSubline:'TENNISFLOW'[\s\S]*appShellBg:'#875C3C'[\s\S]*topbarDivider:'#805435'[\s\S]*liveClockColor:'#E0D3C9'[\s\S]*liveDotColor:'#78DB89'/, 'shell theme should centralize brand and topbar styles');
assert.match(html, /function renderTopbarShell\(/, 'topbar should render from the shared shell component');
assert.doesNotMatch(html, /· TENNIS · FLOW ·/, 'brand subline should not keep side dots');

assert.match(html, /goPage\('products',this\)[\s\S]*?课程产品/, 'sidebar should keep products page');
assert.match(html, /goPage\('packages',this\)[\s\S]*?课包产品/, 'sidebar should add packages page');
assert.doesNotMatch(html, /<div class="sb-item" onclick="goPage\('purchases',this\)">[\s\S]*?购买记录<\/div>/, 'sidebar should remove purchases as a standalone first-level nav entry');
assert.match(html, /goPage\('admin-users',this\)[\s\S]*?账号管理/, 'sidebar should add account management page');
assert.doesNotMatch(html, /goPage\('entitlements',this\)[\s\S]*?权益账户/, 'sidebar should hide the old entitlement page entry');

[
  ['leads', '线索池'],
  ['package-students', '在期学员', 'students'],
  ['trial-students', '历史学员', 'trial-students'],
  ['courts', '订场用户'],
  ['memberships', '会员管理'],
  ['matches', '约球活动'],
  ['schedule', '排课管理'],
  ['coachschedule', '排课日历'],
  ['packages', '课包产品'],
  ['admin-users', '账号管理'],
  ['campusmgr', '校区管理'],
  ['coaches', '教练管理']
].forEach(([page, label, iconKey]) => {
  const icon = iconKey || page;
  assert.match(html, new RegExp(`goPage\\('${page}',this\\)[\\s\\S]*?sidebarIcon\\('${icon}'\\)[\\s\\S]*?${label}`), `${label} should render through sidebarIcon`);
  assert.match(html, new RegExp(`data-sidebar-icon="${icon}"`), `${label} should provide the custom svg`);
});
assert.match(html, /data-sidebar-icon="trial-students" width="23" height="23"/, 'trial student sidebar icon should render at 23px');
assert.match(pagesCss, /--shell-sidebar-icon-color:#C5B0A2/, 'inactive sidebar icon color should match design');
assert.match(pagesCss, /--shell-sidebar-active-icon-color:#EFE7E2/, 'active sidebar icon color should match design');
assert.match(pagesCss, /\.sb-item\{[^}]*height:38px/, 'sidebar rows should be tightened to 38px');
assert.match(pagesCss, /\.sb-item\.active::before\{[^}]*left:0/, 'active sidebar bar should sit inside the selected row');
assert.match(pagesCss, /\.sb-logo\{[^}]*border-bottom:0\.5px solid var\(--shell-sidebar-divider\)/, 'sidebar logo divider should be 0.5px');
assert.match(pagesCss, /\.sb-bottom\{[^}]*border-top:0\.5px solid var\(--shell-sidebar-divider\)/, 'sidebar bottom divider should be 0.5px');
assert.match(pagesCss, /\.topbar\{[^}]*background:var\(--shell-app-bg\)[^}]*border-bottom:0\.5px solid var\(--shell-topbar-divider\)/, 'topbar should use shared shell colors with a 0.5px divider');
assert.match(pagesCss, /\.content\{[^}]*background:var\(--shell-app-bg\)/, 'content area should use shared shell background');

assert.match(html, /id="page-packages"/, 'should have packages page section');
assert.match(packageShellConfig, /pkgTimeBandFilterHost/, 'package page should expose a time band filter');
assert.match(packageShellConfig, /pkgCoachFilterHost/, 'package page should expose a coach filter');
assert.match(packageShellConfig, /pkgAudienceFilterHost/, 'package page should expose an adult/youth filter');
assert.match(html, /id="page-purchases"/, 'should have purchases page section');
assert.match(html, /course-showcase/, 'course product page should use the new showcase container');
assert.match(packageShellConfig, /course-package-showcase/, 'package page should use the new showcase container');
assert.match(html, /product-card-shell/, 'product page should render the gemini-style product cards');
assert.match(html, /package-card-shell/, 'package page should render the gemini-style package cards');
assert.match(html, /function packageSortValue\(/, 'package list should expose a persisted sort value helper');
assert.match(html, /function renderPackages[\s\S]*packageSortValue\(a\)-packageSortValue\(b\)[\s\S]*String\(b\.createdAt\|\|''\)\.localeCompare\(String\(a\.createdAt\|\|''\)\)/, 'package list should sort by persisted package order before falling back to newer records first');
assert.match(fnBody('packageBoardCardHtml'), /draggable="true"[\s\S]*onDragStart="startPackageDrag/, 'package cards should be draggable');
assert.match(html, /async function savePackageOrder\([\s\S]*\/packages\/order/, 'package drag order should save through a dedicated endpoint');
assert.match(packageRoutesSource, /path==='\/packages\/order'&&method==='PUT'[\s\S]*sortOrder/, 'package order should have a dedicated backend endpoint');
assert.match(packageRoutesSource, /const id=decodeURIComponent\(pkgM\[1\]\)/, 'package update route should decode URL-encoded package ids before reading TableStore');
assert.match(html, /function packageDisplayTitle\(p\)[\s\S]*return packageListTitle\(p\)/, 'package cards should reuse the unified package list title');
assert.match(fnBody('packageListTitle'), /packageLessonUnitLabel\(p\)[\s\S]*packageListClassLabel\(p\)[\s\S]*packageListTimeBandLabel/, 'package list title should build from class size, time band and lesson unit');
assert.match(html, /function packageTimeBandBadgeClass\([\s\S]*黄金[\s\S]*非黄金[\s\S]*全天/, 'package time band badge should expose three visual states');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /packageTimeBandBadgeHtml\(p\)/, 'package cards should not render time band as a separate title badge');
assert.match(fnBody('packageBoardCardHtml'), /package-card-meta[\s\S]*packageAvailableDate\(p\)[\s\S]*package-order-link/, 'package cards should keep available date and order link without labels');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /\$\{esc\(p\.id\|\|'-'\)\}/, 'package cards should not render the full raw package id');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /packageDisplayShortId\(p\)|package-meta-id/, 'package cards should not show package id in the footer');
assert.doesNotMatch(html, /package-card-meta[^`]*创建/, 'package card footer should not show the created label');
assert.doesNotMatch(html, /showcase-kv-label">创建时间/, 'package cards should not show created time as a normal field row');
assert.match(fnBody('packageBoardCardHtml'), /packageCourseTypeTitle\(p\)[\s\S]*packageRuleIcon\('course'\)[\s\S]*packageCampusSummaryText\(p\.campusIds\)[\s\S]*packageRuleIcon\('campus'\)/, 'package card should show course type and campus rules');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /活动期|使用期/, 'package cards should not show sale or usage ranges');
assert.doesNotMatch(fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'scripts', 'pages', 'purchases.js'), 'utf8'), /主归属教练/, 'purchase records should use 归属教练 wording');
assert.match(html, /归属教练[\s\S]*可上课教练/, 'purchase records should expose owner coach and teachable coaches');
assert.match(html, /系统价格[\s\S]*实收金额[\s\S]*改价原因/, 'purchase modal should expose system price, actual paid amount and override reason');
assert.doesNotMatch(html, /tms-pill-tabs/, 'sidebar navigation should replace the demo top tabs');
assert.doesNotMatch(html, /const t=\{students:[\s\S]*?\n\s*const t=\{students:/, 'page title map should not be declared twice after merge');
assert.match(html, /workbench:'工作台'/, 'page title map should include coach workbench');
assert.doesNotMatch(html, /function syncPackageProductMeta/, 'package modal should not sync product metadata anymore');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_productId|课程产品|课程类型跟随课程产品/, 'package modal should no longer require course product selection');
assert.match(openPackageModalBody, /renderDetailDrawerFormCard\('基础属性'[\s\S]*renderDetailDrawerFormCard\('规格与价格'[\s\S]*renderDetailDrawerFormCard\('时间规则'[\s\S]*renderDetailDrawerFormCard\('教练和场地'/, 'package modal should follow the standardized package card order');
assert.match(openPackageModalBody, /学员类型[\s\S]*课程类型[\s\S]*上课人数[\s\S]*状态[\s\S]*pkg_lessons_label[\s\S]*价格[\s\S]*活动时间[\s\S]*可用时间[\s\S]*时段类型[\s\S]*可用时段[\s\S]*归属教练[\s\S]*可用校区[\s\S]*可上课教练[\s\S]*备注/, 'package modal should include the standardized package creation fields');
assert.match(fnBody('openPackageModal'), /courseType==='小班课'\|\|courseType==='专项课'[\s\S]*'次数':'课时'/, 'small group and special course package modal should label package amount as count');
assert.match(fnBody('openPackageModal'), /10\$\{packageUnitLabel\}[\s\S]*20\$\{packageUnitLabel\}/, 'package shortcut chips should follow the current package unit label');
assert.match(fnBody('standardPackageLabel'), /packageLessonUnitLabel\(p\)/, 'small group package labels should show count instead of lesson hours');
assert.match(fnBody('packageListTitle'), /packageLessonUnitLabel\(p\)/, 'small group package cards should show count instead of lesson hours');
assert.doesNotMatch(fnBody('openPackageModal'), /有效天数|pkg_validDays/, 'package modal should hide valid days');
assert.match(fnBody('openPackageModal'), /renderStandardDropdownHtml\('pkg_type'/, 'package modal should allow direct course type selection');
assert.match(fnBody('openPackageModal'), /renderStandardDropdownHtml\('pkg_audience'/, 'package modal should allow adult or youth selection');
assert.match(fnBody('openPackageModal'), /renderStandardDropdownHtml\('pkg_ownerCoach'/, 'package modal should allow direct main coach selection');
assert.match(fnBody('openPackageModal'), /pkg_experienceType/, 'package modal should expose a second-level selector for experience courses');
assert.match(fnBody('openPackageModal'), /pkg_smallClassType/, 'package modal should expose a second-level selector for small group packages');
assert.match(courseSource, /function applySmallClassPackagePreset\(/, 'package modal should define small group package presets');
assert.match(fnBody('applySmallClassPackagePreset'), /bootcamp:\{price:1999,lessons:10,timeBand:'黄金时段',maxStudents:'4'\}/, 'small group bootcamp preset should default to 10 lessons');
assert.match(fnBody('applySmallClassPackagePreset'), /currentMaxStudents[\s\S]*if\(!currentMaxStudents\|\|currentMaxStudents==='1'\)setStandardDropdownValue\('pkg_maxStudents'/, 'small group presets should not overwrite an already selected 1v2/1v3/1v4 class size');
assert.match(fnBody('openPackageModal'), /data-lessons="10"[\s\S]*10\$\{packageUnitLabel\}[\s\S]*data-lessons="20"[\s\S]*20\$\{packageUnitLabel\}/, 'package modal should expose 10 and 20 package amount shortcuts');
assert.doesNotMatch(fnBody('openPackageModal'), /data-lessons="6"[\s\S]*6课时/, 'package modal should not force six lesson packages');
assert.doesNotMatch(courseSource, /小班单次价格必须是 260 元|训练营价格必须是 1999 元|随到随学价格必须是 1499 元/, 'small group package prices should not be locked to preset amounts');
assert.doesNotMatch(courseSource, /训练营固定 4 人|随到随学必须是 6 次/, 'small group package rules should not force bootcamp 1v4 or dropin 6-session packages');
assert.match(fnBody('savePackage'), /freeAbsenceLimit[\s\S]*smallClassType==='bootcamp'\?1:0/, 'small group bootcamp package should persist one free absence');
assert.match(fnBody('packageExperienceTypeLabel'), /p=p\|\|\{\}/, 'package experience label should tolerate creating a package without existing row data');
assert.match(fnBody('openProductModal'), /p_experienceType/, 'course product modal should expose a second-level selector for experience courses');
assert.match(fnBody('saveProduct'), /experienceType:/, 'course product save should persist the selected experience subtype');
assert.match(fnBody('savePackage'), /const audience=document\.getElementById\('pkg_audience'\)\.value[\s\S]*const data=\{[\s\S]*audience,type:audience/, 'package save should persist the selected adult or youth type');
assert.match(fnBody('openPackageModal'), /renderStandardDropdownHtml\('pkg_type'/, 'package modal course type should use the shared custom dropdown');
assert.match(fnBody('openPackageModal'), /renderStandardDropdownHtml\('pkg_maxStudents'/, 'package modal class size should use the shared custom dropdown');
assert.match(fnBody('openPackageModal'), /renderStandardDropdownHtml\('pkg_timeBand'/, 'package modal time band should use the shared custom dropdown');
assert.doesNotMatch(fnBody('openPackageModal'), /适用日期|pkg_timeScope/, 'package modal should not expose applicable-day selectors');
assert.match(html, /function courseSurchargePayMethodOptions\(\)[\s\S]*payMethodOptions\(\)\.filter/, 'schedule surcharge payment should reuse shared payment methods');
assert.match(fnBody('courseSurchargePayMethodOptions'), /\['课包划扣','大众点评券码','抖音券码','其他'\]\.includes\(option\.value\)/, 'schedule surcharge payment should hide package, coupon, and unsupported methods while allowing stored value');
assert.doesNotMatch(fnBody('saveSchedule'), /场地费不能用储值卡扣款/, 'schedule field fee should allow stored-value payment after balance validation');
assert.match(fnBody('openScheduleModal'), /sch_fieldFeePayMethod/, 'schedule field fee should use an independent payment method control');
assert.match(fnBody('openScheduleModal'), /schedule-course-type-item[\s\S]*schedule-settlement-row">\$\{settlementField\}\$\{fieldFeeModeField\}/, 'schedule modal should order course type before settlement and field fee row');
assert.match(fnBody('openScheduleModal'), /const settlementField=`[\s\S]*结算方式[\s\S]*const packageField=`[\s\S]*扣减课包/, 'schedule modal settlement row should render settlement type before package deduction');
assert.match(fnBody('openScheduleModal'), /schedule-course-type-item[\s\S]*schedule-settlement-row">\$\{settlementField\}\$\{fieldFeeModeField\}<\/div>\$\{paymentRow\}\$\{packageField\}/, 'schedule modal should keep settlement and field fee mode on one row before payment and package rows');
assert.match(fnBody('openScheduleModal'), /schedule-settlement-type-item[\s\S]*schedule-entitlement-item/, 'schedule settlement and package columns should keep their standard classes');
assert.match(fnBody('openScheduleModal'), /schedule-payment-row[\s\S]*课时费支付[\s\S]*课时费[\s\S]*场地费支付[\s\S]*场地费/, 'schedule payment row should show independent lesson and field fee payment controls in one compact row');
assert.match(pagesCss, /schedule-course-type-item[\s\S]*flex:0 0 120px[\s\S]*max-width:120px/, 'schedule modal course type should use a compact 120px column');
assert.match(pagesCss, /schedule-settlement-type-item[\s\S]*flex:0 0 120px[\s\S]*max-width:120px/, 'schedule modal settlement type should use a compact 120px column');
assert.match(pagesCss, /schedule-entitlement-item[\s\S]*flex:1 1 0[\s\S]*min-width:0[\s\S]*max-width:100%/, 'schedule modal package deduction should take the remaining width without overflowing');
assert.match(pagesCss, /schedule-payment-row[\s\S]*grid-template-columns:repeat\(4,113px\)/, 'schedule payment row should use compact equal-width fields');
assert.match(html, /packageTimeBandPresetWindows[\s\S]*工作日[\s\S]*周六日/, 'package modal should derive applicable days from time band presets');
assert.match(fnBody('applyPackageTimeBandPreset'), /pkg_timeStart\$\{suffix\}[\s\S]*getScheduleTimeOptions/, 'package modal start time should use the schedule custom time picker');
assert.match(fnBody('applyPackageTimeBandPreset'), /pkg_timeEnd\$\{suffix\}[\s\S]*getScheduleTimeOptions/, 'package modal end time should use the schedule custom time picker');
assert.doesNotMatch(fnBody('openPackageModal'), /type="time"/, 'package modal should not use native time inputs');
assert.doesNotMatch(fnBody('packageTimeScopeOptions'), /value:'custom'|自定义/, 'package time window scope should not include custom');
assert.match(fnBody('openPackageModal'), /packageCoachPickerHtml\(rv\(p,'coachNames',\[\]\)\)/, 'package allowed coaches should use the drawer choice UI');
assert.match(fnBody('packageCoachChecks'), /pkg-coach-cb/, 'package allowed coach checks should keep the save selector class');
assert.match(html, /function applyPackageTimeBandPreset/, 'package modal should apply simple default windows for time band presets');
assert.match(html, /function setPackageLessonShortcut\(/, 'package modal should provide lesson shortcuts');
assert.match(fnBody('openPackageModal'), /10\$\{packageUnitLabel\}[\s\S]*20\$\{packageUnitLabel\}/, 'package modal should expose package amount shortcut chips');
assert.doesNotMatch(html, /50课时/, 'package modal should leave non-standard lesson counts to manual input');
assert.match(html, /黄金时段'[\s\S]*16:00[\s\S]*22:00[\s\S]*09:00[\s\S]*22:00/, 'prime preset should be weekday evening plus weekend daytime');
assert.match(html, /非黄金时段'[\s\S]*09:00[\s\S]*16:00/, 'non-prime preset should be weekday daytime');
assert.match(fnBody('savePackage'), /presetWindows\.map[\s\S]*daysOfWeek:preset\.daysOfWeek/, 'package save should persist preset applicable days');
assert.doesNotMatch(fnBody('savePackage'), /windowRow|secondWindow/, 'package save should not depend on modal-local time window variables');
assert.doesNotMatch(fnBody('savePackage'), /pkg_validDays/, 'package save should not read hidden valid days field');
assert.match(fnBody('savePackage'), /experienceType:/, 'package save should persist the selected experience subtype');
assert.match(fnBody('savePackage'), /validDays:\s*0/, 'package save should clear package valid days');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_type'[\s\S]{0,120}\$\{locked\?' disabled'/, 'sold package course type should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_ownerCoach'[\s\S]{0,160}pointer-events:none/, 'sold package owner coach should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /id="pkg_timeBand"[\s\S]{0,120}\$\{locked\?' disabled'/, 'sold package time band should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /id="pkg_timeStart"[\s\S]{0,120}\$\{locked\?' readonly'/, 'sold package available time should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_saleStartDate_btn[\s\S]{0,180}\$\{locked\?' disabled'/, 'sold package sale start date should stay editable');
assert.doesNotMatch(fnBody('openPackageModal'), /pkg_usageStartDate_btn[\s\S]{0,180}\$\{locked\?' disabled'/, 'sold package usage start date should stay editable');
assert.match(html, /function productHasReferences/, 'product modal should know whether product is referenced');
assert.match(html, /function packageHasPurchases/, 'package modal should know whether package is sold');
assert.match(html, /onclick="openPackageMergeModal\(\)"[\s\S]*合并课包/, 'package page should expose a package merge entry');
assert.match(html, /function mergePackage\(\)[\s\S]*\/packages\/merge/, 'package merge should call the dedicated merge endpoint');
assert.match(html, /openPackageMergeModal[\s\S]*renderCoursePackagePickerDropdownHtml\('pkg_merge_master'[\s\S]*renderCoursePackagePickerDropdownHtml\('pkg_merge_source'/, 'package merge modal should use the shared searchable package dropdown');
assert.match(html, /openStandardModal\(\{title:'合并课包'[\s\S]*modal-merge-package/, 'package merge modal should use the dedicated overflow class through standard modal');
assert.doesNotMatch(html, /<select class="fselect tms-form-control" id="pkg_merge_/, 'package merge modal should not use native select controls');
assert.doesNotMatch(html, /只支持规则一致的课包合并。并入课包会在后台隐藏，购买记录和课包余额会显示为保留课包。/, 'package merge notice should remove the unreadable yellow hint');
assert.doesNotMatch(html, /课程产品定义上什么课；售卖课包定义怎么卖、什么时候能买、什么时候能用。创建售卖课包时会直接绑定一个课程产品。/, 'package page should remove the long banner description');
assert.doesNotMatch(html, /id="page-packages"[\s\S]*搜索课包名称、课程产品、时段/, 'package search should no longer mention course products');
assert.match(html, /openPackageModal\(null\)">创建课包/, 'package page primary action should say create package');
assert.match(fnBody('openPackageModal'), /titleHtml:packageDrawerHeaderHtml\(p,id\?'edit':'create'\)/, 'package modal title should use create package copy');
assert.match(fnBody('packageBoardCardHtml'), /deactivatePackage\('\$\{p\.id\}'\)[\s\S]*下架/, 'package card should use deactivate copy');
assert.doesNotMatch(html, /id="page-purchases"[\s\S]*搜索学员、课包、课程产品/, 'purchase search should no longer mention course products');
assert.doesNotMatch(html, /id="page-packages"[\s\S]*还没有课程产品|id="page-packages"[\s\S]*先创建课程产品，再基于课程产品创建售卖课包。/, 'package page should not require course products to create a package');
assert.doesNotMatch(html, /关联产品:/, 'package cards should not show linked product subtitle');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /showcase-status-tag[\s\S]*启用/, 'package cards should not show the redundant active status tag');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /packageCardTags/, 'package cards should not show duplicate course type tags');
assert.match(fnBody('packageStatusBadge'), /packageListStatusValue[\s\S]*已停售/, 'package stopped sale state should render from package status');
assert.match(fnBody('getFilteredPackages'), /document\.getElementById\('pkgTimeBandFilter'\)/, 'package cards should filter by time band');
assert.match(fnBody('getFilteredPackages'), /document\.getElementById\('pkgCoachFilter'\)/, 'package cards should filter by coach');
assert.match(fnBody('getFilteredPackages'), /document\.getElementById\('pkgAudienceFilter'\)/, 'package cards should filter by adult or youth');
assert.match(fnBody('getFilteredPackages'), /packageAudienceLabelFromText\(\[p\.audience,p\.type,p\.productName,p\.name,p\.packageName,p\.notes\]\)!==af/, 'package audience filter should use the structured audience label');
assert.match(html, /const PACKAGE_BOARD_COLUMNS=\[[\s\S]*青少年 · 私教课[\s\S]*青少年 · 小班课[\s\S]*成人 · 私教课[\s\S]*成人 · 小班课[\s\S]*朝珺/, 'package board should render the four teaching columns plus a Chaojun column');
assert.match(html, /function packageIsChaojunOnlyOwned\([\s\S]*ownerCoach[\s\S]*includes\('朝珺'\)/, 'package board should identify packages whose owner coach name includes Chaojun');
assert.doesNotMatch(fnBody('packageIsChaojunOnlyOwned'), /coachNames|coachIds/, 'package board should not move packages into Chaojun just because Chaojun is an available coach');
assert.match(html, /function packageBoardColumnKey\([\s\S]*packageIsChaojunOnlyOwned\(p\)[\s\S]*chaojun[\s\S]*小班体验课[\s\S]*小班课[\s\S]*私教课[\s\S]*other/, 'package board should classify Chaojun-owner packages before the normal teaching columns and keep an other fallback');
assert.doesNotMatch(html, /function packageBoardColumnKey\([\s\S]*boardColumn/, 'package board classification should not be overridden by stale saved board columns');
assert.match(fnBody('renderPackages'), /package-board-column[\s\S]*package-board-title[\s\S]*package-board-count[\s\S]*packageBoardCardHtml/, 'package page should render a Notion-style board with column counts and package cards');
assert.match(fnBody('buildCampusTabs'), /currentPage==='packages'[\s\S]*renderPackageTopFilters/, 'package page should reuse the coach ops top campus dropdown');
assert.match(html, /function selectPackageTopCampus\([\s\S]*refreshPackageTopFilters\(\)[\s\S]*renderPackages\(\)[\s\S]*closeStandardTopDropdowns\(\)/, 'package top campus dropdown should refresh label and package board');
assert.match(fnBody('dropPackageCard'), /packageBoardColumnKey\(dragged\)!==packageBoardColumnKey\(target\)[\s\S]*return/, 'package card sorting should stay inside the same board column');
assert.match(fnBody('dropPackageCard'), /savePackageBoardOrder\(ordered\)/, 'package card drops should only save in-column ordering');
assert.match(fnBody('savePackageBoardOrder'), /savePackageOrder\(orderedIds\)/, 'package drag sorting should persist order only');
assert.match(fnBody('packageBoardCardHtml'), /ondrop="dropPackageCard\(event,'\$\{p\.id\}'\)"/, 'package cards should accept package drops');
assert.match(fnBody('renderPackages'), /draggable="true"[\s\S]*startPackageColumnDrag\(event,'\$\{esc\(col\.key\)\}'\)[\s\S]*dropPackageColumn\(event,'\$\{esc\(col\.key\)\}'\)/, 'package board columns should support drag sorting between columns');
assert.match(html, /async function dropPackageColumn\([\s\S]*apiCall\('PUT','\/package-board-preferences',\{columnOrder:next\}\)/, 'package board should persist column order through the backend');
assert.match(packageBoardRoutesSource, /path==='\/package-board-preferences'&&method==='GET'[\s\S]*getPackageBoardPreferences/, 'package board should load saved column order from the backend');
assert.match(packageBoardRoutesSource, /path==='\/package-board-preferences'&&method==='PUT'[\s\S]*savePackageBoardPreferences/, 'package board should save column order to the backend');
assert.match(html, /packageBoardPreferences:\(\)=>apiCall\('GET','\/package-board-preferences'\)/, 'package page should request board preferences while loading data');
assert.doesNotMatch(html, /async function dropPackageToColumn\(/, 'package board should not support dragging cards into another column');
assert.doesNotMatch(fnBody('savePackageOrder'), /boardColumnById/, 'package order save should not send board column placement');
assert.doesNotMatch(apiSource, /path==='\/packages\/order'&&method==='PUT'[\s\S]*boardColumnById/, 'package order endpoint should not persist card column placement');
assert.match(fnBody('syncPackageFilterOptions'), /withLinkedFilterCounts\(\[[\s\S]*key:'type'[\s\S]*packageMatchesCourseType/, 'package type filter should show linked per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /withLinkedFilterCounts\(\[[\s\S]*key:'audience'[\s\S]*packageMatchesAudience/, 'package audience filter should show linked per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /withLinkedFilterCounts\(\[[\s\S]*key:'coach'[\s\S]*packageMatchesCoach/, 'package coach filter should show linked per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /withLinkedFilterCounts\(\[[\s\S]*key:'status'[\s\S]*packageMatchesStatus/, 'package status filter should show linked per-option package counts');
assert.match(fnBody('syncPackageFilterOptions'), /withLinkedFilterCounts\(\[[\s\S]*key:'timeBand'[\s\S]*packageMatchesTimeBand/, 'package time-band filter should show linked per-option package counts');
assert.match(fnBody('packageBoardCardHtml'), /package-rule-line[\s\S]*packageRuleIcon[\s\S]*package-rule-tooltip/, 'package cards should show icon rules with hover tooltip');
assert.doesNotMatch(fnBody('packageBoardCardHtml'), /packageRuleIcon\('time'\)/, 'package cards should move time band out of the rules area');
assert.match(fnBody('packageBoardCardHtml'), /package-order-link[\s\S]*package-order-chevron/, 'package order count should show a hover chevron affordance');
assert.match(fnBody('packageBoardCardHtml'), /deactivatePackage\('\$\{p\.id\}'/, 'package card should use deactivate instead of delete');
assert.match(html, /currentPage==='packages'\)renderPackages\(\)/, 'global campus tabs should refresh packages page');
assert.match(html, /campusTabs'\)\.style\.display=[\s\S]*'packages'/, 'global campus tabs should show on packages page');
assert.doesNotMatch(html, /查看课程产品/, 'package toolbar should remove the product shortcut button');
assert.match(html, /保存后会同步更新已购订单和学员课包余额/, 'sold package edits should tell operators that saved changes sync existing orders and balances');
assert.match(html, /function openPurchaseDetailModal/, 'purchase page should have detail modal');
assert.match(html, /function openPurchaseEditModal/, 'purchase page should have edit modal');
assert.match(fnBody('openPurchaseEditModal'), /packages\.filter\(pkg=>\(pkg\.status!=='inactive'&&pkg\.status!=='merged'\)\|\|pkg\.id===p\.packageId\)/, 'purchase edit package picker should hide merged packages except the current saved package');
assert.match(html, /function savePurchaseEdit/, 'purchase page should save purchase edits');
assert.match(html, /function openPurchaseModal/, 'purchase page should provide the unified purchase modal');
assert.match(fnBody('openPurchaseModal'), /packages\.filter\(p=>p\.status!=='inactive'&&p\.status!=='merged'\)/, 'purchase create package picker should hide merged packages');
assert.match(html, /function purchasePackagePickerLabel/, 'purchase package picker should have a dedicated display label');
assert.match(fnBody('purchasePackagePickerLabel'), /standardPackageLabel\(p,true\)[\s\S]*Number\(p\.price\)[\s\S]*\$\{price\}元[\s\S]*coachName\(p\.ownerCoach\)/, 'purchase package picker label should include package price and bound owner coach');
assert.match(html, /function coursePackageBusinessSortValue\(/, 'course package dropdown should expose business sorting by audience, course type, class size, lesson count, time band, price and coach');
assert.match(html, /function renderCoursePackagePickerDropdownHtml\(/, 'course package dropdown should have a shared searchable grouped renderer');
assert.match(fnBody('renderCoursePackagePickerDropdownHtml'), /renderStandardSearchableDropdownHtml[\s\S]*搜索课包 \/ 教练 \/ 价格 \/ 课时/, 'course package picker should be searchable by package, coach, price and lesson count');
assert.match(fnBody('coursePackageDropdownOptions'), /searchText:\[label,p\.audience/, 'course package search should directly include audience words such as 成人 and 青少年');
assert.match(fnBody('openPurchaseModal'), /renderCoursePackagePickerDropdownHtml\('pur_packageId'[\s\S]*includeCoach:true/, 'purchase create package picker should use the searchable grouped package dropdown');
assert.match(fnBody('openPurchaseEditModal'), /renderCoursePackagePickerDropdownHtml\('pur_edit_packageId'[\s\S]*includeCoach:true/, 'purchase edit package picker should use the searchable grouped package dropdown');
assert.match(fnBody('refreshPurchaseFilters'), /renderCoursePackagePickerDropdownHtml\('purPackageFilter'[\s\S]*showAllOption:true[\s\S]*includeCoach:true/, 'purchase record package filter should use the searchable grouped package dropdown');
assert.match(fnBody('openPackageMergeModal'), /renderCoursePackagePickerDropdownHtml\('pkg_merge_master'[\s\S]*renderCoursePackagePickerDropdownHtml\('pkg_merge_source'/, 'package merge modal should use the searchable grouped package dropdown for both package selectors');
assert.match(html, /function purchaseStudentPickerHtml\(/, 'purchase modal should expose a searchable student picker helper');
assert.match(html, /function selectPurchaseStudent\(/, 'purchase modal should allow selecting a student from search results');
assert.match(html, /id="pur_studentSearch"/, 'purchase modal should provide a student search input');
assert.match(fnBody('openPurchaseModal'), /purchaseDrawerActions\('closeModal\(\)','savePurchase\(\)','purchaseSaveBtn'\)/, 'purchase create save button should have a stable id used by the save handler');
assert.match(fnBody('openPurchaseEditModal'), /purchaseDrawerActions\(`openPurchaseDetailModal\('\$\{p\.id\}'\)`,`savePurchaseEdit\('\$\{p\.id\}'\)`,'purchaseEditSaveBtn'\)/, 'purchase edit save button should have a stable id used by the edit save handler');
assert.doesNotMatch(fnBody('savePurchase'), /document\.querySelector\('\.btn-save'\)/, 'purchase create save should not depend on the legacy btn-save class');
assert.doesNotMatch(fnBody('savePurchaseEdit'), /document\.querySelector\('\.btn-save'\)/, 'purchase edit save should not depend on the legacy btn-save class');
assert.match(html, /function getFilteredPurchases[\s\S]*String\(b\.purchaseDate\|\|b\.createdAt\|\|''\)\.localeCompare\(String\(a\.purchaseDate\|\|a\.createdAt\|\|''\)\)/, 'purchase list should sort newer payment dates first');
assert.match(html, /function isMeaningfulPurchaseRecord/, 'purchase list should filter worthless empty purchase rows');
assert.match(fnBody('getFilteredPurchases'), /isMeaningfulPurchaseRecord\(p\)/, 'purchase filters should skip worthless empty rows before rendering');
assert.match(html, /function packagePurchaseCount/, 'package card should calculate purchase order count');
assert.match(readModelSource, /filter\(rowActive\)/, 'package unified view should exclude voided purchases from order count');
assert.match(fnBody('purchaseMatchesPackage'), /purchaseIdsByEntitlement[\s\S]*String\(p\.packageId\|\|''\)===String\(packageId\)/, 'package order count should use exact package id and entitlement-linked purchases');
assert.doesNotMatch(fnBody('packagePurchaseCount'), /packageName|productName|originalPackageName/, 'package order count should not count by package or product names');
assert.match(html, /function purchaseMatchesPackage\(/, 'purchase filtering should share the package matching rule used by package order counts');
assert.match(fnBody('getFilteredPurchases'), /purchaseMatchesPackage\(p,packageId\)/, 'purchase package filter should include the same purchases counted on package cards');
assert.match(fnBody('getFilteredPurchases'), /purchaseMatchesCampus\(p,campus\)/, 'purchase filters should follow the top campus selector');
assert.match(fnBody('getFilteredPurchases'), /activePurchaseDateRange\(\)[\s\S]*purchaseDateWithinRange/, 'purchase filters should follow the top time selector');
assert.match(html, /let purPackageFilterValue=''/, 'purchase package filter should keep a page-level value before the dropdown exists');
assert.match(html, /let purDateRangeFilterValue='全部'/, 'purchase page should keep a top time filter value');
assert.match(html, /function renderPurchaseTopFilters\([\s\S]*purchaseTopCampus[\s\S]*purchaseTopDate/, 'purchase page should render top campus and time filters');
assert.match(fnBody('buildCampusTabs'), /currentPage==='purchases'[\s\S]*renderPurchaseTopFilters/, 'purchase page should show top campus and time filters');
assert.match(html, /function selectPurchaseTopCampus\([\s\S]*refreshPurchaseTopFilters\(\)[\s\S]*renderPurchases\(\)/, 'purchase top campus selector should refresh orders');
assert.match(html, /function onPurchaseDateRangeFilterChange\([\s\S]*purDateRangeFilterValue=value[\s\S]*renderPurchases\(\)/, 'purchase top time selector should refresh orders');
assert.match(fnBody('getFilteredPurchases'), /purchaseSelectedPackageFilter\(\)/, 'purchase filtering should not depend only on the rendered dropdown input');
assert.match(fnBody('focusPurchaseByPackage'), /purPackageFilterValue=String\(packageId\|\|''\)[\s\S]*clearPurchasePageFiltersForPackageFocus\(\)[\s\S]*goPage\('purchases'/, 'package order drilldown should set the package filter before navigating');
assert.match(fnBody('focusPurchaseByPackage'), /purOwnerCoachFilterValue=coachName\(ownerCoach\|\|''\)/, 'package order drilldown should keep the package owner coach filter');
assert.match(fnBody('getFilteredPurchases'), /purOwnerCoachFilterValue[\s\S]*coachName\(p\.ownerCoach\)!==ownerCoachFilter/, 'purchase drilldown should filter by order owner coach when provided');
assert.match(fnBody('packagePurchaseCount'), /purchaseCountByOwnerCoach/, 'package card order count should read owner-coach count from unified package view');
assert.match(fnBody('packageBoardCardHtml'), /packagePurchaseCount\(p\.id,p\.ownerCoach\)/, 'package card order count should include the package owner coach');
assert.match(fnBody('packageBoardCardHtml'), /focusPurchaseByPackage\('\$\{p\.id\}',\$\{jsArg\(p\.ownerCoach\|\|''\)\}\)/, 'package card order drilldown should pass the package owner coach');
assert.match(fnBody('getFilteredPackages'), /const courseType=standardCourseTypeFilterValue\(p\)/, 'package card should normalize legacy course type labels to standard filter values');
assert.match(html, /function packageCoreClassLabel\([\s\S]*体验课[\s\S]*experienceType[\s\S]*私教体验课[\s\S]*小班体验课/, 'shared package label should show both experience-course names');
assert.match(html, /const PAY_METHODS=BUSINESS_TAXONOMY\.PAY_METHODS/, 'package purchase pay method should use the global pay method dictionary');
assert.match(fnBody('openPurchaseModal'), /PAY_METHODS\.map/, 'purchase create modal should use shared pay methods');
assert.match(fnBody('openPurchaseEditModal'), /PAY_METHODS\.map/, 'purchase edit modal should use shared pay methods');
assert.match(fnBody('packageBoardCardHtml'), /\$\{packagePurchaseCount\(p\.id,p\.ownerCoach\)\} 笔订单/, 'package card order button should show owner-filtered order count');
assert.doesNotMatch(packageShellConfig, /pager:/, 'package board page should not mount standard table pagination');
assert.doesNotMatch(fnBody('renderPackages'), /standardListSlice|pkgPagerInfo|renderPackagePagerControls/, 'package board should render all filtered cards without table pagination');
assert.match(buttonsCss, /\.course-package-showcase-actions \.tms-btn-primary\{[^}]*background-color:#D19356[^}]*box-shadow:none/, 'package create button should use the standardized primary toolbar style');
assert.match(buttonsCss, /\.course-package-showcase-actions \.tms-btn-primary::before\{[^}]*width:10px[^}]*background:url/, 'package create button should use the standardized plus icon');
assert.match(pagesCss, /#page-packages \.course-package-showcase \.tms-search-wrapper\{width:300px/, 'package search should use the shared 300px width');
assert.match(filtersCss, /\.tms-dropdown-display\{[^}]*height:36px[^}]*min-width:0[^}]*width:auto/, 'package filters should inherit the adaptive dropdown width standard');
assert.doesNotMatch(pagesCss, /#pkg(Type|Coach|Status|TimeBand)FilterHost \.tms-dropdown:not\(\.has-value\) \.tms-dropdown-display[\s\S]*width:60px/, 'package filters should not keep page-level 60px overrides');
assert.match(pagesCss, /package-board-column\{[^}]*border:1px solid rgba\(255,255,255,\.05\)[^}]*border-radius:12px[^}]*background:rgba\(0,0,0,\.05\)[^}]*padding:12px/, 'package board columns should use the subtle dark slot style');
assert.match(pagesCss, /body\.is-packages-page \.content\{overflow:hidden\}/, 'package page should stop the outer page scroller');
assert.match(html, /document\.body\.classList\.toggle\('is-packages-page',pg==='packages'\)/, 'package navigation should toggle the package-only scroll state');
assert.match(pagesCss, /#page-packages \.course-package-showcase\{height:100%;min-height:0\}/, 'package board should fill the fixed page area');
assert.match(pagesCss, /\.course-package-showcase-toolbar\{flex:0 0 56px;height:56px\}/, 'package filters should reserve a fixed header height');
assert.match(pagesCss, /#page-packages \.course-package-showcase-grid\{[^}]*flex:1[^}]*min-height:0[^}]*overflow-x:auto[^}]*overflow-y:hidden/, 'package board grid should only handle horizontal scrolling');
assert.match(pagesCss, /#page-packages \.course-package-showcase-grid\{[^}]*overscroll-behavior-x:contain[^}]*touch-action:pan-x pan-y/, 'package board horizontal scrolling should not trigger browser back navigation');
assert.match(pagesCss, /package-board-column\{[^}]*height:100%[^}]*display:flex[^}]*flex-direction:column/, 'package board columns should stay fixed-height flex containers');
assert.match(pagesCss, /package-board-stack\{[^}]*flex:1 1 auto[^}]*min-height:0[^}]*overflow-y:auto[^}]*overscroll-behavior:contain[^}]*padding-bottom:24px/, 'package cards below each title should scroll inside their column');
assert.match(pagesCss, /package-board-stack\{[^}]*scrollbar-width:none[^}]*-ms-overflow-style:none/, 'package board column scrollbars should be hidden');
assert.match(pagesCss, /package-board-stack::-webkit-scrollbar\{display:none\}/, 'package board column webkit scrollbars should be hidden');
assert.match(pagesCss, /package-board-title\{[^}]*color:#FFFFFF[^}]*font-size:15px[^}]*font-weight:600[^}]*letter-spacing:\.025em/, 'package board title should use white semibold tracking');
assert.match(pagesCss, /package-board-count\{[^}]*background:rgba\(255,255,255,\.2\)[^}]*color:#FFFFFF[^}]*font-size:12px[^}]*font-weight:400/, 'package board count should use white 12px regular text');
assert.match(pagesCss, /package-card-shell\{[^}]*position:relative[^}]*background:#FFFFFF[^}]*border-radius:12px[^}]*border-color:#F3F4F6[^}]*padding:12px[^}]*box-shadow:0 1px 2px 0 rgba\(0,0,0,\.05\)/, 'package cards should use white 12px rounded shadow-sm style');
assert.match(pagesCss, /package-card-shell\.is-inactive\{[^}]*opacity:\.9[^}]*border-color:#F3F4F6/, 'inactive package cards should be visually de-emphasized');
assert.match(pagesCss, /package-sales-card-body\{[^}]*gap:0[^}]*padding:0/, 'package card upper content should rely on the 12px card padding');
assert.match(pagesCss, /package-sales-subtitle\{[^}]*color:#6B7280[^}]*font-size:13px[^}]*margin-top:4px[^}]*margin-bottom:16px/, 'package audience and lesson text should use 13px gray spacing');
assert.match(pagesCss, /package-rule-line\{[^}]*font-size:11px[^}]*color:#9CA3AF[^}]*line-height:1\.2/, 'package campus and coach text should use compact gray text');
assert.match(pagesCss, /package-sales-footer \.showcase-action-btn\{[^}]*padding:4px 8px[^}]*background:#FFFFFF[^}]*color:#4B5563[^}]*border:1px solid #E5E7EB[^}]*font-size:12px/, 'package edit and deactivate buttons should use compact 12px styling');
assert.match(pagesCss, /package-card-meta\{[^}]*color:#9CA3AF[^}]*font-size:10px/, 'package created date and order count should use compact gray text');
assert.match(pagesCss, /package-time-band-badge\{[^}]*border-radius:6px[^}]*font-size:10px[^}]*font-weight:500/, 'package time band tag should use 10px medium rounded style');
assert.match(pagesCss, /package-time-band-badge\.is-prime\{[^}]*background:#FEF9E7[^}]*color:#D4AF37[^}]*border-color:#FBEBA7/, 'package prime tag should use the gold design');
assert.match(pagesCss, /package-time-band-badge\.is-offpeak\{[^}]*background:#F3F4F6[^}]*color:#6B7280[^}]*border-color:#E5E7EB/, 'package off-peak tag should use the gray design');
assert.match(pagesCss, /package-time-band-badge\.is-all\{[^}]*background:#E6F0FA[^}]*color:#4A90E2/, 'package all-day tag should use the blue design');
assert.match(fnBody('packageTimeBandBadgeHtml'), /package-time-band-crown[\s\S]*packageTimeBandBadgeClass/, 'prime package badge should include a small crown icon');
assert.match(pagesCss, /package-status-badge\{[^}]*position:absolute[^}]*top:12px[^}]*right:12px[^}]*font-size:10px[^}]*font-weight:500/, 'package sale status should be positioned at the card top right');
assert.match(pagesCss, /package-status-badge\.is-on\{background:#F0FDF4;color:#16A34A;border-color:#DCFCE7/, 'active package status should use green badge styling');
assert.match(pagesCss, /package-status-badge\.is-off\{background:#F9FAFB;color:#9CA3AF;border-color:#E5E7EB/, 'inactive package status should use gray badge styling');
assert.match(pagesCss, /package-sales-footer\{[^}]*justify-content:space-between[^}]*border-top:1px dashed #E5E7EB[^}]*margin-top:12px[^}]*padding:14px 0 0/, 'package footer should use dashed divider and card-side alignment');
assert.match(pagesCss, /package-sales-title\{font-size:13px[^}]*font-weight:600[^}]*color:#111827/, 'package title should use 13px semibold gray-900');
assert.match(pagesCss, /package-sales-title-row\{[^}]*flex-wrap:nowrap/, 'package time band tag should stay to the right of the title');
assert.match(pagesCss, /package-sales-price\{[^}]*align-items:baseline[^}]*color:#C2593F[^}]*letter-spacing:-\.025em/, 'package price should use terracotta red and tight baseline layout');
assert.match(pagesCss, /package-sales-currency\{font-size:14px;font-weight:600;margin-right:2px\}/, 'package currency should use 14px semibold with 2px right spacing');
assert.match(pagesCss, /package-sales-amount\{font-size:26px;font-weight:700\}/, 'package amount should use 26px bold text');
assert.match(pagesCss, /package-card-shell\.is-inactive \.package-sales-price\{color:#9CA3AF/, 'inactive package price should be gray');
assert.match(pagesCss, /package-sales-core\{[^}]*align-items:center/, 'package price and rule block should vertically align in the middle');
assert.match(pagesCss, /package-sales-footer \.showcase-action-btn\{[^}]*color:#4B5563[^}]*border:1px solid #E5E7EB[^}]*border-radius:4px/, 'package edit button should use gray ghost styling');
assert.match(pagesCss, /package-sales-footer \.showcase-action-btn\.is-danger\{[^}]*background:#FFFFFF[^}]*color:#EF4444[^}]*border-color:#FEE2E2/, 'package deactivate button should use red ghost styling');
assert.match(html, /function showPackageRuleTooltip\(/, 'package rule tooltip should use a fixed floating tooltip');
assert.match(fnBody('packageBoardCardHtml'), /onmouseenter="showPackageRuleTooltip\(event\)"[\s\S]*onmouseleave="hidePackageRuleTooltip\(\)"/, 'package rule tooltip should not be clipped inside the scroll column');
assert.doesNotMatch(purchaseShellConfig, /导出/, 'purchase page should remove export button');
assert.doesNotMatch(purchaseShellConfig, /导入/, 'purchase page should remove import button');
assert.doesNotMatch(purchaseShellConfig, /goPage\(\\'packages\\'\)[\s\S]*课包售卖/, 'purchase page should remove the duplicate package sales back entry');
assert.doesNotMatch(purchaseShellConfig, /purDateFrom/, 'purchase page should remove start date filter');
assert.doesNotMatch(purchaseShellConfig, /purDateTo/, 'purchase page should remove end date filter');
assert.match(html, /function openPurchaseModal[\s\S]*支付方式[\s\S]*margin-bottom:0[\s\S]*可上课教练/, 'purchase modal should put pay method and allowed coach fields on separate rows to avoid layout overlap');
assert.match(html, /openPurchaseEntryModal\(\)">课包购买/, 'purchase page should expose a direct package purchase entry button');
assert.match(purchaseShellConfig, /label:'支付日期',style:'width:100px;padding-left:20px'[\s\S]*label:'姓名',style:'width:80px'[\s\S]*label:'课包',style:'width:260px'[\s\S]*label:'实收',style:'width:70px'[\s\S]*label:'余额',style:'width:80px'[\s\S]*label:'状态',style:'width:64px'[\s\S]*label:'归属教练',style:'width:78px'[\s\S]*label:'支付方式',style:'width:78px'/, 'purchase table should widen package column and compact secondary columns');
assert.doesNotMatch(html, /购买记录用于查账和追溯/, 'purchase page should remove the long audit explanation');
assert.doesNotMatch(fnBody('purchasePackageListLabel'), /replace\(\s*\/\^1v\\d私教课/, 'purchase package column should keep the 1v1/1v2 prefix');
assert.match(fnBody('purchasePackageListLabel'), /replace\([^)]*已停售/, 'purchase package column should only remove stopped-sale copy from the package label');
assert.doesNotMatch(html, /先选择学员[\s\S]*下一步/, 'purchase modal should not require a separate first-step student gate');
assert.match(html, /购买时规则快照/, 'purchase detail should show package snapshot');
assert.match(html, /系统价格[\s\S]*成交金额[\s\S]*改价原因/, 'purchase detail should show price snapshot fields');
assert.match(html, /支付日期[\s\S]*学员/, 'purchase detail should show business date and customer identity');
assert.doesNotMatch(html, new RegExp(['系统', '录入时间'].join('')), 'purchase detail should not expose system insertion time');
assert.match(html, /function openPurchaseVoidModal/, 'purchase page should use dedicated void modal');
assert.match(html, /function voidPurchase/, 'purchase page should send void reason');
assert.match(html, /作废原因/, 'void modal should require reason');
assert.match(html, /function resolveUniqueStudentIdByText/, 'purchase import should resolve students uniquely');
assert.match(html, /function resolveUniquePackageIdByText/, 'purchase import should resolve packages uniquely');
assert.match(html, /匹配到多个/, 'purchase import should warn duplicate matches');
assert.doesNotMatch(html, /真正消课的是课包余额/, 'purchase page should remove the old package balance explanation');
assert.match(html, /私教课/, 'course pages should expose 私教课 as a fixed type');
assert.match(html, /体验课/, 'course pages should expose 体验课 as a fixed type');
assert.match(html, /训练营/, 'course pages should expose 训练营 as a fixed type');
assert.match(html, /大师课/, 'course pages should expose 大师课 as a fixed type');
assert.doesNotMatch(html, /课程性质/, 'course pages should not mention the removed 课程性质 field');
assert.doesNotMatch(courseSource, /正式课/, 'course pages should not keep the old 正式课 wording');
assert.doesNotMatch(courseSource, /半私教课/, 'course pages should not show the old half-private lesson wording');

console.log('course management nav tests passed');
