const assert = require('assert');
const { appSource: source } = require('./helpers/read-index-bundle');

assert.match(source,/data-finance-panel="ledger"[\s\S]*?财务总览[\s\S]*data-finance-panel="revenue"[\s\S]*?收入流水[\s\S]*data-finance-panel="recognized"[\s\S]*?已入账流水[\s\S]*data-finance-panel="settlement"[\s\S]*?教练结算/,'sidebar should expose the verified finance menu entries');
assert.match(source,/id="page-finance"/,'finance center page should exist');
assert.doesNotMatch(source,/id="financeTabLedger"|id="financeTabRevenue"|id="financeTabRecognized"|id="financeTabSettlement"/,'finance center should not keep duplicate top tabs after sidebar split');
assert.match(source,/id="financeLedgerPanel"/,'finance center should render ledger panel');
assert.match(source,/id="financeRevenuePanel"/,'finance center should render revenue panel');
assert.match(source,/id="financeRecognizedPanel"/,'finance center should render recognized panel');
assert.match(source,/id="financeSettlementPanel"/,'finance center should render settlement panel');
assert.match(source,/function setFinancePanel\(/,'finance center should expose tab switch logic');
assert.match(source,/financePanel='ledger'/,'finance center should default to ledger tab');
assert.match(source,/function renderFinanceCenter\(/,'finance center should expose page render logic');
assert.match(source,/function renderFinanceOverview\(/,'finance center should render summary stats inside ledger tab');
assert.match(source,/function renderFinanceLedger\(/,'finance center should render ledger table');
assert.match(source,/function renderFinanceRevenueReport\(/,'finance center should render revenue detail table');
assert.match(source,/function renderFinanceConsumeReport\(/,'finance center should render consume detail table');
assert.match(source,/function renderFinanceSettlementSummary\(/,'finance center should render settlement summary');
assert.match(source,/id="financeLedgerBusinessTypeFilterHost"/,'ledger should expose business type filter host');
assert.match(source,/id="financeLedgerTransactionTypeFilterHost"/,'ledger should expose transaction type filter host');
assert.match(source,/id="financeLedgerPayMethodFilterHost"/,'ledger should expose pay method filter host');
assert.match(source,/renderCourtDropdownHtml\('financeLedgerBusinessTypeFilter'/,'ledger business type filter should reuse shared dropdown style');
assert.match(source,/renderCourtDropdownHtml\('financeLedgerTransactionTypeFilter'/,'ledger transaction type filter should reuse shared dropdown style');
assert.match(source,/renderCourtDropdownHtml\('financeLedgerPayMethodFilter'/,'ledger pay method filter should reuse shared dropdown style');
assert.match(source,/id="financeRevenueTypeFilterHost"/,'revenue table should expose business type filter host');
assert.match(source,/id="financeRevenuePayMethodFilterHost"/,'revenue table should expose pay method filter host');
assert.match(source,/renderCourtDropdownHtml\('financeRevenueTypeFilter'/,'revenue type filter should reuse shared dropdown style');
assert.match(source,/renderCourtDropdownHtml\('financeRevenuePayMethodFilter'/,'revenue pay method filter should reuse shared dropdown style');
assert.match(source,/日期[\s\S]*星期[\s\S]*时间段[\s\S]*客户[\s\S]*业务类型[\s\S]*支付方式[\s\S]*应收[\s\S]*实收[\s\S]*差价[\s\S]*差价说明[\s\S]*收款人[\s\S]*备注[\s\S]*校区[\s\S]*状态[\s\S]*financeRevenueTbody/,'revenue table should follow the owner-facing sheet column order');
assert.doesNotMatch(source,/coachOpsRevenueSearch"[^>]*placeholder="[^"]*收入类型|<th[^>]*>收入类型<\/th>|全部收入类型/,'revenue table should no longer label business type as income type');
assert.match(source,/businessType:row\.displayBusinessType\|\|financeUnifiedRevenueType\(row\)/,'revenue rows should display standardized business type');
assert.match(source,/normalizedPaymentMethod:row\.normalizedPaymentMethod\|\|normalizePaymentMethod\(row\.paymentChannel\|\|row\.payMethod\)/,'revenue rows should use standardized payment method');
assert.doesNotMatch(source,/financeRevenuePanel[\s\S]{0,3000}关联单据/,'revenue table should not expose internal related document column');
assert.doesNotMatch(source,/financeRevenueTbody[\s\S]{0,1800}class="tms-sticky-r"/,'revenue rows should not keep a sticky right internal document column');
assert.match(source,/finance-revenue-toolbar/,'revenue toolbar should use the standardized compact toolbar class');
assert.match(source,/finance-revenue-remark/,'revenue notes should render as a single-line remark');
assert.match(source,/确认日期[\s\S]*客户[\s\S]*确认类型[\s\S]*来源项目[\s\S]*扣减标的[\s\S]*确认收入[\s\S]*校区[\s\S]*状态[\s\S]*关联单据[\s\S]*financeConsumeTbody/,'consume table should explain where recognized revenue comes from');
assert.doesNotMatch(source,/先看总账和顶部汇总/,'finance overview should remove the old guidance note');
assert.match(source,/交易时间[\s\S]*姓名[\s\S]*交易类型[\s\S]*交易金额[\s\S]*业务类型[\s\S]*支付方式[\s\S]*校区[\s\S]*操作人[\s\S]*备注[\s\S]*financeLedgerTbody/,'ledger table should use the standardized owner-facing column order');
assert.match(source,/withStandardFilterCounts\(\[\{ value:'', label:'全部', emptyDisplay:'业务类型' \}/,'ledger business type filter should use the standardized placeholder and count labels');
assert.match(source,/withStandardFilterCounts\(\[\{ value:'', label:'全部', emptyDisplay:'交易类型' \}/,'ledger transaction type filter should use the standardized placeholder and count labels');
assert.match(source,/withStandardFilterCounts\(\[\{ value:'', label:'全部', emptyDisplay:'支付方式' \}/,'ledger pay method filter should use the standardized placeholder and count labels');
assert.match(source,/renderCourtDropdownHtml\('financeLedgerBusinessTypeFilter','业务类型'/,'ledger business type dropdown should show the standardized default label');
assert.match(source,/renderCourtDropdownHtml\('financeLedgerTransactionTypeFilter','交易类型'/,'ledger transaction type dropdown should show the standardized default label');
assert.match(source,/renderCourtDropdownHtml\('financeLedgerPayMethodFilter','支付方式'/,'ledger pay method dropdown should show the standardized default label');
assert.match(source,/financeOperatorDisplayText/,'ledger should normalize operator display text in the frontend');
assert.match(source,/financeDateTimeDisplayText/,'ledger should render full Beijing datetime text');
assert.match(source,/finance-ledger-remark/,'ledger notes should render as a single-line remark');
assert.match(source,/finance-date-host finance-date-host-compact/,'ledger date filters should use the compact width wrapper');
assert.match(source,/id="financeLedgerPageSize"/,'ledger should keep the same page-size host structure as student page');
assert.match(source,/id="financeLedgerPagerBtns"/,'ledger should keep the same pager button host structure as student page');
assert.match(source,/courtDateButtonHtml\(id,value,label,handler\)/,'finance date controls should refresh reports after selecting a date');
assert.match(source,/renderFinanceLedgerReport\(\)">查询|renderFinanceLedger\(\)">查询/,'ledger date filters should have an explicit query button');
assert.match(source,/renderFinanceRevenueReport\(\)">查询/,'revenue date filters should have an explicit query button');
assert.match(source,/renderFinanceConsumeReport\(\)">查询/,'consume date filters should have an explicit query button');
assert.doesNotMatch(source,/未入账明细/,'ledger should no longer show a second prepaid detail table');
assert.match(source,/实收 \/ 已入账[\s\S]*课程收入[\s\S]*课包收入 \/ 已核销[\s\S]*会员收入 \/ 已入账[\s\S]*散客订场/,'ledger summary should use the five owner-facing finance metrics');
assert.match(source,/financeRecognitionPercent/,'overview cards should render recognition percentage');
assert.match(source,/financeTransactionAmountHtml/,'ledger should render transaction amount with standardized style');
assert.match(source,/row\.differenceReason[\s\S]*return false/,'finance ledger should hide difference rows from the main transaction table');
assert.doesNotMatch(source,/全部交易类型[\s\S]{0,3000}差异/,'finance transaction type filter should not expose difference as a business type');
assert.doesNotMatch(source,/总流水笔数/,'ledger summary should not keep total flow count card');
assert.doesNotMatch(source,/总收入（实收）|总已入账|总未入账|课程总收入 \/ 已入账|订场收入 \/ 已入账|全部动作|来源单据|未入账/,'ledger summary should not keep the old mixed top-card labels or old ledger columns');
assert.match(source,/function financeCoursePackageMetrics\(/,'finance page should centralize course/package metric splitting');
assert.match(source,/courseIncome=Number\(overview\?\.courseIncome\|\|overview\?\.packageIncome\|\|0\)/,'finance page should prefer backend course total income when available');
assert.match(source,/directCourseIncome=Number\(overview\?\.directCourseIncome/,'finance page should read direct course income separately from package income');
assert.match(source,/directCourseIncome=Number\(overview\?\.directCourseIncome\)\|\|Math\.max\(0,courseIncome-packageIncome\)/,'finance page should fall back to course minus package when backend direct course field is stale zero');
assert.match(source,/const courseMetrics=overview\?financeCoursePackageMetrics\(\[\],overview\):financeCoursePackageMetrics\(financeUnifiedRows\(\),overview\)/,'overview cards should prefer backend overview metrics instead of overriding them with row-derived metrics');
assert.match(source,/packageReceiptRows=courseRows\.filter\(row=>row\.action==='收款'&&String\(row\.sourceDocument\|\|row\.relatedDocument\|\|''\)\.startsWith\('购买记录'\)\)/,'finance page package income should be purchase-only when deriving from rows');
assert.match(source,/finalDirectCourseIncome=courseMetrics\.directIncome\|\|Math\.max\(0,finalCourseIncome-finalPackageIncome\)/,'revenue stats should derive direct course income separately from package income');
assert.match(source,/课程收入[\s\S]*课包收入[\s\S]*订场收入[\s\S]*会员储值/,'revenue stats should show direct course and package-only income separately');
assert.doesNotMatch(source,/\['课程总收入'/,'revenue stats should not label package-inclusive course income as course revenue');
assert.match(source,/function financeRevenueBaseRows\(\)\{[\s\S]*return financeUnifiedRows\(\)\.filter/,'revenue report should read from the unified finance snapshot');
assert.match(source,/function financeRecognizedRows\(\)\{[\s\S]*return financeUnifiedRows\(\)\.filter/,'recognized report should read from the unified finance snapshot');
assert.match(source,/const businessRows=rows\.filter\(row=>!row\.differenceReason\);[\s\S]*const diffRows=rows\.filter\(row=>row\.differenceReason\);[\s\S]*bookingIncome=businessRows\.filter\(row=>\['会员订场','散客订场','约球局'\]\.includes\(row\.sourceBusinessCategory\)\)/,'revenue stats should count booking income by original business category and split diff rows');
assert.match(source,/storedValueConsumedRows=rows\.filter\(row=>row\.businessTypeLevel1==='场地'&&row\.businessTypeLevel2==='会员订场'&&row\.transactionType==='消耗'\)/,'stored value recognized amount should use standardized member booking consumption rows');
assert.match(source,/id="financeRevenuePagerInfo"/,'revenue should expose pager info');
assert.match(source,/id="financeRevenuePageSize"/,'revenue should expose page size selector');
assert.match(source,/id="financeRevenuePagerBtns"/,'revenue should expose pager buttons');
assert.match(source,/function setFinanceRevenuePageSize\(/,'revenue should support switching page size');
assert.match(source,/function setFinanceRevenuePage\(/,'revenue should support switching pages');
assert.match(source,/function resetFinanceRevenuePage\(/,'revenue filters should reset to the first page');
assert.match(source,/renderCourtDropdownHtml\('financeRevenuePageSizeValue',`\$\{financeRevenuePageSize\}条\/页`/,'revenue page size selector should reuse shared dropdown style');
assert.match(source,/id="financeLedgerPagerInfo"/,'ledger should expose pager info');
assert.match(source,/id="financeLedgerPageSize"/,'ledger should expose page size selector');
assert.match(source,/id="financeLedgerPagerBtns"/,'ledger should expose pager buttons');
assert.match(source,/function setFinanceLedgerPageSize\(/,'ledger should support switching page size');
assert.match(source,/function setFinanceLedgerPage\(/,'ledger should support switching pages');
assert.match(source,/20条\/页[\s\S]*50条\/页[\s\S]*100条\/页/,'ledger page size selector should offer 20, 50, and 100 rows per page');
assert.match(source,/查看迟到月结/,'finance center should expose late settlement entry');

console.log('finance page view tests passed');
