const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: source } = require('./helpers/read-index-bundle');
function sliceBetween(text,startMarker,endMarker){
  const start = text.indexOf(startMarker);
  const end = start === -1 ? -1 : text.indexOf(endMarker, start);
  return text.slice(start, end === -1 ? text.length : end);
}
const ledgerShell = sliceBetween(source, "key:'finance-ledger'", "key:'finance-revenue'");
const revenueShell = sliceBetween(source, "key:'finance-revenue'", "key:'finance-recognized'");
const recognizedShell = sliceBetween(source, "key:'finance-recognized'", 'function mountStandardListShells');
const ledgerPanel = sliceBetween(source, 'id="financeLedgerPanel"', 'id="financeRevenuePanel"') + ledgerShell;
const revenuePanelStart = source.indexOf('id="financeRevenuePanel"');
const revenuePanelEnd = source.indexOf('id="financeRecognizedPanel"', revenuePanelStart);
const revenuePanel = source.slice(revenuePanelStart, revenuePanelEnd === -1 ? source.length : revenuePanelEnd) + revenueShell;
const recognizedPanel = sliceBetween(source, 'id="financeRecognizedPanel"', 'id="financeSettlementPanel"') + recognizedShell;
const pagesCss = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'pages.css'), 'utf8');
const financeSnapshotSource = fs.readFileSync(path.join(__dirname, '..', 'server', 'page-data', 'finance-snapshot.js'), 'utf8');

assert.match(source,/data-finance-panel="ledger"[\s\S]*?财务总览[\s\S]*data-finance-panel="revenue"[\s\S]*?收入流水/,'sidebar should expose the visible finance menu entries');
assert.doesNotMatch(source,/data-finance-panel="settlement"[\s\S]*?教练结算/,'sidebar should hide coach settlement entry');
assert.match(source,/id="page-finance"/,'finance center page should exist');
assert.doesNotMatch(source,/id="financeTabLedger"|id="financeTabRevenue"|id="financeTabRecognized"|id="financeTabSettlement"/,'finance center should not keep duplicate top tabs after sidebar split');
assert.match(source,/id="financeLedgerPanel"/,'finance center should render ledger panel');
assert.match(source,/id="financeRevenuePanel"/,'finance center should render revenue panel');
assert.match(source,/id="financeRecognizedPanel"/,'finance center should render recognized panel');
assert.match(source,/id="financeSettlementPanel"/,'finance center should render settlement panel');
assert.match(source,/function setFinancePanel\(/,'finance center should expose tab switch logic');
assert.match(source,/financePanel='ledger'/,'finance center should default to ledger tab');
assert.match(source,/function renderFinanceCenter\(/,'finance center should expose page render logic');
assert.match(source,/function renderFinanceOverview\(/,'finance center should render summary stats inside ledger tab');
assert.match(source,/function renderFinanceLedger\(/,'finance center should render ledger table');
assert.match(source,/function renderFinanceRevenueReport\(/,'finance center should render revenue detail table');
assert.match(source,/function renderFinanceConsumeReport\(/,'finance center should render consume detail table');
assert.match(source,/function renderFinanceSettlementSummary\(/,'finance center should render settlement summary');
assert.match(ledgerShell,/financeLedgerBusinessTypeFilterHost/,'ledger should expose business type filter host');
assert.match(ledgerShell,/financeLedgerTransactionTypeFilterHost/,'ledger should expose transaction type filter host');
assert.match(ledgerShell,/financeLedgerPayMethodFilterHost/,'ledger should expose pay method filter host');
assert.match(source,/renderStandardDropdownHtml\('financeLedgerBusinessTypeFilter'/,'ledger business type filter should reuse shared dropdown style');
assert.match(source,/renderStandardDropdownHtml\('financeLedgerTransactionTypeFilter'/,'ledger transaction type filter should reuse shared dropdown style');
assert.match(source,/renderStandardDropdownHtml\('financeLedgerPayMethodFilter'/,'ledger pay method filter should reuse shared dropdown style');
assert.match(revenueShell,/financeRevenueTypeFilterHost/,'revenue table should expose business type filter host');
assert.match(revenueShell,/financeRevenuePayMethodFilterHost/,'revenue table should expose pay method filter host');
assert.match(source,/renderStandardDropdownHtml\('financeRevenueTypeFilter'/,'revenue type filter should reuse shared dropdown style');
assert.match(source,/renderStandardDropdownHtml\('financeRevenuePayMethodFilter'/,'revenue pay method filter should reuse shared dropdown style');
assert.match(revenuePanel,/financeRevenueTbody[\s\S]*交易时间[\s\S]*姓名[\s\S]*业务类型[\s\S]*支付方式[\s\S]*应收[\s\S]*实收[\s\S]*差价[\s\S]*差价说明[\s\S]*校区[\s\S]*操作人[\s\S]*备注/,'revenue table should follow the owner-facing sheet column order');
assert.doesNotMatch(revenuePanel,/星期|时间段|客户|收款人|状态/,'revenue table should remove the old split time, collector, and status columns');
assert.doesNotMatch(source,/coachOpsRevenueSearch"[^>]*placeholder="[^"]*收入类型|<th[^>]*>收入类型<\/th>|全部收入类型/,'revenue table should no longer label business type as income type');
assert.match(source,/businessType:row\.displayBusinessType\|\|financeUnifiedRevenueType\(row\)/,'revenue rows should display standardized business type');
assert.match(source,/normalizedPaymentMethod:row\.normalizedPaymentMethod\|\|normalizePaymentMethod\(row\.paymentChannel\|\|row\.payMethod\)/,'revenue rows should use standardized payment method');
assert.doesNotMatch(revenuePanel,/关联单据/,'revenue table should not expose internal related document column');
assert.doesNotMatch(revenuePanel,/class="tms-sticky-r"/,'revenue rows should not keep a sticky right internal document column');
assert.match(revenueShell,/toolbarClass:'tms-toolbar finance-table-toolbar finance-revenue-toolbar'/,'revenue toolbar should use the standardized compact finance toolbar class');
assert.match(recognizedShell,/toolbarClass:'tms-toolbar finance-table-toolbar'/,'recognized toolbar should use the same standardized compact finance toolbar class');
assert.match(source,/finance-revenue-remark/,'revenue notes should render as a single-line remark');
assert.match(recognizedPanel,/financeConsumeTbody[\s\S]*交易时间[\s\S]*姓名[\s\S]*业务类型[\s\S]*支付方式[\s\S]*扣减标的[\s\S]*确认收入[\s\S]*校区[\s\S]*操作人[\s\S]*备注/,'recognized table should follow the owner-facing ledger column order');
assert.doesNotMatch(recognizedPanel,/确认日期|客户|确认类型|来源项目|状态|关联单据/,'recognized table should remove old internal source/status columns');
assert.doesNotMatch(source,/先看总账和顶部汇总/,'finance overview should remove the old guidance note');
assert.match(ledgerPanel,/financeLedgerTbody[\s\S]*交易时间[\s\S]*姓名[\s\S]*交易类型[\s\S]*交易金额[\s\S]*业务类型[\s\S]*支付方式[\s\S]*校区[\s\S]*操作人[\s\S]*备注/,'ledger table should use the standardized owner-facing column order');
assert.match(source,/withLinkedFilterCounts\(\[[\s\S]*emptyDisplay:'业务类型'/,'ledger business type filter should use linked standardized count labels');
assert.match(source,/withLinkedFilterCounts\(\[[\s\S]*emptyDisplay:'交易类型'/,'ledger transaction type filter should use linked standardized count labels');
assert.match(source,/withLinkedFilterCounts\(\[[\s\S]*emptyDisplay:'支付方式'/,'ledger pay method filter should use linked standardized count labels');
assert.match(source,/renderStandardDropdownHtml\('financeLedgerBusinessTypeFilter','业务类型'/,'ledger business type dropdown should show the standardized default label');
assert.match(source,/renderStandardDropdownHtml\('financeLedgerTransactionTypeFilter','交易类型'/,'ledger transaction type dropdown should show the standardized default label');
assert.match(source,/renderStandardDropdownHtml\('financeLedgerPayMethodFilter','支付方式'/,'ledger pay method dropdown should show the standardized default label');
assert.match(source,/financeOperatorDisplayText/,'ledger should normalize operator display text in the frontend');
assert.match(source,/financeDateTimeDisplayText/,'ledger should render full Beijing datetime text');
assert.match(source,/const businessDate=String\(row\?\.businessDate\|\|row\?\.purchaseDate\|\|''\)/,'revenue transaction time should read purchaseDate when businessDate is not present');
assert.match(source,/function financeDateTimeDisplayText\([\s\S]*businessDate\.slice\(0,19\)/,'ledger transaction time should keep seconds when backend provides full datetime');
assert.doesNotMatch(source,/timeText\.match/,'ledger transaction time should not fall back to course time text');
assert.match(source,/finance-ledger-remark/,'ledger notes should render as a single-line remark');
assert.match(source,/function financeHumanNote\(/,'finance tables should clean system-generated audit notes before display');
assert.match(source,/订场收入细项修数\|会员订场修正\|马坡补账\|私教课CSV.*导入/,'finance note cleaner should hide import and repair audit text');
assert.match(source,/consumeRecordText='课包消耗'\+'记录'/,'finance note cleaner should hide generated package consume audit text');
assert.match(source,/financeHumanNote\(row\.notes\)/,'finance tables should render cleaned human notes');
assert.match(source,/financeHumanNote\(row\.notes\)[\s\S]*renderFinancePrepaidBalance/,'prepaid balance notes should render cleaned human notes');
assert.match(source,/collector==='未记录'/,'finance tables should not show missing historical operators as 未记录');
assert.match(source,/importHint\|\|collector==='未记录'[\s\S]*return '系统导入'/,'finance tables should show imported or repaired rows as 系统导入 when no account operator exists');
assert.doesNotMatch(ledgerPanel,/>\s*查询\s*</,'ledger toolbar should not keep a local query button');
assert.doesNotMatch(revenuePanel,/>\s*查询\s*</,'revenue toolbar should not keep a local query button');
assert.doesNotMatch(recognizedPanel,/>\s*查询\s*</,'recognized toolbar should not keep a local query button');
assert.match(revenueShell,/statsId:'coachOpsRevenueStats'[\s\S]*statsClass:'tms-stats-row finance-ledger-stats'/,'revenue stats should reuse the finance summary card style');
assert.match(recognizedShell,/statsId:'coachOpsConsumeStats'[\s\S]*statsClass:'tms-stats-row finance-ledger-stats'/,'recognized stats should reuse the finance summary card style');
assert.match(pagesCss,/#page-finance #financeLedgerPanel \.tms-table td,#page-finance #financeRevenuePanel \.tms-table td,#page-finance #financeRecognizedPanel \.tms-table td\{[^}]*font-size:12px/,'finance ledger, revenue, and recognized tables should share the compact global table text size');
assert.match(pagesCss,/#page-finance \.finance-table-toolbar\{[^}]*margin-bottom:10px/,'finance revenue and recognized list toolbars should share the same search-to-table spacing');
assert.match(ledgerShell,/pageSizeId:'financeLedgerPageSize'/,'ledger should keep the same page-size host structure as student page');
assert.match(ledgerShell,/buttonsId:'financeLedgerPagerBtns'/,'ledger should keep the same pager button host structure as student page');
assert.doesNotMatch(source,/financeLedgerFromHost|financeLedgerToHost|coachOpsRevenueFromHost|coachOpsRevenueToHost|coachOpsConsumeFromHost|coachOpsConsumeToHost/,'finance panels should remove local date filters and use the global top time filter');
assert.doesNotMatch(source,/document\.getElementById\('financeLedgerFrom'\)|document\.getElementById\('coachOpsRevenueFrom'\)|document\.getElementById\('coachOpsConsumeFrom'\)/,'finance data rows should not read removed local date inputs');
assert.doesNotMatch(source,/未入账明细/,'ledger should no longer show a second prepaid detail table');
assert.match(source,/总实收[\s\S]*总核销确收[\s\S]*会员储值[\s\S]*散客订场[\s\S]*课程收入/,'ledger summary should show the five requested owner-facing finance metrics');
assert.doesNotMatch(source,/散客单次课程|课包专项/,'ledger summary should merge direct course and package income into course income');
assert.match(source,/课程实收 vs 课程已核销/,'merged course summary card should explain course income and recognized revenue');
assert.match(source,/class="tms-stat-sub"/,'finance summary card captions should use the visible shared caption style');
assert.doesNotMatch(source,/总核销确收[\s\S]{0,260}financePercent\(metrics\.totalRecognized,metrics\.totalCash\)/,'overview total recognized card should not show a recognized-vs-cash percentage under date filters');
assert.doesNotMatch(source,/storedValueRecognized,metrics\.totalRecognized/,'overview membership recognized amount should not show a percentage');
assert.doesNotMatch(source,/courseRecognized,metrics\.totalRecognized/,'overview course recognized amount should not show a percentage');
assert.doesNotMatch(pagesCss,/#page-finance \.finance-ledger-stats \.tms-stat-value\{[^}]*overflow:hidden/,'finance overview stat values should not clip long currency text');
assert.match(source,/Math\.round\(\(Number\(numerator\|\|0\)\/base\)\*100\)/,'finance card percentages should drop decimal places');
assert.match(source,/function financeFitOverviewStatValues\(\)/,'finance overview should shrink oversized stat values instead of clipping them');
assert.match(source,/while\(el\.scrollWidth>el\.clientWidth&&size>12\)/,'finance overview should keep shrinking until the value fits');
assert.match(source,/financeTransactionAmountHtml/,'ledger should render transaction amount with standardized style');
assert.match(source,/row\.differenceReason[\s\S]*return false/,'finance ledger should hide difference rows from the main transaction table');
assert.doesNotMatch(source,/全部交易类型[\s\S]{0,3000}差异/,'finance transaction type filter should not expose difference as a business type');
assert.doesNotMatch(source,/总流水笔数/,'ledger summary should not keep total flow count card');
assert.doesNotMatch(source,/实收 \/ 已入账|课包收入 \/ 已核销|会员收入 \/ 已入账|总收入（实收）|总已入账|总未入账|课程总收入 \/ 已入账|订场收入 \/ 已入账|全部动作|来源单据|未入账/,'ledger summary should not keep the old mixed top-card labels or old ledger columns');
assert.match(source,/function financeCoursePackageMetrics\(/,'finance page should centralize course/package metric splitting');
assert.match(source,/courseIncome=Number\(overview\?\.courseIncome\|\|overview\?\.packageIncome\|\|0\)/,'finance page should prefer backend course total income when available');
assert.match(source,/directCourseIncome=Number\(overview\?\.directCourseIncome/,'finance page should read direct course income separately from package income');
assert.match(source,/directCourseIncome=Number\(overview\?\.directCourseIncome\)\|\|Math\.max\(0,courseIncome-packageIncome\)/,'finance page should fall back to course minus package when backend direct course field is stale zero');
assert.match(source,/packageReceiptRows=courseRows\.filter\(row=>row\.action==='收款'&&String\(row\.sourceDocument\|\|row\.relatedDocument\|\|''\)\.startsWith\('购买记录'\)\)/,'finance page package income should be purchase-only when deriving from rows');
assert.match(source,/const metrics=financeCurrentMetrics\(financeLedgerRows\(\)\)/,'overview cards should calculate from the currently filtered ledger rows');
assert.match(source,/const courseIncome=directCourseIncome\+packageIncome/,'current overview metrics should merge direct course and package income');
assert.match(source,/directCourseIncome=businessRows\.filter\(row=>row\.sourceBusinessCategory==='课程'&&String\(row\.relatedDocument\|\|''\)\.startsWith\('排课'\)\)/,'revenue stats should derive direct course income from filtered schedule receipts');
assert.match(source,/const courseIncome=directCourseIncome\+packageIncome[\s\S]*课程流水/,'revenue stats should merge direct course and package income into course flow');
assert.match(source,/成交笔数[\s\S]*实收合计[\s\S]*会员储值[\s\S]*散客订场[\s\S]*课程流水/,'revenue stats should show requested income card labels');
assert.doesNotMatch(source,/散客课程|课包收入/,'revenue stats should not show direct course or package as separate cards');
assert.match(source,/const courseRecognized=directCourseRecognized\+packageRecognized[\s\S]*课程已入账/,'recognized stats should merge direct course and package recognized revenue');
assert.match(source,/流水条数[\s\S]*确收合计[\s\S]*散客订场核销[\s\S]*会员耗卡核销[\s\S]*课程已入账/,'recognized stats should show requested recognized card labels');
assert.doesNotMatch(source,/课包消课核销|散客课程核销/,'recognized stats should not show direct course or package recognized cards separately');
assert.doesNotMatch(source,/\['课程总收入'/,'revenue stats should not label package-inclusive course income as course revenue');
assert.match(source,/function financeRevenueBaseRows\(\)\{[\s\S]*return financeUnifiedRows\(\)\.filter/,'revenue report should read from the unified finance snapshot');
assert.match(source,/function financeRecognizedRows\(\)\{[\s\S]*return financeUnifiedRows\(\)\.filter/,'recognized report should read from the unified finance snapshot');
assert.match(source,/bookingIncome=businessRows\.filter\(row=>\['会员订场','散客订场','约球局'\]\.includes\(row\.sourceBusinessCategory\)\)/,'revenue stats should count booking income by original business category');
assert.match(source,/storedValueConsumedRows=businessRows\.filter\(row=>[\s\S]*row\.businessTypeLevel2==='会员订场'[\s\S]*row\.businessType==='会员订场'/,'stored value recognized amount should use standardized member booking consumption rows');
assert.match(financeSnapshotSource,/businessDate:financeBusinessDateTime\(row\.createdAt,row\.recordedAt,row\.relatedDate\)/,'course consume transaction time should prefer ledger creation time over future class time');
assert.match(revenueShell,/infoId:'financeRevenuePagerInfo'/,'revenue should expose pager info');
assert.match(revenueShell,/pageSizeId:'financeRevenuePageSize'/,'revenue should expose page size selector');
assert.match(revenueShell,/buttonsId:'financeRevenuePagerBtns'/,'revenue should expose pager buttons');
assert.match(source,/function setFinanceRevenuePageSize\(/,'revenue should support switching page size');
assert.match(source,/function setFinanceRevenuePage\(/,'revenue should support switching pages');
assert.match(source,/function resetFinanceRevenuePage\(/,'revenue filters should reset to the first page');
assert.match(source,/renderPageSizeSelectorHtml\('financeRevenuePageSizeValue',financeRevenuePageSize,'setFinanceRevenuePageSize'\)/,'revenue page size selector should reuse shared numeric page-size dropdown');
assert.match(ledgerShell,/infoId:'financeLedgerPagerInfo'/,'ledger should expose pager info');
assert.match(ledgerShell,/pageSizeId:'financeLedgerPageSize'/,'ledger should expose page size selector');
assert.match(ledgerShell,/buttonsId:'financeLedgerPagerBtns'/,'ledger should expose pager buttons');
assert.match(source,/function setFinanceLedgerPageSize\(/,'ledger should support switching page size');
assert.match(source,/function setFinanceLedgerPage\(/,'ledger should support switching pages');
assert.match(source,/renderPageSizeSelectorHtml\('financeLedgerPageSizeValue',financeLedgerPageSize,'setFinanceLedgerPageSize'\)/,'ledger page size selector should reuse shared numeric page-size dropdown');
assert.match(source,/查看迟到月结/,'finance center should expose late settlement entry');
assert.match(source,/data-sidebar-icon="finance-ledger" width="15" height="15"/,'finance overview sidebar icon should use the 15px custom icon');
assert.match(source,/data-sidebar-icon="finance-revenue" width="14" height="14"/,'revenue sidebar icon should use the 14px custom icon');
assert.match(source,/data-sidebar-icon="finance-recognized" width="16" height="16"/,'recognized revenue sidebar icon should use the 16px custom icon');

console.log('finance page view tests passed');
