const assert = require('assert');
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, '../public/index.html'), 'utf8');
const components = fs.readFileSync(path.join(__dirname, '../public/assets/scripts/core/components.js'), 'utf8');

assert.match(html, /assets\/styles\/base\.css/, 'index.html should load base.css');
assert.match(html, /assets\/styles\/components\.css/, 'index.html should load components.css');
assert.match(html, /assets\/styles\/pages\.css/, 'index.html should load pages.css');
assert.match(html, /assets\/styles\/pages\.css\?v=/, 'index.html should version pages.css to bust stale modal styles');
assert.match(html, /assets\/styles\/pages\.css\?v=20260720-coach-calendar-now-line-align-v1/, 'index.html should bust stale cached pages.css after coach calendar current-time alignment fix');
assert.match(html, /assets\/scripts\/core\/constants\.js/, 'index.html should load constants.js');
assert.match(html, /assets\/scripts\/core\/utils\.js/, 'index.html should load utils.js');
assert.match(html, /assets\/scripts\/core\/utils\.js\?v=20260608-student-drawer-v2/, 'index.html should bust stale cached utils.js after coach operations split changes');
assert.match(html, /assets\/scripts\/core\/api\.js/, 'index.html should load api.js');
assert.match(html, /assets\/scripts\/core\/state\.js/, 'index.html should load state.js');
assert.match(html, /assets\/scripts\/core\/shell\.js/, 'index.html should load shell.js');
assert.match(html, /assets\/scripts\/core\/bootstrap\.js/, 'index.html should load bootstrap.js');
assert.match(html, /assets\/scripts\/pages\/admin-users\.js/, 'index.html should load admin-users page module');
assert.match(html, /assets\/scripts\/pages\/coaches\.js/, 'index.html should load coaches page module');
assert.match(html, /assets\/scripts\/pages\/campusmgr\.js/, 'index.html should load campusmgr page module');
assert.match(html, /assets\/scripts\/pages\/leads\.js/, 'index.html should load leads page module');
assert.doesNotMatch(html, /assets\/scripts\/pages\/classes\.js|assets\/scripts\/pages\/plans\.js/, 'index.html should not load deprecated classes or plans page modules');
assert.match(html, /assets\/scripts\/pages\/products\.js/, 'index.html should load products page module');
assert.match(html, /assets\/scripts\/pages\/packages\.js/, 'index.html should load packages page module');
assert.match(html, /assets\/scripts\/pages\/purchases\.js/, 'index.html should load purchases page module');
assert.match(html, /assets\/scripts\/pages\/entitlements\.js/, 'index.html should load entitlements page module');
assert.match(html, /assets\/scripts\/pages\/coach-portal\.js/, 'index.html should load coach-portal page module');
assert.match(html, /assets\/scripts\/pages\/coachops\.js/, 'index.html should load coachops page module');
assert.match(html, /assets\/scripts\/pages\/coachops\.js\?v=20260719-coach-calendar-time-buffer-v1/, 'index.html should version coachops.js after coach calendar time buffer polish');
assert.match(html, /assets\/scripts\/standard\/charts\.js\?v=20260701-channel-quality-matrix-v1/, 'index.html should bust stale cached charts.js after channel quality matrix changes');
assert.match(html, /assets\/scripts\/pages\/operations\.js\?v=20260701-channel-quality-matrix-v1/, 'index.html should bust stale cached operations.js after channel quality matrix changes');
assert.match(html, /assets\/scripts\/pages\/courts\.js/, 'index.html should load courts page module');
assert.match(html, /assets\/scripts\/pages\/courts\.js\?v=/, 'index.html should bust stale cached courts.js when court filters change');
assert.match(html, /assets\/scripts\/pages\/students\.js/, 'index.html should load students page module');
assert.match(html, /assets\/scripts\/pages\/students\.js\?v=20260612-student-delete-card-v1/, 'index.html should bust stale cached students.js after student delete card updates');
assert.match(html, /assets\/scripts\/pages\/schedule\.js/, 'index.html should load schedule page module');
assert.match(html, /id="sidebarHost"/, 'index.html should keep the shared sidebar mount host');
assert.match(html, /id="topbarHost"/, 'index.html should keep the shared topbar mount host');
assert.doesNotMatch(html, /goPage\('leads',this\)[\s\S]*线索池/, 'index.html should not keep sidebar entries inline');
assert.doesNotMatch(html, /<div class="topbar">[\s\S]*id="topTitle"/, 'index.html should not keep topbar markup inline');
assert.match(components, /goPage\('leads',this\)[\s\S]*线索池/, 'components.js should render the leads sidebar entry');
assert.match(components, /function renderTopbarShell\(/, 'components.js should render the shared topbar');
assert.match(html, /id="page-leads"/, 'index.html should render the leads page section');
assert.match(html, /assets\/scripts\/pages\/schedule\.js\?v=/, 'index.html should version schedule.js to avoid stale modal behavior');
assert.match(html, /assets\/scripts\/pages\/schedule\.js\?v=20260716-schedule-edit-calendar-v1/, 'index.html should bust stale cached schedule.js after edit entitlement recommendation fixes');

assert.doesNotMatch(html, /<style>[\s\S]*<\/style>/, 'index.html should no longer keep inline style blocks');
assert.doesNotMatch(html, /<script>[\s\S]*<\/script>/, 'index.html should no longer keep one giant inline script block');

console.log('index asset split tests passed');
