const assert = require('assert');
const fs = require('fs');
const path = require('path');

const publicDir = path.join(__dirname, '../public');
const html = fs.readFileSync(path.join(publicDir, 'index.html'), 'utf8');
const componentsSource = fs.readFileSync(path.join(publicDir, 'assets/scripts/core/components.js'), 'utf8');
const standardSource = fs.readFileSync(path.join(publicDir, 'assets/scripts/standard/components.js'), 'utf8');
const bootstrapSource = fs.readFileSync(path.join(publicDir, 'assets/scripts/core/bootstrap.js'), 'utf8');
const stateSource = fs.readFileSync(path.join(publicDir, 'assets/scripts/core/state.js'), 'utf8');
const apiSource = fs.readFileSync(path.join(__dirname, '../api/index.js'), 'utf8');
const css = [
  'assets/styles/pages.css',
  'assets/styles/components/tables.css',
  'assets/styles/components/modals.css'
].map(file=>fs.readFileSync(path.join(publicDir, file), 'utf8')).join('\n');
const leadsSourcePath = path.join(publicDir, 'assets/scripts/pages/leads.js');
const leadsSource = fs.existsSync(leadsSourcePath) ? fs.readFileSync(leadsSourcePath, 'utf8') : '';

function fnBody(name){
  const start = leadsSource.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = leadsSource.indexOf('\nfunction ', start + 1);
  return leadsSource.slice(start, nextFunction === -1 ? leadsSource.length : nextFunction);
}

assert.match(componentsSource, /goPage\('leads',this\)[\s\S]*线索池/, 'sidebar should expose a leads entry');
assert.match(html, /id="page-leads" data-standard-list-shell="leads"/, 'leads page should mount through the standard list shell');
assert.match(standardSource, /function renderStandardSearchHtml\(\{id='',placeholder='搜索姓名、手机号'[\s\S]*key:'leads'[\s\S]*search:\{id:'leadSearch'/, 'leads page should provide the agreed search field through the standard list shell');
assert.match(standardSource, /leadSourceFilterHost/, 'leads page should provide source filter host');
assert.match(standardSource, /leadConsultFilterHost/, 'leads page should provide consult filter host');
assert.match(standardSource, /leadStageFilterHost/, 'leads page should provide a single lead stage filter host');
assert.doesNotMatch(standardSource, /leadStatusFilterHost|leadConversionTypeFilterHost/, 'leads page should not keep duplicate status and conversion filters');
assert.doesNotMatch(standardSource, /leadConvertedFilterHost/, 'leads page should not keep the ambiguous converted yes/no filter');
assert.match(standardSource, /leadOwnerFilterHost/, 'leads page should provide owner filter host');
assert.doesNotMatch(html, /id="leadTodoFilterHost"/, 'leads page should remove the follow-up todo filter host');
assert.doesNotMatch(html, /id="leadDateFilterHost"/, 'leads page should remove the date filter host');
assert.match(standardSource, /class="tms-import-action" onclick="openLeadImportPreviewModal\(\)">导入<\/span>/, 'leads toolbar should expose the shared text import entry');
assert.match(html, /assets\/styles\/components\/modals\.css/, 'index should load shared modal styles');
assert.match(standardSource, /新增线索/, 'leads toolbar should expose the create lead entry');
assert.doesNotMatch(html, /id="leadDateScopeBar"[\s\S]*lead-date-scope-label">线索时间/, 'leads page should remove the top lead time scope row');
assert.doesNotMatch(html, /id="leadDateFrom_btn"[\s\S]*toggleGlobalDatePicker\(event,'leadDateFrom','leadDateFrom_btn','开始日期'\)[\s\S]*id="leadDateTo_btn"[\s\S]*toggleGlobalDatePicker\(event,'leadDateTo','leadDateTo_btn','结束日期'\)/, 'leads page should not render custom lead date controls');
assert.doesNotMatch(html, /<input class="lead-date-input" id="leadDateFrom" type="date"/, 'custom lead date controls should not expose native date inputs');
assert.match(standardSource, /statsId:'leadStatsRow'/, 'leads page should expose the top stats row');
assert.match(standardSource, /微信名[\s\S]*线索时间[\s\S]*线索渠道[\s\S]*客户类型[\s\S]*需求产品[\s\S]*水平[\s\S]*基本信息[\s\S]*线索阶段[\s\S]*跟进优先级[\s\S]*跟进人[\s\S]*体验课时间[\s\S]*成交教练[\s\S]*流失原因[\s\S]*操作/, 'leads table should expose the requested reordered columns');
assert.doesNotMatch(standardSource, /label:'跟进状态'|label:'转化类型'/, 'leads table should not keep duplicate status and conversion columns');
assert.doesNotMatch(standardSource, /label:'是否转化'/, 'leads table should not keep the ambiguous converted yes/no column');
assert.match(standardSource, /bodyId:'leadTbody'/, 'leads page should provide the list tbody mount');
assert.match(standardSource, /infoId:'leadPagerInfo'/, 'leads page should provide pager info');
assert.match(standardSource, /pageSizeId:'leadPageSize'/, 'leads page should provide page size selector host');
assert.match(standardSource, /buttonsId:'leadPagerBtns'/, 'leads page should provide pager buttons');
assert.match(standardSource, /leadSearch[\s\S]*oninput:'applyLeadSearch\(\)'/, 'leads search should update results immediately while typing');
assert.doesNotMatch(html, /leadSearch[\s\S]*onkeydown="if\(event\.key==='Enter'\)applyLeadSearch\(\)"/, 'leads search should not wait for enter');
assert.doesNotMatch(html, /onclick="applyLeadSearch\(\)">查询/, 'leads toolbar should remove the query button');
assert.doesNotMatch(html, /onclick="resetLeadFilters\(\)"[\s\S]*重置/, 'leads toolbar should remove the reset button');
assert.match(standardSource, /label:'微信名'[\s\S]*className:'tms-sticky-l'|className:'tms-sticky-l'[\s\S]*label:'微信名'/, 'leads table should pin the first identity column');
assert.match(standardSource, /data-lead-sort="leadDate"[\s\S]*线索时间/, 'leads table should sort by lead date');
assert.match(standardSource, /data-lead-sort="trialLessonAt"[\s\S]*体验课时间/, 'leads table should sort by trial lesson date');
assert.doesNotMatch(html, /最近跟进|跟进次数|正式课报名时间/, 'leads table should remove columns outside the requested order');

assert.match(bootstrapSource, /'leads'/, 'bootstrap should register leads routing');
assert.match(bootstrapSource, /leads:'线索池'/, 'bootstrap should map the leads page title');
assert.match(bootstrapSource, /globalTopFilterPages\(\)\.includes\(pg\)[\s\S]*\?'flex':'none'/, 'lead page should expose the top campus filter');

assert.match(leadsSource, /function renderLeads\(/, 'leads page should expose the list renderer');
assert.match(leadsSource, /function leadDedupKey\(/, 'leads page should deduplicate repeated lead rows');
assert.match(leadsSource, /function renderLeadTag\(/, 'leads page should render tag-style lead cells');
assert.match(leadsSource, /function leadTrialDateText\(/, 'leads page should format trial lesson date with relative days');
assert.match(leadsSource, /function leadRecentDateText\(/, 'leads page should format recent follow-up date with relative days');
assert.match(leadsSource, /function leadFormalSignupDateText\(/, 'leads page should format formal signup date');
assert.match(leadsSource, /function leadPurchaseSignupDate\(/, 'converted course leads should be able to use package purchase dates for formal signup date');
assert.match(leadsSource, /function leadFollowupCount\(/, 'leads page should expose the follow-up count helper');
assert.match(leadsSource, /function leadCanonicalNameKey\(/, 'leads page should merge leads with the same visible name');
assert.match(leadsSource, /function leadStatsData\(/, 'leads page should expose summary stats for the filtered lead rows');
assert.match(leadsSource, /线索数[\s\S]*全盘最终成交[\s\S]*邀约体验课成交[\s\S]*体验课成单成交[\s\S]*高意向蓄水池/, 'lead stats should expose the requested five metrics');
assert.match(leadsSource, /已成交线索 \/ 线索数[\s\S]*已上体验课 \/ 线索数[\s\S]*已体验且成交 \/ 已上体验课[\s\S]*已体验待成交 \/ 已上体验课/, 'lead stats should explain the requested formulas');
assert.match(leadsSource, /function leadDateRangeForPreset\(/, 'leads page should expose date preset range helper');
assert.match(leadsSource, /function setLeadDatePreset\(/, 'leads page should expose lead date preset switching');
assert.match(leadsSource, /function setLeadCustomDateRange\(/, 'leads page should expose custom lead date range switching');
assert.match(leadsSource, /if\(!leadInDateRange\(lead,getLeadDateFilterRange\(\)\)\)return false;/, 'lead filtering should apply the global lead date scope');
assert.match(leadsSource, /function renderLeads\([\s\S]*const list=getSortedLeads\(getFilteredLeads\(\)\)[\s\S]*renderLeadStats\(list\)/, 'lead stats should follow the current lead filters and campus scope');
assert.match(leadsSource, /function leadCommunicationText\(/, 'leads page should expose the communication summary helper');
assert.match(leadsSource, /function leadDealTypeText\(/, 'leads page should expose a deal type helper');
assert.match(leadsSource, /function leadStageText\(/, 'leads page should expose a single lead stage helper');
assert.match(leadsSource, /leadStageText\(lead\)/, 'leads list and detail should render the lead stage');
assert.match(leadsSource, /stageValue&&leadStageText\(lead\)!==stageValue/, 'lead filtering should support lead stage');
assert.match(fnBody('leadConvertedYesNo'), /leadDealTypeText\(lead\)[\s\S]*leadStageText\(lead\)==='已成交'/, 'converted yes/no should align with displayed deal type');
assert.match(leadsSource, /function getFilteredLeads\(/, 'leads page should centralize lead filtering');
assert.match(leadsSource, /function setLeadPageSize\(/, 'leads page should expose page size switching');
assert.match(leadsSource, /function applyLeadSearch\(\)[\s\S]*leadPage=standardListFirstPage\(\)[\s\S]*renderLeads\(\)/, 'leads search should reset pagination through the standard list flow before rendering');
assert.match(leadsSource, /function cycleLeadSort\([\s\S]*leadSortDir='asc'[\s\S]*leadSortDir='desc'[\s\S]*leadSortKey='';leadSortDir='';/, 'leads sortable headers should cycle asc, desc, and no sort');
assert.match(leadsSource, /function updateLeadSortHeaders\(/, 'leads page should update sortable header state');
assert.match(leadsSource, /function getSortedLeads\(/, 'leads page should sort after filtering and before pagination');
assert.match(fnBody('leadRows'), /leadSortCreatedValue\(b\)-leadSortCreatedValue\(a\)/, 'lead default order should use createdAt descending');
assert.doesNotMatch(fnBody('leadRows'), /leadSortDateValue\(b\?\.leadDate,b\)-leadSortDateValue\(a\?\.leadDate,a\)/, 'lead default order should not use lead time as the primary order');
assert.match(leadsSource, /renderStandardPaginationButtonsHtml\(leadPage,pages,'setLeadPage'\)/, 'leads page should render compact pager numbers through the global standard pager');
assert.match(leadsSource, /function renderLeadPagerControls\(/, 'leads page should render standard pager controls');
assert.match(leadsSource, /function jumpLeadPage\(/, 'leads page should support jump-to-page');
assert.match(leadsSource, /leadPageSize=standardListPageSize\(value,leadPageSize\)/, 'leads page size should be limited by the global 20, 50, and 100 rule');
assert.match(leadsSource, /withLinkedFilterCounts\(\[[\s\S]*key:'source'[\s\S]*key:'consult'[\s\S]*key:'stage'/, 'leads toolbar filters should use linked count labels');
assert.match(leadsSource, /function leadOwnerFilterValues\([\s\S]*lead-owner-filter-cb:checked/, 'lead owner filter should collect checked owners');
assert.match(leadsSource, /function leadOwnerFilterHtml\([\s\S]*tms-dropdown[\s\S]*leadOwnerFilter_dropdown[\s\S]*type="checkbox"[\s\S]*lead-owner-filter-cb[\s\S]*toggleLeadOwnerFilter/, 'lead owner filter should render as a checkbox dropdown');
assert.match(leadsSource, /function toggleLeadOwnerFilter\([\s\S]*leadPage=standardListFirstPage\(\)[\s\S]*renderLeads\(\)/, 'checking lead owners should refresh the list');
assert.match(fnBody('getFilteredLeads'), /const ownerValues=leadOwnerFilterValues\(\)[\s\S]*if\(ownerValues\.length&&!ownerValues\.includes\(String\(lead\?\.owner\|\|''\)\)\)return false;/, 'lead filtering should support multiple checked owners');
assert.match(leadsSource, /function leadPriorityOptions\(\)[\s\S]*\['P0','P1','P2','P3','P4'\]/, 'lead page should expose P0-P4 follow-up priority options');
assert.match(leadsSource, /function leadPriorityText\(lead\)[\s\S]*lead\?\.followupPriority/, 'lead page should read follow-up priority from the lead record');
assert.match(fnBody('renderLeads'), /renderLeadTag\(leadPriorityText\(lead\),'priority'\)/, 'lead list rows should show follow-up priority');
assert.match(leadsSource, /function leadEmptyStateHtml\([\s\S]*没有匹配的线索[\s\S]*暂无线索[\s\S]*调整搜索或筛选后再试[\s\S]*点击右上角新增线索开始录入/, 'leads empty state should distinguish filtered results from no data');
assert.match(leadsSource, /function leadDetailFieldHtml\(/, 'lead detail should expose readonly field helper');
assert.match(leadsSource, /function leadDetailFieldHtml\([\s\S]*renderDetailDrawerField/, 'lead detail readonly fields should use the shared drawer field helper');
assert.match(leadsSource, /function leadDetailBlockHtml\(/, 'lead detail should expose readonly block helper');
assert.match(leadsSource, /function leadDetailBlockHtml\([\s\S]*renderDetailDrawerBlock/, 'lead detail long readonly blocks should use the shared drawer block helper');
assert.match(leadsSource, /function leadDetailTabsHtml\(/, 'lead detail should expose drawer tabs');
assert.match(leadsSource, /function leadDrawerCardHtml\(/, 'lead detail should expose a shared drawer card helper');
assert.match(leadsSource, /function openLeadDetail\(/, 'leads page should expose the lead detail drawer');
const leadDetailSource=(leadsSource.match(/function openLeadDetail\([\s\S]*?function openLeadModal/)||[''])[0];
assert.match(leadDetailSource, /openStandardDetailDrawer\(/, 'lead detail should use the standard right drawer');
assert.match(leadDetailSource, /leadDetailHeroHtml\(lead\)[\s\S]*leadDetailTabsHtml\(leadDetailActiveTab\)/, 'lead detail drawer should render hero and tabs');
assert.match(leadDetailSource, /leadDetailActiveTab==='basic'[\s\S]*leadDetailBasicTabHtml\(lead\)[\s\S]*leadDetailActiveTab==='followups'[\s\S]*leadDetailFollowupsTabHtml\(lead\)[\s\S]*leadDetailConversionTabHtml\(lead\)/, 'lead detail should route basic, follow-up and conversion tabs');
assert.match(leadDetailSource, /modal-lead-drawer/, 'lead detail should use the scoped lead drawer class');
assert.match(leadsSource, /function leadBasicInfoReadonlyHtml\(lead\)[\s\S]*leadDetailFieldHtml\('微信名',leadWechatText\(lead\)\)[\s\S]*leadDetailFieldHtml\('电话',lead\?\.phone\|\|'-'\)[\s\S]*leadDetailFieldHtml\('水平',leadLevelText\(lead\)\)[\s\S]*leadDetailFieldHtml\('线索时间',lead\?\.leadDate\|\|'-'\)[\s\S]*leadDetailFieldHtml\('线索来源',leadSourceText\(lead\)\|\|'-'\)[\s\S]*leadDetailFieldHtml\('所属校区',leadCampusText\(lead\)\)[\s\S]*leadDetailFieldHtml\('客户类型',leadCustomerTypeText\(lead\)\|\|'-'\)[\s\S]*leadDetailFieldHtml\('需求产品',leadDemandProductText\(lead\)\|\|'-'\)[\s\S]*leadDetailFieldHtml\('意向类型',lead\?\.intentLevel\|\|'-'\)[\s\S]*leadDetailFieldHtml\('跟进优先级',leadPriorityText\(lead\)\)[\s\S]*leadDetailFieldHtml\('跟进人',lead\?\.owner\|\|'-'\)[\s\S]*leadDetailBlockHtml\('基本信息',esc\(leadProfileText\(lead\)\),\{hideEmpty:true\}\)/, 'lead detail basic tab should keep the current basic fields and normalize labels');
assert.match(leadsSource, /function leadTimelineLineText\(item\)[\s\S]*return `\$\{date\} · \$\{by\} 跟进 · （\$\{status\}）\\n\$\{note\}`/, 'lead timeline should render date, follower, conversion result, then note on the second line');
assert.match(componentsSource, /function renderDetailDrawerTimeline\(/, 'detail drawer timeline should be shared');
assert.match(leadsSource, /function leadTimelineHtml\(lead\)[\s\S]*renderDetailDrawerTimeline\(rows\.map\(item=>leadFollowupTimelineItemHtml\(lead,item\)\),\{emptyText:'暂无跟进时间线',className:'lead-followup-timeline'\}\)/, 'lead timeline should render through the shared drawer timeline component');
assert.match(leadsSource, /function leadFollowupTimelineItemHtml\(lead,item\)[\s\S]*className:'lead-followup-item'[\s\S]*startLeadFollowupDrawerEdit/, 'lead timeline should provide item content for the shared student lesson record style');
assert.match(leadsSource, /function openLeadFollowupModal\(/, 'leads page should expose the follow-up modal');
assert.match(leadsSource, /openLeadFollowupModal\(leadId,followupId=''\)/, 'follow-up modal should support editing existing records');
assert.match(leadsSource, /apiCall\('PUT',`\/lead-followups\/\$\{followupId\}`/, 'follow-up save should update an existing record when editing');
assert.match(leadsSource, /function saveLeadFollowupFromDrawer\(/, 'follow-up save should also work inside the lead drawer');
assert.match(leadsSource, /跟进时间[\s\S]*跟进人[\s\S]*跟进方式[\s\S]*沟通内容[\s\S]*用户顾虑[\s\S]*本次结论[\s\S]*当前状态[\s\S]*下次跟进时间[\s\S]*下次动作/, 'follow-up modal should expose the required fields');
assert.doesNotMatch(leadsSource, /type="datetime-local"/, 'follow-up date should not use native datetime-local');
assert.match(leadsSource, /courtDateButtonHtml\('lead_followupAt'[\s\S]*leadFollowupDateInputValue/, 'follow-up date should use the shared date picker');
assert.match(leadsSource, /function openLeadImportPreviewModal\(/, 'leads page should expose the import preview modal');
assert.match(leadsSource, /识别到的字段[\s\S]*缺失字段提醒[\s\S]*总行数[\s\S]*状态归类统计[\s\S]*自动匹配统计[\s\S]*疑似匹配列表[\s\S]*未匹配列表/, 'import preview modal should expose the required sections');
assert.match(leadsSource, /const body=`<div class="tms-form-row lead-form-row-4">[\s\S]*<label class="tms-form-label">微信名<\/label><input class="finput tms-form-control" id="lead_wechatName"[\s\S]*<label class="tms-form-label">电话<\/label><input class="finput tms-form-control" id="lead_phone"[\s\S]*<label class="tms-form-label">水平<\/label>\$\{leadLevelControlHtml\(lead\)\}[\s\S]*<label class="tms-form-label">线索时间<\/label>[\s\S]*<label class="tms-form-label">线索来源<\/label>[\s\S]*<label class="tms-form-label">所属校区<\/label>[\s\S]*<label class="tms-form-label">客户类型<\/label>[\s\S]*<label class="tms-form-label">需求产品<\/label>[\s\S]*<label class="tms-form-label">意向类型<\/label>[\s\S]*<label class="tms-form-label">跟进优先级<\/label>[\s\S]*leadPriorityOptions\(\)[\s\S]*<label class="tms-form-label">跟进人<\/label>[\s\S]*<label class="tms-form-label">基本信息<\/label>/, 'lead create and edit modal should use the requested field order without a section title');
assert.doesNotMatch(leadsSource, /<div class="tms-section-header" style="margin-top:0;">基础信息<\/div><div class="tms-form-row lead-form-row-4">/, 'lead create and edit modal should not show the basic info section title');
assert.match(leadsSource, /openStandardModal\(\{title:leadId\?'编辑线索':'新增线索',bodyHtml:body,actionsHtml:actions,extraClass:'modal-complex modal-leads-form'\}\)/, 'lead create and edit modal should use the standard 800px complex modal');
assert.doesNotMatch(leadsSource, /setCourtModalFrame\(leadId\?'编辑线索':'新增线索'/, 'lead create and edit modal should not keep the old shell');
assert.match(leadsSource, /lead_campus','所属校区'/, 'lead create and edit modal should expose campus selection');
assert.match(leadsSource, /const campusValue=lead\?\.campus\|\|\(campus!=='all'\?campus:'mabao'\)/, 'new leads should default to the current campus or mabao');
assert.doesNotMatch(leadsSource, /id="lead_systemStatus"/, 'lead create and edit modal should remove the current status field');
assert.match(leadsSource, /function leadConversionActionPanelHtml\(lead\)[\s\S]*转为学员[\s\S]*转为订场用户[\s\S]*关联已有学员[\s\S]*关联已有订场用户/, 'lead conversion tab should expose conversion actions inside the drawer');
assert.match(leadsSource, /查看[\s\S]*跟进/, 'lead rows should expose view and follow-up actions');
assert.doesNotMatch(fnBody('renderLeads'), /转化/, 'lead rows should not expose conversion action');
assert.match(leadsSource, /function leadSourceOptions\(\)[\s\S]*FlowTennisBusinessTaxonomy\.optionList\('leadSources'\)/, 'lead source options should use the global business dictionary');
assert.match(leadsSource, /function leadCustomerTypeOptions\(\)[\s\S]*FlowTennisBusinessTaxonomy\.optionList\('leadCustomerTypes'\)/, 'lead customer type options should use the global business dictionary');
assert.match(leadsSource, /function leadDemandProductOptions\(\)[\s\S]*FlowTennisBusinessTaxonomy\.optionList\('leadDemandProducts'\)/, 'lead demand product options should use the global business dictionary');
assert.match(leadsSource, /function leadSourceText\(lead\)[\s\S]*FlowTennisBusinessTaxonomy\.normalizeLeadSource\(lead\?\.source\)/, 'lead source display should normalize legacy source values');
assert.match(leadsSource, /function leadCustomerTypeText\(lead\)[\s\S]*FlowTennisBusinessTaxonomy\.normalizeLeadCustomerType/, 'lead customer type display should normalize legacy values');
assert.match(leadsSource, /function leadDemandProductText\(lead\)[\s\S]*FlowTennisBusinessTaxonomy\.normalizeLeadDemandProduct/, 'lead demand product display should normalize legacy values');
assert.match(leadsSource, /function leadIntentOptions\(\)[\s\S]*FlowTennisBusinessTaxonomy\.optionList\('leadIntentLevels'\)/, 'lead intent options should use the global business dictionary');
assert.match(leadsSource, /function leadLevelOptions\(\)[\s\S]*FlowTennisBusinessTaxonomy\.optionList\('leadLevels'\)/, 'lead level options should use the global business dictionary');
assert.match(leadsSource, /function leadLevelCanonicalValue\(value\)[\s\S]*\['1','2','3','4','5'\]\.includes\(text\)[\s\S]*`\$\{text\}\.0`/, 'lead standard integer levels should display and edit as x.0');
assert.match(leadsSource, /function leadLevelText\(lead\)[\s\S]*leadLevelCanonicalValue\(lead\?\.level\)/, 'lead level display should preserve standard decimal labels');
assert.match(leadsSource, /function leadLevelControlHtml\([\s\S]*lead_level_custom[\s\S]*toggleLeadLevelCustomInput/, 'custom lead level should provide an input instead of saving the literal custom label');
assert.match(fnBody('leadPayloadFromForm'), /const levelValue=document\.getElementById\('lead_level'\)\?\.value\|\|''[\s\S]*level:levelValue==='自定义'\?document\.getElementById\('lead_level_custom'\)\?\.value\?\.trim\?\.\(\)\|\|'':levelValue/, 'lead save payload should use custom level input value');
assert.match(fnBody('leadPayloadFromForm'), /followupPriority:document\.getElementById\('lead_followupPriority'\)\?\.value\|\|''/, 'lead save payload should include follow-up priority');
assert.match(apiSource, /const LEAD_LIST_PROJECTION_FIELDS=\[[\s\S]*'level'[\s\S]*\]/, 'lead list API projection should include level');
assert.match(apiSource, /const LEAD_LIST_PROJECTION_FIELDS=\[[\s\S]*'followupPriority'[\s\S]*\]/, 'lead list API projection should include follow-up priority');
assert.match(stateSource, /function renderLeadTableLoading\([\s\S]*renderTableSkeletonLoading\('leadTbody',14,'线索数据加载中\.\.\.'\)/, 'leads loading state should use the shared full-table skeleton');
assert.match(stateSource, /function renderLeadTableError\([\s\S]*tms-table-error-state[\s\S]*加载失败[\s\S]*重新加载/, 'leads load failure should render an inline retry state');
assert.match(stateSource, /function renderLeadTableLoading\([\s\S]*renderTableSkeletonLoading\('leadTbody',14/, 'leads loading state should pass all visible columns to the skeleton helper');
assert.match(stateSource, /function renderLeadTableError\(message\)[\s\S]*colspan="14"/, 'leads error state should span all visible columns');
assert.match(stateSource, /if\(pg==='leads'\)renderLeadTableLoading\(\);/, 'leads page should use the dedicated loading renderer');
assert.match(stateSource, /if\(pg==='leads'\)renderLeadTableError\(String\(e\.message\|\|e\)\);/, 'leads page load failure should render the dedicated error state');
assert.match(stateSource, /leads:\['campuses','leads'\]/, 'leads page should require campuses so the campus tabs can render');
assert.match(fnBody('renderLeads'), /leadDateOnly\(lead\?\.leadDate,lead\)[\s\S]*renderLeadTag\(leadSourceText\(lead\),'source'\)[\s\S]*renderLeadTag\(leadCustomerTypeText\(lead\),'customerType'\)[\s\S]*renderLeadTag\(leadDemandProductText\(lead\),'demandProduct'\)[\s\S]*leadLevelText\(lead\)[\s\S]*leadProfileText\(lead\)[\s\S]*renderLeadTag\(leadStageDisplayText\(lead\),'stage'\)/, 'lead list rows should show normalized source, customer type, demand product, level, basic info, and stage in the table order');
assert.match(css, /#page-leads \.tms-table-wrapper\{max-height:calc\(100vh - 210px\);overflow-x:auto;overflow-y:auto\}/, 'leads table should keep scrolling inside the table region');
assert.match(css, /#page-leads \.tms-table th\{padding-top:8px;padding-bottom:8px;font-size:12px\}/, 'leads table header should match the standard table font size');
assert.match(css, /#page-leads \.tms-table td\{padding-top:6px;padding-bottom:6px;font-size:12px;line-height:1\.15;vertical-align:middle\}/, 'leads table rows should match the standard row height and font size');
assert.match(standardSource, /style:'width:220px'[\s\S]*data-lead-sort="trialLessonAt"/, 'lead trial lesson column should be wide enough for the full date/time text');
assert.match(standardSource, /label:'需求产品'[\s\S]*style:'width:110px'/, 'lead demand product column should use the requested width');
assert.match(css, /#page-leads \.tms-text-primary,#page-leads \.tms-cell-text,#page-leads \.tms-text-remark\{font-size:12px\}/, 'leads nested table text should match the student page font size');
assert.match(css, /#page-leads \.tms-tag-lead-communicated\{background:#E3F0ED;color:#2E766E\}/, 'leads tags should use grounded colors instead of purple');
assert.match(css, /\.modal\.modal-court\.modal-leads-form \.mbody\{overflow:visible\}/, 'lead form modal should keep dropdowns from being clipped');
assert.match(css, /\.modal\.modal-court \.lead-form-row-4\{display:grid;grid-template-columns:repeat\(4,minmax\(0,1fr\)\);gap:14px\}/, 'lead form should use four equal columns');
assert.match(css, /\.modal\.modal-court \.tms-readonly-card\{[^}]*background:#FFFFFF[^}]*border-radius:12px[^}]*border:1px solid #E6E1DC[^}]*box-shadow:0 1px 2px rgba\(0,0,0,\.05\)[^}]*padding:24px[^}]*margin-bottom:32px/, 'readonly detail sections should sit on the shared white card');
assert.match(css, /\.modal\.modal-court \.tms-readonly-card \.tms-detail-grid\{[^}]*grid-template-columns:repeat\(2,minmax\(0,1fr\)\)[^}]*row-gap:24px[^}]*column-gap:32px/, 'readonly detail cards should use the wider data grid');
assert.match(css, /\.modal\.modal-court \.tms-readonly-card\.lead-readonly-card\{grid-column:1\/-1\}/, 'lead detail readonly card should span the full modal width');
assert.match(css, /\.modal\.modal-court \.tms-readonly-card\.lead-readonly-card-4 \.tms-detail-grid\{grid-template-columns:repeat\(4,minmax\(0,1fr\)\)\}/, 'lead detail basic readonly card should use four columns');
assert.doesNotMatch(css, /lead-timeline-list/, 'lead timeline should not keep the old custom axis styles');
assert.doesNotMatch(css, /lead-timeline-item/, 'lead timeline should not keep the old custom row styles');
assert.match(css, /\.student-lesson-timeline-item::before\{[\s\S]*left:6px[\s\S]*background:#ECE7E1/, 'lead timeline should inherit the shared student lesson vertical line');
assert.match(css, /#page-leads \.tms-empty-state[\s\S]*#page-leads \.tms-state-action/, 'leads empty, loading, and error states should have scoped standard styles');
assert.match(css, /\.tms-sort-header\{[^}]*display:inline-flex[^}]*cursor:pointer/, 'leads sortable headers should use the shared sort style');
assert.match(css, /#page-leads \.tms-stats-row\{[^}]*display:grid[^}]*grid-template-columns:repeat\(auto-fit,minmax\(200px,1fr\)\)[^}]*overflow:visible/, 'lead stats should use the shared adaptive top data card grid');
assert.match(leadsSource, /renderStandardDataCards\(cardData\)/, 'lead stats should render through the shared data card helper');

console.log('leads view tests passed');
