const assert = require('assert');
const fs = require('fs');
const path = require('path');

const publicDir = path.join(__dirname, '../public');
const html = fs.readFileSync(path.join(publicDir, 'index.html'), 'utf8');
const bootstrapSource = fs.readFileSync(path.join(publicDir, 'assets/scripts/core/bootstrap.js'), 'utf8');
const stateSource = fs.readFileSync(path.join(publicDir, 'assets/scripts/core/state.js'), 'utf8');
const css = fs.readFileSync(path.join(publicDir, 'assets/styles/pages.css'), 'utf8');
const leadsSourcePath = path.join(publicDir, 'assets/scripts/pages/leads.js');
const leadsSource = fs.existsSync(leadsSourcePath) ? fs.readFileSync(leadsSourcePath, 'utf8') : '';

assert.match(html, /goPage\('leads',this\)[\s\S]*线索池/, 'sidebar should expose a leads entry');
assert.match(html, /id="page-leads"[\s\S]*id="leadSearch"[\s\S]*placeholder="搜索姓名、手机号、微信名"/, 'leads page should provide the agreed search field');
assert.match(html, /id="leadSourceFilterHost"/, 'leads page should provide source filter host');
assert.match(html, /id="leadConsultFilterHost"/, 'leads page should provide consult filter host');
assert.match(html, /id="leadStatusFilterHost"/, 'leads page should provide status filter host');
assert.match(html, /id="leadConvertedFilterHost"/, 'leads page should provide converted filter host');
assert.match(html, /id="leadOwnerFilterHost"/, 'leads page should provide owner filter host');
assert.doesNotMatch(html, /id="leadTodoFilterHost"/, 'leads page should remove the follow-up todo filter host');
assert.doesNotMatch(html, /id="leadDateFilterHost"/, 'leads page should remove the date filter host');
assert.match(html, /onclick="openLeadImportPreviewModal\(\)">导入<\/button>/, 'leads toolbar should expose the import entry');
assert.match(html, /新增线索/, 'leads toolbar should expose the create lead entry');
assert.match(html, /id="leadDateScopeBar"[\s\S]*线索时间[\s\S]*setLeadDatePreset\('today'\)[\s\S]*今日[\s\S]*setLeadDatePreset\('week'\)[\s\S]*本周[\s\S]*setLeadDatePreset\('month'\)[\s\S]*本月[\s\S]*setLeadDatePreset\('custom'\)[\s\S]*自定义[\s\S]*id="leadDateCustomRange"/, 'custom lead date controls should sit next to the custom preset');
assert.match(html, /id="leadDateFrom_btn"[\s\S]*toggleGlobalDatePicker\(event,'leadDateFrom','leadDateFrom_btn','开始日期'\)[\s\S]*id="leadDateTo_btn"[\s\S]*toggleGlobalDatePicker\(event,'leadDateTo','leadDateTo_btn','结束日期'\)/, 'custom lead date controls should use the shared drawn date picker');
assert.doesNotMatch(html, /<input class="lead-date-input" id="leadDateFrom" type="date"/, 'custom lead date controls should not expose native date inputs');
assert.match(html, /id="leadStatsRow"/, 'leads page should expose the top stats row');
assert.match(html, /<table class="tms-table">[\s\S]*微信名[\s\S]*跟进状态[\s\S]*是否转化[\s\S]*体验课时间[\s\S]*未成交原因[\s\S]*最近跟进[\s\S]*跟进次数[\s\S]*意向类型[\s\S]*咨询需求[\s\S]*基本信息[\s\S]*正式课报名时间[\s\S]*正式课教练[\s\S]*线索时间[\s\S]*线索渠道[\s\S]*所属校区[\s\S]*跟进人[\s\S]*操作/, 'leads table should expose the requested reordered columns');
assert.match(html, /id="leadTbody"/, 'leads page should provide the list tbody mount');
assert.match(html, /id="leadPagerInfo"/, 'leads page should provide pager info');
assert.match(html, /id="leadPageSize"/, 'leads page should provide page size selector host');
assert.match(html, /id="leadPagerBtns"/, 'leads page should provide pager buttons');
assert.match(html, /leadSearch[\s\S]*onkeydown="if\(event\.key==='Enter'\)applyLeadSearch\(\)"/, 'leads search should run on enter');
assert.doesNotMatch(html, /onclick="applyLeadSearch\(\)">查询/, 'leads toolbar should remove the query button');
assert.match(html, /onclick="resetLeadFilters\(\)"[\s\S]*重置/, 'leads toolbar should provide a reset button');
assert.match(html, /class="tms-sticky-l"[\s\S]*微信名/, 'leads table should pin the first identity column');
assert.match(html, /data-lead-sort="leadDate"[\s\S]*线索时间/, 'leads table should sort by lead date');
assert.match(html, /data-lead-sort="trialLessonAt"[\s\S]*体验课时间/, 'leads table should sort by trial lesson date');
assert.match(html, /data-lead-sort="lastFollowupAt"[\s\S]*最近跟进/, 'leads table should sort by latest follow-up');
assert.match(html, /data-lead-sort="followupCount"[\s\S]*跟进次数/, 'leads table should sort by follow-up count');
assert.match(html, /data-lead-sort="formalSignupAt"[\s\S]*正式课报名时间/, 'leads table should sort by formal signup date');

assert.match(bootstrapSource, /'leads'/, 'bootstrap should register leads routing');
assert.match(bootstrapSource, /leads:'线索池'/, 'bootstrap should map the leads page title');
assert.match(bootstrapSource, /globalTopFilterPages\(\)\.includes\(pg\)[\s\S]*\?'flex':'none'/, 'lead page should expose the top campus filter');

assert.match(leadsSource, /function renderLeads\(/, 'leads page should expose the list renderer');
assert.match(leadsSource, /function leadDedupKey\(/, 'leads page should deduplicate repeated lead rows');
assert.match(leadsSource, /function renderLeadTag\(/, 'leads page should render tag-style lead cells');
assert.match(leadsSource, /function leadTrialDateText\(/, 'leads page should format trial lesson date with relative days');
assert.match(leadsSource, /function leadRecentDateText\(/, 'leads page should format recent follow-up date with relative days');
assert.match(leadsSource, /function leadFormalSignupDateText\(/, 'leads page should format formal signup date');
assert.match(leadsSource, /function leadPurchaseSignupDate\(/, 'converted course leads should be able to use package purchase dates for formal signup date');
assert.match(leadsSource, /function leadFollowupCount\(/, 'leads page should expose the follow-up count helper');
assert.match(leadsSource, /function leadStatsData\(/, 'leads page should expose summary stats for the filtered lead rows');
assert.match(leadsSource, /线索数[\s\S]*已上体验课数[\s\S]*体验课完成率[\s\S]*已转化线索数[\s\S]*线索转化率[\s\S]*体验课转化率[\s\S]*已体验待转化数/, 'lead stats should expose the required seven metrics');
assert.match(leadsSource, /已上体验课 \/ 线索数[\s\S]*已转化线索 \/ 线索数[\s\S]*已体验且已转化 \/ 已上体验课[\s\S]*已上体验课 - 已体验且已转化/, 'lead stats should explain the formulas under rate and pending cards');
assert.match(leadsSource, /function leadDateRangeForPreset\(/, 'leads page should expose date preset range helper');
assert.match(leadsSource, /function setLeadDatePreset\(/, 'leads page should expose lead date preset switching');
assert.match(leadsSource, /function setLeadCustomDateRange\(/, 'leads page should expose custom lead date range switching');
assert.match(leadsSource, /if\(!leadInDateRange\(lead,getLeadDateFilterRange\(\)\)\)return false;/, 'lead filtering should apply the global lead date scope');
assert.match(leadsSource, /function renderLeads\([\s\S]*const list=getSortedLeads\(getFilteredLeads\(\)\)[\s\S]*renderLeadStats\(list\)/, 'lead stats should follow the current lead filters and campus scope');
assert.match(leadsSource, /function leadCommunicationText\(/, 'leads page should expose the communication summary helper');
assert.match(leadsSource, /leadFollowupStatusText\(lead\)/, 'leads page should keep the status filter aligned with the displayed follow-up status');
assert.match(leadsSource, /leadConvertedYesNo\(lead\)/, 'leads page should expose the converted yes\/no helper to filters');
assert.match(leadsSource, /function getFilteredLeads\(/, 'leads page should centralize lead filtering');
assert.match(leadsSource, /function setLeadPageSize\(/, 'leads page should expose page size switching');
assert.match(leadsSource, /function leadStatusOptionValues\(/, 'leads page should derive status filters from the latest data');
assert.match(leadsSource, /function applyLeadSearch\(\)[\s\S]*leadPage=1[\s\S]*renderLeads\(\)/, 'leads search should reset pagination before rendering');
assert.match(leadsSource, /function resetLeadFilters\(\)[\s\S]*leadSearch[\s\S]*leadSourceFilter[\s\S]*leadConvertedFilter[\s\S]*leadPage=1[\s\S]*renderLeads\(\)/, 'leads reset should clear filters and return to first page');
assert.match(leadsSource, /function cycleLeadSort\([\s\S]*leadSortDir='asc'[\s\S]*leadSortDir='desc'[\s\S]*leadSortKey='';leadSortDir='';/, 'leads sortable headers should cycle asc, desc, and no sort');
assert.match(leadsSource, /function updateLeadSortHeaders\(/, 'leads page should update sortable header state');
assert.match(leadsSource, /function getSortedLeads\(/, 'leads page should sort after filtering and before pagination');
assert.match(leadsSource, /function leadPageNumbers\(/, 'leads page should render compact pager numbers');
assert.match(leadsSource, /function renderLeadPagerControls\(/, 'leads page should render standard pager controls');
assert.match(leadsSource, /function jumpLeadPage\(/, 'leads page should support jump-to-page');
assert.match(leadsSource, /leadPageSize=\[20,50,100\]\.includes\(next\)\?next:20/, 'leads page size should be limited to 20, 50, and 100');
assert.match(leadsSource, /withStandardFilterCounts[\s\S]*sourceOptions[\s\S]*consultOptions[\s\S]*statusOptions[\s\S]*convertedOptions[\s\S]*ownerOptions/, 'leads toolbar filters should use standard count labels');
assert.match(leadsSource, /function leadEmptyStateHtml\([\s\S]*没有匹配的线索[\s\S]*暂无线索[\s\S]*调整搜索或筛选后再试[\s\S]*点击右上角新增线索开始录入/, 'leads empty state should distinguish filtered results from no data');
assert.match(leadsSource, /function leadDetailFieldHtml\(/, 'lead detail should expose readonly field helper');
assert.match(leadsSource, /function leadDetailBlockHtml\(/, 'lead detail should expose readonly block helper');
assert.match(leadsSource, /function leadDetailSectionHtml\(/, 'lead detail should expose section helper');
assert.match(leadsSource, /function openLeadDetail\(/, 'leads page should expose the lead detail modal');
const leadDetailSource=(leadsSource.match(/function openLeadDetail\([\s\S]*?function openLeadModal/)||[''])[0];
assert.match(leadDetailSource, /leadDetailSectionHtml\('基础信息'[\s\S]*leadDetailSectionHtml\('当前跟进'[\s\S]*leadDetailSectionHtml\('跟进时间线'[\s\S]*leadDetailSectionHtml\('转化关系'/, 'lead detail should expose the updated four required sections');
assert.match(leadDetailSource, /leadDetailFieldHtml\('所属校区',leadCampusText\(lead\)\)/, 'lead detail should expose the campus field');
assert.doesNotMatch(leadDetailSource, /<input class="finput tms-form-control"/, 'lead detail should be read-only rather than editable');
assert.match(leadsSource, /function openLeadFollowupModal\(/, 'leads page should expose the follow-up modal');
assert.match(leadsSource, /跟进时间[\s\S]*跟进人[\s\S]*跟进方式[\s\S]*沟通内容[\s\S]*用户顾虑[\s\S]*本次结论[\s\S]*当前状态[\s\S]*下次跟进时间[\s\S]*下次动作/, 'follow-up modal should expose the required fields');
assert.match(leadsSource, /type="datetime-local"/, 'follow-up modal should use a proper datetime-local input');
assert.match(leadsSource, /function openLeadImportPreviewModal\(/, 'leads page should expose the import preview modal');
assert.match(leadsSource, /识别到的字段[\s\S]*缺失字段提醒[\s\S]*总行数[\s\S]*状态归类统计[\s\S]*自动匹配统计[\s\S]*疑似匹配列表[\s\S]*未匹配列表/, 'import preview modal should expose the required sections');
assert.match(leadsSource, /modal-wide modal-leads-form/, 'lead create and edit modal should use the leads-specific shell');
assert.match(leadsSource, /lead_campus','所属校区'/, 'lead create and edit modal should expose campus selection');
assert.match(leadsSource, /const campusValue=lead\?\.campus\|\|\(campus!=='all'\?campus:'mabao'\)/, 'new leads should default to the current campus or mabao');
assert.match(leadsSource, /lead-form-row-4[\s\S]*lead_owner[\s\S]*lead_systemStatus[\s\S]*lead_profileNote/, 'lead form should keep status in a four-column row before the remark field');
assert.match(leadsSource, /查看[\s\S]*跟进[\s\S]*转化/, 'lead rows should only expose the three compact actions');
assert.match(stateSource, /function renderLeadTableLoading\([\s\S]*tms-table-loading-state[\s\S]*线索数据加载中/, 'leads loading state should use the standard table loading style');
assert.match(stateSource, /function renderLeadTableError\([\s\S]*tms-table-error-state[\s\S]*加载失败[\s\S]*重新加载/, 'leads load failure should render an inline retry state');
assert.match(stateSource, /function renderLeadTableLoading\([\s\S]*colspan="17"/, 'leads loading state should span all visible columns');
assert.match(stateSource, /function renderLeadTableError\(message\)[\s\S]*colspan="17"/, 'leads error state should span all visible columns');
assert.match(stateSource, /if\(pg==='leads'\)renderLeadTableLoading\(\);/, 'leads page should use the dedicated loading renderer');
assert.match(stateSource, /if\(pg==='leads'\)renderLeadTableError\(String\(e\.message\|\|e\)\);/, 'leads page load failure should render the dedicated error state');
assert.match(stateSource, /leads:\['campuses','leads'\]/, 'leads page should require campuses so the campus tabs can render');
assert.match(css, /#page-leads \.tms-table-wrapper\{max-height:calc\(100vh - 210px\);overflow-x:auto;overflow-y:auto\}/, 'leads table should keep scrolling inside the table region');
assert.match(css, /#page-leads \.tms-table th\{padding-top:8px;padding-bottom:8px;font-size:10px\}/, 'leads table header should match the standard table height and font size');
assert.match(css, /#page-leads \.tms-table td\{padding-top:6px;padding-bottom:6px;font-size:12px;line-height:1\.15;vertical-align:middle\}/, 'leads table rows should match the standard row height and font size');
assert.match(html, /style="width:240px"><button class="tms-sort-header" data-lead-sort="trialLessonAt"/, 'lead trial lesson column should be wide enough for the full date/time text');
assert.match(html, /style="width:220px">咨询需求/, 'lead consult column should be wide enough for longer tags');
assert.match(css, /#page-leads \.tms-text-primary,#page-leads \.tms-cell-text,#page-leads \.tms-text-remark\{font-size:12px\}/, 'leads nested table text should match the student page font size');
assert.match(css, /#page-leads \.tms-tag-lead-communicated\{background:#E3F0ED;color:#2E766E\}/, 'leads tags should use grounded colors instead of purple');
assert.match(css, /\.modal\.modal-court\.modal-leads-form \.mbody\{overflow:visible\}/, 'lead form modal should keep dropdowns from being clipped');
assert.match(css, /\.modal\.modal-court \.lead-form-row-4\{display:grid;grid-template-columns:repeat\(4,minmax\(0,1fr\)\);gap:14px\}/, 'lead form should use four equal columns');
assert.match(css, /\.modal\.modal-court \.lead-timeline-item\{[^}]*white-space:nowrap[^}]*overflow:hidden[^}]*text-overflow:ellipsis/, 'lead timeline should stay in one line inside the modal');
assert.match(css, /#page-leads \.tms-empty-state[\s\S]*#page-leads \.tms-state-action/, 'leads empty, loading, and error states should have scoped standard styles');
assert.match(css, /#page-leads \.tms-sort-header\{[^}]*display:inline-flex[^}]*cursor:pointer/, 'leads sortable headers should use the standard compact sort style');
assert.match(css, /#page-leads \.tms-stats-row\{[^}]*display:grid[^}]*grid-template-columns:repeat\(7,minmax\(0,1fr\)\)[^}]*overflow:visible/, 'lead stats should fit seven cards in one row');
assert.match(css, /#page-leads \.tms-stat-card\{[^}]*min-height:82px/, 'lead stat cards should stay compact');

console.log('leads view tests passed');
