const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: html } = require('./helpers/read-index-bundle');
const stateSource = fs.readFileSync(path.join(__dirname, '../public/assets/scripts/core/state.js'), 'utf8');

const pagesCss = fs.readFileSync(path.join(__dirname, '../public/assets/styles/pages.css'), 'utf8');
const statusCss = fs.readFileSync(path.join(__dirname, '../public/assets/styles/components/status-tags.css'), 'utf8');
function fnBody(name) {
  const start = html.indexOf(`function ${name}`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const next = html.indexOf('\nfunction ', start + 1);
  return html.slice(start, next === -1 ? html.length : next);
}
function standardConfigBlock(key) {
  const marker = `key:'${key}'`;
  const start = html.indexOf(marker);
  assert.notStrictEqual(start, -1, `${key} should have a standard list config`);
  const rest = html.slice(start);
  const next = rest.search(/\n    \{key:|\n  \];/);
  return next === -1 ? rest : rest.slice(0, next);
}

const membershipShell = standardConfigBlock('memberships');
const membershipPlanShell = standardConfigBlock('membership-plans');
const courtShell = standardConfigBlock('courts');

assert.match(html, /goPage\('memberships',this\)[\s\S]*?会员管理/, 'sidebar should add membership management entry');
assert.match(html, /goPage\('membership-plans',this\)[\s\S]*?会员方案/, 'sidebar should add membership plan entry');
assert.match(html, /data-sidebar-icon="membership-plans" width="16" height="16"/, 'membership plan sidebar icon should use the 16px custom icon');
assert.match(html, /id="page-memberships"/, 'should have memberships page section');
assert.match(html, /id="page-membership-plans"/, 'should have dedicated membership plans page section');
assert.match(html, /id="page-membership-plans" data-standard-list-shell="membership-plans"/, 'membership plan page should mount the standard list shell');
assert.match(membershipPlanShell, /search:\{id:'membershipPlanSearch'/, 'membership plan page should use the court-style toolbar');
assert.match(membershipPlanShell, /bodyId:'membershipPlanTbody'/, 'membership plan page should use the standard table shell');
assert.match(pagesCss, /#page-membership-plans \.tms-table th\.tms-sticky-l[\s\S]*left:0/s, 'membership plan table should freeze the left name column');
assert.match(pagesCss, /#page-membership-plans \.tms-table td\.tms-sticky-r[\s\S]*right:0/s, 'membership plan table should keep the action column fixed on the right');
assert.doesNotMatch(html, /membershipTabOrders|membershipTabAccounts|membershipTabBenefits/, 'membership page should no longer use tabs');
assert.match(membershipShell, /历史订单[\s\S]*权益消耗记录/, 'membership page should expose audit buttons near the main actions');
assert.doesNotMatch(html, /page-memberships[\s\S]*方案配置/, 'membership management page should remove the scheme config shortcut');
assert.match(membershipShell, /statsId:'membershipStatsRow'/, 'membership management page should expose summary stat cards');
assert.match(html, /function renderMembershipStats/, 'membership management page should compute summary stat cards');
assert.match(html, /会员储值[\s\S]*充值金额[\s\S]*需履约总金额[\s\S]*已核销金额[\s\S]*待履约金额/, 'membership summary should show the requested five finance cards');
assert.match(fnBody('renderMembershipStats'), /会员人数 vs 储值次数[\s\S]*充值金额 \+ 赠送金额[\s\S]*已核销金额 \/ 累计实收\+累计赠送占比[\s\S]*待履约金额 \/ 累计实收\+累计赠送占比/, 'membership summary should use requested captions and percentage ratios');
assert.match(fnBody('renderMembershipStats'), /renderStandardDataCards\(/, 'membership summary should use the global data card renderer');
assert.match(fnBody('renderMembershipStats'), /percent:statPercentText\(totalRecognized,poolTotal\)[\s\S]*percent:statPercentText\(pendingTotal,poolTotal\)/, 'membership recognized and pending cards should use global percentage formatting');
assert.match(fnBody('renderMemberships'), /const rows=getMembershipRows\(\);[\s\S]*const stats=FlowTennisPlatformDataStandards\.currentMembershipSummary\(rows\);[\s\S]*renderMembershipStats\(stats\);/, 'membership summary should summarize the same filtered unified rows as the table list');
assert.match(fnBody('renderMembershipStats'), /financeSummary\.paidAmount[\s\S]*financeSummary\.consumableAmount[\s\S]*financeSummary\.consumedAmount[\s\S]*financeSummary\.pendingAmount/, 'membership summary should display the current filtered unified membership summary');
assert.doesNotMatch(fnBody('renderMembershipStats'), /courtAccountListViewData\?\.summary\?\.membershipFinanceSummary/, 'membership summary should not read the unfiltered global summary as the current filter result');
assert.doesNotMatch(fnBody('renderMembershipStats'), /totalDeposit|membershipReadModelFinanceForCourt|validOrders|membershipOrders\.filter/, 'membership summary should not read old local fields or recalculate paid amount');
assert.match(html, /function membershipReadModelItemForCourt\(/, 'membership management should resolve account facts from the court account read model');
assert.match(fnBody('membershipSortMetric'), /membershipReadModelFinanceForCourt\([\s\S]*membershipReadModelBookingForCourt\(/, 'membership sorting should read balance and booking facts from the court account read model');
assert.match(fnBody('renderMemberships'), /slice\.map\(item=>[\s\S]*membershipReadModelFinanceForCourt\(item\)[\s\S]*membershipReadModelBookingForCourt\(item\)/, 'membership list rows should render unified read-model items');
assert.match(fnBody('courtMembershipPanelHtml'), /membershipReadModelItemForCourt\(/, 'membership account detail should read account overview facts from the court account read model');
assert.match(stateSource, /if\(pg==='courts'\|\|pg==='memberships'\|\|pg==='membership-orders'\|\|pg==='membership-ledger'\)\{[\s\S]*await loadCourtReadModelGuardData\(\{force,allowStaleOnError:quiet\|\|hadUsableDataBeforeLoad\}\);/, 'membership pages should load the court account read model before rendering membership metrics and audit rows, and background refresh should keep the current data when refresh fails');
assert.match(html, /id="page-memberships" data-standard-list-shell="memberships"/, 'membership management page should mount the standard list shell');
assert.match(membershipShell, /search:\{id:'membershipSearch'/, 'membership management page should use the court-style toolbar');
assert.match(membershipShell, /bodyId:'membershipTbody'/, 'membership management page should use the standard table shell');
assert.match(membershipShell, /id:'membershipSearch'/, 'membership management search should use the unified search placeholder');
assert.doesNotMatch(html, /id="page-membership-orders"[\s\S]*返回会员管理/, 'membership purchase records should not keep a duplicate back button');
assert.doesNotMatch(html, /id="page-membership-ledger"[\s\S]*返回会员管理/, 'membership benefit ledger should not keep a duplicate back button');

assert.match(html, /let courts=\[\],students=\[\],products=\[\],packages=\[\],purchases=\[\],entitlements=\[\],entitlementLedger=\[\],financialLedger=\[\],membershipPlans=\[\],membershipAccounts=\[\],membershipOrders=\[\],membershipBenefitLedger=\[\],membershipAccountEvents=\[\]/, 'frontend state should load membership data separately');
assert.match(html, /membershipPlans=Array\.isArray\(data\?\.membershipPlans\)\?data\.membershipPlans:\[\]/, 'load-all should store membership plans');
assert.match(html, /membershipAccounts=Array\.isArray\(data\?\.membershipAccounts\)\?data\.membershipAccounts:\[\]/, 'load-all should store membership accounts');
assert.match(html, /membershipOrders=Array\.isArray\(data\?\.membershipOrders\)\?data\.membershipOrders:\[\]/, 'load-all should store membership orders');
assert.match(html, /membershipBenefitLedger=Array\.isArray\(data\?\.membershipBenefitLedger\)\?data\.membershipBenefitLedger:\[\]/, 'load-all should store membership benefit ledger');

assert.match(courtShell, /账户类型[\s\S]*会员类型[\s\S]*会员余额[\s\S]*最近订场/, 'courts table should show membership account columns');
assert.match(courtShell, /姓名[\s\S]*手机号[\s\S]*校区[\s\S]*账户类型[\s\S]*会员类型[\s\S]*会员余额[\s\S]*最近订场[\s\S]*会员订场[\s\S]*累计订场[\s\S]*累计消费[\s\S]*跟进人[\s\S]*储值态度[\s\S]*备注/, 'courts table should show requested account columns');
assert.doesNotMatch(courtShell, /账户状态|对接人|熟悉程序|熟悉程度/, 'courts table should remove old account status, owner copy, and familiarity columns');
assert.match(fnBody('renderCourtHeaderFilters'), /const accountTypes=\['会员账户','普通账户'\]/, 'court account filter should only expose member and normal account states');
assert.match(fnBody('renderCourtAccountListView'), /courtAccountStateLabel\(item\)/, 'court read-model list should filter and render by displayed account state');
assert.match(fnBody('renderCourts'), /renderCourtAccountListView\(\)/, 'court page should render through the unified read-model list');
assert.match(html, /function courtCleanUserNotes\(/, 'court user list should clean system merge notes before display');
assert.doesNotMatch(fnBody('renderCourts'), /courtFinanceLocal|courtBookingSummary|title="\$\{esc\(u\.notes\|\|''\)\}"/, 'court page should not keep legacy local display calculations');
assert.doesNotMatch(fnBody('renderCourtAccountListView'), /title="\$\{esc\(item\.notesSummary\|\|''\)\}"/, 'court read-model list should not display raw system merge notes');
assert.match(fnBody('courtCleanUserNotes'), /合并重复订场账户[\s\S]*系统[\s\S]*导入[\s\S]*修数/, 'court user notes should strip system generated notes');
assert.match(html, /function courtMembershipSummary/, 'courts page should compute membership summaries');
assert.match(fnBody('renderCourtAccountListView'), /openCourtMembershipPanel\('\$\{item\.id\}'\)">查看[\s\S]*openCourtFinanceModal\('\$\{item\.id\}'\)">订场/, 'court read-model row actions should only expose view and booking drawer entries');
assert.doesNotMatch(fnBody('renderCourtAccountListView'), /openCourtModal\('\$\{item\.id\}'\)">编辑/, 'court read-model row actions should remove edit copy');
assert.doesNotMatch(fnBody('renderCourts'), /openCourtModal\('\$\{u\.id\}'\)|openCourtMembershipPanel\('\$\{u\.id\}'\)/, 'court page should not keep legacy row action rendering');
assert.match(fnBody('openCourtModal'), /openStandardDetailDrawer\(/, 'court edit should use the standard right drawer');
assert.doesNotMatch(fnBody('openCourtModal'), /openStandardModal\(/, 'court edit should not use centered modal');
assert.match(html, /function openCourtMembershipPanel/, 'membership actions should move into dedicated account panel');
assert.match(html, /function courtMembershipPanelHtml/, 'membership account should render through dedicated panel html');
assert.match(fnBody('openCourtMembershipPanel'), /openMembershipDrawer\(/, 'membership account panel should open through the membership drawer');
assert.match(html, /function openMembershipDrawer/, 'membership account should use a dedicated drawer helper');
assert.match(fnBody('openMembershipDrawer'), /openStandardDetailDrawer\(/, 'membership drawer helper should call the standard right drawer');
assert.match(fnBody('openMembershipDrawer'), /modal-membership-drawer/, 'membership drawer should use scoped membership drawer class');
assert.match(html, /let membershipDetailActiveTab='overview',membershipDrawerMode='view'/, 'membership drawer should keep tab and mode state');
assert.match(html, /function membershipDetailTabsHtml/, 'membership drawer should expose tabs');
assert.match(fnBody('membershipDetailTabsHtml'), /账户概览[\s\S]*订场[\s\S]*权益[\s\S]*充值记录[\s\S]*权益流水/, 'membership drawer should have overview, booking, rights, orders and ledger tabs');
assert.match(html, /function membershipDrawerContentHtml/, 'membership drawer should route view and edit modes');
assert.match(fnBody('membershipDrawerContentHtml'), /membershipDrawerMode==='order'[\s\S]*membershipOrderDrawerHtml[\s\S]*membershipDrawerMode==='benefit-picker'[\s\S]*membershipBenefitPickerDrawerHtml[\s\S]*membershipDrawerMode==='benefit-action'[\s\S]*membershipBenefitActionDrawerHtml[\s\S]*membershipDrawerMode==='void'[\s\S]*membershipVoidDrawerHtml/, 'membership drawer should keep order, benefit and void flows inside the drawer');
assert.match(html, /function courtBookingDrawerHtml/, 'membership drawer should render court booking records inside a tab');
assert.match(fnBody('membershipDrawerContentHtml'), /membershipDetailActiveTab==='booking'[\s\S]*courtBookingDrawerHtml/, 'membership drawer should route booking tab to the booking drawer');
assert.doesNotMatch(fnBody('courtBookingDrawerHtml'), /财务摘要|确认订场收入|本次实收\/现金流入|待确认\/代用户订场|内部占用次数/, 'booking tab should not repeat account finance summary');
assert.match(fnBody('courtBookingDrawerHtml'), /订场记录[\s\S]*courtBookingRecordsTableHtml[\s\S]*actionsHtml:actions/, 'booking tab should lead with booking records');
assert.match(fnBody('courtBookingDrawerHtml'), /openCourtBookingEntryInline[\s\S]*新增订场流水/, 'booking tab should expose a lightweight add action');
assert.doesNotMatch(fnBody('courtBookingDrawerHtml'), /renderDetailDrawerCard\('流水录入'[\s\S]*renderDetailDrawerCard\('订场记录'/, 'booking entry form should not be permanently fixed above records');
assert.match(html, /function courtBookingRecordsTableHtml/, 'booking records should render as a table');
assert.match(fnBody('courtBookingRecordsTableHtml'), /label:'订场日期'[\s\S]*label:'时间'[\s\S]*label:'场地'[\s\S]*label:'类型'[\s\S]*label:'支付方式'[\s\S]*label:'金额'[\s\S]*label:'备注'/, 'booking records table should use the requested columns');
assert.doesNotMatch(fnBody('courtBookingRecordsTableHtml'), /录入时间|recordedAt|createdAt/, 'booking records table should not show recorded time');
assert.match(fnBody('courtBookingRecordsTableHtml'), /minWidth:'660px'[\s\S]*label:'订场日期'[\s\S]*width:'90px'[\s\S]*label:'时间'[\s\S]*width:'150px'[\s\S]*label:'场地'[\s\S]*width:'70px'[\s\S]*label:'类型'[\s\S]*width:'80px'[\s\S]*label:'支付方式'[\s\S]*width:'80px'[\s\S]*label:'金额'[\s\S]*width:'70px'[\s\S]*label:'备注'[\s\S]*width:'120px'/, 'booking records table should use compact widths and a 150px booking time column');
assert.match(fnBody('courtBookingRecordsTableHtml'), /cellClassName:'membership-booking-note-cell'/, 'booking record notes should support horizontal overflow for long notes');
assert.match(html, /function courtBookingHumanNote/, 'booking records should filter system-generated notes');
assert.match(fnBody('courtBookingRecordsTableHtml'), /courtBookingHumanNote\(h\)/, 'booking records table should only render human notes');
assert.doesNotMatch(fnBody('courtBookingRecordsTableHtml'), /internalReason/, 'booking records table should not show system/internal reason as note');
assert.match(fnBody('courtBookingHumanNote'), /订场收入细项修数|修数/, 'booking note filter should hide imported repair summaries');
assert.match(fnBody('courtBookingHumanNote'), /马坡补账[\s\S]*私教课CSV.*导入[\s\S]*网球兄弟.*csv/, 'booking note filter should hide generated import audit notes');
assert.match(fnBody('courtCleanUserNotes'), /私教课CSV.*导入[\s\S]*马坡补账/, 'court user notes should hide generated import audit notes');
assert.match(fnBody('courtBookingDrawerHtml'), /const closeAction=`<button[\s\S]*closeCourtBookingEntryInline/, 'expanded booking entry should define a close action');
assert.match(fnBody('courtBookingDrawerHtml'), /renderDetailDrawerCard\('新增订场流水',form,\{useGrid:false,actionsHtml:closeAction\}/, 'expanded booking entry should expose close action in the card header');
assert.doesNotMatch(fnBody('courtBookingDrawerHtml'), /\$\{form\}<div class="schedule-detail-card-actions">/, 'expanded booking entry should not hide cancel action at the bottom');
assert.match(pagesCss, /membership-booking-records[\s\S]*detail-drawer-table-wrapper[\s\S]*max-height:min\(72vh,720px\)/, 'booking records table should use a taller drawer table area');
assert.match(html, /function openCourtBookingEntryInline/, 'booking entry should expand inline on demand');
assert.match(fnBody('courtBookingDrawerHtml'), /renderStandardDropdownHtml\('nrStudentId','关联学员'[\s\S]*renderStandardDropdownHtml\('nrCompanionCoach','陪打教练'/, 'booking tab should keep linked student and companion coach fields');
assert.match(fnBody('courtBookingDrawerHtml'), /courtVenueOptionsForCampus\(defaultCampus/, 'booking tab should read venue options from campus config');
assert.match(fnBody('courtBookingDrawerHtml'), /handleCourtFinanceCampusChange/, 'changing booking campus should refresh the configured venue dropdown');
assert.match(fnBody('saveCourtFinanceRecord'), /const selectedVenue=courtVenueByValue\(recCampus,venueValue\)/, 'booking save should resolve configured venue metadata');
assert.match(fnBody('saveCourtFinanceRecord'), /venueId:selectedVenue\?\.id\|\|''[\s\S]*venueSpaceType:selectedVenue\?\.spaceType\|\|''/, 'booking save should persist venue id and indoor/outdoor type');
assert.match(fnBody('openCourtFinanceModal'), /openCourtMembershipPanel\(courtId,\{tab:'booking'\}\)/, 'legacy booking entry should open the membership booking drawer tab');
assert.match(fnBody('openCourtFinanceModal'), /membershipBookingEntryOpen=true[\s\S]*openCourtMembershipPanel\(courtId,\{tab:'booking'\}\)/, 'legacy booking entry should open the booking tab with entry form expanded');
assert.match(html, /function membershipOrderDrawerHtml/, 'membership order form should render inside the drawer');
assert.match(fnBody('membershipOrderDrawerHtml'), /会员方案 \*[\s\S]*系统价格[\s\S]*实收\/充值金额[\s\S]*改价原因[\s\S]*本次额外赠送/, 'membership order drawer should keep plan, price and adjustment fields');
assert.match(html, /function membershipBenefitPickerDrawerHtml/, 'membership benefit picker should render inside the drawer');
assert.match(html, /function membershipBenefitActionDrawerHtml/, 'membership benefit action should render inside the drawer');
assert.match(fnBody('membershipBenefitActionDrawerHtml'), /扣减预览[\s\S]*membershipBenefitConsumePreview/, 'membership consume drawer should keep batch preview');
assert.match(fnBody('membershipBenefitActionDrawerHtml'), /归属购买批次 \*[\s\S]*不会生成新的购买记录/, 'membership supplement drawer should keep existing-batch attribution');
assert.match(html, /function membershipVoidDrawerHtml/, 'membership void confirmation should render inside the drawer');
assert.match(fnBody('membershipVoidDrawerHtml'), /作废原因[\s\S]*确认作废/, 'membership void drawer should require a reason and confirmation action');
assert.doesNotMatch(fnBody('voidMembership'), /window\.prompt|confirm\(/, 'void membership should not use browser prompt or confirm');
assert.doesNotMatch(fnBody('openMembershipOrderModal'), /openStandardModal\(/, 'membership order should no longer use centered modal');
assert.doesNotMatch(fnBody('openMembershipBenefitPickerModal'), /openStandardModal\(/, 'membership benefit picker should no longer use centered modal');
assert.doesNotMatch(fnBody('openMembershipBenefitActionModal'), /document\.getElementById\('mBody'\)\.innerHTML/, 'membership benefit action should no longer manually fill legacy modal body');
assert.doesNotMatch(fnBody('openCourtMembershipLedgerModal'), /openStandardModal\(/, 'membership ledger should no longer use centered modal');
['账户类型','累计充值','累计消费','当前余额','累计订场','当前会员','实收金额','赠送金额','当前折扣','余额有效期','清零时间','充值备注','基本信息','跟进人','储值态度','备注'].forEach(label=>{
  assert.match(html,new RegExp(label),'membership account panel should expose the requested account overview fields');
});
['加入日期','末次跟进日期','下次跟进日期','熟悉程度'].forEach(label=>{
  assert.doesNotMatch(fnBody('courtProfileReadonlyHtml'), new RegExp(label), 'membership account profile should remove deprecated fields');
  assert.doesNotMatch(fnBody('courtProfileFormHtml'), new RegExp(label), 'membership account profile form should remove deprecated fields');
});
assert.doesNotMatch(fnBody('courtMembershipPanelHtml'), /renderDetailDrawerCard\('当前权益'/, 'membership account overview should not repeat current rights');
assert.match(fnBody('courtMembershipPanelHtml'), /renderDetailDrawerField\('账户类型'[\s\S]*renderDetailDrawerField\('累计充值'[\s\S]*renderDetailDrawerField\('累计消费'[\s\S]*renderDetailDrawerField\('当前余额'[\s\S]*renderDetailDrawerField\('累计订场'[\s\S]*\.\.\.memberFields[\s\S]*renderDetailDrawerField\('充值备注'/, 'membership account overview should render common account fields before member-only fields');
assert.match(html, /function courtProfileReadonlyHtml/, 'court detail should render user profile as a readonly card');
assert.match(html, /function courtProfileFormHtml/, 'court detail should render user profile as an inline edit form');
assert.match(html, /function editCourtProfileInline/, 'court detail should switch profile card into edit mode in place');
assert.match(html, /function cancelCourtProfileInlineEdit/, 'court detail should cancel profile editing back to readonly detail');
assert.match(html, /function saveCourtProfileInline/, 'court detail should save profile editing from inside the detail drawer');
assert.doesNotMatch(fnBody('courtMembershipPanelHtml'), /openCourtModal\('\$\{court\.id\}'\)/, 'court detail profile edit should not jump to the separate edit drawer');
assert.match(fnBody('courtMembershipPanelHtml'), /editCourtProfileInline\('\$\{court\.id\}'\)[\s\S]*courtProfileReadonlyHtml\(court\)/, 'court profile card should start readonly and expose inline edit');
assert.match(fnBody('membershipDrawerContentHtml'), /membershipDrawerMode==='profile-edit'[\s\S]*courtProfileEditPanelHtml\(court\)/, 'membership drawer should route profile edit mode inside the same drawer');
assert.match(fnBody('courtProfileEditPanelHtml'), /schedule-detail-card-actions[\s\S]*取消[\s\S]*保存/, 'court profile edit actions should stay in one right-aligned action group');
assert.match(fnBody('courtProfileReadonlyHtml'), /renderDetailDrawerField\('跟进人'[\s\S]*renderDetailDrawerField\('储值态度'[\s\S]*renderDetailDrawerField\('备注'[\s\S]*courtCleanUserNotes/, 'membership account overview should show standard follow-up fields in the profile card');
assert.match(fnBody('courtMembershipPanelHtml'), /const memberFields=account\?\[[\s\S]*renderDetailDrawerField\('当前会员'[\s\S]*renderDetailDrawerField\('开卡日期'[\s\S]*renderDetailDrawerField\('实收金额'[\s\S]*renderDetailDrawerField\('赠送金额'[\s\S]*renderDetailDrawerField\('当前折扣'[\s\S]*renderDetailDrawerField\('余额有效期'[\s\S]*renderDetailDrawerField\('清零时间'/, 'member-only fields should keep the requested member detail order');
assert.match(fnBody('courtMembershipPanelHtml'), /const memberFields=account\?\[[\s\S]*当前会员[\s\S]*\]:\[\]/, 'member-only fields should be hidden for normal users');
assert.doesNotMatch(fnBody('courtMembershipPanelHtml'), /renderDetailDrawerCard\('最近开卡'|renderDetailDrawerField\('说明'/, 'membership account overview should not keep the previous separate recent card');
assert.match(html, /function membershipOrderBenefitLinesHtml/, 'membership drawer should format purchase benefit summary as separate lines');
assert.match(fnBody('membershipOrderBenefitLinesHtml'), /split\('；'\)[\s\S]*membership-order-benefit-line/, 'membership purchase benefit summary should render each benefit on its own line');
assert.match(fnBody('membershipOrdersDrawerHtml'), /order\.customAdjustment[\s\S]*membershipPlanName[\s\S]*tms-tag[\s\S]*membership-order-title/, 'membership order custom tag should come from the read model');
assert.match(fnBody('membershipOrdersDrawerHtml'), /membershipReadModelRechargeRowsForCourt\(court\)[\s\S]*order\.benefitSummary/, 'membership order tab should use read-model benefit summary');
assert.doesNotMatch(html, /余额来自 courts\.history，仅展示不可直接修改/, 'membership account panel should not expose backend wording');
assert.match(html, /余额由充值和消费自动计算，不能在这里手动改/, 'membership account panel should explain readonly balance in user wording');
assert.match(html, /个性化调整|标准权益/, 'membership account panel should call out customized rights');
assert.doesNotMatch(html, /当前可用权益[\s\S]*权益批次[\s\S]*最近购买记录[\s\S]*本次成交权益/, 'membership account panel should not repeat the same rights three times');
assert.match(html, /function saveMembershipBenefitInline/, 'membership rights table should save consume and supplement inline');
assert.doesNotMatch(fnBody('membershipRightsDrawerHtml'), /label:'最早到期'|key:'expire'/, 'membership rights tab should not show earliest expiry column');
assert.doesNotMatch(fnBody('membershipRightsDrawerHtml'), /label:'次数'[\s\S]*membershipBenefitInlineInputId/, 'membership rights tab should not show a default count input column');
assert.match(fnBody('membershipRightsDrawerHtml'), /label:'操作'[\s\S]*openMembershipBenefitInlineEditor[\s\S]*消耗[\s\S]*补发/, 'membership rights tab should expose standard row actions');
assert.match(fnBody('membershipRightsDrawerHtml'), /minWidth:'510px'[\s\S]*label:'权益'[\s\S]*width:'150px'[\s\S]*label:'总次数'[\s\S]*width:'70px'[\s\S]*label:'已消耗'[\s\S]*width:'70px'[\s\S]*label:'剩余'[\s\S]*width:'70px'[\s\S]*label:'操作'[\s\S]*width:'150px'[\s\S]*align:'right'/, 'membership rights table should use compact columns and right aligned actions');
assert.match(pagesCss, /membership-rights-table \.detail-drawer-table[\s\S]*table-layout:fixed/, 'membership rights table should keep compact widths from being stretched');
assert.match(pagesCss, /membership-inline-count\{width:34px/, 'membership inline count input should be compact enough to avoid clipping');
assert.match(pagesCss, /membership-inline-actions[\s\S]*justify-content:flex-end/, 'membership rights row actions should align to the right');
assert.match(fnBody('membershipRightsDrawerHtml'), /membership-inline-editor[\s\S]*membershipBenefitInlineInputId[\s\S]*saveMembershipBenefitInline[\s\S]*取消/, 'membership rights tab should confirm consume and supplement inline');
assert.doesNotMatch(fnBody('membershipRightsDrawerHtml'), /openMembershipBenefitActionModal|openMembershipBenefitHistoryModal/, 'membership rights row actions should not navigate away from the rights tab');
assert.match(fnBody('membershipRightsDrawerHtml'), /消耗[\s\S]*补发/, 'membership rights row actions should show consume and supplement text');
assert.doesNotMatch(fnBody('membershipRightsDrawerHtml'), /actionsHtml:membershipDrawerActionButtons/, 'membership rights tab should not put global action buttons in the card header');
assert.match(fnBody('membershipAccountActionButtons'), /schedule-detail-action(?! primary)[\s\S]*续充会员[\s\S]*作废会员/, 'membership account actions should be text actions, not primary buttons');
assert.doesNotMatch(fnBody('courtMembershipPanelHtml'), /危险操作/, 'membership account overview should keep void action in member actions instead of a separate danger card');
assert.doesNotMatch(fnBody('courtMembershipPanelHtml'), /renderDetailDrawerCard\('会员操作'/, 'membership actions should live inside the membership account card instead of a separate module');
assert.match(fnBody('courtMembershipPanelHtml'), /renderDetailDrawerCard\('会员账户'[\s\S]*actionsHtml:membershipAccountActionButtons\(court\)/, 'membership account card should place membership actions in the title action area');
assert.match(html, /function courtMembershipBenefitRowsHtml/, 'membership account panel should render benefit rows');
assert.match(html, /function membershipBenefitBatchCardsHtml/, 'membership account panel should render benefit batches by order');
assert.match(html, /购买日期[\s\S]*方案名[\s\S]*批次到期/, 'membership batches should show purchase date, plan and expiry');
assert.match(html, /function membershipActionVisibility/, 'membership account panel should compute action visibility by status');
assert.match(html, /if\(\['voided','cleared'\]\.includes\(account\.status\)\)return \{reopen:true,ledger:true\}/, 'reopen should only be available for voided or cleared accounts');
assert.match(html, /已作废[\s\S]*折扣失效[\s\S]*权益不可再使用/, 'voided account panel should explain disabled discount and benefits');
assert.match(html, /重新开卡[\s\S]*权益流水/, 'voided or cleared accounts should keep reopen and ledger access');
assert.match(html, /if\(\['voided','cleared'\]\.includes\(account\?\.status\)\)return \[\]/, 'voided or cleared accounts should stop exposing available rights');
assert.match(html, /function openMembershipBenefitActionModal/, 'benefit actions should use dedicated modal');
assert.match(html, /function membershipBenefitConsumePreview/, 'benefit consume modal should build batch preview');
assert.match(html, /当前总剩余[\s\S]*优先扣减批次/, 'benefit consume modal should explain batch allocation');
assert.match(html, /如果当前批次不足，将继续扣减下一批/, 'benefit consume modal should explain cross-batch deduction');
assert.match(html, /本次补发会记入所选购买批次的权益调整，不会生成新的购买记录/, 'supplement modal should explain existing-batch attribution');
assert.match(html, /function openMembershipBenefitHistoryModal/, 'benefit history should have dedicated modal');
assert.match(html, /查看明细/, 'benefit card should use shorter history label');
assert.match(fnBody('membershipDetailTabsHtml'), /权益流水/, 'court detail should provide ledger access through the drawer tab');
assert.match(html, /function openCourtMembershipLedgerModal/, 'court detail should support all-benefit history modal');
assert.match(fnBody('openCourtMembershipLedgerModal'), /openCourtMembershipPanel\(courtId,\{tab:'ledger'\}\)/, 'all-benefit ledger should stay in the membership drawer');
assert.doesNotMatch(fnBody('membershipLedgerDrawerHtml'), /membershipBenefitLedger\.filter|membershipOrdersForAccount|membershipBenefitRowsForAccount/, 'member drawer ledger should not scan frontend raw orders or benefit ledger');
assert.match(fnBody('membershipLedgerDrawerHtml'), /membershipReadModelLedgerRowsForCourt\(court\)/, 'member drawer ledger should use unified read-model ledger rows');
assert.match(fnBody('membershipLedgerDrawerHtml'), /!membershipDrawerBenefitCode\|\|l\.benefitCode===membershipDrawerBenefitCode/, 'all-benefit history should support both all rows and one benefit detail');
assert.doesNotMatch(html, /openMembershipBenefitActionModal\('\$\{court\.id\}','ballMachine','consume'\)/, 'court detail shortcut actions should not hardcode ballMachine consume');
assert.doesNotMatch(html, /openMembershipBenefitActionModal\('\$\{court\.id\}','ballMachine','supplement'\)/, 'court detail shortcut actions should not hardcode ballMachine supplement');
assert.doesNotMatch(html, /openMembershipBenefitHistoryModal\('\$\{court\.id\}','ballMachine'\)/, 'court detail shortcut actions should not hardcode ballMachine history');

assert.match(html, /function studentMembershipSummaryHtml/, 'student detail should render linked court membership summary');
assert.match(html, /关联订场账户会员摘要/, 'student detail should label linked membership summary');
assert.match(html, /大师公开课[\s\S]*穿线免手工费[\s\S]*发球机免费[\s\S]*国家二级运动员陪打[\s\S]*指定教练陪打/, 'membership plan form should expose structured benefit fields');
assert.match(html, /余额有效期按支付日期起算 12 个月/, 'membership purchase flow should surface balance validity rule based on pay date');
assert.match(html, /系统创建日期只用于留痕，不影响会员有效期/, 'membership purchase flow should explain created time does not affect validity');
assert.match(html, /若到期时仍有余额，可自动进入延续期，最长至 24 个月/, 'membership purchase flow should surface extended validity rule');
assert.match(html, /低于原合规档位续充时，余额有效期不会重置/, 'membership purchase flow should warn when low-tier renewal does not reset validity');
assert.match(html, /余额由充值和消费自动计算，不能在这里手动改/, 'membership views should explain readonly balance in user wording');
assert.match(html, /每批赠送权益有效期 12 个月/, 'membership purchase flow should surface benefit batch validity rule');
assert.match(html, /function membershipOrderPreview/, 'membership order modal should build preview data');
assert.match(html, /function openMembershipOrderModal\(courtId,mode='renew'\)/, 'membership order modal should support first open renew and reopen modes');
assert.doesNotMatch(fnBody('refreshMembershipOrderPreview'), /本次会发生什么/, 'membership order preview should not show the old extra heading');
assert.match(html, /是否重置有效期[\s\S]*折扣变化[\s\S]*原有权益保留[\s\S]*本次新增权益/, 'membership order preview should explain the main impact clearly');
assert.match(fnBody('membershipOrderDrawerHtml'), /renderStandardDropdownHtml\('mo_plan','会员方案 \*'[\s\S]*onMembershipOrderPlanChange/, 'membership order plan should use the standard dropdown');
assert.doesNotMatch(fnBody('membershipOrderDrawerHtml'), /<select[^>]+id="mo_plan"/, 'membership order plan should not use native select');
assert.match(fnBody('membershipOrderDrawerHtml'), /<details class="membership-drawer-details" open>[\s\S]*本次额外赠送/, 'one-time adjustments should be expanded by default');
assert.match(fnBody('membershipOrderDrawerHtml'), /id="mo_notes"[\s\S]*\$\{help\}/, 'membership validity help should sit below notes');
assert.match(fnBody('membershipOrderDrawerHtml'), /membership-drawer-help[\s\S]*当前订场折扣按最近一次充值档位生效/, 'membership validity help should keep the full rule copy');
assert.match(html, /我了解折扣和有效期变化，确认续充/, 'low-tier renewal should use stronger confirm wording');
assert.match(html, /function membershipOrderDraftFromPlan/, 'membership order modal should derive one-time benefit draft from selected plan');
assert.match(html, /function membershipStepperHtml/, 'membership forms should use stepper helper');
assert.match(html, /function membershipPlanPreviewHtml/, 'membership plan form should render realtime preview');
assert.match(html, /function refreshMembershipPlanPreview/, 'membership plan form should refresh preview on input');
assert.match(html, /售卖开始日期[\s\S]*售卖结束日期[\s\S]*方案状态/, 'membership plan form should expose sale window and plan status fields');
assert.match(html, /草稿[\s\S]*上架[\s\S]*停售/, 'membership plan form should expose draft, active and inactive statuses');
assert.match(html, /saleStartDate[\s\S]*saleEndDate/, 'membership plan save and rendering should include sale window fields');
assert.doesNotMatch(html, /id="mp_discount"[^>]*value="1"/, 'membership plan discount should not force default value 1 in html');
assert.doesNotMatch(html, /例如 8 折填 0\.8/, 'membership plan discount should not ask operators to type decimal discount');
assert.match(html, /mp_discount/, 'membership plan discount should use explicit option selection');
assert.doesNotMatch(html, /id="mp_publicLesson"[^>]*value="0"/, 'membership plan benefit inputs should not force default zero in html');
assert.doesNotMatch(html, /id="mo_publicLesson"[^>]*value="0"/, 'membership order adjustment inputs should not force default zero in html');
assert.match(html, /本次额外赠送/, 'membership order modal should allow one-time benefit adjustments');
assert.match(html, /大师公开课本次调整[\s\S]*穿线免手工费本次调整[\s\S]*发球机免费本次调整[\s\S]*国家二级运动员陪打本次调整[\s\S]*指定教练陪打本次调整/, 'membership order modal should expose one-time benefit adjustment fields');
assert.match(html, /指定教练范围本次调整/, 'membership order modal should expose one-time designated coach override');
assert.match(html, /选择指定教练/, 'membership plan and order forms should use coach-linked designated coach selector');
assert.match(html, /function membershipCoachSelectorHtml/, 'designated coach selection should be rendered by helper');
assert.match(html, /coaches\.map/, 'designated coach selector should be linked to coach records');
assert.match(html, /function membershipOrderBenefitSummaryHtml/, 'membership purchase list should render readable benefit batch summary');
assert.match(html, /额外赠送/, 'membership purchase list should show one-off extra benefit adjustments');
assert.match(html, /function renderMembershipOrdersAuditPage/, 'membership page should render purchase audit as a standalone page');
assert.match(html, /function renderMembershipLedgerAuditPage/, 'membership page should render ledger audit as a standalone page');
assert.match(membershipShell, /onclick="goPage\(\\'membership-orders\\'\)"/, 'membership management purchase audit entry should navigate to standalone page');
assert.match(membershipShell, /onclick="goPage\(\\'membership-ledger\\'\)"/, 'membership management ledger audit entry should navigate to standalone page');
assert.match(fnBody('membershipLedgerAuditRows'), /courtAccountListViewData\?\.membershipLedgerAuditRows\|\|\[\][\s\S]*l\.action!=='grant'/, 'global benefit audit should hide grant rows from the unified read model');
assert.doesNotMatch(fnBody('membershipLedgerAuditRows'), /membershipBenefitLedger|courts\.find\(/, 'global benefit audit must not scan frontend raw benefit ledger or court rows');
assert.match(html, /支付日期[\s\S]*订场用户[\s\S]*会员方案[\s\S]*系统价[\s\S]*成交价[\s\S]*赠送金额[\s\S]*折扣[\s\S]*是否重置有效期[\s\S]*当次权益摘要[\s\S]*状态/, 'membership purchase audit should keep reduced audit fields');
assert.match(html, /时间[\s\S]*订场用户[\s\S]*购买批次[\s\S]*权益[\s\S]*变动[\s\S]*动作[\s\S]*原因/, 'membership ledger audit should keep audit columns only');
assert.match(html, /此页面仅用于审计与追溯，不用于日常操作/, 'audit page should explain read-only positioning');
assert.match(html, /权益有效期固定 12 个月[\s\S]*余额最长按当前系统规则至 24 个月/, 'membership plan form should explain fixed validity rules');
assert.match(html, /可用权益/, 'membership account list should expose benefit summary');
assert.match(fnBody('renderMemberships'), />查看<\/span>/, 'membership account list should expose account detail entry');
assert.match(html, /function membershipDisplayStatus/, 'frontend should compute display status labels');
assert.match(html, /function membershipStatusTagMeta/, 'frontend should compute membership status tag styles');
assert.match(html, /assets\/styles\/components\/status-tags\.css/, 'membership status tags should live in the shared component stylesheet');
assert.match(fnBody('membershipStatusTagMeta'), /tagClass:'tms-member-status is-active'[\s\S]*tagClass:'tms-member-status is-inactive'[\s\S]*tagClass:'tms-member-status is-expired'/, 'membership status tag metadata should use the shared component classes');
assert.match(fnBody('membershipStatusTagMeta'), /text:'活跃'[\s\S]*text:'未开通'[\s\S]*text:'已过期'/, 'membership status tag labels should use the standard three labels');
assert.match(statusCss, /\.tms-member-status\{[^}]*display:inline-flex[^}]*height:16px[^}]*min-width:42px[^}]*padding:0 6px[^}]*border-radius:6px[^}]*font-size:10px/, 'membership status tag should use the compact active-tag size');
assert.match(statusCss, /\.tms-member-status::before\{[^}]*width:4px[^}]*height:4px[^}]*border-radius:50%/, 'membership status tag should render the standard 4px status dot');
assert.match(statusCss, /\.tms-member-status\.is-inactive,.tms-member-status\.is-expired\{min-width:54px;padding:0 8px\}/, 'longer membership status labels should adapt wider than the active tag');
assert.match(statusCss, /\.tms-member-status\.is-active\{[^}]*background:#ECFDF5[^}]*border-color:#D9F9E6[^}]*color:#047857/, 'active membership tag should use the standard green colors');
assert.match(statusCss, /\.tms-member-status\.is-active:hover\{background:#D9F9E6\}/, 'active membership tag hover should use the standard green hover color');
assert.match(statusCss, /\.tms-member-status\.is-active::before\{background:#10B981\}/, 'active membership tag dot should use the standard green dot');
assert.match(statusCss, /\.tms-member-status\.is-inactive\{[^}]*background:#F4F4F5[^}]*border-color:#E5E5E8[^}]*color:#52525B/, 'inactive membership tag should use the standard gray colors');
assert.match(statusCss, /\.tms-member-status\.is-inactive:hover\{background:#E5E5E8\}/, 'inactive membership tag hover should use the standard gray hover color');
assert.match(statusCss, /\.tms-member-status\.is-inactive::before\{background:#A1A1A9\}/, 'inactive membership tag dot should use the standard gray dot');
assert.match(statusCss, /\.tms-member-status\.is-expired\{[^}]*background:#FCF3F2[^}]*border-color:#FAE3E3[^}]*color:#AA2E26/, 'expired membership tag should use the standard red colors');
assert.match(statusCss, /\.tms-member-status\.is-expired:hover\{background:#FAE3E3\}/, 'expired membership tag hover should use the standard red hover color');
assert.match(statusCss, /\.tms-member-status\.is-expired::before\{background:#DD524C\}/, 'expired membership tag dot should use the standard red dot');
assert.match(html, /function membershipValidityHint/, 'frontend should compute validity hint text');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*开通会员/, 'court edit modal should not include membership open action');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*续充会员/, 'court edit modal should not include membership renew action');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*消耗 1 次/, 'court edit modal should not include benefit consume action');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*补发/, 'court edit modal should not include benefit supplement action');
assert.match(html, /function normalizeCurrentPageForRole/, 'frontend should normalize landing page by role before rendering');
assert.match(html, /function renderRoleShell/, 'frontend should centralize role shell rendering');
assert.match(html, /function toggleSidebarCollapsed\(/, 'shell should support collapsing and expanding the left sidebar');
assert.match(html, /class="sidebar-toggle" onclick="toggleSidebarCollapsed\(\)"/, 'sidebar should expose a dedicated collapse toggle');
assert.match(html, /width="20" height="20" viewBox="0 0 20 20"[\s\S]*fill="#C5B0A2"/, 'sidebar collapse icon should use the requested 20px warm gray svg');
assert.match(pagesCss, /body\.sidebar-collapsed\{--sw:64px\}/, 'collapsed sidebar should shrink to icon width and let main content adapt');
assert.match(pagesCss, /body\.sidebar-collapsed \.sb-item\{[^}]*justify-content:center/, 'collapsed sidebar should show icon-only menu items');
assert.match(html, /function syncSidebarItemTitles\(/, 'collapsed sidebar should sync menu labels for hover tooltips');
assert.match(html, /item\.setAttribute\('title',title\)/, 'collapsed sidebar should expose menu names through native hover title');
assert.match(pagesCss, /body\.sidebar-collapsed \.sb-item:hover::after\{[^}]*content:attr\(data-title\)/, 'collapsed sidebar should show menu name on hover');
assert.match(pagesCss, /\.sidebar\{[^}]*transition:width 180ms ease/, 'sidebar width should animate like a drawer');
assert.match(pagesCss, /\.main\{[^}]*transition:margin-left 180ms ease/, 'main content should follow sidebar drawer animation');
assert.match(html, /applyLoadedData[\s\S]*normalizeCurrentPageForRole\(\);[\s\S]*renderRoleShell\(\);/, 'load-all should re-sync shell after user role changes');
assert.match(html, /function clearLoadedData/, 'frontend should clear stale data when login\/load-all fails');
assert.match(html, /let lastDataSyncAt=0,isSyncingAll=false,dataRequestVersion=0;/, 'frontend should track request version to ignore stale load-all responses');
assert.match(html, /const requestVersion=\+\+dataRequestVersion;[\s\S]*if\(requestVersion!==dataRequestVersion\)return;/, 'load-all and background sync should ignore stale responses from older sessions');
assert.match(html, /clearLoadedData\(\);[\s\S]*buildCampusTabs\(\);[\s\S]*renderAll\(\);[\s\S]*toast\('加载失败：'/, 'load-all failure should clear stale data and stale campus tabs before showing error');
assert.match(html, /if\(!court\)\{toast\('当前订场用户数据未加载，请刷新后重试','warn'\);return;\}/, 'membership entry should not silently fail when court data is missing');
assert.match(html, /function effectiveMembershipBenefitSource/, 'membership summary should treat empty snapshots as missing and keep falling back');
assert.match(html, /function membershipOrderEffectiveBenefitSource/, 'frontend should centralize deal snapshot priority for benefit display');
assert.doesNotMatch(html, /effectiveMembershipBenefitSource\(order\?\.benefitSnapshot,order,order\?\.planBenefitTemplateSnapshot,plan\)/, 'frontend benefit display should not refill omitted rights from the plan after a deal snapshot exists');
assert.match(html, /const planCount=parseInt\(planSnap\?\.\[item\.code\]\?\.count\)\|\|0;/, 'membership purchase list should compare current order total against plan base count');
assert.match(html, /const benefits=benefitRows\.length\?benefitRows\.map\(b=>`\$\{b\.label\} \$\{b\.remaining\}\/\$\{b\.total\}`\)\.join\('；'\):'-';/, 'membership account list should show remaining\/total benefit counts');
assert.match(html, /function resetModalActions\(\)/, 'membership modals should clear stale footer actions before using body-level action areas');
assert.match(html, /function openMembershipOrderModal/, 'membership order modal should remain available');
assert.match(html, /function openMembershipBenefitActionModal/, 'benefit action modal should remain available');
assert.match(fnBody('openMembershipDrawer'), /actionsHtml:''/, 'membership account drawer should not append an extra close footer');
assert.doesNotMatch(html, /extraClass:'modal-member'|className=.*modal-member(?!ship)/, 'membership account panel should not use the old centered member modal shell');
assert.match(pagesCss, /modal-membership-drawer/, 'membership drawer should have scoped drawer styling');
assert.match(html, /售卖时间[\s\S]*方案状态[\s\S]*操作/, 'membership plan list should show sale window and plan status columns');
assert.match(html, /tms-action-link[\s\S]*(删除[\s\S]*上架[\s\S]*编辑|停售[\s\S]*编辑)/, 'membership plan list should use the requested action order');
assert.match(html, /style="white-space:normal;line-height:1\.55;min-width:500px;max-width:none;color:#A3968F"/, 'membership plan benefits should show full text when the table scrolls horizontally');
assert.match(html, /if\(pg==='membership-orders'\)renderMembershipOrdersAuditPage\(\);/, 'page router should render standalone purchase audit page');
assert.match(html, /if\(pg==='membership-ledger'\)renderMembershipLedgerAuditPage\(\);/, 'page router should render standalone ledger audit page');
assert.match(html, /'membership-orders'[\s\S]*'membership-ledger'/, 'admin pages should include membership audit pages');
assert.doesNotMatch(html, /async function saveMembershipOrder[\s\S]*?await loadAll\(\)[\s\S]*?function openMembershipBenefitModal/, 'membership order save should avoid full reload to reduce waiting time');
assert.match(html, /if\(Date\.now\(\)-lastDataSyncAt>60000\)syncAllQuietly\(\);/, 'background sync should not refetch full data too aggressively');
assert.match(html, /setInterval\(syncAllQuietly,180000\);/, 'background sync interval should be reduced to avoid overloading save flows');
assert.doesNotMatch(html, /membershipBenefitCourtFilter/, 'membership management page should remove the global benefit batch filter');
assert.doesNotMatch(html, /赠送权益批次 = 每次购买送了什么、还剩多少、何时到期/, 'membership management page should no longer expose global benefit batch explanation');
assert.doesNotMatch(html, /请选择权益账户，排课必须绑定课包权益/, 'schedule form should not hard-block saving when no entitlement is selected');
assert.doesNotMatch(membershipShell, /会员状态|余额有效期|清零时间/, 'membership management list should hide member status, balance validity and clear time columns');
assert.match(html, /function membershipBookingCount\(/, 'membership management should expose a helper to count stored-value bookings');
assert.match(fnBody('membershipBookingCount'), /h\.type==='消费'&&isStoredValuePayMethod\(h\.payMethod\)&&String\(h\.category\|\|''\)\.includes\('订场'\)/, 'membership booking count should only include stored-value booking consumption');
assert.match(membershipShell, /class="tms-membership-audit-action tms-membership-audit-action-orders" onclick="goPage\(\\'membership-orders\\'\)"[\s\S]*历史订单/, 'membership purchase audit entry should use the new history order entry');
assert.match(membershipShell, /class="tms-membership-audit-action tms-membership-audit-action-ledger" onclick="goPage\(\\'membership-ledger\\'\)"[\s\S]*权益消耗记录/, 'membership ledger audit entry should use the new benefit consume entry');
assert.match(pagesCss, /\.tms-toolbar-secondary-actions\{display:flex;align-items:center;gap:8px\}/, 'toolbar secondary button container should keep 8px spacing');
assert.match(pagesCss, /\.tms-membership-audit-action\{[^}]*display:inline-flex[^}]*align-items:center[^}]*gap:6px[^}]*color:#F1E9E2[^}]*font-size:13px[^}]*font-weight:400[^}]*line-height:36px/, 'membership audit entries should match import/export text action style');
assert.match(pagesCss, /\.tms-membership-audit-action svg\{[^}]*width:16px[^}]*height:16px[^}]*color:#F1E9E2/, 'membership audit icons should use 16px cream icons');
assert.doesNotMatch(fnBody('renderMemberships'), /const statusMeta=membershipStatusTagMeta\(account\);/, 'membership management rows should not render a member status column');
assert.match(html, /function membershipVisibleCourt/, 'membership management should ignore deleted or archived court users');
assert.match(fnBody('membershipBaseRows'), /courtAccountListViewData\?\.items/, 'membership management should build rows from the unified court account read model');
assert.match(fnBody('membershipBaseRows'), /courtAccountListViewData\?\.items\|\|\[\][\s\S]*item=>item\?\.accountType==='会员账户'/, 'membership management list should come from the unified court account read model');
assert.doesNotMatch(fnBody('membershipBaseRows'), /membershipLifecycleRows\(\)|membershipAccounts\.filter/, 'membership management list should not fall back to lifecycle/raw membership account scans');
assert.match(html, /function isActiveCourtRecord\(/, 'frontend should centralize active court filtering');
assert.match(fnBody('isActiveCourtRecord'), /status!=='inactive'&&status!=='deleted'&&!court\?\.deletedAt&&!court\?\.mergedIntoCourtId/, 'active court filtering should exclude hidden, deleted and merged users');
assert.match(fnBody('renderMemberships'), /openCourtMembershipPanel\('\$\{item\.id\}'\)/, 'membership account action should open the account for the visible read-model row');
assert.match(html, /const accountState=courtAccountStateLabel\(item\);/, 'court rows should derive account state from read-model item');
assert.match(html, /memberLabel:'-',tierLabel:'-',status:membershipDisplayStatus\(account\),discount:'-',validUntil:'-'/, 'voided or cleared membership summaries should clear benefit display in court list');
assert.match(html, /style="white-space:normal;line-height:1\.55;min-width:320px;color:#A3968F"/, 'membership management benefits should use the same remark color as membership plan notes');
assert.match(html, /style="white-space:normal;line-height:1\.55;min-width:500px;max-width:none;color:#A3968F"/, 'membership plan benefits should use the remark color while staying fully visible');
assert.match(fnBody('renderCourtAccountListView'), />查看<\/span>/, 'court user list should label the account action as view');
assert.match(html, /function openMembershipBenefitPickerModal/, 'generic consume and supplement actions should let operators choose a benefit type');
assert.match(fnBody('saveMembershipBenefit'), /runStandardMutation\('membershipBenefitSaveBtn'/, 'benefit save action should show a submitting state through the global mutation helper');
assert.match(fnBody('saveMembershipBenefit'), /refresh:async\(\)=>\{[\s\S]*await loadCourtReadModelGuardData\(\{force:true\}\);[\s\S]*openCourtMembershipPanel\(courtId,\{tab:'rights'\}\)/, 'benefit save should force-refresh the unified membership read model before reopening rights');
assert.match(fnBody('saveMembershipBenefitInline'), /refresh:async\(\)=>\{[\s\S]*await loadCourtReadModelGuardData\(\{force:true\}\);[\s\S]*membershipInlineBenefitAction=\{benefitCode:'',mode:''\}/, 'inline benefit save should force-refresh the unified membership read model before redrawing rights');
assert.match(html, /会员管理[\s\S]*\/[\s\S]*会员购买记录/, 'purchase audit page should use breadcrumb-style navigation');
assert.match(html, /会员管理[\s\S]*\/[\s\S]*会员权益流水/, 'ledger audit page should use breadcrumb-style navigation');
assert.match(html, /tms-audit-note/, 'audit pages should use a slim read-only note');
assert.match(html, /label:'支付日期'[\s\S]*label:'录入时间'[\s\S]*label:'订场用户'/, 'membership order audit should show pay date and recorded time columns');
assert.match(html, /会员方案 \*[\s\S]*系统价格[\s\S]*实收\/充值金额[\s\S]*改价原因/, 'membership order modal should expose system price and override reason fields');
assert.match(html, /label:'支付日期'[\s\S]*label:'系统价'[\s\S]*label:'成交价'[\s\S]*label:'改价原因'/, 'membership order audit should show price snapshot columns');
assert.match(fnBody('renderMemberships'), /const tierLabel=item\.membershipTierLabel\|\|'-'/, 'membership management should show the read-model member tier');
assert.match(html, /formatMembershipLedgerTime/, 'membership ledger audit should format readable date and time');
assert.match(html, /membershipLedgerActionText/, 'membership ledger audit should translate backend actions to Chinese');
assert.match(html, /membershipLedgerOperatorText/, 'membership ledger audit should normalize operator account names');
assert.match(html, /renderStandardCellText\(membershipLedgerOperatorText\(l\.operator\)\)/, 'membership ledger audit should render the normalized operator account name');
assert.match(html, /操作账号/, 'membership ledger audit should show operator account');
assert.match(html, /已消耗/, 'membership account rights should show consumed count');
assert.match(html, /作废信息[\s\S]*作废时间[\s\S]*作废人[\s\S]*作废原因/, 'membership account panel should show voiding audit information');
assert.match(pagesCss, /membership-rights-row\{display:grid;grid-template-columns:minmax\(0,1fr\) 110px 110px 110px 140px/, 'membership rights should keep expiry and counts in one row');
assert.match(fnBody('membershipBenefitRowsForAccount'), /courtAccountListViewData\?\.items[\s\S]*item\?\.benefitRows\|\|\[\]/, 'frontend benefit summary should read totals and remaining counts from the unified read model');
assert.doesNotMatch(fnBody('membershipBenefitSummaryForOrder'), /membershipBenefitLedger\.filter|positiveDelta|negativeDelta/, 'frontend benefit summary must not recalculate supplements and consumption from raw ledger rows');
assert.match(html, /let membershipPage=1,membershipPageSize=15,membershipSortKey='firstOpenDate',membershipSortDir='desc'/, 'membership management should default to first-open date descending with the global 15-row page size');
assert.match(fnBody('membershipDefaultSortDir'), /return 'desc'/, 'first-open date sort should start with newest member first');
assert.match(html, /function setMembershipSort\(key\)/, 'membership management should support standard three-state sorting');
assert.match(fnBody('renderMemberships'), /const firstOpenDate=String\(item\.firstOpenDate\|\|''\)\.slice\(0,10\)/, 'membership management should show first-open date from the read model');
assert.match(html, /function onMembershipSearchChange\(\)/, 'membership management search should reset to the first page');
assert.match(membershipShell, /search:\{id:'membershipSearch',oninput:'onMembershipSearchChange\(\)'/, 'membership management search should use the standard search handler');
assert.match(html, /let membershipTierFilterValue=''/, 'membership management should keep a member type filter value');
assert.match(membershipShell, /filterHostIds:\['membershipTierFilter'\]/, 'membership management should expose a member type filter');
assert.match(html, /function onMembershipToolbarFilterChange\(\)/, 'membership member type filter should rerender from page one');
assert.match(membershipShell, /会员类型[\s\S]*会员余额[\s\S]*会员订场[\s\S]*累计订场/, 'membership management should use the requested column labels and booking columns');
assert.match(membershipShell, /首次开卡时间[\s\S]*续费次数[\s\S]*会员余额/, 'membership management should show renewal count after first open date');
assert.match(membershipShell, /label:'操作'[\s\S]*style:'width:90px;padding-right:12px;text-align:right'/, 'membership management action column should use the compact action width');
assert.doesNotMatch(fnBody('renderMemberships'), /当前会员|当前余额|订场次数/, 'membership management should remove old column labels');
assert.match(fnBody('renderMemberships'), /renderCourtMiniBar\(finance\.balance,finance\.totalDeposit/, 'membership balance should use the same mini bar as court users');
assert.match(fnBody('renderMemberships'), /membershipReadModelBookingForCourt\(item\)[\s\S]*memberBookingCount[\s\S]*bookingCount/, 'membership management should show member bookings and total bookings from the unified read model');
assert.match(fnBody('renderMemberships'), /const renewalCount=Math\.max\(0,Number\(item\.membershipRenewalCount\)\|\|0\)/, 'membership management should render renewal count from the unified read model');
assert.match(fnBody('renderMemberships'), /\$\{renewalCount\}次/, 'membership management should display renewal count as times');
assert.match(fnBody('renderMemberships'), /查看<\/span><span class="tms-action-link" onclick="openCourtFinanceModal\('\$\{item\.id\}'\)">订场/, 'membership management should provide view and booking actions');
assert.match(membershipShell, /data-membership-sort="firstOpenDate"[\s\S]*首次开卡时间[\s\S]*data-membership-sort="balance"[\s\S]*data-membership-sort="bookingCount"/, 'membership management should expose sortable first-open date, balance and booking count columns');
assert.doesNotMatch(membershipShell, /data-membership-sort="validUntil"/, 'membership management should not expose validity sorting after hiding the validity column');
assert.match(fnBody('renderMemberships'), /<div class="tms-text-primary">\$\{esc\(item\.displayName\)\}<\/div>/, 'membership management name should use the same bold primary style as formal students');
assert.match(membershipShell, /label:'姓名'[\s\S]*className:'tms-sticky-l'/, 'membership management should freeze the member name column using the global customer display name');
assert.match(membershipShell, /membershipPagerInfo[\s\S]*membershipPageSize[\s\S]*membershipPagerBtns/, 'membership management should use the standard compact pager');
assert.match(fnBody('renderMemberships'), /renderStandardEmptyText\(benefits\)/, 'membership management should normalize empty benefit text to hyphen');
assert.doesNotMatch(fnBody('renderMemberships'), /membershipBenefitRowsForAccount|membershipFirstOpenDate|courtMembershipTierLabel\(a\)/, 'membership management rows should not recalculate tier, first-open date, or benefits from frontend raw data');
assert.doesNotMatch(fnBody('courtMembershipPanelHtml'), /membershipOrdersForAccount|membershipBenefitRowsForAccount|membershipBenefitLedger\.filter/, 'membership overview drawer should not scan frontend raw membership facts');
assert.match(fnBody('membershipOrdersDrawerHtml'), /membershipReadModelRechargeRowsForCourt\(court\)/, 'membership recharge drawer should use unified read-model recharge rows');
assert.match(fnBody('membershipRightsDrawerHtml'), /membershipReadModelBenefitRowsForCourt\(court\)/, 'membership rights drawer should use unified read-model benefit rows');
assert.match(fnBody('courtBookingDrawerHtml'), /membershipReadModelBookingRowsForCourt\(court\)/, 'membership booking drawer should use unified read-model booking rows');
assert.match(pagesCss, /#page-memberships \.tms-table th\.tms-sticky-l[\s\S]*left:0/s, 'membership management table should freeze the left name column');
assert.match(pagesCss, /#page-memberships \.tms-pagination[\s\S]*min-height:32px/, 'membership management pager should keep the standard compact height');
assert.match(pagesCss, /#page-memberships \.tms-table td\{padding-top:6px;padding-bottom:6px;font-size:12px;line-height:1\.15\}/, 'membership management rows should use the compact standard row height');

console.log('membership view tests passed');
