const assert = require('assert');
const fs = require('fs');
const path = require('path');

const repoRoot = path.join(__dirname, '..');
const operationsPagePath = path.join(repoRoot, 'server/page-data/operations-page.js');
const operationsMetricsPath = path.join(repoRoot, 'server/metrics/operations-metrics.js');
const operationsSnapshotPath = path.join(repoRoot, 'server/page-data/operations-snapshot.js');
const operationsSnapshotRunnerPath = path.join(repoRoot, 'scripts/rebuild-operations-snapshot.js');
const operationsSnapshotWorkflowPath = path.join(repoRoot, '.github/workflows/operations-snapshot-rebuild.yml');
const residualPageDataPath = path.join(repoRoot, 'server/page-data/residual-pages.js');
const courtReadModelPath = path.join(repoRoot, 'server/page-data/court-account-read-model.js');
const leadSourceReadModelPath = path.join(repoRoot, 'server/lead-source-read-model.js');
const operationsSourcePath = path.join(repoRoot, 'server/read-models/operations-source.js');
const apiIndexPath = path.join(repoRoot, 'api/index.js');
const budgetPath = path.join(repoRoot, 'config/api-index-budget.json');

assert.ok(fs.existsSync(operationsPagePath), 'operations page-data route should live in server/page-data/operations-page.js');
assert.ok(fs.existsSync(operationsMetricsPath), 'operations metric calculations should live in server/metrics/operations-metrics.js');
assert.ok(fs.existsSync(operationsSnapshotPath), 'operations page should have a dedicated snapshot read model');
assert.ok(fs.existsSync(operationsSnapshotRunnerPath), 'operations snapshot rebuild should have a Node runner outside Vercel');
assert.ok(fs.existsSync(operationsSnapshotWorkflowPath), 'operations snapshot rebuild should have a scheduled GitHub workflow');
assert.ok(fs.existsSync(leadSourceReadModelPath), 'lead list and operations conversion should share one lead source read model');
assert.ok(fs.existsSync(operationsSourcePath), 'all four operations dashboards should read base rows from one operations source model');

const operationsPageSource = fs.readFileSync(operationsPagePath, 'utf8');
const operationsMetricsSource = fs.readFileSync(operationsMetricsPath, 'utf8');
const operationsSnapshotSource = fs.readFileSync(operationsSnapshotPath, 'utf8');
const operationsSnapshotRunnerSource = fs.readFileSync(operationsSnapshotRunnerPath, 'utf8');
const operationsSnapshotWorkflowSource = fs.readFileSync(operationsSnapshotWorkflowPath, 'utf8');
const courtReadModelSource = fs.readFileSync(courtReadModelPath, 'utf8');
const leadSourceReadModelSource = fs.readFileSync(leadSourceReadModelPath, 'utf8');
const operationsSourceModelSource = fs.readFileSync(operationsSourcePath, 'utf8');
const residualSource = fs.readFileSync(residualPageDataPath, 'utf8');
const apiSource = fs.readFileSync(apiIndexPath, 'utf8');
const budget = JSON.parse(fs.readFileSync(budgetPath, 'utf8'));

assert.match(operationsPageSource, /function handleOperationsPageData/, 'operations page-data module should expose handleOperationsPageData');
assert.match(operationsPageSource, /buildOperationsMetrics/, 'operations page-data should delegate calculations to server/metrics/operations-metrics.js');
assert.match(operationsPageSource, /function projectOperationsPagePayload/, 'operations page-data should support lightweight view-model projection');
assert.match(operationsPageSource, /view === 'coach'[\s\S]*operations: \{[\s\S]*overview:[\s\S]*coach:/, 'coach operations view should return only overview guard data and coach metrics');
assert.match(operationsPageSource, /view: view === 'coach' \? 'coach' : ''/, 'operations page scope should include the lightweight coach view key');
assert.match(operationsSnapshotSource, /createOperationsSnapshotLoader/, 'operations snapshot should expose a direct loader for the page route');
assert.match(operationsSnapshotSource, /scopeKey\(user, scope\)/, 'operations snapshot key must include the current user scope, campus and date range');
assert.match(operationsSnapshotSource, /SNAPSHOT_SOURCE_MARKER_ID/, 'operations snapshot should track source writes so stale data is not served as latest');
assert.match(operationsPageSource, /require\('\.\.\/read-models\/customer-lifecycle\.js'\)/, 'operations page-data should import the unified customer lifecycle read model');
assert.match(operationsPageSource, /const customerLifecycleRows=buildCustomerLifecycleRows\(scoped\);[\s\S]*customerLifecycleRows,/, 'operations page-data should pass unified lifecycle rows into operations metrics');
assert.match(courtReadModelSource, /module\.exports = \{[\s\S]*bookingDurationHours[\s\S]*courtHistoryBusinessDate[\s\S]*isCourtBookingHistoryRow[\s\S]*normalizeCourtHistory/, 'court account read model should export the court history helpers used by operations metrics');
assert.match(operationsPageSource, /getFinancePageSnapshot/, 'operations page-data should be able to read the same full finance snapshot as the finance overview');
assert.match(operationsPageSource, /await getFinancePageSnapshot\(\)/, 'operations page-data should cold-build the full finance snapshot instead of depending on a lucky cache hit');
assert.match(operationsPageSource, /scanFirstRows/, 'operations page-data should use projected first-row reads instead of full raw table scans');
assert.match(operationsSourceModelSource, /OPERATIONS_CACHE_TTL_MS/, 'operations source model should cache raw read rows briefly so date switches do not rescan every table');
assert.match(leadSourceReadModelSource, /const LEAD_SOURCE_READ_LIMIT = 2000;/, 'shared lead source should use one current full-pool read limit instead of page-specific 300/600 limits');
assert.match(leadSourceReadModelSource, /detectOverflow:\s*true/, 'shared lead source should fail loudly when the unified read limit is exceeded');
assert.match(operationsSourceModelSource, /readLeadSourceRows/, 'operations conversion should read leads from the shared lead source');
assert.match(operationsSourceModelSource, /detectOverflow:\s*true/, 'operations source reads should fail loudly when a table exceeds the trusted projection limit');
assert.doesNotMatch(operationsPageSource, /T_LEADS[\s\S]{0,160}limit:\s*600/, 'operations conversion must not keep its own 600-row lead source');
assert.match(operationsPageSource, /require\('\.\.\/read-models\/operations-source\.js'\)/, 'operations page-data should depend on the shared operations source model');
assert.match(operationsSourceModelSource, /function getOperationsBaseRows/, 'operations source model should own the shared base row loading');
assert.match(operationsSourceModelSource, /function getOperationsCoachBaseRows/, 'operations source model should expose a lightweight coach view source');
assert.match(operationsSourceModelSource, /getOperationsCoachBaseRows[\s\S]*courts: \[\],[\s\S]*membershipAccounts: \[\],[\s\S]*membershipOrders: \[\]/, 'coach operations source should not read court history or membership tables');
assert.match(operationsPageSource, /scope\?\.view === 'coach' \? getOperationsCoachBaseRows : getOperationsBaseRows/, 'coach operations view should use the lightweight coach source loader');
assert.match(operationsSourceModelSource, /readLeadSourceRows/, 'operations source model should use the same lead source as the leads page');
assert.doesNotMatch(operationsPageSource, /async function getOperationsBaseRows/, 'operations page-data should not keep a second base row loader');
assert.match(operationsPageSource, /getOperationsRowsCacheKey/, 'operations snapshot rebuild scope should be scoped before reuse');
assert.doesNotMatch(operationsPageSource, /OPERATIONS_RESULT_STALE_TTL_MS/, 'operations page-data must not return old stale results as realtime operations data');
assert.match(operationsPageSource, /getOperationsResultCacheKey[\s\S]*scope\.campus[\s\S]*scope\.campusName[\s\S]*dateRange\.startDate[\s\S]*dateRange\.endDate/, 'computed operations cache should be scoped by selected campus and date range');
assert.doesNotMatch(operationsPageSource, /const cachedOperations = operationsResultCache\.get\(resultCacheKey\)/, 'operations page-data request path must not reuse in-process computed payloads as latest data');
assert.match(operationsPageSource, /function invalidateOperationsPageDataCache\(\)/, 'operations page-data should keep the invalidation hook used by source writes');
assert.doesNotMatch(operationsPageSource, /function readStaleOperationsResultCache/, 'operations page-data should not keep a stale-result read path');
assert.doesNotMatch(operationsPageSource, /return sendJson\(res, stalePayload\)/, 'operations page-data should not answer with stale cached payloads');
assert.doesNotMatch(operationsPageSource, /operationsResultCache\.set\(resultCacheKey/, 'operations page-data request path must not calculate then cache the dashboard on open');
assert.match(operationsPageSource, /operationsSnapshotSync\?\.enqueueRebuildTask/, 'page requests should only enqueue snapshot work when a snapshot is missing or stale');
assert.doesNotMatch(operationsPageSource, /operationsSnapshotSync\?\.queueRebuildScope/, 'page requests must not start heavy snapshot rebuilds inside Vercel');
assert.match(operationsSourceModelSource, /OPERATIONS_LEAD_FIELDS[\s\S]*OPERATIONS_SCHEDULE_FIELDS/, 'operations source model should keep a dedicated projection field list for the operations read model');
assert.match(operationsSourceModelSource, /OPERATIONS_LEAD_FIELDS[\s\S]*formalCoach/, 'operations source model should include formalCoach for conversion coach filters');
assert.match(operationsSourceModelSource, /OPERATIONS_PURCHASE_FIELDS[\s\S]*'paidAmount'[\s\S]*'receivedAmount'[\s\S]*'coachPriceName'[\s\S]*'coachPriceSnapshot'/, 'operations source model should read real coach ownership and receipt fallback fields for coach efficiency');
assert.match(operationsSourceModelSource, /OPERATIONS_COURT_FIELDS[\s\S]*'history'/, 'operations source model should read court history for campus venue heatmaps');
assert.match(operationsSourceModelSource, /OPERATIONS_SCHEDULE_FIELDS[\s\S]*'venueId'[\s\S]*'locationType'[\s\S]*'externalVenueName'/, 'operations source model should read schedule venue id and external venue flags for utilization');
assert.match(operationsSourceModelSource, /function getOperationsScheduleRows/, 'operations source model should own the operations schedule read path');
assert.match(operationsSourceModelSource, /getOperationsScheduleRows\(\{[\s\S]*getScheduleListRows[\s\S]*table:\s*T_SCHEDULE[\s\S]*columns:\s*OPERATIONS_SCHEDULE_FIELDS/, 'operations source should prefer the same complete schedule rows used by schedule list and calendar');
assert.doesNotMatch(operationsSourceModelSource, /readOperationsRows\(\{\s*table:\s*T_SCHEDULE/, 'operations source should not cap schedule rows with the generic first-row read path');
assert.match(operationsPageSource, /const loadBaseRows = scope\?\.view === 'coach' \? getOperationsCoachBaseRows : getOperationsBaseRows;[\s\S]*getScheduleListRows,/, 'operations page-data should pass the schedule list reader into the selected operations source');
assert.match(residualSource, /handleOperationsPageData\(\{[\s\S]*getScheduleListRows[\s\S]*tables:\{[\s\S]*T_SCHEDULE/, 'residual operations route should pass getScheduleListRows into operations page-data');
assert.match(operationsSourceModelSource, /OPERATIONS_ENTITLEMENT_LEDGER_FIELDS[\s\S]*'sourceDate'[\s\S]*'sourceTimeBand'[\s\S]*'sourceVenue'/, 'operations source model should read historical course ledger venue and time fields for heatmaps');
assert.match(operationsSourceModelSource, /T_ENTITLEMENT_LEDGER[\s\S]*OPERATIONS_ENTITLEMENT_LEDGER_FIELDS/, 'operations source model should scan entitlement ledger rows for court heatmaps');
assert.match(operationsSourceModelSource, /OPERATIONS_FOLLOWUP_FIELDS[\s\S]*'leadId'[\s\S]*'followupAt'[\s\S]*'statusAfter'/, 'operations source model should read lead follow-up event dates for evidence-based conversion trends');
assert.match(operationsSourceModelSource, /T_LEAD_FOLLOWUPS[\s\S]*OPERATIONS_FOLLOWUP_FIELDS/, 'operations source model should scan lead followups for conversion event evidence');
assert.match(operationsMetricsSource, /leadFollowups:\s*filterRowsByDateRange/, 'operations metrics should include lead followups in date-range evidence rows');
assert.match(operationsMetricsSource, /function buildOverviewTrendDailyRows\(\{[\s\S]*financeNormalizedRows[\s\S]*buildFinanceOverviewSummaryFromRows\(dayFinanceRows\)/, 'overview KPI trends should aggregate real finance rows through the shared finance summary read model');
assert.match(operationsMetricsSource, /function lifecycleRowsForData\(data = \{\}\)/, 'operations metrics should use one lifecycle row source for conversion calculations');
assert.match(operationsMetricsSource, /if \(Array\.isArray\(data\.customerLifecycleRows\) && data\.customerLifecycleRows\.length\) return data\.customerLifecycleRows;/, 'operations metrics should prefer lifecycle rows already built by page-data');
assert.doesNotMatch(operationsMetricsSource, /buildPlatformMetrics/, 'operations conversion must not use the full searchable customer pool as course lead statistics');
assert.match(operationsMetricsSource, /require\('\.\.\/read-models\/platform-metrics\.js'\)/, 'operations metrics should reuse the unified lead-pool read model when deriving raw lead stages');
assert.match(operationsMetricsSource, /buildRawLeadConversionMetrics/, 'operations metrics should call the unified raw lead conversion read model');
assert.match(operationsMetricsSource, /const rawLeadConversion = buildRawLeadConversionMetrics\(\{[\s\S]*leads: metricLifecycleSource\.leads \|\| \[\],[\s\S]*customerLifecycleRows: metricCustomerLifecycleRows[\s\S]*\}\)/, 'operations conversion should derive scoped raw lead cohort metrics from platform-metrics');
assert.match(operationsMetricsSource, /metricLifecycleSource[\s\S]*buildScopedLifecycleSource\(\{[\s\S]*rangedData[\s\S]*customerLifecycleRows[\s\S]*\},\s*metricScope\)/, 'operations conversion should scope lead/student metrics through the unified lifecycle source');
assert.doesNotMatch(operationsMetricsSource, /function buildOperationsLeadStudentRoster|function buildLeadStudentRoster|leadStudentRoster:\s*\[[\s\S]*HISTORICAL_STUDENTS/, 'operations must not define a second backend formula for the lead/student roster funnel');
assert.match(operationsMetricsSource, /const stageRows = rawLeadConversion\.stageRows/, 'operations stage rows should be driven by unified raw lead-pool rows instead of a second local stage tree');
assert.match(operationsMetricsSource, /const totalLeads = rawLeadConversion\.totalLeads/, 'operations conversion lead total should use unified raw valid leads only');
assert.match(operationsMetricsSource, /const convertedLeads = rawLeadConversion\.convertedLeads/, 'operations converted leads should use total成交口径 from unified raw lead rows');
assert.match(operationsMetricsSource, /const sourceRows = rawLeadConversion\.sourceRows/, 'operations source rows should use total成交口径 from unified raw lead rows');
assert.match(operationsMetricsSource, /function courtTrendDays\(\{[\s\S]*financeNormalizedRows[\s\S]*financeCourtBookingRows/, 'court KPI trends should use real finance booking row dates when court history is unavailable');
assert.match(operationsMetricsSource, /function conversionTrendSourceDates[\s\S]*appointmentEventDate[\s\S]*attendanceEventDate[\s\S]*dealEventDate/, 'conversion KPI trends should use real event evidence dates instead of leadDate only');
assert.match(operationsMetricsSource, /function financeRowsAsCoachPurchases[\s\S]*financeCourseRows[\s\S]*cashDelta[\s\S]*purchaseDate: financeBusinessDate/, 'coach KPI trends should use real course finance rows when purchase detail rows are unavailable');
assert.match(operationsMetricsSource, /function operationsTrendDateRange/, 'operations metrics should derive a real multi-day trend window separately from the selected KPI range');
assert.match(operationsMetricsSource, /function buildTrendDiagnostics/, 'operations metrics should expose trend diagnostics for all four dashboards');
assert.match(operationsMetricsSource, /trendDiagnostics:\s*buildTrendDiagnostics/, 'each operations dashboard should return trend diagnostics');
assert.match(operationsPageSource, /mergeDuplicateLeadRows/, 'operations page-data should use the same deduped lead pool as the leads page');
assert.match(operationsSourceModelSource, /function invalidateOperationsSourceCache\(\)[\s\S]*operationsRowsCache\.clear\(\)/, 'operations source model should expose raw row cache invalidation for realtime writes');
assert.match(apiSource, /OPERATIONS_SOURCE_TABLES=new Set\(\[[\s\S]*T_LEADS[\s\S]*T_LEAD_FOLLOWUPS[\s\S]*T_SCHEDULE[\s\S]*T_COURTS[\s\S]*T_PURCHASES[\s\S]*\]\)/, 'api should list operation source tables that invalidate operations caches');
assert.match(apiSource, /onTableWrite\(t,meta\)\{[\s\S]*OPERATIONS_SOURCE_TABLES\.has\(t\)[\s\S]*invalidateOperationsSourceCache\(\)[\s\S]*invalidateOperationsPageDataCache\(\)[\s\S]*recordSourceChange/, 'storage writes to operation source tables should invalidate operations caches and mark snapshots stale immediately');
assert.match(residualSource, /require\('\.\/operations-page\.js'\)/, 'residual page-data routes should import operations-page.js');
assert.match(residualSource, /path==='\/page-data\/operations'&&method==='GET'/, 'residual page-data routes should own /page-data/operations');
assert.match(residualSource, /handleOperationsPageData/, 'residual page-data routes should delegate the operations route');
assert.match(residualSource, /loadOperationsSnapshot:operationsSnapshotSync\.loadSnapshot|loadOperationsSnapshot/, 'residual operations route should pass the operations snapshot loader');
assert.match(operationsPageSource, /enqueueRebuildTask\(\{ user, scope, reason: 'page-miss' \}\)/, 'operations page should persist snapshot rebuild tasks on miss without blocking the page request');
assert.doesNotMatch(operationsPageSource, /pageData\.operationsSnapshot\.bootstrap/, 'operations page request must not synchronously bootstrap slow snapshots');
assert.doesNotMatch(apiSource, /\/page-data\/operations[\s\S]{0,300}buildOperationsMetrics/, 'api/index.js should not inline operations calculations');
assert.match(apiSource, /T_OPERATIONS_SNAPSHOT='ft_operations_snapshot'/, 'API must declare the operations snapshot table');
assert.match(apiSource, /\[T_OPERATIONS_SNAPSHOT,\{ttlMs:60000\}\]/, 'operations snapshot should use hot row cache for 1s reads');
assert.match(apiSource, /\/admin\/operations-snapshot\/rebuild/, 'API should expose an admin rebuild endpoint for operations snapshots');
assert.match(apiSource, /prewarmStudentTeachingSummaryCache\(\)\{[\s\S]*DISABLE_HOT_SCAN_PREWARM/, 'API load-time teaching summary prewarm must be disabled for snapshot runner commands');
assert.match(apiSource, /\['campus','campusName','startDate','endDate','view'\]/, 'manual operations snapshot rebuild should preserve the lightweight view scope');
assert.match(apiSource, /createOperationsSnapshotSync\(\{getCachedRow,put,mkTable,scanByIdPrefix/, 'operations snapshot sync must be able to scan queued rebuild tasks by id prefix');
assert.doesNotMatch(apiSource, /\/cron\/operations-snapshot\/rebuild/, 'slow operations snapshot rebuild must not run inside Vercel request handlers');
assert.match(operationsSnapshotRunnerSource, /view: value\('--view'\)/, 'operations snapshot runner should support rebuilding the lightweight coach view');
assert.match(operationsSnapshotRunnerSource, /commonScopes: argv\.includes\('--common-scopes'\)/, 'operations snapshot runner should support prebuilding common date scopes');
assert.match(operationsSnapshotRunnerSource, /shardCount: Math\.max\(1, Math\.min\(parseInt\(value\('--shard-count'\)/, 'operations snapshot runner should support sharded common date rebuilds');
assert.match(operationsSnapshotRunnerSource, /function buildCommonScopeArgs\(/, 'operations snapshot runner should build common coach date ranges before users open filters');
assert.match(operationsSnapshotRunnerSource, /processQueuedRebuilds\(\{ limit: args\.limit, includeFailed: false \}\)/, 'operations snapshot runner must process date-filter misses from the durable queue');
assert.match(operationsSnapshotWorkflowSource, /matrix:[\s\S]*shard: \[0, 1, 2, 3, 4, 5\]/, 'operations snapshot workflow must split common scopes into parallel shards');
assert.match(operationsSnapshotWorkflowSource, /--write --view coach --common-scopes --shard-count 6 --shard-index \$\{\{ matrix\.shard \}\}/, 'operations snapshot workflow must prebuild common date scopes in bounded shards');
assert.match(operationsSnapshotRunnerSource, /parseInt\(value\('--limit'\) \|\| '1'/, 'operations snapshot runner should keep queued rebuild batches small by default');
assert.match(operationsSnapshotRunnerSource, /processQueuedRebuilds\(\{ limit: args\.limit, includeFailed: false \}\)/, 'operations snapshot runner must process durable queued tasks without retrying failed jobs every run');
assert.match(operationsSnapshotRunnerSource, /listCampusesWithDefaults\(\)[\s\S]*buildCommonScopeArgs\(args, new Date\(\), campusRows\)[\s\S]*rebuildScope\(\{ user, scope: buildScope\(scopeArgs\), reason: args\.commonScopes \? 'script-common-scope' : 'script-default' \}\)/, 'operations snapshot runner must prebuild the default, campus and common date scopes');
assert.match(apiSource, /T_LEADS/, 'api/index.js should pass lead tables into extracted page-data routes');
assert.match(apiSource, /getFinancePageSnapshot/, 'api/index.js should pass the full finance snapshot accessor into extracted page-data routes');
assert.match(apiSource, /scanFirstRows/, 'api/index.js should pass projected read support into extracted page-data routes');
assert.ok(
  budget.extractedModules.includes('server/page-data/operations-page.js') &&
  budget.extractedModules.includes('server/metrics/operations-metrics.js'),
  'api index budget should track the new extracted operations modules'
);

console.log('operations page-data tests passed');
