const assert = require('assert');
const fs = require('fs');
const path = require('path');

const repoRoot = path.join(__dirname, '..');
const indexSource = fs.readFileSync(path.join(repoRoot, 'public/index.html'), 'utf8');
const componentsSource = fs.readFileSync(path.join(repoRoot, 'public/assets/scripts/core/components.js'), 'utf8');
const bootstrapSource = fs.readFileSync(path.join(repoRoot, 'public/assets/scripts/core/bootstrap.js'), 'utf8');
const stateSource = fs.readFileSync(path.join(repoRoot, 'public/assets/scripts/core/state.js'), 'utf8');
const chartsPath = path.join(repoRoot, 'public/assets/scripts/standard/charts.js');
const operationsPath = path.join(repoRoot, 'public/assets/scripts/pages/operations.js');
const stylesPath = path.join(repoRoot, 'public/assets/styles/pages.css');

assert.ok(fs.existsSync(chartsPath), 'global chart wrapper should live in public/assets/scripts/standard/charts.js');
assert.ok(fs.existsSync(operationsPath), 'operations page should live in public/assets/scripts/pages/operations.js');
assert.ok(fs.existsSync(stylesPath), 'operations page styles should live in public/assets/styles/pages.css');

const chartsSource = fs.readFileSync(chartsPath, 'utf8');
const operationsSource = fs.readFileSync(operationsPath, 'utf8');
const stylesSource = fs.readFileSync(stylesPath, 'utf8');
const courtOverviewSource = operationsSource.slice(
  operationsSource.indexOf('function renderOperationsCourtCampusOverview'),
  operationsSource.indexOf('function renderOperationsCourtHeatCell')
);

assert.match(indexSource, /id="page-operations"/, 'index.html should contain the operations page section');
assert.match(indexSource, /cdn\.jsdelivr\.net\/npm\/echarts/, 'index.html should load Apache ECharts from a CDN');
assert.match(indexSource, /\/assets\/scripts\/standard\/charts\.js/, 'index.html should load the global chart wrapper');
assert.match(indexSource, /\/assets\/scripts\/pages\/operations\.js/, 'index.html should load the operations page script');
assert.match(componentsSource, /setOperationsTab\('court'\);goPage\('operations',this\)[\s\S]*场地运转/, 'sidebar should expose court operations as a left menu item');
assert.doesNotMatch(componentsSource, /setOperationsTab\('overview'\);goPage\('operations',this\)[\s\S]*经营总览/, 'sidebar should not expose operations overview');
assert.doesNotMatch(componentsSource, /setOperationsTab\('conversion'\);goPage\('operations',this\)[\s\S]*转化与留存/, 'sidebar should not expose conversion');
assert.doesNotMatch(componentsSource, /setOperationsTab\('coach'\);goPage\('operations',this\)[\s\S]*教练人效/, 'sidebar should not expose coach efficiency');
assert.doesNotMatch(componentsSource, /data-nav-page="operations" data-operations-tab="overview"/, 'operations overview should not be a left menu item');
assert.doesNotMatch(componentsSource, /data-nav-page="operations" data-operations-tab="conversion"/, 'operations conversion should not be a left menu item');
assert.match(componentsSource, /<div class="sb-sec">财务中心<\/div>[\s\S]*财务总览[\s\S]*收款流水[\s\S]*入账流水/, 'finance menu should remain as an independent module');
assert.match(componentsSource, /<div class="sb-sec">财务中心<\/div>[\s\S]*<div class="sb-sec">经营分析<\/div>[\s\S]*<div class="sb-sec">基础设置<\/div>/, 'operations menu should sit between finance center and basic settings');
assert.match(bootstrapSource, /operations:'经营分析'/, 'page title map should include operations');
assert.match(bootstrapSource, /OPERATIONS_TITLE_MAP=\{court:'场地运转'\}/, 'operations page title should use court operations only');
assert.match(bootstrapSource, /n\.dataset\.operationsTab===tab/, 'operations sidebar should only highlight the selected sub menu item');
assert.match(bootstrapSource, /adminPages=\[[^\]]*'operations'/, 'operations should be admin-only');
assert.match(stateSource, /if\(pg==='operations'\)renderOperations\(\)/, 'renderPageData should render operations');
assert.match(operationsSource, /let operationsActiveTab = 'court'/, 'operations should open court operations by default');
assert.match(operationsSource, /operationsActiveTab = tab === 'court' \? 'court' : 'court'/, 'operations should only allow the court tab for now');
assert.match(componentsSource, /globalTopFilterPages\(\)\{[\s\S]*'operations'/, 'operations page should reuse the global top date filter');
assert.match(componentsSource, /if\(currentPage==='operations'\)\{\s*return `[^`]*renderStandardTopDropdown\('globalTopDate'/, 'operations top filter should only render the date filter');
assert.doesNotMatch(componentsSource, /if\(currentPage==='operations'\)\{\s*return `[^`]*globalTopCampus/, 'operations top filter should not render campus filter');
assert.match(componentsSource, /if\(currentPage==='operations'\)reloadOperationsPageDataWithInlineLoading\(\)/, 'operations page should reload aggregate data through inline skeletons when the global date filter changes');
assert.match(stateSource, /async function reloadOperationsPageDataWithInlineLoading\(\)/, 'operations page should have a dedicated inline refresh path');
assert.match(stateSource, /reloadOperationsPageDataWithInlineLoading[\s\S]*renderOperationsLoading\(\)[\s\S]*ensureDatasetsByName\(\['operationsPage'\],\{force:true\}\)/, 'operations inline refresh should show local skeleton and refresh only operations data');
assert.doesNotMatch(stateSource, /reloadOperationsPageDataWithInlineLoading[\s\S]{0,500}pageLoading/, 'operations inline refresh should not show the global loading overlay');
assert.match(stateSource, /function operationsPageDataUrl\(\)/, 'state loader should build an operations endpoint URL with date range params');
assert.match(stateSource, /operationsPage:\(\)=>apiCall\('GET',operationsPageDataUrl\(\)\)/, 'state loader should call the operations aggregate endpoint with the selected date range');
assert.match(stateSource, /operations:\['operationsPage'\]/, 'operations page should rely on the aggregate endpoint only');
assert.match(stateSource, /loadedDatasets\.add\('operationsPage'\)/, 'operations aggregate data should be tracked as loaded');
assert.match(chartsSource, /echarts\.init/, 'only the standard chart wrapper should initialize ECharts');
assert.match(chartsSource, /renderStandardChart/, 'standard chart wrapper should expose renderStandardChart');
assert.match(chartsSource, /buildStandardPieChartOption/, 'standard chart wrapper should expose a reusable pie chart option builder');
assert.match(chartsSource, /renderProgressFunnel/, 'standard chart wrapper should expose the Gemini-style progress funnel component');
assert.match(chartsSource, /operations-funnel-track[\s\S]*operations-funnel-step-rate[\s\S]*环节转化/, 'progress funnel should show step conversion rate inside the funnel bar');
assert.doesNotMatch(chartsSource, /占总线索/, 'progress funnel should no longer show overall total-lead rate');
assert.doesNotMatch(chartsSource, /operations-funnel-total-rate/, 'progress funnel should remove the external total-rate line');
assert.match(chartsSource, /operations-funnel-scale[\s\S]*25%[\s\S]*50%[\s\S]*75%[\s\S]*100%/, 'progress funnel should include dashboard-style percentage scale marks');
assert.match(chartsSource, /operations-funnel-loss-badge[\s\S]*流失/, 'progress funnel should show visible loss badges beside each drop-off step');
assert.match(stylesSource, /operations-funnel-card\{min-height:374px\}/, 'funnel card should be roughly one third shorter than the previous 560px version');
assert.match(stylesSource, /operations-funnel-host\{min-height:304px\}/, 'funnel host should be roughly one third shorter than the previous 456px version');
assert.match(stylesSource, /operations-funnel-track\{height:30px/, 'funnel bars should shrink with the compact card');
assert.match(chartsSource, /emphasis[\s\S]*focus/, 'ECharts series should expose hover emphasis');
assert.match(chartsSource, /buildOperationsCourtQuadrantChartOption/, 'court comparison should use a dedicated quadrant bubble chart builder');
assert.match(chartsSource, /type:\s*'scatter'/, 'court comparison should render as a scatter bubble chart');
assert.match(chartsSource, /markLine[\s\S]*平均利用率[\s\S]*平均收入/, 'court quadrant should show average lines for business positioning');
assert.match(chartsSource, /symbolSize[\s\S]*bookingCount/, 'court quadrant bubble size should express booking count');
assert.match(chartsSource, /#14B8A6[\s\S]*#CBD5E1/, 'court quadrant should use professional revenue/no-data colors');
assert.match(chartsSource, /grid: \{ left: 12, right: 12, top: 28, bottom: 34, containLabel: false \}/, 'court quadrant should reduce left whitespace and prevent right-side clipping');
assert.match(chartsSource, /axisLabel: \{ inside: true[\s\S]*formatter: value => `¥\$\{fmt\(value \/ 10000\)\}万`/, 'court quadrant should use compact inside revenue labels');
assert.match(chartsSource, /const source = rawRows\.filter\(row => row\.hasData\)/, 'court quadrant should only plot campuses that already have data');
assert.doesNotMatch(chartsSource, /label: \{ color: row\.hasData \?/, 'court quadrant should not style or label no-data campuses in the plot');
assert.match(stylesSource, /operations-funnel-row:hover[\s\S]*operations-funnel-track/, 'custom funnel should have visible hover interaction');
assert.match(stylesSource, /operations-channel-card:hover[\s\S]*transform:translateY/, 'channel cards should have visible hover interaction');
assert.match(stylesSource, /operations-attribute-card:hover[\s\S]*transform:translateY/, 'attribute cards should have visible hover interaction');
assert.match(stylesSource, /operations-court-top-grid\{display:grid;grid-template-columns:minmax\(0,1\.65fr\) minmax\(320px,\.9fr\);gap:14px\}/, 'court quadrant should get the primary visual area beside a ranking matrix');
assert.match(stylesSource, /operations-court-top-grid \.operations-section\{min-height:380px;padding:18px;overflow:hidden\}/, 'court top cards should have enough height for a professional dashboard chart');
assert.match(stylesSource, /operations-module-head h3\{[^}]*font-size:13px/, 'court module titles should be 13px');
assert.match(stylesSource, /operations-module-head span\{[^}]*font-size:11px/, 'court module subtitles should be 11px');
assert.match(stylesSource, /operations-court-ranking-matrix/, 'court overview should render as a dashboard ranking matrix');
assert.match(stylesSource, /operations-court-comparison-chart\{height:296px;min-height:296px\}/, 'court quadrant chart should have enough vertical room');
assert.match(stylesSource, /operations-court-ranking-row\{[^}]*display:grid;grid-template-columns:112px minmax\(0,1fr\)/, 'ranking rows should use a fixed campus column so metrics get enough space');
assert.match(stylesSource, /operations-court-ranking-metric\{[^}]*grid-template-columns:132px minmax\(92px,1fr\)/, 'ranking metrics should separate label/value from the data bar');
assert.match(stylesSource, /operations-court-status-badge/, 'ranking matrix should expose business status badges');
assert.match(stylesSource, /operations-rate-cell strong\{[^}]*font-size:12px[^}]*font-weight:400/, 'court overview progress numbers should use 12px normal text');
assert.doesNotMatch(stylesSource, /@media\(max-width:1500px\)\{[\s\S]*operations-court-top-grid\{grid-template-columns:1fr\}/, 'court comparison and overview should stay side by side on normal desktop widths');
assert.doesNotMatch(stylesSource, /operations-court-overview-table/, 'court overview should no longer use a table shell');
assert.match(stylesSource, /operations-court-heat-cell:hover[\s\S]*transform:translateY[\s\S]*box-shadow[\s\S]*z-index/, 'court heat cells should lift and highlight on hover');
assert.match(stylesSource, /operations-court-heat-tooltip\{[\s\S]*position:absolute[\s\S]*pointer-events:none/, 'court heat cells should use custom hover tooltip instead of the browser title bubble');
assert.match(stylesSource, /operations-court-heat-cell:hover \.operations-court-heat-tooltip\{[\s\S]*opacity:1[\s\S]*visibility:visible/, 'custom heat tooltip should appear on cell hover');
assert.match(stylesSource, /operations-court-heat-scroll\{[^}]*scrollbar-width:none/, 'court heatmap horizontal scroll should stay usable with an invisible scrollbar');
assert.match(stylesSource, /operations-court-heat-scroll::-webkit-scrollbar\{display:none\}/, 'court heatmap should hide the WebKit scrollbar track');
assert.match(stylesSource, /operations-court-heatmap-card\{gap:12px;background:#FFFFFF;border-color:#E3E8F2\}/, 'court heatmap should share the same dashboard card surface as the top charts');
assert.match(stylesSource, /operations-court-heatmap-card \.operations-module-head\{margin-bottom:8px;padding-bottom:10px\}/, 'court heatmap tabs should sit closer to the header');
assert.match(stylesSource, /operations-court-heat-campus-tabs\{[^}]*padding:4px[^}]*background:#F8FAFC/, 'court heatmap tabs should use a restrained segmented-control style');
assert.match(stylesSource, /operations-court-heat-hour\{[^}]*font-size:10px/, 'court heatmap hour labels should be 10px');
assert.match(stylesSource, /operations-court-heat-cell\{[^}]*height:24px/, 'court heatmap cells should be compact and aligned with the dashboard style');
assert.match(stylesSource, /operations-court-heat-legend\{[^}]*gap:16px[^}]*padding-top:12px[^}]*font-size:11px/, 'court heatmap legend should be smaller and tighter');
assert.match(stylesSource, /operations-court-heat-legend i\{[^}]*width:14px[^}]*height:14px/, 'court heatmap legend squares should be smaller');
assert.match(stylesSource, /operations-court-heat-kpis div\{[^}]*display:flex[^}]*min-height:52px/, 'court heatmap KPI blocks should be compact horizontal metric bars');
assert.match(stylesSource, /operations-court-empty-heat/, 'empty campus heatmaps should render a clear empty state instead of blank space');
assert.match(stylesSource, /\.operations-page\{display:flex;flex-direction:column;gap:16px;background:transparent;border-radius:0;padding:0/, 'operations page should not render an extra large outer background frame');
assert.match(stylesSource, /operations-court-skeleton-grid\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\);gap:14px\}/, 'court loading skeleton should match the real court layout');
assert.match(stylesSource, /operations-funnel-head strong\{font-size:13px;line-height:20px;font-weight:400/, 'funnel step labels should be 13px normal weight');
assert.match(operationsSource, /renderStandardChart/, 'operations page should use standard chart wrapper');
assert.match(operationsSource, /renderProgressFunnel/, 'conversion page should use the Gemini-style progress funnel component');
assert.match(operationsSource, /renderOperationsCourtComparison[\s\S]*校区经营象限/, 'court page should render a business quadrant chart');
assert.match(operationsSource, /renderOperationsCourtCampusOverview[\s\S]*校区指标排行/, 'court page should render the ranking matrix');
assert.match(operationsSource, /const rows = data\.court\?\.campusRows \|\| \[\]/, 'court overview should render campus rows');
assert.match(operationsSource, /operations-court-ranking-row[\s\S]*收入[\s\S]*利用率[\s\S]*体验转化[\s\S]*老客转化/, 'court overview should render visual metric rows instead of columns');
assert.match(operationsSource, /operationsCourtStatus/, 'court overview should classify each campus into a readable business status');
assert.match(operationsSource, /return \{ label: '', tone: 'idle' \}/, 'court overview should not show a pending-input badge for no-data campuses');
assert.match(operationsSource, /status\.label \? `<span class="operations-court-status-badge/, 'court overview should only render a status badge when there is a real label');
assert.doesNotMatch(operationsSource, /待录入/, 'operations court dashboard should not render pending-input labels');
assert.match(operationsSource, /\{ height: 296 \}/, 'court comparison render height should match the quadrant chart CSS height');
assert.doesNotMatch(courtOverviewSource, /片场地|次使用|venueCount|usageCount/, 'court overview should only show the requested fields');
assert.match(operationsSource, /renderOperationsCourtHeatmap[\s\S]*校区热力看板/, 'court page should render the renamed heatmap board');
assert.match(operationsSource, /operationsCourtHeatCampusTabs[\s\S]*顺义马坡[\s\S]*朝阳十里堡[\s\S]*蓝色港湾[\s\S]*国网[\s\S]*朝珺私教/, 'court heatmap should expose campus tabs with the requested default campus order');
assert.match(operationsSource, /operationsActiveCourtHeatCampus\s*=\s*'顺义马坡'/, 'court heatmap should default to Shunyi Mapo');
assert.match(operationsSource, /setOperationsCourtHeatCampus\(campusName\)/, 'court heatmap campus tabs should switch inside the shared heatmap card');
assert.doesNotMatch(operationsSource, /operationsHelpMark|operations-help-mark|\?<\/span>/, 'court modules should not render question mark help icons');
assert.doesNotMatch(courtOverviewSource, /operationsSimpleTable/, 'court overview should not use the standard table component');
assert.match(operationsSource, /operations-court-ranking-matrix[\s\S]*operations-court-ranking-row/, 'court overview should render as one-row-per-campus ranking matrix');
assert.match(operationsSource, /renderOperationsCourt[\s\S]*operations-court-top-grid[\s\S]*renderOperationsCourtComparison[\s\S]*renderOperationsCourtCampusOverview[\s\S]*renderOperationsCourtHeatmaps/, 'court comparison and overview should be grouped in one row before heatmap');
assert.match(operationsSource, /renderOperationsLoading[\s\S]*operationsActiveTab === 'court'[\s\S]*operations-court-skeleton-grid/, 'court loading skeleton should use the court layout');
assert.match(operationsSource, /renderOperationsCourtHeatCell\(slot = \{\}, venue = \{\}, options = \{\}\)/, 'court heat cell should receive venue context and row options for hover detail');
assert.match(operationsSource, /slot\.heatRate[\s\S]*operationsCourtHeatStyle\(toneRate, usedMinutes\)/, 'court heat cell color should use a continuous relative heat scale while keeping true utilization in the label');
assert.match(operationsSource, /data-heat="\$\{fmt\(toneRate\)\}"/, 'court heat cell should expose relative heat data for debugging visual gradients');
assert.match(operationsSource, /capacityMinutes[\s\S]*occupiedCount[\s\S]*dayCount[\s\S]*占用 \$\{fmt\(occupiedCount\)\}次 \/ \$\{fmt\(dayCount\)\}天[\s\S]*时长 \$\{fmt\(usedMinutes\)\} \/ \$\{fmt\(capacityMinutes\)\}分钟/, 'court heat tooltip should show count and minute numerator/denominator');
assert.match(operationsSource, /operationsCourtHeatVenueName[\s\S]*legacyUnmatchedVenueNames[\s\S]*未匹配/, 'court heatmap should normalize legacy unmatched names at render time');
assert.match(operationsSource, /aria-label="[^"]*\$\{esc\(venueName\)\}[\s\S]*\$\{esc\(hour\)\}[\s\S]*\$\{fmt\(rate\)\}%[\s\S]*\$\{fmt\(usedMinutes\)\}分钟/, 'court heat cell should expose venue, time, utilization and occupied minutes for hover/accessibility');
assert.doesNotMatch(operationsSource, /title="\$\{esc\(label\)\}"/, 'court heat cell should not rely on the browser native tooltip');
assert.match(operationsSource, /data-rate="\$\{fmt\(rate\)\}"/, 'court heat cell should expose utilization data for debugging hover states');
assert.match(operationsSource, /operations-court-empty-heat[\s\S]*暂无启用场地/, 'campus heatmap should show a clear empty state when no active venues exist');
assert.match(operationsSource, /operationsCourtHeatTone\(value, minutes = 0\)[\s\S]*usedMinutes > 0[\s\S]*return 'low'/, 'court heatmap should show any occupied slot as low load instead of looking empty');
assert.match(operationsSource, /黄金时段利用率[\s\S]*非黄金时段利用率/, 'court heatmap should expose golden and off-peak utilization rates');
assert.match(operationsSource, /grid-template-columns:86px repeat[\s\S]*minmax\(0, 1fr\)/, 'court heatmap time cells should stretch to align with the KPI blocks');
assert.match(operationsSource, /闲置[\s\S]*较低[\s\S]*中等[\s\S]*较高[\s\S]*高热/, 'court heat legend should use concise five-level labels');
assert.doesNotMatch(operationsSource, /历史未匹配场地/, 'court heatmap UI should rename historical unmatched venues to unmatched');
assert.doesNotMatch(operationsSource, /场地使用排行/, 'court page should remove the old venue ranking card');
assert.doesNotMatch(operationsSource, /场地时段热力/, 'court page should remove the old single heatmap chart card');
assert.match(operationsSource, /operationsFallbackCourseRows[\s\S]*stageRows[\s\S]*sourceRows/, 'conversion page should fall back to existing operations summary data instead of rendering empty panels');
assert.doesNotMatch(operationsSource, /echarts\.init/, 'operations page should not initialize ECharts directly');
assert.doesNotMatch(operationsSource, /schedule-detail-tabs|schedule-detail-tab/, 'operations page should not reuse schedule detail tabs as its top navigation');
assert.doesNotMatch(operationsSource, /operationsTabsHtml|operations-tabs|operations-tab/, 'operations page should not render page-level horizontal tabs');
assert.match(operationsSource, /renderConversionCommandCenter[\s\S]*转化与留存数据中心[\s\S]*最大流失环节/, 'conversion page should render a data-center style command summary');
assert.match(operationsSource, /operationsConversionKpiCards[\s\S]*预约率[\s\S]*到课率[\s\S]*成交率[\s\S]*续费率/, 'conversion page should render monitor KPI cards derived from the funnel');
assert.match(operationsSource, /renderConversionInsightModule[\s\S]*关键洞察[\s\S]*最大问题[\s\S]*最稳环节[\s\S]*续费风险/, 'conversion page should render business insight cards next to the funnel');
assert.match(operationsSource, /renderConversionFunnelModule[\s\S]*全局转化漏斗/, 'conversion page should render the global conversion funnel module');
assert.match(operationsSource, /operations-conversion-monitor-grid[\s\S]*renderConversionFunnelModule[\s\S]*renderConversionInsightModule/, 'conversion funnel and insight panel should render side by side in the monitor grid');
assert.match(operationsSource, /renderConversionChannelEfficiencyModule[\s\S]*渠道效率监控/, 'conversion page should render channel efficiency as monitor cards');
assert.match(operationsSource, /operationsBuildChannelGroups[\s\S]*高价值渠道[\s\S]*高流量低转化[\s\S]*低效渠道/, 'channel efficiency should group channels into business-readable buckets');
assert.match(operationsSource, /col\.html/, 'operations simple table should allow trusted HTML cells for progress bars');
assert.doesNotMatch(operationsSource, /体验到课率/, 'channel efficiency table should not show attendance rate');
assert.match(operationsSource, /operationsChannelCard[\s\S]*体验课转化率[\s\S]*trialConversionRate/, 'channel cards should show trial conversion rate');
assert.match(operationsSource, /operationsChannelCard[\s\S]*成交转化率[\s\S]*dealConversionRate/, 'channel cards should show deal conversion rate over leads');
assert.match(operationsSource, /operationsRateTone[\s\S]*<\s*40[\s\S]*danger/, 'conversion progress bars should show low rates in red');
assert.match(operationsSource, /renderConversionAttributeModule[\s\S]*学员属性与转化[\s\S]*不同人群的商业表现/, 'conversion page should render the student attributes conversion module');
assert.match(operationsSource, /留存\/续费风险榜[\s\S]*续费偏低/, 'conversion page should call out retention risk instead of only listing attribute cards');
assert.match(operationsSource, /operationsAttributeMetric[\s\S]*operations-attribute-metric-head[\s\S]*operations-rate-track/, 'student attribute metrics should render label and percent above the progress bar');
assert.match(operationsSource, /到期续费[\s\S]*首购/, 'student attribute renewal label should expose paid-deal denominator');
assert.match(operationsSource, /operationsExtractPersonas[\s\S]*私教课[\s\S]*小班课/, 'student attributes should derive lesson demand tags from available row fields');
assert.match(operationsSource, /operationsRowPersonas[\s\S]*未标注人群/, 'student attributes should have a fallback group instead of rendering empty when profile tags are missing');
assert.doesNotMatch(operationsSource, /转化指标/, 'conversion page should remove the old conversion metrics header');
assert.doesNotMatch(operationsSource, /renderOperationsConversion[\s\S]{0,240}renderStandardDataCards/, 'conversion page should not render the old top four metric cards');

console.log('operations view tests passed');
