const assert = require('assert');
const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, '../public/assets/scripts/core/state.js'), 'utf8');

assert.match(source, /students:\['campuses','students','coaches'\]/, 'students page should only block on the datasets needed to paint the list and coach filter immediately');
assert.match(source, /leads:\['campuses','leads'\]/, 'leads page should only block on the data needed for first paint');
assert.match(source, /'package-students':\['campuses','students','coaches','lifecycleMetricsPage'\]/, 'formal student page should use coaches and the lightweight lifecycle metrics endpoint before first render');
assert.match(source, /'trial-students':\['campuses','students','coaches','lifecycleMetricsPage'\]/, 'normal student page should use coaches and the lightweight lifecycle metrics endpoint before first render');
assert.doesNotMatch(source, /leads:\['campuses','leads','purchasesPage'\]/, 'leads page should not block on the full purchases aggregate for lifecycle stats');
assert.doesNotMatch(source, /'package-students':\['campuses','students','purchasesPage'\]/, 'formal student page should not block on the full purchases aggregate for lifecycle stats');
assert.doesNotMatch(source, /'trial-students':\['campuses','students','purchasesPage'\]/, 'normal student page should not block on the full purchases aggregate for lifecycle stats');
assert.match(source, /packages:\['packages','products','purchases','entitlements','packageBoardPreferences'\]/, 'packages page should wait for its package-sale dependencies so the empty state is stable');
assert.match(source, /purchases:\[\]/, 'purchases page should open shell immediately and load data in background');
assert.match(source, /finance:\[\]/, 'finance center should open shell immediately and load aggregated data in background');
assert.match(source, /courts:\[\]/, 'courts page should open shell immediately and load data in background');
assert.match(source, /memberships:\[\]/, 'memberships page should open shell immediately and load data in background');
assert.match(source, /workbench:\[\]/, 'coach workbench should open immediately and load data in background');
assert.match(source, /postfeedback:\[\]/, 'coach post-class feedback should open immediately and load data in background');
assert.match(source, /mystudents:\[\]/, 'coach students should open immediately and load data in background');
assert.match(source, /myclasses:\[\]/, 'coach classes should open immediately and load data in background');
assert.match(source, /schedule:\['campuses','students','courts','schedule','coaches','coachProposals'\]/, 'schedule page should load court accounts for stored-value balance hints without blocking on feedback, entitlement, or ledger datasets');
assert.match(source, /const PAGE_DATA_BACKGROUND_REQUIREMENTS=\{[\s\S]*students:\['classes','schedule','courts'\][\s\S]*leads:\['leadFollowups','lifecycleMetricsPage'\][\s\S]*purchases:\['purchasesPage'\][\s\S]*schedule:\['classes','feedbacks','entitlements','entitlementLedger'\][\s\S]*finance:\['financePage'\][\s\S]*courts:\['courtsPage'\][\s\S]*memberships:\[\][\s\S]*workbench:\['workbenchPage'\][\s\S]*postfeedback:\['workbenchPage'\][\s\S]*mystudents:\['campuses','students','classes','schedule','feedbacks','entitlements'\][\s\S]*myclasses:\['students','classes'\]/, 'heavy page datasets should move behind first render, memberships should use the court account read model instead of the old membership aggregate');
assert.match(source, /const STUDENT_PAGE_DEFERRED_REQUIREMENTS=\['entitlements','entitlementLedger','feedbacks','products','purchasesPage','membershipBenefitLedger'\];/, 'students page should delay the heaviest follow-up datasets into a second background batch and load student benefits');
assert.match(source, /,purchasesPage:\(\)=>apiCall\('GET','\/page-data\/purchases'\)/, 'purchases page should use a dedicated aggregated endpoint');
assert.match(source, /,lifecycleMetricsPage:\(\)=>apiCall\('GET','\/page-data\/lifecycle-metrics'\)/, 'standard lifecycle stats should use a lightweight lifecycle metrics endpoint');
assert.match(source, /,financePage:\(\)=>apiCall\('GET','\/page-data\/finance'\)/, 'finance center should use a dedicated aggregated endpoint');
assert.match(source, /,courtsPage:\(\)=>apiCall\('GET','\/page-data\/courts'\)/, 'courts page should use a dedicated aggregated endpoint');
assert.doesNotMatch(source, /membershipsPage:\(\)=>apiCall\('GET','\/page-data\/memberships'\)/, 'memberships page should not keep the old raw membership aggregate loader');
assert.match(source, /,courtAccountListViewPage:\(\)=>apiCall\('GET','\/page-data\/court-account-list-view'\)/, 'membership pages should use the unified court account read model endpoint');
assert.match(source, /,workbenchPage:\(\)=>apiCall\('GET','\/page-data\/workbench'\)/, 'coach workbench should use a dedicated aggregated endpoint');
assert.match(source, /leads:\(\)=>apiCall\('GET','\/leads'\)/, 'leads page should load its primary list dataset from /leads');
assert.match(source, /leadFollowups:\(\)=>apiCall\('GET','\/lead-followups'\)/, 'leads page should load follow-up detail data separately');
assert.match(source, /Promise\.allSettled\(immediateNames\.map/, 'background loading should fetch the current background batch in parallel');
assert.match(source, /if\(isStudentListPage\(pg\)&&STUDENT_PAGE_DEFERRED_REQUIREMENTS\.length\)\{[\s\S]*setTimeout\(\(\)=>\{[\s\S]*ensureDatasetsByName\(STUDENT_PAGE_DEFERRED_REQUIREMENTS,\{force\}\)/, 'student list pages should delay the heaviest follow-up datasets into a later background batch');
assert.match(source, /if\(name==='purchasesPage'\)\{[\s\S]*setDatasetValue\('purchases',data\.purchases\|\|\[\]\);[\s\S]*setDatasetValue\('packages',data\.packages\|\|\[\]\);[\s\S]*setDatasetValue\('students',data\.students\|\|\[\]\);[\s\S]*setDatasetValue\('entitlements',data\.entitlements\|\|\[\]\);[\s\S]*setDatasetValue\('entitlementLedger',data\.entitlementLedger\|\|\[\]\);/, 'purchases page aggregate loader should hydrate all dependent datasets from one response');
assert.match(source, /if\(name==='lifecycleMetricsPage'\)\{[\s\S]*setDatasetValue\('customerLifecycleRows',data\.customerLifecycleRows\|\|\[\],\{persist:false\}\);[\s\S]*teachingStudentViews=data\.teachingStudentViews/, 'lifecycle metrics loader should hydrate only lifecycle rows and teaching views');
assert.match(source, /if\(name==='financePage'\)\{[\s\S]*setDatasetValue\('campuses',data\.campuses\|\|\[\]\);[\s\S]*financeOverviewData=data\.financeOverviewData\|\|null;[\s\S]*loadedDatasets\.add\('financePage'\);/, 'finance aggregate loader should only hydrate finance payload fields and not clear unrelated datasets');
assert.match(source, /if\(name==='courtsPage'\)\{[\s\S]*setDatasetValue\('campuses',data\.campuses\|\|\[\]\);[\s\S]*setDatasetValue\('students',data\.students\|\|\[\]\);[\s\S]*setDatasetValue\('courts',data\.courts\|\|\[\]\);[\s\S]*loadedDatasets\.add\('courtsPage'\);/, 'courts page aggregate loader should only hydrate court first-screen datasets');
assert.doesNotMatch(source, /if\(name==='membershipsPage'\)\{[\s\S]*membershipOrders[\s\S]*membershipBenefitLedger[\s\S]*membershipFinanceSummary/, 'membership pages must not hydrate raw membership facts from the old aggregate response');
assert.match(source, /pg==='courts'\|\|pg==='memberships'\|\|pg==='membership-orders'\|\|pg==='membership-ledger'/, 'membership management, purchase records, and benefit ledger should all load the unified court account read model');
assert.match(source, /if\(name==='workbenchPage'\)\{[\s\S]*setDatasetValue\('campuses',data\.campuses\|\|\[\]\);[\s\S]*setDatasetValue\('students',data\.students\|\|\[\]\);[\s\S]*setDatasetValue\('classes',data\.classes\|\|\[\]\);[\s\S]*setDatasetValue\('schedule',data\.schedule\|\|\[\]\);[\s\S]*setDatasetValue\('feedbacks',data\.feedbacks\|\|\[\]\);[\s\S]*setDatasetValue\('purchases',data\.purchases\|\|\[\]\);/, 'workbench aggregate loader should hydrate coach homepage dependencies from one response');
assert.match(source, /if\(name==='workbenchPage'\)\{[\s\S]*window\.coachWorkbenchStats=data\.stats\|\|\{/, 'workbench aggregate loader should keep the backend standard stats payload');
assert.match(source, /if\(name==='workbenchPage'\)\{[\s\S]*setDatasetValue\('schedule',data\.schedule\|\|\[\]\);/, 'workbench aggregate loader should still hydrate schedule rows from the aggregated payload');
assert.match(source, /const DATA_CACHE_PREFIX='ft_dataset_cache_';/, 'state should persist the last successful datasets for refresh fallback');
assert.match(source, /function hydrateDatasetsFromCache\(\)/, 'state should hydrate cached datasets before network refresh');
assert.match(source, /function persistDatasetCache\(name,data\)/, 'state should cache every successful dataset load');
assert.doesNotMatch(source, /function persistDatasetCache\(name,data\)\{\s*return;\s*\}/, 'dataset cache persistence should not be disabled');
assert.doesNotMatch(source, /function readDatasetCache\(name\)\{\s*return null;\s*\}/, 'dataset cache reads should not be disabled');
assert.match(source, /const DATASETS_EXCLUDED_FROM_CACHE=new Set\(\['leads','leadFollowups','students','schedule','packages','purchases','entitlements','entitlementLedger','coachProposals'\]\);/, 'volatile lead, schedule, package, purchase, ledger, and coach proposal datasets should stay network-only while normal lists use refresh cache');
assert.match(source, /function missingRequiredDatasetsForPage\(pg\)/, 'state should be able to detect when the current page still lacks blocking datasets');
assert.match(source, /function missingInitialDatasetsForPage\(pg\)/, 'state should detect empty-shell pages waiting for their first background dataset');
assert.match(source, /function renderPageLoading\(pg\)/, 'state should render inline loading placeholders instead of empty pages');
assert.match(source, /if\(pg==='leads'\)renderLeadTableLoading\(\);/, 'leads page should render an inline list loading placeholder');
assert.doesNotMatch(source, /renderBlockLoading\('coachOpsRevenueStats','财务汇总加载中\.\.\.'\)/, 'finance page should not render a duplicate top loading line above the revenue table');
assert.match(source, /if\(pageNeedsInlineLoading\(pg\)\)\{[\s\S]*renderPageLoading\(pg\);\s*return;\s*\}/, 'page rendering should show inline loading placeholders until the page has the datasets it needs');
assert.match(source, /const datasetLoadPromises=new Map\(\);/, 'state should de-duplicate concurrent dataset requests');
assert.match(source, /datasetLoadPromises\.has\(requestKey\)/, 'dataset loading should reuse in-flight requests');
assert.match(source, /loadPageBackgroundDatasets\(pg,requestVersion,\{force\}\);/, 'page background loading should revalidate cached data without blocking first paint');

console.log('page data requirements tests passed');
