const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { html, appSource } = require('./helpers/read-index-bundle');
const styles = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'pages.css'), 'utf8');
function fnBody(name){
  const start = appSource.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = appSource.indexOf('\nfunction ', start + 1);
  const nextAsync = appSource.indexOf('\nasync function ', start + 1);
  const candidates = [nextFunction, nextAsync].filter(i => i !== -1);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return appSource.slice(start, next === -1 ? appSource.length : next);
}

assert.doesNotMatch(appSource, /<div class="sb-item" onclick="goPage\('prices',this\)"[\s\S]*?价格方案<\/div>/, 'sidebar should hide price management page');
assert.match(html, /id="page-prices"/, 'price management page section should exist');
assert.match(appSource, /bodyId:'priceTbody'/, 'price page should render one unified price table');
assert.doesNotMatch(html, /id="priceVenueTbody"/, 'price page should not render a separate venue table');
assert.doesNotMatch(html, /id="priceChannelTbody"/, 'price page should not render a separate channel table');
assert.match(appSource, /priceTypeFilterHost/, 'price page should expose a type filter dropdown host');
assert.match(appSource, /priceProductTypeFilterHost/, 'price page should expose a product type filter dropdown host');
assert.match(appSource, /function renderPrices/, 'price page script should expose renderPrices');
assert.match(appSource, /function syncPriceFilterOptions/, 'price page script should sync the type filter dropdown');
assert.match(appSource, /function openPriceModal/, 'price page script should expose openPriceModal');
assert.match(appSource, /function savePricePlan/, 'price page script should expose savePricePlan');
assert.match(fnBody('openPriceModal'), /priceExperienceType/, 'price plan modal should expose a trial course subtype when product type is experience course');
assert.match(fnBody('savePricePlan'), /experienceType:/, 'price plan save should persist trial course subtype');
assert.match(appSource, /新增价格/, 'price page should expose one generic create button');
assert.doesNotMatch(html, /同步默认马坡价格/, 'price page should no longer expose a built-in default sync button');
assert.match(appSource, /tms-btn-primary" onclick="openPriceModal/, 'price create button should match student page primary action style');
assert.match(appSource, /渠道[\s\S]*?名称[\s\S]*?场地类型[\s\S]*?日期类型[\s\S]*?商品类型[\s\S]*?关联业务[\s\S]*?时间段[\s\S]*?时长/, 'price table should split channel, name, venue type, date type, product type, business type, time band and duration');
assert.match(appSource, /price-table/, 'price table should use compact page-specific table sizing');
assert.match(appSource, /style:'width:372px'[\s\S]*label:'名称'|label:'名称'[\s\S]*style:'width:372px'/, 'price table should further expand the name column for readability');
assert.ok(styles.includes('padding-left:4px;padding-right:4px'), 'price table should further tighten cell padding to reduce column gaps');
assert.ok(styles.includes('#page-prices .price-table{min-width:1120px;table-layout:fixed}'), 'price table should shrink overall width so more columns fit on one screen');
assert.match(appSource, /function priceTimeBandText\(/, 'price page should expose a dedicated time-band renderer');
assert.match(appSource, /function priceDurationText\(/, 'price page should expose a dedicated duration renderer');
assert.match(appSource, /function priceChannelText\(/, 'price page should expose a dedicated channel renderer');
assert.match(appSource, /function priceNameText\(/, 'price page should expose a dedicated name renderer');
assert.match(appSource, /function priceVenueSpaceTypeText\(/, 'price page should expose a dedicated venue space type renderer');
assert.match(appSource, /function priceAmountText\(/, 'price page should expose a dedicated amount renderer');
assert.doesNotMatch(fnBody('priceAmountText'), /\/小时/, 'price page should not render hourly suffix in amount text');
assert.match(appSource, /青少年1v1私教体验课/, 'default ShunyiMapo products should use the updated 1v1 youth trial name');
assert.match(appSource, /1小时/, 'default ShunyiMapo products should keep fixed one-hour durations as text');
assert.match(appSource, /1-2小时/, 'default ShunyiMapo products should support range durations as text');
assert.match(appSource, /新客福利 约球双打局 2H/, 'default ShunyiMapo products should keep the updated 2H product');
assert.match(appSource, /venueSpaceType:\s*'室内'/, 'default ShunyiMapo venue prices should default to indoor');

console.log('price page view tests passed');
