const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: source } = require('./helpers/read-index-bundle');
const styles = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'pages.css'), 'utf8');

function fnBody(name){
  const start = source.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = source.indexOf('\nfunction ', start + 1);
  const nextAsync = source.indexOf('\nasync function ', start + 1);
  const candidates = [nextFunction, nextAsync].filter(i => i !== -1);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return source.slice(start, next === -1 ? source.length : next);
}

assert.match(source, /function buildRepeatScheduleSeeds\(/, 'schedule page should expose a repeat schedule helper');
assert.match(fnBody('openScheduleModal'), /sch_repeatEnabled/, 'schedule modal should allow enabling repeat scheduling');
assert.match(fnBody('openScheduleModal'), /循环排课/, 'schedule modal should describe weekly repeat scheduling');
assert.match(fnBody('openScheduleModal'), /是否迟到/, 'schedule modal should support marking coach-late free lessons');
assert.match(fnBody('openScheduleModal'), /需承担场地费用/, 'schedule modal should capture coach late field fee');
assert.match(fnBody('scheduleSaveConfirmText'), /迟到免费/, 'schedule save confirm copy should show coach-late free status');
assert.doesNotMatch(fnBody('scheduleSaveConfirmText'), /班次：/, 'schedule save confirm copy should not show obsolete class linkage copy');
assert.match(fnBody('saveSchedule'), /buildRepeatScheduleSeeds\(/, 'saving schedules should fan out repeat seeds when enabled');
assert.match(fnBody('saveSchedule'), /coachLateFree/, 'saving schedules should persist coach late fields');
assert.match(fnBody('saveSchedule'), /await appConfirm\(/, 'saving schedules should use app confirm instead of browser confirm');
assert.doesNotMatch(fnBody('saveSchedule'), /window\.confirm\(/, 'saving schedules should not use browser confirm');
assert.match(fnBody('scheduleSaveConfirmText'), /schedule-confirm-card/, 'schedule save confirm should render a structured confirmation card');
assert.match(fnBody('scheduleSaveConfirmText'), /schedule-confirm-row[\s\S]*时间[\s\S]*学员[\s\S]*教练[\s\S]*场地[\s\S]*课程[\s\S]*结算方式/, 'schedule save confirm should keep all key fields as structured rows');
assert.match(fnBody('scheduleSaveConfirmText'), /`\$\{day\} · \$\{startClock\} - \$\{endClock\}`/, 'schedule save confirm should show same-day time as date dot time range');
assert.doesNotMatch(fnBody('scheduleSaveConfirmText'), /<strong>/, 'schedule save confirm should not force bold values');
assert.match(fnBody('scheduleSaveConfirmText'), /schedule-confirm-charge/, 'schedule save confirm should highlight lesson deduction');
assert.match(source, /function scheduleSaveChargeUnit\(/, 'schedule save confirm should centralize the deduction unit');
assert.match(fnBody('scheduleSaveChargeUnit'), /小班课[\s\S]*次/, 'small group schedules should display count-based deductions');
assert.match(fnBody('scheduleSaveChargeText'), /data\.coachLateFree[\s\S]*本次不扣课[\s\S]*scheduleSaveChargeUnit\(data,selectedEntitlement\)/, 'coach-late free confirm should not display a deduction amount and package deductions should still use the proper unit');
assert.match(source, /function scheduleSaveChargeLabel\(/, 'schedule save confirm should centralize whether the row means deduction or service time');
assert.match(fnBody('scheduleSaveChargeLabel'), /settlementType==='direct'[\s\S]*本次服务/, 'direct-paid schedules should not label service time as lesson deduction');
assert.match(source, /function scheduleLessonDisplayField\(/, 'schedule detail should centralize the lesson display field');
assert.match(fnBody('scheduleLessonDisplayField'), /settlementType==='direct'[\s\S]*服务时长/, 'direct-paid schedule detail should not label service time as consumed lessons');
assert.match(fnBody('saveSchedule'), /const lc=scheduleCurrentLessonCount\(\);/, 'schedule save should preserve half-lesson counts');
assert.doesNotMatch(fnBody('saveSchedule'), /const lc=parseInt\(document\.getElementById\('sch_lc'\)\.value\)\|\|1;/, 'schedule save should not truncate half-lesson counts');
assert.match(fnBody('saveSchedule'), /html:true[\s\S]*hideIcon:true[\s\S]*boxClass:'schedule-confirm-box'/, 'schedule save confirm should use the compact visual confirm layout');
assert.match(source, /function appConfirm\([\s\S]*html=false[\s\S]*hideIcon=false[\s\S]*boxClass=''/, 'appConfirm should support structured HTML content for specialized confirmations');
assert.match(styles, /\.schedule-confirm-box[\s\S]*\.schedule-confirm-charge/, 'schedule save confirm should have dedicated scoped styles');
assert.match(styles, /\.schedule-confirm-box #confDesc[\s\S]*font-size:13px/, 'schedule save confirm should use compact 13px body text');
assert.match(styles, /\.schedule-confirm-value[\s\S]*font-weight:400/, 'schedule save confirm values should use regular weight');
assert.match(fnBody('refreshSchEntitlementOptions'), /setScheduleEntitlementDropdown\(\[\], '', ids\.length>1\?'正在匹配学员课包':'正在重新计算可用课包'\);[\s\S]*hint\.textContent='正在匹配可用课包…';/, 'refreshing schedule entitlements should clear stale package options before async recommend returns');
assert.match(source, /function resetScheduleSaveButton\(/, 'schedule save should use a helper to restore the save button safely');
assert.match(fnBody('saveSchedule'), /runStandardMutation\('scheduleSaveBtn'/, 'schedule save should restore the save button through the global mutation helper');
assert.doesNotMatch(fnBody('saveSchedule'), /catch\(e\)\{toast\('保存失败：'\+e\.message,'error'\);btn\.disabled=false;btn\.textContent='保存';\}/, 'schedule save failure should not assume the save button exists');
assert.match(source, /function renderAfterScheduleMutation\(\)/, 'schedule save should render follow-up views through a safe helper');
assert.match(fnBody('renderAfterScheduleMutation'), /try\{renderSchedule\(\);renderCoachOps\(\);renderMySchedule\(\);refreshCoachOpsWorkbenchAfterScheduleMutation\(\);\}catch\(err\)/, 'post-save render failures should not be reported as save failures');
assert.doesNotMatch(fnBody('saveSchedule'), /renderSchedule\(\);renderCoachOps\(\);renderMySchedule\(\);[\s\S]*catch\(e\)\{toast\('保存失败：'/, 'successful API saves should not be caught as failed saves when rendering fails');
assert.match(fnBody('openCancelScheduleModal'), /确认取消/, 'schedule cancel should use a dedicated confirm modal instead of reopening the edit form');
assert.match(fnBody('openCancelScheduleModal'), /取消本节及后续未上课的循环课/, 'repeat schedules should expose a future-lessons cancel option');
assert.match(fnBody('openCancelScheduleModal'), /schedule-cancel-summary/, 'schedule cancel modal should use a readable summary block instead of low-contrast warning text');
assert.match(fnBody('openCancelScheduleModal'), /schedule-cancel-scope/, 'schedule cancel modal should render the cancellation scope options in a dedicated stacked layout');
assert.match(fnBody('confirmScheduleCancel'), /effectiveScheduleStatus\(item\)==='已排课'/, 'repeat cancellation should only touch not-yet-started lessons');
assert.match(fnBody('confirmScheduleCancel'), /scope==='future'/, 'repeat cancellation should support current-and-future scope');
assert.doesNotMatch(fnBody('confirmScheduleCancel'), /window\.confirm\(/, 'schedule cancel flow should not fall back to the browser confirm');
assert.match(fnBody('renderSchedule'), /const isCancelled=status==='已取消'/, 'cancelled schedule rows should derive a dedicated action state');
assert.match(fnBody('renderSchedule'), /openScheduleDetail\('\$\{s\.id\}'\)">查看[\s\S]*isCancelled\?`<span class="tms-action-link" onclick="confirmDel\('\$\{s\.id\}','误建排课','schedule'\)">删除<\/span>`:`<span class="tms-action-link" onclick="openCancelScheduleModal\('\$\{s\.id\}'\)">取消<\/span>`/, 'schedule rows should keep exactly two actions: view/cancel or view/delete');
assert.doesNotMatch(fnBody('renderSchedule'), /openScheduleModal\('\$\{s\.id\}'\)">编辑/, 'schedule rows should not show edit action');
assert.doesNotMatch(fnBody('openScheduleModal'), /误建删除|scheduleModalCanDelete/, 'schedule edit drawer header should not show mistaken-create delete');
assert.match(source, /function scheduleEntitlementUnavailableReason\(/, 'schedule package picker should translate unavailable package reasons into user-facing copy');
assert.match(fnBody('applySchEntitlementOptions'), /scheduleEntitlementUnavailableReason\(res\.options\|\|\[\]\)/, 'schedule package picker should show why packages are unavailable');
assert.doesNotMatch(fnBody('applySchEntitlementOptions'), /hint\.textContent=selected\?[^;]+:'';/, 'schedule package picker should not hide unavailable package reasons behind empty hint text');
assert.match(fnBody('openScheduleDetail'), /设置迟到/, 'schedule detail should show coach late settlement info');
assert.match(source, /globalTopFilterPages\(\)\.includes\(pg\)[\s\S]*\?'flex':'none'/, 'schedule page should show the global campus filter tabs');
assert.match(source, /if\(currentPage==='schedule'\)renderSchedule\(\);/, 'global campus filter should rerender the schedule page');
assert.match(source, /schCoachFilterHost/, 'schedule toolbar should expose a coach filter host');
assert.match(source, /function syncScheduleFilterOptions\([\s\S]*schCoachFilter[\s\S]*教练/, 'schedule filters should use coach instead of in-toolbar campus');
assert.doesNotMatch(source, /schCampusFilterHost|schCampusFilter/, 'schedule toolbar should not keep the old campus dropdown filter');
assert.match(source, /function scheduleLocationText\(/, 'schedule page should centralize location display');
assert.match(fnBody('openScheduleModal'), /地点类型[\s\S]*校区内[\s\S]*校区外/, 'schedule modal should support in-campus and off-campus lesson location types');
assert.match(fnBody('openScheduleModal'), /renderScheduleDetailFormCard\('基础信息',basicForm/, 'schedule modal should render the basic info form card');
assert.match(fnBody('openScheduleModal'), /sch_standardCourseType[\s\S]*sch_settlementType|sch_settlementType[\s\S]*sch_standardCourseType/, 'schedule modal should keep standard course type and settlement controls in basic info');
assert.match(fnBody('openScheduleModal'), /sch_entitlementHost[\s\S]*schedule-time-field|schedule-time-field[\s\S]*sch_entitlementHost/, 'schedule modal should keep package and time controls in basic info');
assert.doesNotMatch(fnBody('openScheduleModal'), /<select[^>]+id="sch_entitlement"/, 'schedule entitlement should use the standard custom dropdown instead of native select');
assert.match(source, /function renderScheduleStudentEntitlementRows\(/, 'multi-student small group schedules should render package matching by student');
assert.match(fnBody('renderScheduleStudentEntitlementRows'), /title="\$\{esc\(`\$\{name\}：\$\{text\}`\)\}"/, 'multi-student package rows should expose the full package text on hover');
assert.match(source, /function refreshScheduleStudentEntitlementRows\(/, 'schedule modal should refresh per-student package rows when students or lesson data changes');
assert.match(fnBody('openScheduleModal'), /sch_studentEntitlementRows/, 'schedule modal should include a per-student package matching host');
assert.match(fnBody('refreshSchEntitlementOptions'), /refreshScheduleStudentEntitlementRows\(/, 'multi-student package refresh should update per-student package rows');
assert.doesNotMatch(fnBody('refreshSchEntitlementOptions'), /ids\.length>1\)\{setScheduleEntitlementDropdown\(\[\], '', '系统按参与学员自动扣课'\)/, 'multi-student package refresh should not hide package details behind one generic message');
assert.match(fnBody('openScheduleModal'), /上课教练[\s\S]*sch_coach[\s\S]*地点类型[\s\S]*sch_locationType[\s\S]*schedule-location-row[\s\S]*sch_ownLocationRow[\s\S]*sch_campus[\s\S]*sch_venue/, 'own campus location fields should sit after coach and location type');
assert.match(source, /function scheduleVenueOptionsForCampus\(/, 'schedule page should expose venue options by campus');
assert.match(fnBody('scheduleVenueOptionsForCampus'), /activeCampusVenueRows\(campusCode\)/, 'schedule page should read venue options from campus config');
assert.match(source, /function scheduleCampusAllowsCustomVenue\(/, 'schedule page should expose custom venue rule by campus');
assert.match(fnBody('scheduleCampusAllowsCustomVenue'), /return !activeCampusVenueRows\(campusCode\)\.length/, 'schedule page should only allow custom venues when a campus has no configured venues');
assert.match(fnBody('openScheduleModal'), /sch_venueFieldHost/, 'schedule modal should render venue through a dedicated host');
assert.match(fnBody('openScheduleModal'), /handleScheduleCampusChange/, 'schedule campus change should refresh venue options');
assert.match(source, /function updateScheduleCreateHeaderSubtitle\(/, 'schedule create drawer should refresh the header subtitle from current form values');
assert.match(fnBody('scheduleDetailCreateHeaderHtml'), /scheduleCreateSubtitle/, 'schedule create header should expose a dynamic subtitle target');
assert.match(fnBody('handleScheduleCampusChange'), /updateScheduleCreateHeaderSubtitle\(\)/, 'changing campus should refresh the create header subtitle');
assert.match(fnBody('renderScheduleVenueField'), /handleScheduleVenueChange|updateScheduleCreateHeaderSubtitle/, 'changing venue should refresh the create header subtitle');
assert.match(fnBody('saveSchedule'), /const selectedVenue=locationType==='own'\?scheduleVenueByValue\(campusValue,venueValue\):null/, 'schedule save should resolve selected venue metadata');
assert.match(fnBody('saveSchedule'), /venueId:selectedVenue\?\.id\|\|''[\s\S]*venueSpaceType:selectedVenue\?\.spaceType\|\|''/, 'schedule save should persist venue id and indoor/outdoor type for configured venues');
assert.match(fnBody('openScheduleModal'), /地点类型[\s\S]*sch_locationType[\s\S]*schedule-location-row[\s\S]*sch_externalLocationRow[\s\S]*sch_externalVenueName[\s\S]*sch_externalCourtName[\s\S]*sch_externalNotes/, 'external location fields should sit after coach and location type');
assert.match(fnBody('openScheduleModal'), /姓名[\s\S]*课程类型[\s\S]*sch_standardCourseType[\s\S]*schedule-settlement-row[\s\S]*schedule-time-row[\s\S]*上课教练[\s\S]*地点类型[\s\S]*sch_locationPlaceLabel[\s\S]*场地[\s\S]*schedule-repeat-row/, 'schedule modal should follow the adjusted editable field order');
assert.match(fnBody('openScheduleModal'), /id="sch_lc_label">消课时数/, 'schedule modal should label scheduled lesson hours as 消课时数');
assert.match(fnBody('openScheduleModal'), /id="sch_countItem"[\s\S]*id="sch_count"[\s\S]*readonly/, 'count-based packages should keep a readonly lesson count value');
assert.match(source, /function refreshScheduleCountFields\(/, 'schedule modal should refresh the separate lesson count field when package selection changes');
assert.match(source, /function scheduleSelectedEntitlementUsesCount\([\s\S]*packageLessonUnitLabel[\s\S]*==='次'/, 'schedule modal should decide the lesson count field from the selected package unit');
assert.match(fnBody('refreshScheduleCountFields'), /label\.textContent=show\?'消课次数':'消课时数'/, 'count-based schedules should rename the deduction field to 消课次数');
assert.match(fnBody('refreshScheduleCountFields'), /lessonInput\.style\.display=show\?'none':''/, 'count-based schedules should hide the lesson-hour input instead of showing two deduction inputs');
assert.match(fnBody('scheduleCurrentLessonCount'), /scheduleSelectedEntitlementUsesCount\(\)[\s\S]*sch_count[\s\S]*sch_lc/, 'schedule save should read the visible deduction input');
assert.match(fnBody('applySchEntitlementOptions'), /const hintText=selected\?'':scheduleEntitlementUnavailableReason\(res\.options\|\|\[\]\)/, 'schedule package hint should only show when package matching has a problem');
assert.match(source, /function maybeSwitchScheduleCourseFromUnavailableEntitlement\(/, 'schedule package matching should recover from selecting the wrong course type');
assert.match(fnBody('maybeSwitchScheduleCourseFromUnavailableEntitlement'), /体验课[\s\S]*normalizeExperienceType\(option\.experienceType\|\|option\.packageName,''\)[\s\S]*refreshSchEntitlementOptions/, 'small group trial packages should switch the schedule to the matching trial subtype before retrying');
assert.match(fnBody('handleScheduleEntitlementChange'), /refreshScheduleCountFields\(\)/, 'manual package changes should refresh the separate lesson count field');
assert.doesNotMatch(source, /消课节数/, 'schedule page should stop using 消课节数 wording');
assert.match(fnBody('openScheduleModal'), /repeatField[\s\S]*sch_repeatEnabled[\s\S]*sch_repeatWeeksWrap[\s\S]*循环周数[\s\S]*tms-form-row schedule-time-row[\s\S]*scheduleTimeRangeControls[\s\S]*tms-form-row schedule-repeat-row/, 'schedule modal should keep date/time and repeat controls on separate rows');
assert.match(source, /const PRODUCT_TYPES=BUSINESS_TAXONOMY\.PRODUCT_TYPES/, 'all course type dropdowns should use the global course type dictionary');
assert.match(source, /const EXPERIENCE_TYPES=BUSINESS_TAXONOMY\.EXPERIENCE_TYPES/, 'all trial course subtype dropdowns should use the global experience type dictionary');
assert.match(fnBody('syncScheduleFilterOptions'), /STANDARD_COURSE_TYPE_OPTIONS/, 'schedule course type filter should use the shared standard subtype source');
assert.match(fnBody('openScheduleModal'), /const courseTypeOptions=STANDARD_COURSE_TYPE_OPTIONS/, 'schedule modal course type dropdown should use the shared standard course type source');
assert.match(source, /function handleScheduleStandardCourseTypeChange\(/, 'schedule modal should translate standard course type into backend fields');
assert.match(fnBody('handleScheduleStandardCourseTypeChange'), /setScheduleCourseTypeFields[\s\S]*refreshSchEntitlementOptions/, 'standard course type change should refresh package matching');
assert.doesNotMatch(fnBody('setScheduleCourseTypeFields'), /setStandardDropdownValue\('sch_standardCourseType'/, 'programmatic standard course updates should not recursively trigger onchange');
assert.match(fnBody('openScheduleModal'), /sch_experienceType/, 'schedule modal should expose a second-level trial course selector');
assert.match(fnBody('saveSchedule'), /experienceType:/, 'schedule save should persist trial course subtype');
assert.match(fnBody('openScheduleModal'), /sch_smallClassType/, 'schedule modal should expose a second-level small group course selector');
assert.match(fnBody('openScheduleModal'), /sch_actualStudentCount/, 'schedule modal should expose actual attendance count for family small group lessons');
assert.match(source, /function syncScheduleSmallClassType\(/, 'schedule modal should sync bootcamp repeat defaults');
assert.match(fnBody('syncScheduleSmallClassType'), /sch_repeatEnabled[\s\S]*weeks\.value=6/, 'small group bootcamp should default to six weekly schedules');
assert.match(fnBody('scheduleLessonUnitsFromFields'), /durMin\(start,end\)[\s\S]*Math\.round\(\(mins\/60\)\*10\)\/10/, 'scheduled lesson hours should follow the real start-end duration');
assert.match(fnBody('saveSchedule'), /smallClassType:/, 'schedule save should persist small group subtype');
assert.match(fnBody('saveSchedule'), /actualStudentCount:/, 'schedule save should persist actual attendance count');
assert.match(fnBody('saveSchedule'), /selectedSmallClassType!=='family'[\s\S]*studentIds\.length<2/, 'non-family small group lessons should still require two selected students');
assert.match(fnBody('openScheduleModal'), /设置迟到/, 'schedule modal should expose late settings beside coach');
assert.match(fnBody('openScheduleModal'), /renderScheduleDetailFormCard\('设置迟到',lateSettings\)/, 'late settings should render as a separate drawer card');
assert.doesNotMatch(fnBody('openScheduleModal'), /schedule-late-field">\$\{lateSettings\}/, 'late settings should not expand inside the coach row field');
assert.match(fnBody('openScheduleModal'), /schedule-checkbox-line schedule-repeat-control \$\{id\?'is-disabled':''\}/, 'repeat scheduling should render as a plain checkbox line');
assert.match(fnBody('openScheduleModal'), /批量排课不支持编辑/, 'edit-mode repeat scheduling should explain batch repeat editing is unsupported');
assert.match(styles, /\.modal\.modal-court \.schedule-repeat-control\.is-disabled[\s\S]*pointer-events:none/, 'disabled repeat scheduling should be non-clickable');
assert.match(styles, /\.modal\.modal-court \.schedule-time-field\{flex:1 1 auto/, 'schedule time field should use flexible width instead of forcing cramped fixed controls');
assert.match(styles, /\.modal\.modal-court \.schedule-repeat-row\{align-items:flex-end;gap:18px\}/, 'schedule repeat controls should have their own row spacing');
assert.doesNotMatch(fnBody('openScheduleModal'), /上课地点|排课会校验时间冲突|取消勾选的人本次记为缺勤|按周生成多节课/, 'schedule modal should remove the extra notice, separate location section, and old repeat copy');
assert.match(fnBody('openScheduleModal'), /姓名<\/label>[\s\S]*sch_stuSearch[\s\S]*sch_studentSuggest[\s\S]*sch_selectedStudentTags/, 'schedule modal should use search suggestions and selected student tags');
assert.match(source, /schedule:\['campuses','students','courts','schedule','coaches','coachProposals','lifecycleMetricsPage'\]/, 'schedule page should load lifecycle student roster before rendering student search');
assert.match(source, /function scheduleStudentRosterRows\([\s\S]*teachingStudentViews\?\.historicalStudents[\s\S]*teachingStudentViews\?\.activeStudents/, 'schedule student search should use the same lifecycle roster as the student list');
assert.match(fnBody('renderScheduleStudentSuggestions'), /const searchRows=scheduleStudentSearchRows\(selectedIds\)[\s\S]*searchRows\.filter/, 'schedule student suggestions should search the lifecycle roster instead of the raw students table');
assert.match(fnBody('scheduleStudentSearchRows'), /scheduleStudentRosterRows\(\)[\s\S]*students\.find/, 'schedule student search should keep a raw-student fallback only for already selected legacy schedule students');
assert.match(source, /function scheduleStudentInlineMeta\([\s\S]*\$\{campus\}｜\$\{last\}上课/, 'schedule student metadata should use compact campus and last lesson copy');
assert.match(source, /function scheduleStudentDisplayName\(/, 'schedule student search should resolve real student display names');
assert.match(fnBody('renderScheduleStudentSuggestions'), /scheduleStudentSearchTokens\(s\)/, 'schedule student suggestions should search real name and phone fields');
assert.match(source, /function renderScheduleStudentTags\([\s\S]*scheduleStudentInlineMeta[\s\S]*removeScheduleStudent/, 'selected schedule students should render as removable tags with inline metadata');
assert.match(fnBody('renderScheduleStudentTags'), /if\(!rows\.length\)return ''/, 'empty student selection should not render a placeholder row');
assert.match(source, /function renderScheduleStudentSuggestions\([\s\S]*selectScheduleStudent/, 'schedule student search should render selectable suggestions');
assert.match(source, /function scheduleSelectedStudentSearchText\(/, 'schedule student search input should derive its text from selected students');
assert.match(fnBody('selectScheduleStudent'), /syncScheduleStudentSearchInput\(\[\.\.\.ids,studentId\]\)/, 'selecting a student should show selected names in the search input');
assert.doesNotMatch(fnBody('selectScheduleStudent'), /input\.value=''/, 'selecting a student should not blank the search input');
assert.match(fnBody('renderScheduleStudentSuggestions'), /pickedMatches[\s\S]*!rows\.length[\s\S]*pickedMatches\.length\?''/, 'matched selected students should not show a no-match state');
assert.doesNotMatch(fnBody('openScheduleModal'), /sch_stuPicker|tms-checkbox-matrix|toggleScheduleStudentCheckbox/, 'schedule modal should no longer show the old checkbox matrix');
assert.doesNotMatch(source, /function toggleScheduleStudentCheckbox/, 'schedule modal should remove the old checkbox selection handler');
assert.doesNotMatch(fnBody('openScheduleModal'), /关联班次|sch_classId|sch_class_hint/, 'schedule modal should remove the obsolete linked-class field');
assert.match(source, /function refreshScheduleTimeDerivedFields\(/, 'schedule modal should expose a time-derived refresh helper');
assert.match(fnBody('openScheduleModal'), /refreshScheduleTimeDerivedFields/, 'schedule modal should refresh lesson units when time changes');
assert.match(source, /function getScheduleTimeOptions\([\s\S]*h=7[\s\S]*h<=22[\s\S]*active:opt\.value===selected/, 'schedule time dropdown should only expose 07:00-22:00 and keep the selected time active');
assert.match(source, /function handleScheduleStartTimeChange\([\s\S]*const mins=[\s\S]*scheduleAddMinutes\(start,mins\)[\s\S]*setStandardDropdownValue\('sch_endTime'/, 'selecting a start time should default end time from course duration rules');
assert.match(fnBody('openScheduleModal'), /sch_repeatWeeksWrap[\s\S]*display:none/, 'repeat weeks should be hidden until weekly repeat is enabled');
assert.match(source, /function toggleScheduleRepeatWeeks\([\s\S]*sch_repeatWeeksWrap[\s\S]*checked\?'':'none'/, 'weekly repeat checkbox should reveal the repeat weeks input only when checked');
assert.match(source, /function setScheduleCourseTypeReadonly\([\s\S]*pointerEvents=readonly\?'none':'auto'/, 'course type readonly helper should still exist for non-package states');
assert.doesNotMatch(fnBody('applySchEntitlementOptions'), /setScheduleCourseTypeReadonly\(true\)/, 'auto package matching should not lock course type');
assert.match(fnBody('applySchEntitlementOptions'), /setScheduleCoachFromEntitlement\(selected\)/, 'schedule entitlement recommendation should default the coach from the selected package owner');
assert.match(source, /function handleScheduleCoachChange\([\s\S]*dataset\.userChanged='1'[\s\S]*refreshSchEntitlementOptions/, 'manual coach changes should be remembered before refreshing package options');
assert.match(source, /function setScheduleCoachFromEntitlement\([\s\S]*dataset\.userChanged==='1'[\s\S]*ownerCoach/, 'package owner coach default should not override a manually changed coach');
assert.match(fnBody('openScheduleModal'), /seed\.scheduleCoachLocked[\s\S]*dataset\.userChanged='1'/, 'coach selected from the calendar should be treated as explicit user intent');
assert.match(fnBody('syncScheduleProfileFromStudents'), /coachInput\?\.dataset\.userChanged!=='1'/, 'student profile defaults should not override a calendar-selected coach');
assert.match(source, /function refreshCoachOpsWorkbenchAfterScheduleMutation\(/, 'schedule saves should refresh the coach schedule workbench read model');
assert.match(fnBody('renderAfterScheduleMutation'), /renderSchedule\(\);renderCoachOps\(\);renderMySchedule\(\);refreshCoachOpsWorkbenchAfterScheduleMutation\(\);/, 'schedule saves should rerender and then refresh coach ops from the unified workbench source');
assert.doesNotMatch(fnBody('scheduleEntitlementLabel'), /需补差价\/场地费|到期\$\{option\.validUntil\|\|'-'\}/, 'package options should hide surcharge copy and empty expiry text');
assert.doesNotMatch(fnBody('applySchEntitlementOptions'), /需补差价\/场地费|到期 \$\{selected\.validUntil\|\|'-'\}/, 'package recommendation hint should hide surcharge copy and empty expiry text');
assert.match(source, /function scheduleEntitlementTimeBandText\(/, 'package picker should avoid repeating the package time-band label when the name already contains it');
assert.match(source, /function scheduleEntitlementExpiryText\(/, 'package picker should only show expiry text when a real expiry exists');
assert.doesNotMatch(styles, /\.schedule-entitlement-item \.tms-dropdown-menu\{[^}]*width:max-content/, 'schedule package dropdown menu should not expand beyond the drawer width');
assert.match(styles, /\.schedule-entitlement-item \.tms-dropdown-menu\{[^}]*width:100%/, 'schedule package dropdown menu should stay within the package field width');
assert.match(fnBody('scheduleSaveConfirmText'), /requiresFieldFee[\s\S]*场地费[\s\S]*fieldFeeAmount/, 'schedule confirm should show the field fee entry before saving');
assert.match(source, /function scheduleEntitlementSmallClassType\(/, 'schedule package picker should read small group subtype from the selected package');
assert.doesNotMatch(fnBody('applySchEntitlementOptions'), /setScheduleCourseTypeFields\(courseType,experienceType,smallClassType\)/, 'auto package matching should keep the selected course type');
assert.doesNotMatch(fnBody('handleScheduleEntitlementChange'), /setScheduleCourseTypeFields\(courseType,experienceType,smallClassType\)/, 'manual package selection should not overwrite course type');
assert.match(fnBody('setScheduleSmallClassTypeReadonly'), /pointerEvents=readonly\?'none':'auto'/, 'small group subtype should become readonly when a package determines it');
assert.doesNotMatch(fnBody('applySchEntitlementOptions'), /当前没有可用课包/, 'empty package state should not repeat the no-package message below the dropdown');
assert.match(styles, /\.modal\.modal-court \.schedule-student-tags[\s\S]*\.modal\.modal-court \.schedule-student-tag/, 'schedule student tags should have scoped modal styles');
assert.match(styles, /\.modal\.modal-court \.schedule-student-tag\{[\s\S]*font-size:11px/, 'selected schedule student tags should use 11px text');
assert.match(styles, /\.modal\.modal-court \.schedule-student-suggest-list button\{[\s\S]*font-size:11px/, 'schedule student search dropdown should use 11px text');
assert.match(fnBody('openScheduleModal'), /sch_externalVenueName[\s\S]*sch_externalCourtName[\s\S]*sch_externalNotes/, 'external venue schedules should capture venue, court, and notes');
assert.doesNotMatch(fnBody('openScheduleModal'), /sch_externalAddress|地址/, 'external venue schedules should not ask for an address');
assert.match(fnBody('openScheduleModal'), /是否迟到[\s\S]*是，本节课不扣学员课时[\s\S]*迟到原因[\s\S]*迟到时长[\s\S]*需承担场地费用[\s\S]*renderScheduleDetailFormCard\('设置迟到',lateSettings\)/, 'coach late fields should render in the requested order');
assert.match(fnBody('openScheduleModal'), /schedule-checkbox-line schedule-late-free-control[\s\S]*sch_coachLateFree/, 'coach late free should render as a plain checkbox line');
assert.doesNotMatch(fnBody('openScheduleModal'), /<div class="finput tms-form-control" style="display:flex;align-items:center;gap:10px"><input type="checkbox" class="tms-checkbox" id="sch_coachLateFree"/, 'coach late free should not render inside an input frame');
assert.doesNotMatch(fnBody('openScheduleModal'), /通知状态|确认状态|确认规则/, 'schedule modal should remove fake notification and confirmation fields');
assert.doesNotMatch(fnBody('scheduleSaveConfirmText'), /确认规则|确认截止|通知：/, 'schedule save confirm copy should not show fake notification rules');
assert.doesNotMatch(fnBody('openScheduleDetail'), /通知 \/ 确认|确认规则/, 'schedule detail should not show fake notification rules');
assert.match(fnBody('scheduleStatusLabel'), /已结束[\s\S]*已下课/, 'schedule ended status should display as 已下课');
assert.match(fnBody('renderSchedule'), /scheduleStatusLabel/, 'schedule list should render user-facing status text');
assert.match(source, /function scheduleRepeatDisplayText\(/, 'schedule list should define a repeat display helper');
assert.match(fnBody('renderSchedule'), /scheduleRepeatDisplayText\(s\)/, 'schedule rows should render a user-facing repeat value');
assert.match(source, /function onScheduleFilterChange\(\)\{schPage=standardListFirstPage\(\);renderSchedule\(\);\}/, 'schedule filters should reset pagination through the standard list flow before rendering');
assert.match(source, /syncScheduleFilterOptions[\s\S]*withLinkedFilterCounts\(\[[\s\S]*key:'courseType'[\s\S]*key:'coach'[\s\S]*key:'proposal'[\s\S]*key:'feedback'[\s\S]*key:'status'/, 'schedule toolbar filters should use linked count labels in the requested order');
assert.match(source, /schCourseTypeFilterHost[\s\S]*schCoachFilterHost[\s\S]*schProposalFilterHost[\s\S]*schFeedbackFilterHost[\s\S]*schStatusFilterHost/, 'schedule toolbar should order filters as course type, coach, lesson plan, feedback, status');
assert.match(source, /function renderSchedulePagerControls\(/, 'schedule page should use the standard compact pager controls');
assert.match(source, /function setSchedulePageSize\(/, 'schedule page should support 15, 50, and 100 row page sizes');
assert.match(source, /function scheduleEmptyStateHtml\([\s\S]*没有匹配的排课[\s\S]*暂无排课[\s\S]*调整搜索或筛选后再试[\s\S]*点击右上角添加排课开始安排课程/, 'schedule empty state should distinguish filtered empty results from no data');
assert.match(source, /pageSizeId:'schPageSize'/, 'schedule pager should expose a page size selector host');
assert.match(source, /label:'日期'[\s\S]*className:'tms-sticky-l'[\s\S]*style:'width:84px;padding-left:14px'/, 'schedule table should keep the date column fixed on the left');
assert.match(fnBody('renderSchedule'), /<td class="tms-sticky-l" style="padding-left:14px">/, 'schedule rows should keep the date cell fixed on the left');
assert.doesNotMatch(fnBody('renderSchedule'), /schedule-date-repeat|prevDate/, 'schedule rows should show the date on every row');
assert.match(fnBody('renderSchedule'), /scheduleProposalStatusHtml\(s\)[\s\S]*scheduleFeedbackStatusHtml\(s\)[\s\S]*scheduleRepeatDisplayText\(s\)/, 'schedule rows should order lesson plan, feedback, then repeat status');
assert.match(source, /schedule-check-text/, 'lesson plan and feedback status should render as plain text instead of tags');
assert.match(styles, /schedule-check-text[\s\S]*is-filled[\s\S]*#047857[\s\S]*is-missing/, 'lesson plan and feedback status should share one colored text style');
assert.doesNotMatch(styles, /schedule-check-status/, 'lesson plan and feedback status should not use pill tag styles');
assert.match(styles, /#page-schedule \.tms-table th\.tms-sticky-l[\s\S]*#page-schedule \.tms-table td\.tms-sticky-r/, 'schedule table should define scoped fixed column styles');
assert.match(styles, /\.tms-pagination\{[^}]*font-size:12px[^}]*line-height:16px[^}]*color:#78716C/, 'schedule pager should use the shared 12px footer standard');
assert.match(source, /function renderScheduleTableLoading\([\s\S]*renderTableSkeletonLoading\('schTbody',12,'排课数据加载中\.\.\.'\)/, 'schedule loading state should use the shared full-table skeleton');
assert.match(source, /function renderScheduleTableError\([\s\S]*tms-table-error-state[\s\S]*加载失败[\s\S]*重新加载/, 'schedule load failure should render an inline retry state');
assert.doesNotMatch(fnBody('openScheduleDetail'), /setCourtModalFrame\('排课详情'[\s\S]*modal-wide/, 'schedule detail should no longer use the old centered modal');
assert.doesNotMatch(fnBody('openScheduleDetail'), /<input|finput|tms-form-control|<textarea|<select/, 'schedule detail should not look editable');
assert.match(fnBody('openScheduleDetail'), /modal-schedule-drawer/, 'schedule detail should open as a right-side drawer');
assert.match(source, /排课信息[\s\S]*教练提案[\s\S]*课后反馈/, 'schedule detail drawer should keep three tabs');
assert.match(fnBody('openScheduleDetail'), /renderScheduleDetailCard\('基础信息'[\s\S]*renderScheduleDetailCard\('反馈内容'/, 'schedule detail drawer should organize fields into Feishu-style cards');
assert.match(fnBody('openScheduleDetail'), /renderScheduleDetailCard\('基础信息'[\s\S]*renderScheduleDetailCard\('设置迟到'[\s\S]*renderScheduleDetailCard\('备注信息'/, 'schedule detail drawer should place late settings between basic info and notes');
assert.match(source, /function scheduleDetailHeaderHtml\([\s\S]*studentNames[\s\S]*renderDetailDrawerHero/, 'schedule detail drawer title should use student names through the shared drawer header');
assert.match(source, /function scheduleResolveStudentName\(/, 'schedule detail should resolve student names from related datasets before rendering');
assert.doesNotMatch(fnBody('scheduleStudentSummary'), /students\.find\(st=>st\.id===id\)\?\.name\|\|id/, 'schedule student summary should not fall back to displaying raw student ids');
assert.match(source, /function scheduleDetailInfoHtml\([\s\S]*姓名[\s\S]*课程类型[\s\S]*standardCourseTypeLabel[\s\S]*结算方式[\s\S]*扣减课包[\s\S]*上课时间[\s\S]*lessonField\.label[\s\S]*上课教练[\s\S]*地点类型[\s\S]*上课校区\/场馆名称[\s\S]*场地[\s\S]*循环排课/, 'schedule detail basic fields should show standard course type and keep repeat scheduling as the last field');
assert.doesNotMatch(source, /历史问题/, 'schedule detail drawer should remove the historical issue field');
assert.match(source, /排课备注/, 'schedule detail drawer should rename coach note to schedule note');
assert.doesNotMatch(source, /if\(!isSmallGroupSchedule\(s\)\)return scheduleDetailField\('教练提案'/, 'schedule detail proposal tab should not collapse non-small-group lessons into one placeholder field');
assert.match(fnBody('isSmallGroupSchedule'), /scheduleCourseType\(s\)==='小班课'[\s\S]*normalizeExperienceType\(s\?\.experienceType/, 'small-group trial lessons should also require coach proposals');
assert.match(fnBody('scheduleDetailTabsHtml'), /create[\s\S]*\[\['info','排课信息'\]\]/, 'new schedule drawer should only show schedule info tab');
assert.match(fnBody('openScheduleModal'), /scheduleDetailTabsHtml\('info',\{create:!id\}\)/, 'schedule create drawer should hide proposal and feedback tabs');
assert.match(source, /function scheduleDetailProposalCardsHtml\(/, 'schedule detail proposal should render filled proposals through dedicated cards');
assert.match(fnBody('scheduleDetailProposalCardsHtml'), /学员信息[\s\S]*学员级别[\s\S]*学员数量[\s\S]*教学目标[\s\S]*教学组织[\s\S]*1级进阶[\s\S]*2级进阶[\s\S]*3级进阶[\s\S]*进阶逻辑[\s\S]*进阶逻辑[\s\S]*结语[\s\S]*提交时间/, 'filled proposal should use the requested three-card field layout');
assert.doesNotMatch(fnBody('scheduleDetailProposalCardsHtml'), /课程名称|进阶1|进阶2|进阶3/, 'schedule detail proposal should remove obsolete proposal labels');
assert.match(source, /function scheduleDetailProposalEmptyHtml\(/, 'schedule detail proposal should expose a scoped empty state');
assert.match(fnBody('scheduleDetailProposalEmptyHtml'), /暂无教练提案[\s\S]*当前学员无需填写教练提案。[\s\S]*教练尚未提交教练提案，可联系教练提交。[\s\S]*请填写本节课教练提案。/, 'proposal empty state should cover manager and coach-side copy');
assert.match(fnBody('scheduleDetailProposalHtml'), /!isSmallGroupSchedule\(s\)[\s\S]*scheduleDetailProposalEmptyHtml\('not-required'\)[\s\S]*!proposal[\s\S]*scheduleDetailProposalEmptyHtml\('missing'\)/, 'proposal tab should show empty states when not required or not submitted');
assert.match(fnBody('openScheduleDetail'), /const proposalCanEdit=isSmallGroupSchedule\(s\)&&\(!!proposal\|\|isCoachDetail\)/, 'coach-side small-group schedules should allow proposal entry even before submission');
assert.match(fnBody('openScheduleDetail'), /section:proposalCanEdit\?'proposal':''/, 'proposal empty states should not show edit action');
assert.match(source, /提交时间/, 'schedule detail proposal should show submitted time');
assert.match(source, /function scheduleDetailFeedbackEmptyHtml\(/, 'schedule detail feedback should expose an empty state');
assert.match(fnBody('scheduleDetailFeedbackEmptyHtml'), /暂无课后反馈[\s\S]*教练尚未填写课后反馈。/, 'missing feedback should show empty-state copy');
assert.match(fnBody('scheduleDetailFeedbackHtml'), /if\(!fb\)return scheduleDetailFeedbackEmptyHtml\(\)/, 'missing feedback should render an empty state');
assert.match(fnBody('openScheduleDetail'), /const feedbackCanEdit=!!fb[\s\S]*section:feedbackCanEdit\?'feedback':''/, 'feedback edit action should only show when feedback exists');
assert.match(fnBody('openScheduleDetail'), /renderScheduleDetailCard\('反馈内容'[\s\S]*className:'schedule-feedback-card'/, 'feedback card should have a scoped class for full-width feedback fields');
assert.match(source, /function editScheduleDetailSection\(/, 'schedule detail drawer should support local section editing');
assert.match(source, /function cancelScheduleDetailSectionEdit\(/, 'schedule detail drawer should support cancelling local edits');
assert.match(source, /function saveScheduleDetailSectionEdit\(/, 'schedule detail drawer should support saving local edits');
assert.match(fnBody('saveScheduleDetailSectionEdit'), /runStandardMutation\(saveButton/, 'local section saves should give immediate saving feedback through the global mutation helper');
assert.doesNotMatch(fnBody('saveScheduleDetailSectionEdit'), /catch\(e\)[\s\S]*saveButton[\s\S]*disabled=false/, 'local section save failures should not restore the save button by hand');
assert.match(fnBody('renderScheduleDetailCard'), /schedule-detail-action muted[\s\S]*取消[\s\S]*schedule-detail-action primary[\s\S]*保存修改/, 'schedule detail local edit actions should show cancel and save modification');
assert.match(styles, /\.overlay\.schedule-drawer-overlay[\s\S]*justify-content:flex-end/, 'schedule detail drawer overlay should align the panel to the right');
assert.match(styles, /\.overlay\.schedule-drawer-overlay \.modal\.modal-court\.modal-schedule-drawer\{[\s\S]*translateX\(100%\)/, 'schedule detail drawer should close by sliding out to the right');
assert.match(styles, /\.overlay\.schedule-drawer-overlay\.open \.modal\.modal-court\.modal-schedule-drawer\{[\s\S]*translateX\(0\)/, 'schedule detail drawer should open by sliding in from the right');
assert.match(source, /mclose-svg[\s\S]*M4\.4978 3\.7938L8\.1458 0\.145803/, 'schedule drawer close button should use the provided svg path');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.mclose \.mclose-svg\{[\s\S]*width:9px[\s\S]*height:9px/, 'schedule drawer close icon should be 9px');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.mclose\{[\s\S]*color:#9EA3AE/, 'schedule drawer close icon should use #9EA3AE by default');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-label[\s\S]*color:#969AA0[\s\S]*font-size:13px/, 'schedule detail drawer labels should match the agreed Feishu token');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-value[\s\S]*color:#333333[\s\S]*font-size:13px[\s\S]*padding:4px 0/, 'schedule detail drawer values should match the agreed Feishu token');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-tab\{[\s\S]*color:#68696F[\s\S]*font-size:13px/, 'schedule detail inactive tabs should match the requested token');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-tab\.active\{[\s\S]*color:#333333/, 'schedule detail active tab should match the requested token');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-section-title\{[\s\S]*font-size:15px[\s\S]*color:#333333/, 'schedule detail section title should match the requested token');
assert.doesNotMatch(styles, /modal-schedule-drawer[\s\S]*#2F5BEA/, 'schedule detail drawer should not use the old blue color');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-action\{[\s\S]*font-weight:400/, 'schedule detail edit actions should not be bold');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.mhead\{[\s\S]*background:#FDFDFD/, 'schedule detail drawer top module should use #FDFDFD');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.mbody\{[\s\S]*background:#F5F2F0/, 'schedule detail drawer content area should use #F5F2F0');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-title\{[\s\S]*font-size:18px[\s\S]*font-weight:600[\s\S]*color:#111827/, 'schedule detail drawer title should be 18px #111827 bold');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-subtitle\{[\s\S]*color:#6B7280[\s\S]*font-size:13px[\s\S]*font-weight:400/, 'schedule detail drawer subtitle should be 13px #6B7280 regular');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-hero\{[\s\S]*padding-bottom:12px/, 'schedule detail hero should use 12px bottom padding');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-tab\{[\s\S]*padding:0 0 2px/, 'schedule detail tab underline spacing should be 2px');
assert.match(fnBody('openStandardDetailDrawer'), /requestAnimationFrame\(\(\)=>ov\.classList\.add\('open'\)\)/, 'detail drawer should add open on the next frame so it slides in from the right');
assert.match(fnBody('openStandardDetailDrawer'), /event\.target===ov[\s\S]*closeModal\(\)/, 'detail drawer should close when clicking the left overlay blank area');
assert.doesNotMatch(fnBody('openScheduleModal'), /setCourtModalFrame\(id\?'编辑排课':'添加排课'/, 'schedule create and edit should no longer use the old centered modal frame');
assert.match(fnBody('openScheduleModal'), /modal-schedule-drawer/, 'schedule create and edit should use the same right-side drawer container');
assert.match(fnBody('openScheduleModal'), /scheduleDetailHeaderHtml[\s\S]*scheduleDetailTabsHtml/, 'schedule create and edit should reuse the detail drawer header and tabs');
assert.match(fnBody('openScheduleModal'), /姓名[\s\S]*课程类型[\s\S]*sch_standardCourseType[\s\S]*schedule-settlement-row[\s\S]*schedule-time-row[\s\S]*上课教练[\s\S]*地点类型[\s\S]*sch_locationPlaceLabel[\s\S]*场地[\s\S]*schedule-repeat-row/, 'schedule create and edit should edit the adjusted field order inside the detail card structure');
assert.match(fnBody('openScheduleModal'), /renderScheduleDetailFormCard\('基础信息'[\s\S]*renderScheduleDetailFormCard\('设置迟到'[\s\S]*renderScheduleDetailFormCard\('备注信息'/, 'schedule create and edit should place late settings between basic info and notes');
assert.doesNotMatch(fnBody('openScheduleModal'), /schedule-drawer-form-head/, 'schedule create and edit should not use a separate form drawer header');
assert.match(source, /function renderScheduleDetailFormCard\(/, 'schedule drawer should expose a card renderer for editable detail modules');
assert.doesNotMatch(fnBody('openCancelScheduleModal'), /setCourtModalFrame\('取消排课'/, 'schedule cancellation should no longer use the old centered modal frame');
assert.match(fnBody('openCancelScheduleModal'), /modal-schedule-drawer/, 'schedule cancellation should use the same right-side drawer container');
assert.match(fnBody('openCancelScheduleModal'), /schedule-drawer-form-actions[\s\S]*scheduleCancelBtn/, 'schedule cancellation should place return/confirm in the drawer header');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-field\{[\s\S]*width:232px[\s\S]*max-width:232px/, 'schedule detail field container should be 232px wide');
assert.match(styles, /\.overlay\.schedule-drawer-overlay \.modal\.modal-court\.modal-schedule-drawer\{[\s\S]*width:600px[\s\S]*max-width:600px/, 'schedule drawer should be 600px wide');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-label[\s\S]*max-width:232px/, 'schedule detail labels should cap at 232px');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-value[\s\S]*max-width:232px/, 'schedule detail values should cap at 232px');
assert.match(fnBody('openScheduleModal'), /schedule-detail-card-actions[\s\S]*取消[\s\S]*class="schedule-detail-action primary"[\s\S]*id="scheduleSaveBtn"[\s\S]*>保存修改</, 'schedule edit drawer actions should only show cancel and save modification');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.tms-form-row\{[\s\S]*grid-template-columns:repeat\(2,232px\)[\s\S]*gap:12px 28px/, 'schedule edit form rows should align to the same 232px two-column grid as readonly');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.tms-form-item\{[\s\S]*width:232px[\s\S]*max-width:232px/, 'schedule edit form fields should cap at 232px');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.tms-form-item\.full-width\{[\s\S]*width:492px[\s\S]*max-width:492px/, 'schedule notes should fill the full row and align to the right column');
assert.match(fnBody('openScheduleModal'), /schedule-student-notes-preview" title="\$\{esc\(studentNotesText\)\}"/, 'student notes preview should expose the full note text on hover');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-student-notes-preview\{[^}]*white-space:nowrap[^}]*overflow:hidden[^}]*text-overflow:ellipsis/, 'student notes preview should stay on one line without overlapping schedule notes');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-student-entitlement-list\{[^}]*display:flex[^}]*flex-direction:column[^}]*gap:8px/, 'multi-student package rows should render one student per line');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-student-entitlement-row\{[^}]*display:flex[^}]*height:32px[^}]*border-radius:8px[^}]*background:#FDF7F2/, 'multi-student package rows should match the selected-student tag style');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-student-entitlement-package\{[^}]*min-width:0[^}]*overflow:hidden[^}]*text-overflow:ellipsis[^}]*white-space:nowrap/, 'multi-student package text should stay on one line with ellipsis');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.tms-form-label\{[\s\S]*color:#969AA0[\s\S]*font-size:13px[\s\S]*line-height:22px/, 'schedule edit form labels should match readonly labels');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.tms-form-control[\s\S]*max-width:232px[\s\S]*font-size:13px[\s\S]*color:#333333/, 'schedule edit form controls should match readonly text width and color');
assert.match(styles, /--schedule-edit-control-height:40px[\s\S]*height:var\(--schedule-edit-control-height\)/, 'schedule edit inputs should use one fixed 40px height token');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-action\{[\s\S]*font-size:13px/, 'schedule detail actions should use 13px text');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-action\.muted\{[\s\S]*color:#6B7280[\s\S]*font-weight:400[\s\S]*\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-action\.muted:hover\{[\s\S]*color:#374151/, 'cancel action should use gray text and darker hover state');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-action\.primary\{[\s\S]*min-width:72px[\s\S]*height:32px[\s\S]*padding:0 12px[\s\S]*border-radius:6px[\s\S]*font-size:13px[\s\S]*font-weight:500[\s\S]*transition:background-color \.2s ease-in-out[\s\S]*box-shadow:0 1px 2px 0 rgba\(0,0,0,\.05\)/, 'save modification action should match the requested button token');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-action\.primary:hover\{[\s\S]*background:#6F462A/, 'save modification action should darken on hover');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form [^{]+::placeholder\{[\s\S]*color:#9EA3AE/, 'schedule drawer inputs should use the requested placeholder color');
assert.match(styles, /border:1px solid #E6E7EB/, 'schedule drawer inputs should use the requested default border color');
assert.match(fnBody('openScheduleModal'), /id="sch_ent_hint" class="schedule-entitlement-alert"/, 'package unavailable hint should render as a styled inline alert');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-entitlement-alert\{[\s\S]*display:none[\s\S]*margin-top:6px[\s\S]*font-size:12px[\s\S]*color:#EF4444/, 'package unavailable hint should use the red inline alert style');
assert.match(fnBody('applySchEntitlementOptions'), /hint\.innerHTML=.*schedule-entitlement-alert-icon[\s\S]*hint\.style\.display/, 'package unavailable hint should include an alert icon and toggle visibility');
assert.match(fnBody('openScheduleModal'), /sch_settlementType[\s\S]*sch_fieldFeeMode[\s\S]*schedule-payment-row[\s\S]*sch_payMethod[\s\S]*sch_paidAmount[\s\S]*sch_fieldFeeAmount/, 'schedule modal should split settlement, field fee mode, pay method, lesson fee, and field fee');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.schedule-payment-row\{[\s\S]*grid-template-columns:repeat\(3,156px\)/, 'payment row should split pay method, lesson fee, and field fee into compact equal columns');
assert.match(fnBody('openScheduleModal'), /sch_payMethod[\s\S]*refreshScheduleStoredValueHint[\s\S]*sch_paidAmount[\s\S]*refreshScheduleStoredValueHint[\s\S]*sch_storedValueHint/, 'stored-value direct payment should show a balance hint below the amount input');
assert.match(source, /function refreshScheduleStoredValueHint\(/, 'schedule page should refresh stored-value balance hint');
assert.match(fnBody('scheduleStoredValuePaymentState'), /isStoredValuePayMethod[\s\S]*courtFinanceLocal/, 'stored-value hint should read the selected student membership balance');
assert.match(fnBody('scheduleStoredValuePaymentState'), /当前储值卡余额/, 'stored-value hint should show current balance copy');
assert.match(fnBody('scheduleStoredValuePaymentState'), /扣后余额/, 'stored-value hint should show after-balance copy');
assert.match(fnBody('scheduleStoredValuePaymentState'), /余额不足/, 'stored-value hint should show insufficient-balance copy');
assert.match(fnBody('setScheduleStudentSelection'), /refreshScheduleStoredValueHint\(\)/, 'changing schedule students should refresh stored-value balance hint');
assert.match(fnBody('saveSchedule'), /scheduleStoredValuePaymentState[\s\S]*储值卡余额不足/, 'saving stored-value direct payment should block insufficient balance');
assert.match(fnBody('mergeScheduleSaveResult'), /result\?\.courts[\s\S]*courts\.findIndex/, 'schedule save should merge returned court account updates so stored-value balance refreshes locally');
assert.match(fnBody('renderCourtHistoryItems'), /sourceType==='schedule'[\s\S]*扣款时间/, 'schedule stored-value history rows should show the actual deduction time');
assert.match(styles, /\.schedule-stored-value-hint\{[\s\S]*font-size:12px/, 'stored-value balance hint should use compact helper text style');
assert.match(fnBody('openScheduleModal'), /schedule-lesson-count-controls[\s\S]*id="sch_lc"[\s\S]*id="sch_countItem"/, 'schedule modal should keep both deduction inputs for mode switching');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-lesson-count-controls\{[\s\S]*display:block[\s\S]*width:232px/, 'lesson hour and count controls should use the same 232px field position');
assert.match(fnBody('openScheduleModal'), /schedule-repeat-field[\s\S]*schedule-repeat-weeks-field[\s\S]*sch_repeatWeeksWrap/, 'repeat weeks should appear as its own aligned field');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-repeat-weeks-field\{[\s\S]*width:232px[\s\S]*max-width:232px/, 'repeat weeks input should use the default 232px field width');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-time-row\{[\s\S]*grid-template-columns:repeat\(2,232px\)/, 'schedule time row should use the standard two 232px columns');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.schedule-time-range\{[\s\S]*grid-template-columns:100px 56px 8px 56px[\s\S]*width:232px/, 'schedule time controls should align to the 232px field width');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.schedule-time-range>div:nth-child\(1\)\{[\s\S]*width:100px/, 'schedule date input should be 100px');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.schedule-time-range>div:nth-child\(2\)[\s\S]*width:56px/, 'schedule start time input should fit the aligned time range');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.schedule-time-range \.tms-dropdown\.tms-dropdown-form \.tms-dropdown-display::after\{[\s\S]*display:none/, 'schedule start and end time dropdown icons should be hidden');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-time-row \.schedule-lesson-count-item\{[\s\S]*width:232px[\s\S]*max-width:232px/, 'deduction input should use the default 232px field width');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.tms-checkbox\{[\s\S]*background-color:#FFFFFF/, 'unchecked schedule drawer checkboxes should be white');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-form \.schedule-time-range>div:nth-child\(4\)[\s\S]*width:56px/, 'schedule end time input should fit the aligned time range');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-proposal-card \.schedule-detail-field\.full-width\{[\s\S]*width:492px[\s\S]*max-width:492px/, 'proposal full-width fields should span both 232px columns');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-feedback-card \.schedule-detail-field\.full-width\{[\s\S]*width:492px[\s\S]*max-width:492px/, 'feedback full-width fields should span both 232px columns');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-proposal-empty-icon\{[\s\S]*width:80px[\s\S]*height:80px[\s\S]*background:#F8F9FA[\s\S]*border:1px solid #F3F4F6[\s\S]*border-radius:50%/, 'proposal empty icon background should match the requested token');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-proposal-empty-title\{[\s\S]*font-size:16px[\s\S]*font-weight:500[\s\S]*color:#374151[\s\S]*margin-bottom:8px/, 'proposal empty title should match requested text style');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-proposal-empty-text\{[\s\S]*font-size:13px[\s\S]*font-weight:400[\s\S]*color:#9CA3AF[\s\S]*max-width:280px/, 'proposal empty subtitle should match requested text style');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-entitlement-item \.tms-dropdown-display\{[\s\S]*overflow:hidden[\s\S]*text-overflow:ellipsis[\s\S]*white-space:nowrap/, 'long package names should stay inside the package dropdown field');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-entitlement-item \.tms-dropdown-menu\{[\s\S]*left:auto[\s\S]*right:0/, 'schedule package dropdown menu should align leftward inside the drawer');
assert.match(styles, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-entitlement-item \.tms-dropdown-item span\{[\s\S]*overflow:hidden[\s\S]*text-overflow:ellipsis/, 'long package option text should not force the menu wider than the drawer');
assert.match(fnBody('scheduleDetailHeaderHtml'), /scheduleStatusTagClass\(rawStatus\)/, 'schedule detail header status tag should use the same color class as the list');
assert.match(fnBody('scheduleDetailLateHtml'), /是否迟到[\s\S]*迟到原因[\s\S]*迟到时长[\s\S]*需承担场地费用/, 'schedule late detail should use the requested field order');
assert.match(fnBody('openScheduleModal'), /上课教练[\s\S]*sch_coach[\s\S]*地点类型[\s\S]*sch_locationType[\s\S]*sch_locationPlaceLabel[\s\S]*场地/, 'location fields should move after coach with dynamic place label');
assert.match(fnBody('toggleScheduleLocationType'), /sch_locationPlaceLabel[\s\S]*type==='external'\?'场馆名称':'上课校区'/, 'location place label should switch between campus and venue name without stars');
assert.doesNotMatch(fnBody('openScheduleModal'), /<label class="tms-form-label">[^<]*\*/, 'schedule create and edit labels should not show required stars');
assert.match(source, /function openCoachLateSettlementModal\(/, 'schedule page should expose coach late settlement modal');
assert.match(source, /迟到月结/, 'schedule page should expose coach late monthly settlement entry');
assert.doesNotMatch(source, /id="page-schedule"[\s\S]*?openCoachLateSettlementModal\(\)[\s\S]*?id="page-coachops"/, 'late monthly settlement should not be a primary schedule-table action');
assert.match(source, /id="page-coachops"[\s\S]*?openCoachLateSettlementModal\(\)/, 'late monthly settlement entry should live in coach operations');
assert.match(fnBody('openCoachLateSettlementModal'), /late-settlement-summary/, 'late settlement modal should show a compact summary');
assert.match(fnBody('openCoachLateSettlementModal'), /迟到次数/, 'late settlement summary should include late count');
assert.match(fnBody('coachLateSettlementRows'), /financeSettlementRowsFromSnapshot/, 'late settlement rows should come from backend finance settlement snapshot');
assert.match(fnBody('openCoachLateSettlementModal'), /来自财务统一结算快照/, 'late settlement summary should explain it uses the unified finance snapshot');
assert.match(fnBody('openCoachLateSettlementModal'), /承担合计/, 'late settlement summary should include payable total');
assert.match(fnBody('openCoachLateSettlementModal'), /late-settlement-table/, 'late settlement modal should use a scoped compact table');
assert.match(fnBody('openCoachLateSettlementModal'), /late-settlement-empty/, 'late settlement modal should use a compact empty state');
assert.match(fnBody('openScheduleModal'), /optionList\('scheduleSettlementTypes'\)[\s\S]*sch_settlementType/, 'schedule modal should let ops choose package, direct payment, or gift settlement from the shared dictionary');
assert.match(fnBody('openScheduleModal'), /sch_payMethod[\s\S]*sch_paidAmount/, 'schedule modal should collect payment method and amount for direct paid lessons');
assert.match(fnBody('saveSchedule'), /settlementType[\s\S]*paidAmount[\s\S]*payMethod/, 'schedule save should send settlement and payment fields to backend');
assert.match(fnBody('refreshSchEntitlementOptions'), /currentScheduleSettlementType\(\)!=='package'/, 'non-package settlement should not try to match entitlements');
assert.doesNotMatch(fnBody('saveSchedule'), /训练营固定 4 人/, 'small group bootcamp schedules should allow two or more attendees instead of requiring four');
assert.match(source, /const FEEDBACK_POSTER_TEMPLATES\s*=/, 'feedback poster should define fixed template configs');
assert.match(source, /blueGreenDiagonal[\s\S]*minimalDarkGreen[\s\S]*retroCourt[\s\S]*blueprintBlue[\s\S]*minimalRacket[\s\S]*activeGreen/, 'feedback poster should expose the selected Gemini template styles');
assert.doesNotMatch(source, /粉蓝笔刷|专业白\(拍网\)|深蓝撞色|波普斜切/, 'feedback poster should remove the rejected poster styles');
assert.match(fnBody('drawFeedbackPoster'), /网球兄弟/, 'feedback poster should use the local brand name');
assert.match(fnBody('drawFeedbackPoster'), /训练反馈/, 'feedback poster should add the training feedback title suffix');
assert.match(source, /function posterDrawFittedTitle\(/, 'feedback poster should fit long student names on one title line');
assert.match(fnBody('drawFeedbackPoster'), /posterDrawFittedTitle\(ctx,nameStr,60,140,630,68,46/, 'feedback poster should shrink long names before drawing the title');
assert.doesNotMatch(fnBody('drawFeedbackPoster'), /const nameWidth=ctx\.measureText\(nameStr\)\.width;[\s\S]*ctx\.fillText\('训练反馈',Math\.min\(60\+nameWidth\+16,560\),140\)/, 'feedback poster title suffix should not sit beside the student name');
assert.match(fnBody('drawFeedbackPoster'), /ctx\.fillText\(`\$\{posterDisplayDate\(data\.date\)\} 训练反馈`,60,195\)/, 'feedback poster should show date and training feedback on the subtitle line');
assert.match(fnBody('drawFeedbackPoster'), /用网球向生活发出邀请/, 'feedback poster should show the brand tagline');
assert.match(source, /function posterDisplayDate\(/, 'feedback poster should format lesson date for poster display');
assert.match(source, /function posterTextGroups\(/, 'feedback poster should support highlighted text groups');
assert.match(fnBody('posterTextGroups'), /raw\[i\]==='【'[\s\S]*highlight:true/, 'feedback poster should use Chinese brackets as manual highlight markers');
assert.doesNotMatch(fnBody('posterTextGroups'), /raw\[i\]==='\\*'|raw\[i\]==='\*'/, 'feedback poster should not treat asterisks as highlight markers');
assert.doesNotMatch(fnBody('posterPushAutoGroups'), /highlight:keywords\.includes\(part\)/, 'feedback poster should not auto-highlight guessed keywords');
assert.match(source, /function posterNormalizeText\(/, 'feedback poster should normalize list markers before drawing text');
assert.match(fnBody('posterApplyLineStyle'), /replace[\s\S]*\\d\+[\s\S]*·/, 'feedback poster should optionally remove line-start numbers and bullets');
assert.match(source, /function posterApplyLineStyle\(/, 'feedback poster should keep coach-entered list markers available for rendering');
assert.match(fnBody('posterApplyLineStyle'), /style==='preserve'[\s\S]*String\(text\|\|'—'\)/, 'feedback poster should preserve coach-entered titles and list markers by default');
assert.match(source, /function posterLineMetrics\(/, 'feedback poster should calculate hanging indents for numbered and bullet list lines');
assert.match(fnBody('posterLineMetrics'), /markerMatch[\s\S]*indent[\s\S]*paragraphGap/, 'feedback poster line metrics should include indent and paragraph spacing');
assert.match(fnBody('posterTextLines'), /availableWidth[\s\S]*maxWidth-line\.hangingIndent[\s\S]*lineWidth\+width>availableWidth/s, 'feedback poster should wrap indented continuation lines inside the card width');
assert.match(fnBody('posterDrawTextBlock'), /posterLineMetrics\(ctx,lineGroups\)[\s\S]*currentX=x\+metrics\.indent[\s\S]*metrics\.paragraphGap/s, 'feedback poster should draw wrapped list text with hanging indent and extra item spacing');
assert.match(source, /function feedbackNextListMarker\(/, 'feedback editor should calculate the next marker when coach presses enter');
assert.match(fnBody('feedbackNextListMarker'), /mode==='normal'[\s\S]*!numberMatch[\s\S]*!bulletMatch[\s\S]*return ''[\s\S]*mode==='bullet'[\s\S]*• [\s\S]*Number\(numberMatch\[1\]\)\+1/, 'feedback editor should only continue lists when the coach starts a numbered or bullet list');
assert.match(source, /function feedbackApplyListStyleToRange\(/, 'feedback editor should format the selected lines instead of replacing selected text with one marker');
assert.match(fnBody('feedbackApplyListStyleToRange'), /end>start[\s\S]*split\('\\n'\)[\s\S]*itemIndex\+=1[\s\S]*`\$\{itemIndex\}\. \$\{clean\}`/s, 'feedback editor should number only the selected non-empty lines');
assert.match(fnBody('feedbackApplyListStyleToRange'), /style==='bullet'[\s\S]*`• \$\{clean\}`/s, 'feedback editor should use the normal bullet glyph for selected bullet lists');
assert.match(fnBody('feedbackInsertListMarker'), /feedbackApplyListStyleToRange\(value,start,end,style\)/, 'feedback list buttons should preserve selected text through the shared formatter');
assert.doesNotMatch(fnBody('feedbackNextListMarker'), /return '· '/, 'feedback enter continuation should not insert the tiny middle dot as bullet');
assert.match(source, /function handleFeedbackListKeydown\(/, 'feedback editor should intercept enter to auto insert the next marker');
assert.match(source, /function setFeedbackListStyle\(/, 'feedback editor should expose buttons to start numbered or bullet lists');
assert.match(fnBody('feedbackListStyleSelect'), /普通[\s\S]*编号[\s\S]*圆点/, 'feedback modal should expose normal, numbered, and bullet typing modes before coaches write feedback');
assert.match(source, /function autoResizeFeedbackTextarea\(/, 'feedback textareas should expose auto height resizing');
assert.match(fnBody('feedbackListTextareaAttrs'), /data-feedback-autoresize="true"[\s\S]*oninput="autoResizeFeedbackTextarea\(this\)"/, 'feedback textareas should resize when content changes');
assert.match(fnBody('openFeedbackModal'), /feedbackListStyleSelect\('fb_list_style'\)/, 'feedback modal should render the feedback typing mode toolbar');
assert.match(fnBody('openFeedbackModal'), /autoResizeFeedbackTextareas\(document\.getElementById\('mBody'\)\)/, 'feedback modal should resize existing feedback text when opened');
assert.match(fnBody('openScheduleDetail'), /autoResizeFeedbackTextareas\(\)/, 'schedule detail feedback edit fields should resize existing text when opened');
assert.match(fnBody('feedbackListTextareaAttrs'), /onkeydown="handleFeedbackListKeydown\(event\)"/, 'feedback modal textareas should auto continue list markers while typing');
assert.match(fnBody('openFeedbackPosterModal'), /preserveListMarkers/, 'feedback poster modal should expose a list marker option');
assert.doesNotMatch(fnBody('openFeedbackPosterModal'), /posterListStyle[\s\S]*自动编号[\s\S]*项目符号[\s\S]*不添加/, 'feedback poster modal should not reformat all lines after coaches already typed the structure');
assert.match(source, /function measureFeedbackPosterLayout\(/, 'feedback poster should expose a layout measurer for dynamic poster height');
assert.match(source, /function posterSectionHasContent\(/, 'feedback poster should detect empty optional sections');
assert.match(fnBody('measureFeedbackPosterLayout'), /posterSectionHasContent\(data\.knowledgePoint\)[\s\S]*knowledge=null/, 'feedback poster should hide practice status when it is empty');
assert.doesNotMatch(fnBody('measureFeedbackPosterLayout'), /lineCaps=\{practiced:12,knowledge:14,nextTraining:10\}/, 'feedback poster should not cap long feedback text');
assert.match(fnBody('measureFeedbackPosterLayout'), /posterTextLines[\s\S]*posterBlockHeight[\s\S]*canvasHeight/s, 'feedback poster layout should derive block heights and final canvas height from wrapped text');
assert.match(fnBody('measureFeedbackPosterLayout'), /footerBaseTop=1156[\s\S]*contentBottom[\s\S]*canvasHeight=Math\.max\(1334,contentBottom\+240\)[\s\S]*footer:\{brandY:footerBaseTop\+56,taglineY:footerBaseTop\+91,accentY:footerBaseTop\+81\}/s, 'feedback poster footer should stay fixed while content controls only the poster height');
assert.doesNotMatch(fnBody('drawFeedbackPoster'), /TRAINING REPORT|Coach/, 'feedback poster should remove the old English report and coach footer');
assert.doesNotMatch(fnBody('drawFeedbackPoster'), /canvas\.width=750;canvas\.height=1334;/, 'feedback poster should not hardcode a fixed export height anymore');
assert.match(fnBody('drawFeedbackPoster'), /const layout=measureFeedbackPosterLayout\(ctx,data\);[\s\S]*canvas\.width=750;canvas\.height=layout\.canvasHeight;/s, 'feedback poster should size the canvas from measured content before drawing');
assert.match(fnBody('drawFeedbackPoster'), /layout\.practiced[\s\S]*if\(layout\.knowledge\)[\s\S]*layout\.nextTraining/s, 'feedback poster should draw measured blocks and skip empty optional status');
assert.match(fnBody('openFeedbackPosterModal'), /blueGreenDiagonal/, 'feedback poster modal should default to the first Gemini template');
assert.match(source, /function drawFeedbackPoster\(/, 'feedback poster should draw fixed templates with canvas');
assert.match(source, /function openFeedbackPosterModal\(/, 'feedback poster should expose a modal entry');
assert.match(source, /function downloadFeedbackPoster\(/, 'feedback poster should expose a direct download action');
assert.match(fnBody('openFeedbackPosterModal'), /下载图片[\s\S]*分享图片/, 'feedback poster modal should separate local download from system share');
assert.match(fnBody('shareFeedbackPoster'), /AbortError/, 'cancelled share should not be treated as a generation failure');
assert.match(fnBody('shareFeedbackPoster'), /navigator\.clipboard[\s\S]*ClipboardItem[\s\S]*image\/png/s, 'desktop poster sharing should try writing the PNG into the clipboard before falling back to system share');
assert.match(fnBody('shareFeedbackPoster'), /try\{[\s\S]*navigator\.clipboard\.write[\s\S]*\}catch\(copyErr\)\{[\s\S]*navigator\.share/s, 'poster sharing should fall back to system share when clipboard image copy fails');
assert.match(styles, /::-webkit-scrollbar\{height:3px\}[\s\S]*max-height:58vh/, 'poster preview should fit the modal and use a thin horizontal scrollbar');
assert.match(fnBody('openFeedbackModal'), /生成海报/, 'saved feedback modal should show a poster entry');
assert.match(fnBody('openFeedbackModal'), /trialFieldsHtml/, 'trial conversion fields should be conditional');
assert.match(fnBody('openFeedbackModal'), /练习情况（非必填）/, 'feedback modal should rename knowledge point to practice status');
assert.match(fnBody('openFeedbackModal'), /体验课内部记录/, 'trial-only fields should be framed as internal notes');
assert.match(fnBody('openFeedbackModal'), /1\.0～1\.5[\s\S]*1\.5～2\.0[\s\S]*2\.0～2\.5[\s\S]*2\.5～3\.0[\s\S]*3\.0～3\.5[\s\S]*3\.5～4\.0/, 'trial level options should use the fixed numeric ladder');
assert.doesNotMatch(fnBody('openFeedbackModal'), /知识点（非必填）|体验课转化判断|零基础|初学|有基础|长期打球/, 'feedback modal should remove the old trial copy and level options');
assert.doesNotMatch(fnBody('openFeedbackModal'), /复制给学员/, 'feedback modal should not keep copy action after poster entry exists');
assert.doesNotMatch(fnBody('saveFeedback'), /openFeedbackPosterModal\(/, 'saving feedback should not force coach into poster generation');

console.log('schedule page view tests passed');
