const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: source } = require('./helpers/read-index-bundle');
const styles = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'pages.css'), 'utf8');

function fnBody(name){
  const start = source.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = source.indexOf('\nfunction ', start + 1);
  const nextAsync = source.indexOf('\nasync function ', start + 1);
  const candidates = [nextFunction, nextAsync].filter(i => i !== -1);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return source.slice(start, next === -1 ? source.length : next);
}

assert.match(source, /function buildRepeatScheduleSeeds\(/, 'schedule page should expose a repeat schedule helper');
assert.match(fnBody('openScheduleModal'), /sch_repeatEnabled/, 'schedule modal should allow enabling repeat scheduling');
assert.match(fnBody('openScheduleModal'), /循环排课/, 'schedule modal should describe weekly repeat scheduling');
assert.match(fnBody('openScheduleModal'), /教练迟到免费/, 'schedule modal should support marking coach-late free lessons');
assert.match(fnBody('openScheduleModal'), /教练承担场地费/, 'schedule modal should capture coach late field fee');
assert.match(fnBody('scheduleSaveConfirmText'), /迟到免费/, 'schedule save confirm copy should show coach-late free status');
assert.doesNotMatch(fnBody('scheduleSaveConfirmText'), /班次：/, 'schedule save confirm copy should not show obsolete class linkage copy');
assert.match(fnBody('saveSchedule'), /buildRepeatScheduleSeeds\(/, 'saving schedules should fan out repeat seeds when enabled');
assert.match(fnBody('saveSchedule'), /coachLateFree/, 'saving schedules should persist coach late fields');
assert.match(fnBody('saveSchedule'), /await appConfirm\(/, 'saving schedules should use app confirm instead of browser confirm');
assert.doesNotMatch(fnBody('saveSchedule'), /window\.confirm\(/, 'saving schedules should not use browser confirm');
assert.match(fnBody('scheduleSaveConfirmText'), /schedule-confirm-card/, 'schedule save confirm should render a structured confirmation card');
assert.match(fnBody('scheduleSaveConfirmText'), /schedule-confirm-row[\s\S]*时间[\s\S]*学员[\s\S]*教练[\s\S]*场地[\s\S]*课程[\s\S]*结算方式/, 'schedule save confirm should keep all key fields as structured rows');
assert.match(fnBody('scheduleSaveConfirmText'), /`\$\{day\} · \$\{startClock\} - \$\{endClock\}`/, 'schedule save confirm should show same-day time as date dot time range');
assert.doesNotMatch(fnBody('scheduleSaveConfirmText'), /<strong>/, 'schedule save confirm should not force bold values');
assert.match(fnBody('scheduleSaveConfirmText'), /schedule-confirm-charge/, 'schedule save confirm should highlight lesson deduction');
assert.match(fnBody('scheduleSaveConfirmText'), /const chargeText=data\.coachLateFree\?'本节不扣课':`\$\{data\.lessonCount\|\|0\} 节`;/, 'coach-late free confirm should not display a lesson deduction amount');
assert.match(fnBody('saveSchedule'), /const lc=parseFloat\(document\.getElementById\('sch_lc'\)\.value\)\|\|1;/, 'schedule save should preserve half-lesson counts');
assert.doesNotMatch(fnBody('saveSchedule'), /const lc=parseInt\(document\.getElementById\('sch_lc'\)\.value\)\|\|1;/, 'schedule save should not truncate half-lesson counts');
assert.match(fnBody('saveSchedule'), /html:true[\s\S]*hideIcon:true[\s\S]*boxClass:'schedule-confirm-box'/, 'schedule save confirm should use the compact visual confirm layout');
assert.match(source, /function appConfirm\([\s\S]*html=false[\s\S]*hideIcon=false[\s\S]*boxClass=''/, 'appConfirm should support structured HTML content for specialized confirmations');
assert.match(styles, /\.schedule-confirm-box[\s\S]*\.schedule-confirm-charge/, 'schedule save confirm should have dedicated scoped styles');
assert.match(styles, /\.schedule-confirm-box #confDesc[\s\S]*font-size:13px/, 'schedule save confirm should use compact 13px body text');
assert.match(styles, /\.schedule-confirm-value[\s\S]*font-weight:400/, 'schedule save confirm values should use regular weight');
assert.match(fnBody('refreshSchEntitlementOptions'), /setScheduleEntitlementDropdown\(\[\], '', '正在重新计算可用课包'\);[\s\S]*hint\.textContent='正在匹配可用课包…';/, 'refreshing schedule entitlements should clear stale package options before async recommend returns');
assert.match(source, /function resetScheduleSaveButton\(/, 'schedule save should use a helper to restore the save button safely');
assert.match(fnBody('saveSchedule'), /resetScheduleSaveButton\(\)/, 'schedule save should restore the save button through the helper');
assert.doesNotMatch(fnBody('saveSchedule'), /catch\(e\)\{toast\('保存失败：'\+e\.message,'error'\);btn\.disabled=false;btn\.textContent='保存';\}/, 'schedule save failure should not assume the save button exists');
assert.match(fnBody('openCancelScheduleModal'), /确认取消/, 'schedule cancel should use a dedicated confirm modal instead of reopening the edit form');
assert.match(fnBody('openCancelScheduleModal'), /取消本节及后续未上课的循环课/, 'repeat schedules should expose a future-lessons cancel option');
assert.match(fnBody('openCancelScheduleModal'), /schedule-cancel-summary/, 'schedule cancel modal should use a readable summary block instead of low-contrast warning text');
assert.match(fnBody('openCancelScheduleModal'), /schedule-cancel-scope/, 'schedule cancel modal should render the cancellation scope options in a dedicated stacked layout');
assert.match(fnBody('confirmScheduleCancel'), /effectiveScheduleStatus\(item\)==='已排课'/, 'repeat cancellation should only touch not-yet-started lessons');
assert.match(fnBody('confirmScheduleCancel'), /scope==='future'/, 'repeat cancellation should support current-and-future scope');
assert.doesNotMatch(fnBody('confirmScheduleCancel'), /window\.confirm\(/, 'schedule cancel flow should not fall back to the browser confirm');
assert.match(fnBody('renderSchedule'), /const isCancelled=status==='已取消'/, 'cancelled schedule rows should derive a dedicated action state');
assert.match(fnBody('renderSchedule'), /!\s*isCancelled\?`<span class="tms-action-link" onclick="openCancelScheduleModal\('\$\{s\.id\}'\)">取消<\/span>`:''/, 'cancelled schedule rows should not keep showing cancel action');
assert.match(fnBody('renderSchedule'), /isCancelled\|\|scheduleCanDeleteMistake\(s\)/, 'cancelled schedule rows should expose delete action');
assert.match(fnBody('openScheduleModal'), /scheduleModalCanDelete/, 'schedule modal should reuse delete visibility for cancelled schedules');
assert.match(source, /function scheduleEntitlementUnavailableReason\(/, 'schedule package picker should translate unavailable package reasons into user-facing copy');
assert.match(fnBody('applySchEntitlementOptions'), /scheduleEntitlementUnavailableReason\(res\.options\|\|\[\]\)/, 'schedule package picker should show why packages are unavailable');
assert.doesNotMatch(fnBody('applySchEntitlementOptions'), /hint\.textContent=selected\?[^;]+:'';/, 'schedule package picker should not hide unavailable package reasons behind empty hint text');
assert.match(fnBody('openScheduleDetail'), /教练迟到处理/, 'schedule detail should show coach late settlement info');
assert.match(source, /document\.getElementById\('campusTabs'\)\.style\.display=\[[^\]]*'schedule'/, 'schedule page should show the global campus filter tabs');
assert.match(source, /if\(currentPage==='schedule'\)renderSchedule\(\);/, 'global campus filter should rerender the schedule page');
assert.match(source, /schCoachFilterHost/, 'schedule toolbar should expose a coach filter host');
assert.match(source, /function syncScheduleFilterOptions\([\s\S]*schCoachFilter[\s\S]*教练/, 'schedule filters should use coach instead of in-toolbar campus');
assert.doesNotMatch(source, /schCampusFilterHost|schCampusFilter/, 'schedule toolbar should not keep the old campus dropdown filter');
assert.match(source, /function scheduleLocationText\(/, 'schedule page should centralize location display');
assert.match(fnBody('openScheduleModal'), /地点类型[\s\S]*校区内[\s\S]*校区外/, 'schedule modal should support in-campus and off-campus lesson location types');
assert.match(fnBody('openScheduleModal'), /学员信息[\s\S]*sch_entitlementHost[\s\S]*sch_courseType[\s\S]*上课信息[\s\S]*schedule-time-field/, 'schedule modal should keep package and course type in student info before lesson time');
assert.doesNotMatch(fnBody('openScheduleModal'), /<select[^>]+id="sch_entitlement"/, 'schedule entitlement should use the standard custom dropdown instead of native select');
assert.match(fnBody('openScheduleModal'), /schedule-location-row[\s\S]*sch_locationType[\s\S]*sch_ownLocationRow[\s\S]*sch_campus[\s\S]*sch_venue/, 'own campus location fields should sit on one row with location type');
assert.match(source, /function scheduleVenueOptionsForCampus\(/, 'schedule page should expose venue options by campus');
assert.match(fnBody('scheduleVenueOptionsForCampus'), /shilipu[\s\S]*5号场/, 'shilipu should expose 1-5 courts');
assert.match(source, /function scheduleCampusAllowsCustomVenue\(/, 'schedule page should expose custom venue rule by campus');
assert.match(fnBody('scheduleCampusAllowsCustomVenue'), /return true/, 'all campuses should allow custom venue input');
assert.match(fnBody('openScheduleModal'), /sch_venueFieldHost/, 'schedule modal should render venue through a dedicated host');
assert.match(fnBody('openScheduleModal'), /handleScheduleCampusChange/, 'schedule campus change should refresh venue options');
assert.match(fnBody('openScheduleModal'), /schedule-location-row[\s\S]*sch_locationType[\s\S]*sch_externalLocationRow[\s\S]*sch_externalVenueName[\s\S]*sch_externalCourtName[\s\S]*sch_externalNotes/, 'external location fields should sit on one row with location type');
assert.match(fnBody('openScheduleModal'), /学员信息[\s\S]*选择学员[\s\S]*扣减课包[\s\S]*课程类型[\s\S]*上课信息[\s\S]*上课日期与时间[\s\S]*循环排课[\s\S]*每周循环[\s\S]*消课节数[\s\S]*上课教练[\s\S]*地点类型/, 'schedule modal should follow the upgraded student-first flow');
assert.match(source, /const PRODUCT_TYPES=\['私教课','小班课','体验课','大师课'\]/, 'all course type dropdowns should share the standard level1 course types');
assert.match(source, /const EXPERIENCE_TYPES=\['私教体验课','小班体验课'\]/, 'all trial course subtype dropdowns should share EXPERIENCE_TYPES');
assert.match(fnBody('syncScheduleFilterOptions'), /PRODUCT_TYPES\.map\(t=>\(\{value:t,label:t\}\)\)/, 'schedule course type filter should use the shared course type source');
assert.match(fnBody('openScheduleModal'), /const courseTypeOptions=PRODUCT_TYPES\.map\(t=>\(\{value:t,label:t\}\)\)/, 'schedule modal course type dropdown should use the shared course type source');
assert.match(fnBody('openScheduleModal'), /sch_experienceType/, 'schedule modal should expose a second-level trial course selector');
assert.match(fnBody('saveSchedule'), /experienceType:/, 'schedule save should persist trial course subtype');
assert.match(fnBody('openScheduleModal'), /sch_smallClassType/, 'schedule modal should expose a second-level small group course selector');
assert.match(source, /function syncScheduleSmallClassType\(/, 'schedule modal should sync bootcamp repeat defaults');
assert.match(fnBody('syncScheduleSmallClassType'), /sch_repeatEnabled[\s\S]*weeks\.value=6/, 'small group bootcamp should default to six weekly schedules');
assert.match(fnBody('scheduleLessonUnitsFromFields'), /courseType==='小班课'[\s\S]*studentCount===3[\s\S]*return 1\.5[\s\S]*studentCount>=4[\s\S]*return 2/, 'small group lesson units should follow attendee count');
assert.match(fnBody('saveSchedule'), /smallClassType:/, 'schedule save should persist small group subtype');
assert.match(fnBody('openScheduleModal'), /设置迟到/, 'schedule modal should expose late settings beside coach');
assert.match(fnBody('openScheduleModal'), /schedule-late-row[\s\S]*full-width[\s\S]*\$\{lateSettings\}/, 'late settings should expand as a full-width row under the lesson module');
assert.doesNotMatch(fnBody('openScheduleModal'), /schedule-late-field">\$\{lateSettings\}/, 'late settings should not expand inside the coach row field');
assert.match(fnBody('openScheduleModal'), /schedule-repeat-control \$\{id\?'is-disabled':''\}/, 'edit-mode repeat scheduling should render as visibly disabled');
assert.match(styles, /\.modal\.modal-court \.schedule-repeat-control\.is-disabled[\s\S]*pointer-events:none/, 'disabled repeat scheduling should be non-clickable');
assert.doesNotMatch(fnBody('openScheduleModal'), /上课地点|排课会校验时间冲突|取消勾选的人本次记为缺勤|按周生成多节课/, 'schedule modal should remove the extra notice, separate location section, and old repeat copy');
assert.match(fnBody('openScheduleModal'), /选择学员 \*<\/label>[\s\S]*sch_stuSearch[\s\S]*sch_studentSuggest[\s\S]*sch_selectedStudentTags/, 'schedule modal should use search suggestions and selected student tags');
assert.match(source, /function scheduleStudentInlineMeta\([\s\S]*归属：[\s\S]*上次上课：/, 'schedule student metadata should include campus and last lesson inline');
assert.match(source, /function renderScheduleStudentTags\([\s\S]*scheduleStudentInlineMeta[\s\S]*removeScheduleStudent/, 'selected schedule students should render as removable tags with inline metadata');
assert.match(fnBody('renderScheduleStudentTags'), /if\(!rows\.length\)return ''/, 'empty student selection should not render a placeholder row');
assert.match(source, /function renderScheduleStudentSuggestions\([\s\S]*selectScheduleStudent/, 'schedule student search should render selectable suggestions');
assert.match(source, /function scheduleSelectedStudentSearchText\(/, 'schedule student search input should derive its text from selected students');
assert.match(fnBody('selectScheduleStudent'), /syncScheduleStudentSearchInput\(\[\.\.\.ids,studentId\]\)/, 'selecting a student should show selected names in the search input');
assert.doesNotMatch(fnBody('selectScheduleStudent'), /input\.value=''/, 'selecting a student should not blank the search input');
assert.match(fnBody('renderScheduleStudentSuggestions'), /pickedMatches[\s\S]*!rows\.length[\s\S]*pickedMatches\.length\?''/, 'matched selected students should not show a no-match state');
assert.doesNotMatch(fnBody('openScheduleModal'), /sch_stuPicker|tms-checkbox-matrix|toggleScheduleStudentCheckbox/, 'schedule modal should no longer show the old checkbox matrix');
assert.doesNotMatch(source, /function toggleScheduleStudentCheckbox/, 'schedule modal should remove the old checkbox selection handler');
assert.doesNotMatch(fnBody('openScheduleModal'), /关联班次|sch_classId|sch_class_hint/, 'schedule modal should remove the obsolete linked-class field');
assert.match(source, /function refreshScheduleTimeDerivedFields\(/, 'schedule modal should expose a time-derived refresh helper');
assert.match(fnBody('openScheduleModal'), /refreshScheduleTimeDerivedFields/, 'schedule modal should refresh lesson units when time changes');
assert.match(source, /function getScheduleTimeOptions\([\s\S]*h=7[\s\S]*h<=22[\s\S]*active:opt\.value===selected/, 'schedule time dropdown should only expose 07:00-22:00 and keep the selected time active');
assert.match(source, /function handleScheduleStartTimeChange\([\s\S]*const mins=[\s\S]*scheduleAddMinutes\(start,mins\)[\s\S]*setCourtDropdownValue\('sch_endTime'/, 'selecting a start time should default end time from course duration rules');
assert.match(fnBody('openScheduleModal'), /sch_repeatWeeksWrap[\s\S]*display:none/, 'repeat weeks should be hidden until weekly repeat is enabled');
assert.match(source, /function toggleScheduleRepeatWeeks\([\s\S]*sch_repeatWeeksWrap[\s\S]*checked\?'':'none'/, 'weekly repeat checkbox should reveal the repeat weeks input only when checked');
assert.match(source, /function setScheduleCourseTypeReadonly\([\s\S]*pointerEvents=readonly\?'none':'auto'/, 'course type should become readonly when a package determines it');
assert.match(fnBody('applySchEntitlementOptions'), /maxRemain[\s\S]*setScheduleCourseTypeReadonly/, 'schedule entitlement recommendation should default to the package with most remaining lessons and lock course type');
assert.match(source, /function scheduleEntitlementSmallClassType\(/, 'schedule package picker should read small group subtype from the selected package');
assert.match(fnBody('applySchEntitlementOptions'), /scheduleEntitlementSmallClassType\(selected\)[\s\S]*setCourtDropdownValue\('sch_smallClassType'/, 'schedule entitlement recommendation should force the package small group subtype');
assert.match(fnBody('handleScheduleEntitlementChange'), /scheduleEntitlementSmallClassType\(\{entitlementId:sel\.value\}\)[\s\S]*setCourtDropdownValue\('sch_smallClassType'/, 'manual package selection should force the package small group subtype');
assert.match(fnBody('setScheduleSmallClassTypeReadonly'), /pointerEvents=readonly\?'none':'auto'/, 'small group subtype should become readonly when a package determines it');
assert.doesNotMatch(fnBody('applySchEntitlementOptions'), /当前没有可用课包/, 'empty package state should not repeat the no-package message below the dropdown');
assert.match(styles, /\.modal\.modal-court \.schedule-student-tags[\s\S]*\.modal\.modal-court \.schedule-student-tag/, 'schedule student tags should have scoped modal styles');
assert.match(fnBody('openScheduleModal'), /sch_externalVenueName[\s\S]*sch_externalCourtName[\s\S]*sch_externalNotes/, 'external venue schedules should capture venue, court, and notes');
assert.doesNotMatch(fnBody('openScheduleModal'), /sch_externalAddress|地址/, 'external venue schedules should not ask for an address');
assert.match(fnBody('openScheduleModal'), /设置迟到[\s\S]*教练迟到免费/, 'coach late fields should remain folded as late settings');
assert.doesNotMatch(fnBody('openScheduleModal'), /通知状态|确认状态|确认规则/, 'schedule modal should remove fake notification and confirmation fields');
assert.doesNotMatch(fnBody('scheduleSaveConfirmText'), /确认规则|确认截止|通知：/, 'schedule save confirm copy should not show fake notification rules');
assert.doesNotMatch(fnBody('openScheduleDetail'), /通知 \/ 确认|确认规则/, 'schedule detail should not show fake notification rules');
assert.match(fnBody('scheduleStatusLabel'), /已结束[\s\S]*已下课/, 'schedule ended status should display as 已下课');
assert.match(fnBody('renderSchedule'), /scheduleStatusLabel/, 'schedule list should render user-facing status text');
assert.match(source, /function scheduleRepeatDisplayText\(/, 'schedule list should define a repeat display helper');
assert.match(fnBody('renderSchedule'), /scheduleRepeatDisplayText\(s\)/, 'schedule rows should render a user-facing repeat value');
assert.match(source, /function onScheduleFilterChange\(\)\{schPage=1;renderSchedule\(\);\}/, 'schedule filters should reset pagination before rendering');
assert.match(source, /syncScheduleFilterOptions[\s\S]*const statusOptions=withStandardFilterCounts[\s\S]*const coachOptions=withStandardFilterCounts[\s\S]*const courseTypeOptions=withStandardFilterCounts/, 'schedule toolbar filters should use standard count labels');
assert.match(source, /function renderSchedulePagerControls\(/, 'schedule page should use the standard compact pager controls');
assert.match(source, /function setSchedulePageSize\(/, 'schedule page should support 20, 50, and 100 row page sizes');
assert.match(source, /function scheduleEmptyStateHtml\([\s\S]*没有匹配的排课[\s\S]*暂无排课[\s\S]*调整搜索或筛选后再试[\s\S]*点击右上角添加排课开始安排课程/, 'schedule empty state should distinguish filtered empty results from no data');
assert.match(source, /id="schPageSize"/, 'schedule pager should expose a page size selector host');
assert.match(source, /<th class="tms-sticky-l" style="width:84px;padding-left:14px">日期<\/th>/, 'schedule table should keep the date column fixed on the left');
assert.match(fnBody('renderSchedule'), /<td class="tms-sticky-l" style="padding-left:14px">/, 'schedule rows should keep the date cell fixed on the left');
assert.match(styles, /#page-schedule \.tms-table th\.tms-sticky-l[\s\S]*#page-schedule \.tms-table td\.tms-sticky-r/, 'schedule table should define scoped fixed column styles');
assert.match(styles, /#page-schedule \.tms-pagination\{padding:4px 12px;font-size:11px/, 'schedule pager should use the compact standard pager style');
assert.match(source, /function renderScheduleTableLoading\([\s\S]*tms-table-loading-state[\s\S]*排课数据加载中/, 'schedule loading state should use the standard table loading style');
assert.match(source, /function renderScheduleTableError\([\s\S]*tms-table-error-state[\s\S]*加载失败[\s\S]*重新加载/, 'schedule load failure should render an inline retry state');
assert.match(fnBody('openScheduleDetail'), /tms-detail-grid[\s\S]*studentDetailFieldHtml[\s\S]*studentDetailBlockHtml/, 'schedule detail should use the same readonly detail display as student detail');
assert.doesNotMatch(fnBody('openScheduleDetail'), /<input|finput|tms-form-control|<textarea|<select/, 'schedule detail should not look editable');
assert.match(source, /function openCoachLateSettlementModal\(/, 'schedule page should expose coach late settlement modal');
assert.match(source, /迟到月结/, 'schedule page should expose coach late monthly settlement entry');
assert.doesNotMatch(source, /id="page-schedule"[\s\S]*?openCoachLateSettlementModal\(\)[\s\S]*?id="page-coachops"/, 'late monthly settlement should not be a primary schedule-table action');
assert.match(source, /id="page-coachops"[\s\S]*?openCoachLateSettlementModal\(\)/, 'late monthly settlement entry should live in coach operations');
assert.match(fnBody('openCoachLateSettlementModal'), /late-settlement-summary/, 'late settlement modal should show a compact summary');
assert.match(fnBody('openCoachLateSettlementModal'), /迟到次数/, 'late settlement summary should include late count');
assert.match(fnBody('openCoachLateSettlementModal'), /迟到分钟/, 'late settlement summary should include late minutes');
assert.match(fnBody('openCoachLateSettlementModal'), /承担合计/, 'late settlement summary should include payable total');
assert.match(fnBody('openCoachLateSettlementModal'), /late-settlement-table/, 'late settlement modal should use a scoped compact table');
assert.match(fnBody('openCoachLateSettlementModal'), /late-settlement-empty/, 'late settlement modal should use a compact empty state');
assert.match(fnBody('openScheduleModal'), /课包扣减[\s\S]*直接收款[\s\S]*赠送\/免费[\s\S]*sch_settlementType/, 'schedule modal should let ops choose package, direct payment, or gift settlement');
assert.match(fnBody('openScheduleModal'), /sch_payMethod[\s\S]*sch_paidAmount/, 'schedule modal should collect payment method and amount for direct paid lessons');
assert.match(fnBody('saveSchedule'), /settlementType[\s\S]*paidAmount[\s\S]*payMethod/, 'schedule save should send settlement and payment fields to backend');
assert.match(fnBody('refreshSchEntitlementOptions'), /currentScheduleSettlementType\(\)!=='package'/, 'non-package settlement should not try to match entitlements');
assert.match(source, /const FEEDBACK_POSTER_TEMPLATES\s*=/, 'feedback poster should define fixed template configs');
assert.match(source, /blueGreenDiagonal[\s\S]*minimalDarkGreen[\s\S]*retroCourt[\s\S]*blueprintBlue[\s\S]*minimalRacket[\s\S]*activeGreen/, 'feedback poster should expose the selected Gemini template styles');
assert.doesNotMatch(source, /粉蓝笔刷|专业白\(拍网\)|深蓝撞色|波普斜切/, 'feedback poster should remove the rejected poster styles');
assert.match(fnBody('drawFeedbackPoster'), /网球兄弟/, 'feedback poster should use the local brand name');
assert.match(fnBody('drawFeedbackPoster'), /训练反馈/, 'feedback poster should add the training feedback title suffix');
assert.match(fnBody('drawFeedbackPoster'), /用网球向生活发出邀请/, 'feedback poster should show the brand tagline');
assert.match(source, /function posterDisplayDate\(/, 'feedback poster should format lesson date for poster display');
assert.match(source, /function posterTextGroups\(/, 'feedback poster should support highlighted text groups');
assert.match(source, /function measureFeedbackPosterLayout\(/, 'feedback poster should expose a layout measurer for dynamic poster height');
assert.match(fnBody('measureFeedbackPosterLayout'), /posterTextLines[\s\S]*posterBlockHeight[\s\S]*canvasHeight/s, 'feedback poster layout should derive block heights and final canvas height from wrapped text');
assert.doesNotMatch(fnBody('drawFeedbackPoster'), /TRAINING REPORT|Coach/, 'feedback poster should remove the old English report and coach footer');
assert.doesNotMatch(fnBody('drawFeedbackPoster'), /canvas\.width=750;canvas\.height=1334;/, 'feedback poster should not hardcode a fixed export height anymore');
assert.match(fnBody('drawFeedbackPoster'), /const layout=measureFeedbackPosterLayout\(ctx,data\);[\s\S]*canvas\.width=750;canvas\.height=layout\.canvasHeight;/s, 'feedback poster should size the canvas from measured content before drawing');
assert.match(fnBody('drawFeedbackPoster'), /layout\.practiced[\s\S]*layout\.knowledge[\s\S]*layout\.nextTraining/s, 'feedback poster should draw the three blocks using measured layout positions');
assert.match(fnBody('openFeedbackPosterModal'), /blueGreenDiagonal/, 'feedback poster modal should default to the first Gemini template');
assert.match(source, /function drawFeedbackPoster\(/, 'feedback poster should draw fixed templates with canvas');
assert.match(source, /function openFeedbackPosterModal\(/, 'feedback poster should expose a modal entry');
assert.match(source, /function downloadFeedbackPoster\(/, 'feedback poster should expose a direct download action');
assert.match(fnBody('openFeedbackPosterModal'), /下载图片[\s\S]*分享图片/, 'feedback poster modal should separate local download from system share');
assert.match(fnBody('shareFeedbackPoster'), /AbortError/, 'cancelled share should not be treated as a generation failure');
assert.match(fnBody('shareFeedbackPoster'), /navigator\.clipboard[\s\S]*ClipboardItem[\s\S]*image\/png/s, 'desktop poster sharing should try writing the PNG into the clipboard before falling back to system share');
assert.match(fnBody('shareFeedbackPoster'), /try\{[\s\S]*navigator\.clipboard\.write[\s\S]*\}catch\(copyErr\)\{[\s\S]*navigator\.share/s, 'poster sharing should fall back to system share when clipboard image copy fails');
assert.match(styles, /::-webkit-scrollbar\{height:3px\}[\s\S]*max-height:58vh/, 'poster preview should fit the modal and use a thin horizontal scrollbar');
assert.match(fnBody('openFeedbackModal'), /生成海报/, 'saved feedback modal should show a poster entry');
assert.match(fnBody('openFeedbackModal'), /trialFieldsHtml/, 'trial conversion fields should be conditional');
assert.match(fnBody('openFeedbackModal'), /练习情况（非必填）/, 'feedback modal should rename knowledge point to practice status');
assert.match(fnBody('openFeedbackModal'), /体验课内部记录/, 'trial-only fields should be framed as internal notes');
assert.match(fnBody('openFeedbackModal'), /1\.0～1\.5[\s\S]*1\.5～2\.0[\s\S]*2\.0～2\.5[\s\S]*2\.5～3\.0[\s\S]*3\.0～3\.5[\s\S]*3\.5～4\.0/, 'trial level options should use the fixed numeric ladder');
assert.doesNotMatch(fnBody('openFeedbackModal'), /知识点（非必填）|体验课转化判断|零基础|初学|有基础|长期打球/, 'feedback modal should remove the old trial copy and level options');
assert.doesNotMatch(fnBody('openFeedbackModal'), /复制给学员/, 'feedback modal should not keep copy action after poster entry exists');
assert.doesNotMatch(fnBody('saveFeedback'), /openFeedbackPosterModal\(/, 'saving feedback should not force coach into poster generation');

console.log('schedule page view tests passed');
