const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: source } = require('./helpers/read-index-bundle');
const css = [
  'assets/styles/components/data-cards.css',
  'assets/styles/components/search.css',
  'assets/styles/components/buttons.css',
  'assets/styles/components/filters.css',
  'assets/styles/components/tables.css',
  'assets/styles/components/modals.css',
  'assets/styles/pages.css'
].filter(file=>fs.existsSync(path.join(__dirname, '../public', file))).map(file=>fs.readFileSync(path.join(__dirname, '../public', file), 'utf8')).join('\n');

function fnBody(name){
  const start = source.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = source.indexOf('\nfunction ', start + 1);
  const nextAsync = source.indexOf('\nasync function ', start + 1);
  const candidates = [nextFunction, nextAsync].filter(i => i !== -1);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return source.slice(start, next === -1 ? source.length : next);
}

assert.match(source, /function renderScheduleStudentSuggestions/, 'schedule modal should provide a dedicated student suggestion helper');
assert.match(source, /function scheduleSelectedStudentHomeCampusMeta/, 'schedule modal should derive the selected student home campus');
assert.match(source, /function scheduleStudentInlineMeta\([\s\S]*\$\{campus\}｜\$\{last\}上课/, 'schedule modal should show selected student home campus inline with the selected tag');
assert.doesNotMatch(source, /id="sch_homeCampusSummary"/, 'schedule modal should not show home campus as a separate row');
assert.match(source, /function syncScheduleHomeCampusFromStudents/, 'schedule modal should sync home campus after student selection changes');
assert.match(source, /function scheduleSelectedStudentCoachMeta/, 'schedule modal should derive the selected student primary coach');
assert.match(source, /function syncScheduleProfileFromStudents/, 'schedule modal should sync selected student coach and campus defaults');
assert.match(source, /setStandardDropdownValue\('sch_coach',selectedCoach,selectedCoach\)/, 'schedule modal should default coach from selected student profile');
assert.match(source, /上课校区/, 'schedule own-location field should be labelled as lesson campus, not student home campus');
assert.match(source, /校区内[\s\S]*校区外/, 'schedule location type copy should separate in-campus and off-campus lessons');
assert.match(source, /id="sch_stuSearch"/, 'schedule modal should provide a searchable student input');
assert.match(source, /id="sch_selectedStudentTags"/, 'schedule modal should show selected students as removable tags');
assert.doesNotMatch(source, /id="sch_stuName"[^>]*placeholder="选班次自动填入"/, 'schedule modal should not use free text student input as the formal selector');
assert.match(source, /function getFilteredStudents\(/, 'student page should centralize filtered student list calculation');
assert.match(source, /function onStudentFilterChange\(\)\{stuPage=standardListFirstPage\(\);renderStudents\(\);\}/, 'student filters should reset pagination through the standard list flow');
assert.match(source, /search:\{id:'stuSearch',oninput:'onStudentFilterChange\(\)'/, 'student search should reset pagination before rendering');
assert.match(source, /function renderStudentToolbarFilters\(/, 'student filters should render through the booking-style dropdown helper');
assert.match(source, /stuTypeFilterHost[\s\S]*onStudentFilterChange/, 'student type filter should reset pagination before rendering');
assert.match(source, /stuSourceFilterHost[\s\S]*onStudentFilterChange/, 'student source filter should reset pagination before rendering');
assert.match(source, /stuCoachFilterHost[\s\S]*onStudentFilterChange/, 'student primary coach filter should reset pagination before rendering');
assert.match(source, /function getStudentDuplicateCandidates\(/, 'student save flow should detect possible duplicates before submit');
assert.match(source, /发现可能重复的学员：/, 'student save flow should warn operators about possible duplicates');
assert.match(source, /const d=getFilteredStudents\(\);[\s\S]*a\.download='FlowTennis_学员_'\+today\(\)\+'.csv'/, 'student csv export should use current filtered result set');
assert.match(source, /stuCoachFilterHost/, 'student page should include primary coach filter host');
assert.match(source, /label:'全部',emptyDisplay:'负责教练'[\s\S]*未分配/, 'student filters should expose responsible coach options with all as the reset item');
assert.match(source, /总学员数[\s\S]*有课包学员数[\s\S]*体验课转化[\s\S]*课包实收[\s\S]*课包可用余额/, 'student top stats should use the requested five card labels');
assert.match(source, /有课包学员数 \/ 总学员数占比[\s\S]*体验课人数 vs 体验课转正人数[\s\S]*课包可用余额 \/ 课包实收占比/, 'student top stat cards should explain the requested formulas');
assert.match(source, /student-stat-divider/, 'student paired stat cards should render a vertical divider between the two values');
assert.match(source, /function studentPageStats\(/, 'student page should centralize top stat calculation');
assert.match(source, /aggregateHistoricalMonthlyLedgerRows\(dedupeEntitlementLedgerForDisplay\(entitlementLedger\)\)/, 'student package recognized amount should use the same net ledger rows as finance');
assert.match(source, /const sign=Number\(row\.lessonDelta\|\|0\)>0\?-1:1/, 'student package recognized amount should subtract returned lessons');
assert.match(source, /function studentStatsCampusNameForPurchase\(/, 'student top package finance stats should resolve campus from entitlement and purchase, not only student profile');
assert.match(source, /studentStatsMatchesPackageCampus\(p,entitlementByPurchaseId\.get\(String\(p\.id\|\|''\)\)\|\|\{\}\)/, 'student top package income should include purchases scoped by package campus');
assert.doesNotMatch(source, /const validEntitlements=entitlements\.filter\(e=>studentIds\.has\(String\(e\.studentId\|\|''\)\)&&entitlementStatusText\(e\)!=='已作废'\)/, 'student top package stats must not drop package-campus rows when the student campus is empty');
assert.match(source, /packageStudentCount:base\.filter\(s=>studentActiveEntitlementRows\(s\)\.length\)\.length/, 'student stats should summarize students with packages');
assert.match(source, /function studentStatusMeta\(/, 'student list should compute business status labels');
assert.match(source, /上课中[\s\S]*待转化[\s\S]*沉默30天[\s\S]*仅订场[\s\S]*无班次/, 'student status labels should cover the agreed business states');
assert.match(source, /function studentNoteSummary\(/, 'student list should compute compact ops-style note summary');
assert.match(source, /data-student-sort="lastLesson"[\s\S]*最近上课/, 'student table should sort by recent lesson');
assert.match(source, /data-student-sort="completedLessons"[\s\S]*累计上课/, 'student table should sort by cumulative lessons');
assert.match(source, /data-student-sort="packageLessons"[\s\S]*课时\/课包/, 'student table should sort by lesson/package balance');
assert.doesNotMatch(source, /<th[^>]*>当前班次<\/th>/, 'student table should hide the current class column');
assert.doesNotMatch(source, /<th[^>]*>订场\/会员<\/th>/, 'student table should hide the booking membership column');
assert.match(source, /columns:\[[\s\S]*\{label:'电话',style:'width:94px'\}[\s\S]*\{label:'类型',style:'width:58px'\}[\s\S]*\{label:'校区',style:'width:105px'\}[\s\S]*style:'width:140px'/, 'student table should widen phone and type columns enough to show their full text');
assert.match(source, /pager:\{infoId:'stuPagerInfo',pageSizeId:'stuPageSize',buttonsId:'stuPagerBtns'\}/, 'student pager should expose a page size selector host');
assert.match(source, /function setStudentPageSize\(/, 'student page should support 20, 50, and 100 row page sizes');
assert.match(source, /function renderStudentPagerControls\(/, 'student page should render compact pager controls');
assert.match(css, /#page-students \.tms-table-wrapper\{max-height:calc\(100vh - 210px\)\}/, 'student table should be taller on screen');
assert.match(source, /function renderStandardDataCards\(/, 'top data cards should have a shared render helper');
assert.match(source, /assets\/styles\/components\/data-cards\.css/, 'index should load shared data card styles');
assert.match(source, /assets\/styles\/components\/search\.css/, 'index should load shared search styles');
assert.match(source, /assets\/styles\/components\/buttons\.css/, 'index should load shared button styles');
assert.match(source, /assets\/styles\/components\/filters\.css/, 'index should load shared filter dropdown styles');
assert.match(source, /assets\/styles\/components\/tables\.css/, 'index should load shared table styles');
assert.match(source, /assets\/styles\/components\/modals\.css/, 'index should load shared modal styles');
assert.match(css, /\.modal\.modal-court\{[^}]*background:#F5F2F0[^}]*border-radius:16px[^}]*box-shadow:0 24px 48px -12px rgba\(0,0,0,\.18\)/, 'shared modal shell should use the standard surface, radius, and shadow');
assert.match(css, /\.modal\.modal-court\.modal-standard\{width:min\(560px,95vw\)\}/, 'standard business modals should use the 560px width');
assert.match(css, /\.modal\.modal-court\.modal-view\{width:min\(720px,95vw\)\}/, 'detail and audit modals should use the 720px width');
assert.match(css, /\.modal\.modal-court\.modal-complex\{width:min\(800px,95vw\)\}/, 'complex workflow modals should use the 800px width');
assert.match(css, /\.modal\.modal-court \.mhead\{[^}]*padding:28px 32px 16px/, 'shared modal header should use the standard padding');
assert.match(css, /\.modal\.modal-court \.mbody\{[^}]*padding:8px 32px/, 'shared modal body should use the standard padding');
assert.match(css, /\.modal\.modal-court \.mactions\{[^}]*padding:16px 32px[^}]*gap:12px[^}]*justify-content:flex-end[^}]*background:#F5F2F0[^}]*border-top:1px solid rgba\(230,225,220,\.6\)/, 'shared modal footer should use the standard action bar');
assert.match(css, /\.modal\.modal-court \.mclose\{[^}]*width:32px[^}]*height:32px[^}]*border-radius:50%[^}]*background:#FFFFFF/, 'shared modal close button should use the standard circular style');
assert.match(css, /\.modal\.modal-court \.tms-form-control\{[^}]*height:40px[^}]*border:1px solid #E6E1DC[^}]*background:#FFFFFF[^}]*color:#2D241F[^}]*font-size:14px[^}]*border-radius:8px/, 'shared modal form controls should use the standard input style');
assert.match(css, /\.modal\.modal-court \.tms-form-control:focus\{[^}]*border-color:#D19356[^}]*box-shadow:0 0 0 3px rgba\(209,147,86,\.15\)/, 'shared modal form controls should use the primary focus ring');
assert.match(css, /\.modal\.modal-court \.tms-data-field[\s\S]*\.modal\.modal-court \.tms-data-label[\s\S]*\.modal\.modal-court \.tms-data-value/, 'shared modal readonly data fields should have component styles');
assert.match(css, /\.tms-stats-row\{[^}]*display:grid[^}]*grid-template-columns:repeat\(auto-fit,minmax\(200px,1fr\)\)/, 'top data card row should adapt from five to six cards using 200px minimum columns');
assert.match(css, /\.tms-stat-card\{[^}]*height:100px[^}]*background-color:#FBF7F4[^}]*border:1px solid #E8DFD5[^}]*border-radius:8px/, 'top data cards should match the shared 200 by 100 visual standard');
assert.match(css, /\.tms-stat-card\{[^}]*padding:18px 16px 14px 22px/, 'top data cards should keep 22px left content padding');
assert.match(css, /\.tms-stat-card\{[^}]*box-shadow:0 8px 20px rgba\(0,0,0,\.08\)/, 'top data cards should use the shared shadow');
assert.match(css, /\.tms-stat-label\{[^}]*font-size:12px[^}]*color:#887565[^}]*margin-bottom:10px[^}]*font-weight:700/, 'top data card titles should use the shared label style');
assert.match(css, /\.tms-stat-value\{[^}]*font-size:21px[^}]*font-weight:700[^}]*color:#3B3026/, 'top data card numbers should use the shared value style');
assert.match(css, /\.tms-stat-percent,\s*\.court-stat-percent\{[^}]*font-size:10px[^}]*color:#A19080/, 'top data card percentages should use the shared small metric style');
assert.match(css, /\.tms-stat-sub\{[^}]*font-size:10px[^}]*color:#A19080[^}]*margin-top:8px/, 'top data card explanations should use the shared caption style');
assert.match(css, /#page-courts \.court-split-value>span:not\(\.court-stat-slash\)\{[^}]*color:#3B3026[^}]*font-weight:700/, 'court top paired stat numbers should keep the shared dark number color');
assert.match(css, /#page-finance \.finance-ledger-stats \.finance-main-number\{[^}]*color:#3B3026[^}]*font-weight:700/, 'finance top main stat numbers should keep the shared dark number color');
assert.match(css, /\.tms-search-wrapper\{[^}]*width:300px/, 'shared search component should use the standard 300px width');
assert.match(css, /\.tms-search-input\{[^}]*height:36px[^}]*border:1px solid #E8DFD5[^}]*background-color:#FBF7F4[^}]*color:#5A4C41[^}]*font-size:13px[^}]*font-weight:400/, 'shared search input should use the standard field style');
assert.match(css, /\.tms-search-input::placeholder\{[^}]*color:#A08E7E[^}]*font-size:13px[^}]*font-weight:400/, 'shared search placeholder should use the standard muted text style');
assert.match(css, /\.tms-search-icon\{[^}]*width:16px[^}]*height:16px[^}]*color:#A08E7E/, 'shared search icon should use the standard size and color');
assert.match(css, /\.tms-search-icon\{[^}]*M5\.77924 3\.57289[^}]*M11\.1648 7\.01855/, 'shared search icon should use the complete provided svg');
assert.doesNotMatch(source, /<svg class="tms-search-icon"[\s\S]*?<circle cx="11" cy="11" r="8">/, 'search fields should not keep old inline circle icons');
assert.match(css, /\.tms-toolbar-right \.tms-btn-primary\{[^}]*min-width:104px[^}]*width:auto[^}]*height:36px[^}]*padding:0 16px[^}]*background-color:#D19356[^}]*border-radius:6px[^}]*color:#FFFFFF[^}]*font-size:13px[^}]*font-weight:400/, 'toolbar add buttons should keep 104px as the four-character default and grow with longer text');
assert.match(css, /\.tms-toolbar-right \.tms-btn-primary::before\{[^}]*width:10px[^}]*height:10px/, 'toolbar add buttons should use the shared plus icon size');
assert.match(css, /\.tms-export-action,.tms-import-action\{[^}]*display:inline-flex[^}]*margin-right:10px[^}]*color:#F1E9E2[^}]*font-size:13px[^}]*font-weight:400/, 'toolbar export and import actions should use the shared text action style');
assert.match(css, /\.tms-export-action::before,.tms-import-action::before\{[^}]*width:16px[^}]*height:16px[^}]*background:url/, 'toolbar export and import actions should use the shared file icon');
assert.match(css, /\.tms-import-action::before\{transform:rotate\(180deg\)\}/, 'toolbar import icon should flip the shared export icon by 180 degrees');
assert.doesNotMatch(source, /id="page-students"[\s\S]*openPurchaseEntryModal\(\)[\s\S]*id="stuTbody"/, 'student page should remove the global package purchase entry');
assert.match(source, /class="tms-export-action" onclick="exportStudentCSV\(\)"[\s\S]*>导出<\/span>[\s\S]*class="tms-btn tms-btn-primary" onclick="openStudentModal/, 'student export should sit immediately before the add button as a shared text action');
assert.match(css, /\.tms-dropdown-display\{[^}]*height:36px[^}]*min-width:0[^}]*width:auto[^}]*padding:0 10px 0 12px[^}]*background-color:#FBF7F4[^}]*border:1px solid #E8DFD5[^}]*border-radius:6px[^}]*color:#A08E7E[^}]*font-size:13px[^}]*font-weight:400/, 'shared filter dropdown should use an adaptive width instead of a fixed 90px width');
assert.match(css, /\.tms-dropdown-display\{[^}]*display:inline-flex[^}]*align-items:center[^}]*gap:8px[^}]*line-height:36px/, 'shared filter dropdown should keep text vertically centered');
assert.match(css, /\.tms-dropdown-display::after\{[^}]*width:16px[^}]*height:16px[^}]*margin-left:0[^}]*transform:translateY\(-1px\)[^}]*background:url/, 'shared filter dropdown should vertically center the svg arrow icon');
assert.match(css, /\.tms-filters \.tms-dropdown\.has-value \.tms-dropdown-display\{[^}]*color:#C06031[^}]*font-weight:400/, 'selected filters should use the shared active state');
assert.match(css, /\.course-package-showcase-filters \.tms-dropdown\.has-value \.tms-dropdown-display\{[^}]*color:#C06031[^}]*font-weight:400/, 'course package filters should reuse the shared active state');
assert.match(css, /\.tms-pagination\{[^}]*font-size:12px[^}]*line-height:16px[^}]*color:#78716C/, 'shared pager footer should use the new 12px stone standard');
assert.match(css, /\.pager-divider\{[^}]*width:1px[^}]*height:12px[^}]*background:#E7E5E4[^}]*margin:0 12px/, 'pager footer should use the standard vertical divider before the page-size dropdown');
assert.match(css, /\.tms-pagination \.tms-dropdown-display\{[^}]*padding:2px 6px[^}]*border-radius:4px[^}]*color:#44403C[^}]*font-weight:500[^}]*transition:all 150ms ease/, 'page-size trigger should match the compact custom trigger standard');
assert.match(css, /\.tms-pagination \.tms-dropdown-menu\{[^}]*bottom:calc\(100% \+ 6px\)[^}]*width:72px[^}]*background:rgba\(242,242,247,\.95\)[^}]*backdrop-filter:blur\(24px\)[^}]*box-shadow:0 8px 24px rgba\(0,0,0,\.12\)/, 'page-size popover should match the apple-like floating panel standard');
assert.match(css, /\.tms-pagination \.tms-dropdown\.open \.tms-dropdown-menu\{[^}]*animation:tmsPagerMenuIn 100ms ease/, 'page-size popover should fade and zoom in');
assert.match(css, /\.tms-pagination \.tms-dropdown-item\{[^}]*padding:6px 8px[^}]*font-size:12px[^}]*color:#292524/, 'page-size menu items should use the compact menu item standard');
assert.match(css, /\.tms-pagination \.tms-dropdown-check svg\{[^}]*width:14px[^}]*height:14px[^}]*stroke-width:3/, 'selected page-size item should render the heavier checkmark svg');
assert.match(css, /\.tms-page-btn\{[^}]*min-width:24px[^}]*height:24px[^}]*font-weight:500[^}]*border-radius:6px[^}]*color:#57534E/, 'shared page buttons should use the new compact page button standard');
assert.match(css, /\.tms-page-btn\.active\{[^}]*background-color:#8C6D53[^}]*color:#FFFFFF[^}]*box-shadow:0 1px 2px rgba\(0,0,0,\.08\)/, 'active page button should use the brand color and subtle shadow');
assert.match(source, /class="tms-dropdown-check"[\s\S]*stroke-width="3"/, 'custom dropdown should render the selected checkmark through the shared component');
assert.match(source, /function renderPagerInfoHtml\(total\)\{\s*return `共 \$\{Number\(total\)\|\|0\} 条`;\s*\}/, 'pager info should keep total number the same style as surrounding text');
assert.doesNotMatch(source, /pager-strong/, 'pager info should not emphasize total count');
assert.match(source, /function renderPageSizeSelectorHtml\(id,pageSize,onchange\)[\s\S]*pager-divider[\s\S]*每页[\s\S]*renderStandardDropdownHtml\(id,String\(pageSize\),\[\{value:'20',label:'20'\},\{value:'50',label:'50'\},\{value:'100',label:'100'\}\][\s\S]*条/, 'pager page-size control should render text around a numeric-only dropdown');
assert.match(css, /\.tms-page-chevron\{[^}]*width:14px[^}]*height:14px[^}]*mask:url\("data:image\/svg\+xml/, 'pager arrows should use the filter chevron glyph at 14px');
assert.match(css, /\.tms-page-chevron-prev\{transform:rotate\(90deg\)\}[\s\S]*\.tms-page-chevron-next\{transform:rotate\(-90deg\)\}/, 'pager arrows should rotate the filter chevron left and right');
assert.doesNotMatch(source, /跳至 <input/, 'pager should not render jump-to-page controls');
assert.match(css, /\.tms-pagination \.tms-dropdown\.has-value \.tms-dropdown-display\{[^}]*font-weight:500/, 'student selected pager dropdown should use the new medium trigger weight');
assert.match(css, /\.tms-dropdown\.has-value \.tms-dropdown-display/, 'selected filters should look different from the default all state');
assert.doesNotMatch(css, /#page-students \.tms-filters \.tms-dropdown\.has-value \.tms-dropdown-display\{color:#C06031;font-weight:400\}/, 'student filter active state should come from the shared filter component');
assert.match(css, /\.tms-table-card\{[^}]*background-color:#E7DFD6[^}]*border:1px solid #E8DFD5[^}]*border-radius:8px/, 'shared table shell should use the standard border and radius');
assert.match(css, /\.tms-table-wrapper\{[^}]*background:#FBF7F4/, 'shared table scroll wrapper should mask the old card background behind sticky headers');
assert.match(css, /\.tms-table thead\{[^}]*position:sticky[^}]*top:0[^}]*z-index:130[^}]*background:#F1E9E2/, 'shared table header should stick as a full header layer while scrolling');
assert.match(css, /\.tms-table th\{[^}]*height:42px[^}]*background-color:#F1E9E2[^}]*color:#887565[^}]*font-size:12px[^}]*font-weight:400/, 'shared table header should use the standard size and color');
assert.match(css, /\.tms-table td\{[^}]*height:42px[^}]*background-color:#FBF7F4[^}]*color:#887565[^}]*font-size:12px[^}]*font-weight:400/, 'shared table rows should use the standard size and color');
assert.match(css, /\.tms-table th,.tms-table td\{[^}]*border-bottom:0\.5px solid #E7DFD6/, 'shared table separators should use the standard 0.5px line');
assert.match(css, /\.tms-table tbody tr:hover td\{[^}]*background-color:#F6EFE8/, 'shared table hover should use the standard hover color');
assert.match(css, /\.tms-table tbody tr\.is-selected td\{[^}]*background-color:#EFE7E2/, 'shared table selected rows should use the standard selected color');
assert.match(css, /\.tms-action-cell \.tms-action-link\+\.tms-action-link\{margin-left:10px\}/, 'shared table action links should keep 10px spacing');
assert.match(css, /\.tms-mini-bar\{[^}]*width:80px[^}]*height:16px/, 'shared mini progress bar should use the standard size');
assert.match(css, /\.tms-mini-bar-fill\{[^}]*background-color:#DFBAA0[^}]*border-radius:3px 0 0 3px/, 'shared mini progress fill should use the standard color and left radius');
assert.match(css, /\.tms-sort-icon\{[^}]*width:14px[^}]*height:14px/, 'shared sort icon should use the standard 14px size');
assert.match(css, /\.tms-sort-icon \.tms-sort-up::before\{[^}]*M7\.19619 2\.9702[^}]*background-color:#BDAB9B/, 'shared sort icon should use the provided svg path');
assert.match(css, /\.tms-sort-header\.asc \.tms-sort-up::before\{background-color:#887565\}/, 'ascending sort should highlight only the upper half');
assert.match(css, /\.tms-sort-header\.desc \.tms-sort-down::before\{background-color:#887565\}/, 'descending sort should highlight only the lower half');
assert.doesNotMatch(css, /\.tms-sort-up[^{}]*\{[^}]*border-bottom:4px solid/, 'shared sort icon should not use the old css triangle');
assert.match(source, /function cycleStudentSort\([\s\S]*stuSortDir='asc'[\s\S]*stuSortDir='desc'[\s\S]*stuSortKey='';stuSortDir='';/, 'student sortable headers should cycle asc, desc, and no sort');
assert.match(source, /function studentEmptyStateHtml\([\s\S]*没有匹配的学员[\s\S]*暂无学员[\s\S]*调整搜索或筛选后再试[\s\S]*点击右上角添加学员开始录入/, 'student empty state should distinguish filtered empty results from no data');
assert.match(source, /function renderTableSkeletonLoading\(/, 'table loading should render through the shared full-table skeleton helper');
assert.match(source, /function renderStudentTableLoading\([\s\S]*renderTableSkeletonLoading\('stuTbody',11,'学员数据加载中\.\.\.'\)/, 'student loading state should use the shared full-table skeleton');
assert.match(css, /\.tms-table-skeleton-state\{[^}]*position:absolute[^}]*inset:0[^}]*background:#FBF7F4/, 'shared table skeleton should cover the whole table area');
assert.match(css, /\.tms-table-skeleton-head\{[^}]*height:42px[^}]*background:#F1E9E2/, 'shared table skeleton should include a header skeleton instead of leaving the real header exposed');
assert.match(css, /\.tms-table-skeleton-row\{[^}]*height:42px[^}]*background:#FBF7F4/, 'shared table skeleton rows should match the standard row height');
assert.match(source, /function renderStudentTableError\([\s\S]*tms-table-error-state[\s\S]*加载失败[\s\S]*重新加载/, 'student load failure should render an inline retry state');
assert.match(source, /if\(pg==='students'\)renderStudentTableLoading\(\);/, 'student page should use the dedicated loading renderer');
assert.match(source, /if\(pg==='students'\)renderStudentTableError\(String\(e\.message\|\|e\)\);/, 'student page load failure should render the dedicated error state');
assert.match(css, /#page-students \.tms-empty-state\{[\s\S]*#page-students \.tms-state-action/, 'student empty, loading, and error states should have scoped standard styles');
assert.match(source, /function studentCompletedLessonCount\(/, 'student page should expose a cumulative completed lesson helper');
assert.match(source, /studentCompletedLessonCount\(s\)/, 'student list should render cumulative completed lessons');
assert.match(source, /function scheduleLessonUnits\(/, 'lesson stats should use schedule lesson units instead of row counts');
assert.match(source, /stuSortKey='lastLesson',stuSortDir='desc'/, 'student list should default to latest lesson descending');
assert.match(source, /function studentLastLessonDate[\s\S]*effectiveScheduleStatus\(x\)==='已结束'/, 'student latest lesson date should use completed lessons');
assert.match(source, /function scheduleDurationLessonUnits[\s\S]*Math\.round\(\(mins\/60\)\*10\)\/10/, 'web lesson units should derive a precise duration fallback from start and end time');
assert.match(source, /function scheduleLessonUnits[\s\S]*Math\.max\(count,durationUnits\)/, 'web lesson units should not let a stale lower lessonCount override a longer real lesson duration');
assert.match(source, /function studentLedgerLessonUnits[\s\S]*Math\.max\(consumed,planned\)/, 'web student lesson totals should not let stale package ledger units undercount the linked schedule duration');
assert.match(source, /studentCompletedLessonUnits[\s\S]*studentLedgerLessonUnits\(row,schedule\)/, 'web student cumulative lesson count should normalize package ledger lesson units');
assert.match(source, /function studentLedgerConsumedText\([\s\S]*packageBalanceUnitLabel[\s\S]*studentLessonDurationText[\s\S]*join\(' · '\)/, 'student lesson records should show count-based package consumption as count plus real lesson duration');
assert.match(source, /function studentLessonRecordKey\(/, 'student cumulative lessons should share one lesson identity key');
assert.match(source, /function studentCompletedLessonUnits[\s\S]*const lessonMap=new Map\(\)[\s\S]*studentConcreteLessonLedgerItems\(stu\)[\s\S]*studentLessonRecordShouldIncludeSchedule[\s\S]*return \[\.\.\.lessonMap\.values\(\)\]\.reduce/, 'student cumulative lessons should merge schedule and package consume records by lesson identity');
assert.match(source, /function studentPrimaryCoachText\(/, 'student list should render primary coach from the profile field');
assert.match(source, /studentPrimaryCoachText\(s\)/, 'student list coach column should use the profile primary coach');
assert.match(source, /未分配/, 'empty primary coach should display 未分配');
assert.match(source, /const SOURCES=\['转介绍','小红书','大众点评','视频号','抖音','播客','孙老师','直接线下到电','群友','小班课转化','开业活动期间','其他'\]/, 'student source options should keep the unified ops order');
assert.match(source, /function renderStandardCellText[\s\S]*const muted=!raw\|\|raw==='-'\|\|raw==='—'\|\|raw==='未开卡'/, 'empty list values should always render with the muted dash style');
assert.match(source, /function renderStandardEmptyText[\s\S]*return raw&&raw!=='—'\?raw:'-'/, 'empty values should render with the short dash');
assert.doesNotMatch(source, /<th>最后订场<\/th>/, 'student table should remove last-court as a primary list column in phase 2');
assert.doesNotMatch(source, /<th>关联账户<\/th>/, 'student table should replace account wording with booking membership summary');
assert.match(source, /style:'width:90px',html:'<button class="tms-sort-header" data-student-sort="packageLessons"[\s\S]*课时\/课包/, 'student package lesson column should be labelled lesson/package');
assert.match(source, /function studentPackageLessonMeta\(/, 'student package lesson summary should expose remaining and total lessons');
assert.match(source, /function studentActiveEntitlementRows\([\s\S]*includes\(entitlementStatusText\(e\)\)[\s\S]*lessonValue\(e\.totalLessons\)>0/, 'student lesson/package summary should keep normal packages even when balance is 0');
assert.match(source, /function studentPackageLessonSummary\([\s\S]*`\$\{lessonQty\(e\.remainingLessons\)\}\/\$\{lessonQty\(e\.totalLessons\)\}`[\s\S]*\|\|meta\.text/, 'student lesson/package summary should show only balance numbers, not package names');
assert.match(source, /function studentPackageLessonMiniBar\(/, 'student package lesson column should render the same mini balance bar as booking accounts');
assert.match(source, /studentPackageLessonMiniBar\(s\)/, 'student list should render package lessons through the mini balance bar');
assert.match(source, /\$\{lessonQty\(remaining\)\}\/\$\{lessonQty\(total\)\}/, 'student package lesson text should use remaining over total lesson count without truncating half lessons');
assert.match(source, /function openStudentDetail\(/, 'student list should provide a dedicated view action');
assert.match(fnBody('renderStudents'), /openStudentDetail\('\$\{s\.id\}'\)[\s\S]*openPurchaseModal\('\$\{s\.id\}'\)/, 'student list should keep only view and package actions');
assert.doesNotMatch(fnBody('renderStudents'), /openStudentModal\('\$\{s\.id\}'\)/, 'student list should not expose inline edit action');
assert.match(source, /modalClass:'modal modal-court modal-schedule-drawer modal-student-drawer'/, 'student detail should use the standard drawer shell');
assert.match(source, /renderDetailDrawerHero\(/, 'student detail should use a clearer header layout');
assert.match(source, /student-detail-metrics/, 'student detail should use summary metric cards');
assert.match(source, /function studentBenefitRows\(/, 'student detail should derive student benefit rows separately from package lessons');
assert.match(source, /studentDrawerCardHtml\('权益列表',studentBenefitListTableHtml\(s\),'student-benefit-section'/, 'student detail should show current benefits in the benefits tab');
assert.match(source, /openStudentBenefitPickerModal\('\$\{s\.id\}','supplement'\)[\s\S]*openStudentBenefitPickerModal\('\$\{s\.id\}','consume'\)/, 'student detail benefits tab should expose supplement and consume benefit actions');
assert.match(source, /const STUDENT_BENEFIT_TYPES=\[[\s\S]*benefitCode:'courtBooking'[\s\S]*benefitCode:'ballMachine'[\s\S]*\]/, 'student benefit actions should only support booking and ball-machine benefits');
assert.match(source, /student-package-card/, 'student detail should render package purchases as cards');
assert.match(source, /student-package-icon-svg/, 'student detail should use a folder-style package icon');
assert.match(source, /student-lesson-timeline/, 'student detail should render lesson records as a timeline');
assert.match(source, /student-reminder-section/, 'student detail should render reminder preferences in a compact block');
assert.match(source, /titleHtml:`服务号提醒偏好<span class="tms-tag \$\{statusClass\}">/, 'student detail should keep the reminder title row compact');
assert.doesNotMatch(source, /studentDetailSectionBlockHtml\('服务号提醒偏好'/, 'student detail should not wrap the reminder block with an extra section title');
assert.doesNotMatch(source, /student-reminder-status/, 'student detail should not show a redundant reminder status line');
assert.match(source, /openStandardDetailDrawer\(/, 'student detail should use the standard detail drawer');
assert.match(source, /openStudentDrawer\(\{titleHtml:`\$\{studentDetailHeroHtml\(s\)\}\$\{studentDetailTabsHtml\(studentDetailActiveTab\)\}`/, 'student detail should move the profile summary into the drawer header');
assert.match(source, /服务号上课提醒/, 'student detail should expose the official account lesson reminder block');
assert.match(source, /复制绑定链接/, 'student detail should let ops copy a student-specific binding link');
assert.match(source, /name="studentReminderMode"/, 'student detail reminder frequency should use single-choice controls instead of loose action buttons');
assert.match(source, /48小时 \+ 24小时[\s\S]*仅24小时[\s\S]*自定义[\s\S]*不提醒/, 'student detail should expose standard, custom and off reminder frequency modes');
assert.match(source, /studentReminderCustomHours/, 'student detail should let ops set custom reminder hours');
assert.match(source, /复制绑定链接/, 'student detail should make copy binding link the primary action');
assert.match(source, /generateStudentReminderBindLink/, 'student page should call the backend to generate a bind link');
assert.match(source, /updateStudentReminderMode/, 'student page should let ops update student reminder frequency');
assert.match(source, /unbindStudentReminder/, 'student page should let ops unbind a student service account recipient');
assert.match(source, /officialAccountSubscribed/, 'student reminder bind page should read the service account subscribe status');
assert.match(source, /qrcode_for_gh_4c6b1a2fe3a9_258\.jpg/, 'student reminder bind page should show the official account QR code when follow is still needed');
assert.match(source, /你已关注「网球兄弟」服务号/, 'student reminder bind page should tell subscribed users they can close the page');
assert.match(source, /关注后无需重新绑定/, 'student reminder bind page should tell unsubscribed users to follow without rebinding');
assert.match(source, /这条链接已经完成绑定/, 'student reminder bind page should explain reused links in user-facing language');
assert.match(fnBody('renderStudents'), /openStudentDetail\('\$\{s\.id\}'\)[\s\S]*openPurchaseModal\('\$\{s\.id\}'\)/, 'student row should prioritize view before package purchase');
assert.doesNotMatch(fnBody('renderStudents'), /openStudentModal\('\$\{s\.id\}'\)/, 'student row should not expose inline edit');
assert.match(source, /function studentTeachingInfoHtml\(/, 'student detail should render teaching info block');
assert.match(source, /function studentOpsInfoHtml\(/, 'student detail should render operations info block');
assert.match(source, /function studentConsumptionInfoHtml\(/, 'student detail should render consumption relation block');
assert.match(source, /function studentLessonRecordHtml\(/, 'student detail should expose a dedicated lesson record helper');
assert.match(source, /function studentEntitlementLedgerHtml\(/, 'student detail should provide a dedicated lesson charge history helper');
assert.match(source, /function entitlementLedgerDisplayDate\(/, 'lesson charge history should display the real lesson or month date instead of import time');
assert.match(source, /function historicalImportedLedgerMonthKey\(/, 'lesson charge history should infer monthly import identity from sourceMonth or reason text');
assert.match(source, /reason\.match\(\s*\/\^历史导入\\s\*\(\\d\{1,2\}\)月消课\$\/\s*\)/, 'lesson charge history should fall back to parsing month from reason text when sourceMonth is missing');
assert.match(source, /dedupeEntitlementLedgerForDisplay/, 'lesson charge history should collapse duplicate ledger rows before display');
assert.match(source, /function historicalImportedLessonUnitsForStudent\(/, 'student page should expose a historical imported lesson helper');
assert.match(source, /STUDENT_PAGE_DEFERRED_REQUIREMENTS=\['entitlements','entitlementLedger','feedbacks','products','purchasesPage','membershipBenefitLedger'\]/, 'student detail should load package consume ledger, purchase amount data, and student benefits');
assert.doesNotMatch(source, /function studentEntitlementLedgerHtml[\s\S]*aggregateHistoricalMonthlyLedgerRows[\s\S]*function classScheduleSummaryHtml/, 'student consume history should show imported lesson rows one by one instead of monthly aggregation');
assert.match(source, /studentCompletedLessonCount[\s\S]*historicalImportedLessonUnitsForStudent/, 'student cumulative lessons should include imported lesson consumption');
assert.match(source, /教学信息[\s\S]*消费与关联信息/, 'student detail should keep the teaching and consumption sections');
assert.match(source, /function studentDetailFieldHtml\(/, 'student detail should render short readonly values without form inputs');
assert.match(source, /function studentDetailFieldHtml\(label,value\)\{[\s\S]*return renderDetailDrawerField\(label,value\)/, 'student detail readonly fields should use the shared detail drawer field helper');
assert.match(source, /function studentDetailBlockHtml\(/, 'student detail should render long readonly content as information blocks');
assert.match(source, /function studentDetailBlockHtml\(label,html,options=\{\}\)[\s\S]*return renderDetailDrawerBlock\(label,html\)/, 'student detail long readonly blocks should use the shared detail drawer block helper');
assert.doesNotMatch(source, /function openStudentDetail[\s\S]*<input[\s\S]*function openStudentModal/, 'student detail modal should not use input controls for readonly values');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*<input[\s\S]*function studentOpsInfoHtml/, 'student teaching detail should not look editable');
assert.doesNotMatch(source, /function studentOpsInfoHtml[\s\S]*<input[\s\S]*function studentConsumptionInfoHtml/, 'student ops detail should not look editable');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*<input[\s\S]*function studentLinkedDetailHtml/, 'student consumption detail should not look editable');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*最近订场[\s\S]*function studentLinkedDetailHtml/, 'student consumption detail should remove duplicated recent booking field');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*关联说明[\s\S]*function studentLinkedDetailHtml/, 'student consumption detail should remove unclear duplicate linked account explanation');
assert.match(css, /\.modal\.modal-court \.tms-detail-grid[\s\S]*\.modal\.modal-court \.tms-detail-value[\s\S]*\.modal\.modal-court \.tms-detail-block/, 'student detail should use dedicated readonly display styles');
assert.match(css, /\.modal\.modal-court\.modal-student-drawer \.student-detail-shell\{[^}]*display:flex[^}]*flex-direction:column/, 'student detail header should sit inside the standard drawer');
assert.match(css, /\.modal\.modal-court\.modal-student-drawer \.student-detail-tabs\{[^}]*display:flex/, 'student detail should render tabs in the drawer title area');
assert.match(css, /\.student-package-icon\{[^}]*background:transparent/, 'student detail package icon should be a bare folder glyph');
assert.match(css, /\.student-reminder-section \.student-reminder-options\{[^}]*max-width:none/, 'student reminder options should use the compact drawer layout');
assert.match(css, /\.student-reminder-section \.student-reminder-copy-btn span\{font-size:13px;font-weight:400/, 'student reminder copy button should use a smaller label');
assert.match(css, /\.student-lesson-title\{[^}]*font-size:13px/, 'student lesson title should stay compact');
assert.match(css, /\.student-lesson-charge strong\{[^}]*font-size:12px[^}]*background:transparent/, 'student lesson charge badge should stay compact and unboxed');
assert.match(source, /function studentDetailBlockHtml\(label,html,options=\{\}\)[\s\S]*options\.hideEmpty&&studentDetailIsEmptyHtml\(html\)/, 'student detail should hide empty long blocks when they add no information');
assert.match(css, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-block\{[^}]*background:#FBFCFE/, 'student detail long content should use the drawer detail block style');
assert.match(source, /const leadHtml=studentDetailBlockHtml\('线索摘要',studentLeadSummaryHtml\(s\),\{hideEmpty:true\}\);[\s\S]*leadHtml\?/, 'student detail should hide the linked lead section when there is no lead');
assert.match(source, /function studentDetailSectionHtml\(/, 'student detail should hide whole empty sections');
assert.doesNotMatch(source, /function studentOpsInfoHtml[\s\S]*最近活跃[\s\S]*function studentConsumptionInfoHtml/, 'student ops detail should remove duplicated recent active field');
assert.doesNotMatch(source, /function studentOpsInfoHtml[\s\S]*最近订场[\s\S]*function studentConsumptionInfoHtml/, 'student ops detail should remove recent booking from ops fields');
assert.match(source, /function studentConsumptionInfoHtml[\s\S]*const linkedFields=linkedCourts\.length\?[\s\S]*:\s*''/, 'student consumption detail should only show linked account fields when linked data exists');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*studentDetailFieldHtml\('订场 \/ 会员'/, 'student consumption detail should not show unlinked booking membership field');
assert.match(source, /function studentLessonRecordTimeText\([\s\S]*slice\(11,16\)[\s\S]*-\$\{end\}/, 'student lesson records should show start and end time');
assert.match(source, /function studentLessonRecordRows\([\s\S]*studentConcreteLessonLedgerItems\(stu\)[\s\S]*studentLessonRecordKey\(\{studentId:stu\?\.id,row,schedule\}\)/, 'student lesson records should merge schedule rows and package consume rows by one lesson identity');
assert.match(source, /function studentLessonRecordHasConcreteTime\([\s\S]*sourceTimeBand[\s\S]*scheduleTime[\s\S]*function studentLessonRecordExpanded/, 'student lesson records should hide historical package summary rows that have no concrete time');
assert.match(source, /function studentConcreteLessonLedgerItems\([\s\S]*studentLessonRecordHasConcreteTime\(item\.row,item\.schedule\)/, 'student lesson record rows should only include package ledger rows with a concrete lesson time');
assert.match(source, /function studentLessonRecordShouldIncludeSchedule\([\s\S]*hasConcretePackageLedger[\s\S]*scheduleCourseType\(schedule\)==='体验课'/, 'student lesson records should not mix unmatched private schedule rows into package ledger records');
assert.match(source, /function studentLedgerBalanceAfter\([\s\S]*laterDelta[\s\S]*Number\(ent\.remainingLessons\)[\s\S]*packageBalanceUnitLabel[\s\S]*return `剩余 \$\{lessonQty\(balance\)\}\/\$\{lessonQty\(ent\.totalLessons\)\} \$\{unit\}`/, 'student lesson records should show the package balance after that specific lesson, not the final balance on every row');
assert.match(source, /function studentLedgerBalanceAfter\([\s\S]*currentTime=studentEntitlementLedgerTimeText[\s\S]*studentEntitlementLedgerTimeText\(item,findScheduleForEntitlementLedgerRow/, 'student lesson record balances should compare concrete lesson times so same-day lessons do not share one balance');
assert.match(source, /function studentLessonRecordPackageText\([\s\S]*standardPackageLabel[\s\S]*扣\$\{studentLedgerConsumedText\(row,ent,schedule\)\}[\s\S]*studentLedgerBalanceAfter\(row,ent\)/, 'student lesson record package rows should show deduct amount, real duration, per-lesson balance, and package name');
assert.match(source, /function studentLessonRecordSectionText\([\s\S]*studentLessonSectionMarker[\s\S]*packageBalanceUnitLabel[\s\S]*第\$\{startText\}\$\{startText===endText\?'':`-\$\{endText\}`\}\$\{unit\}/, 'student lesson record rows should show whole and half lesson section numbers with the package unit');
assert.match(source, /function studentLessonRecordChargeHtml\([\s\S]*免费送课[\s\S]*扣\$\{studentLedgerConsumedText\(row,ent,schedule\)\}/, 'student lesson records should show free lessons without deducting package balance');
assert.match(source, /function studentLessonRecordChargeHtml\([\s\S]*<strong>扣\$\{studentLedgerConsumedText\(row,ent,schedule\)\}（\$\{lessonQty\(balance\?\.remaining\)\}\/\$\{lessonQty\(balance\?\.total\)\}\$\{unit\}）<\/strong>/, 'student lesson record package rows should bold deduct lessons and balance');
assert.match(source, /function studentCumulativeLessonSectionText\([\s\S]*studentEntitlementLedgerRows\(\{id:studentId\}\)[\s\S]*Number\(item\.lessonDelta\)<0[\s\S]*earlierDelta[\s\S]*function studentLessonRecordSectionText\([\s\S]*studentCumulativeLessonSectionText\(row,ent\)/, 'student lesson record section numbers should continue across multiple packages for the same student');
assert.match(source, /function studentLessonRecordRows\([\s\S]*existing\?\.type==='ledger'[\s\S]*lessonDelta:\(Number\(existing\.row\.lessonDelta\)\|\|0\)\+\(Number\(row\.lessonDelta\)\|\|0\)[\s\S]*function studentLedgerPreferredDisplayEntitlement/, 'student lesson record rows should merge split package deductions for one lesson into one display line');
assert.match(source, /function studentLessonRecordMergeKey\([\s\S]*relatedDate[\s\S]*sourceVenue[\s\S]*return \[studentId[\s\S]*function studentLessonRecordRows\([\s\S]*studentLessonRecordMergeKey\(\{studentId:stu\?\.id,row,schedule\}\)/, 'student lesson records should merge same-day same-court continuous package deductions into one display line');
assert.match(source, /function studentEntitlementSummaryHtml\([\s\S]*packageBalanceUnitLabel[\s\S]*student-package-card[\s\S]*报名[\s\S]*应付\$\{fmt\(systemAmount\)\} · 实付\$\{fmt\(paidAmount\)\}[\s\S]*\$\{esc\(renderStandardEmptyText\(ownerCoach\)\)\}[\s\S]*<strong>已扣 \$\{lessonQty\(used\)\}\$\{unit\}（\$\{lessonQty\(remaining\)\}\/\$\{lessonQty\(total\)\}\$\{unit\}）<\/strong>/, 'student package purchase records should show signup, price, owner, and bold used balance with the package unit');
assert.match(source, /function studentLessonRecordHtml\([\s\S]*studentLessonRecordRows\(stu\)[\s\S]*studentLessonRecordPackageHtml[\s\S]*student-lesson-row[\s\S]*rows\.length>10[\s\S]*收起[\s\S]*展开全部/, 'student lesson record list should use package-record style rows and support expand all');
assert.match(source, /function toggleStudentLessonRecordExpanded\(studentId\)[\s\S]*openStudentDetail\(studentId\)/, 'student lesson record expand toggle should refresh the open detail modal');
assert.doesNotMatch(source, /studentDetailBlockHtml\('课包消耗记录'/, 'student detail should not render a second package consume list');
assert.doesNotMatch(source, /function studentEntitlementSummaryHtml[\s\S]*badge b-amber[\s\S]*function studentEntitlementPurchaseDate/, 'student package records should render course type as normal text');
assert.match(source, /function studentEntitlementSummaryHtml\([\s\S]*e\.studentId===stu\?\.id[\s\S]*entitlementStatusText\(e\)!=='已作废'/, 'student purchase records should keep real purchases but hide voided package rows');
assert.match(source, /function packageStatusText\([\s\S]*\['voided','已作废','作废'\]\.includes\(status\)/, 'student purchase records should treat Chinese voided status as voided too');
assert.match(source, /function studentEntitlementSummaryHtml\([\s\S]*purchaseStatusText\(purchases\.find\(p=>p\.id===e\.purchaseId\)\|\|\{\}\)!=='已作废'/, 'student purchase records should hide rows whose linked purchase is voided');
assert.match(source, /function studentEntitlementLedgerRows\(stu\)\{[\s\S]*entitlementStatusText\(e\)!=='已作废'[\s\S]*purchaseStatusText\(purchases\.find\(p=>p\.id===e\.purchaseId\)\|\|\{\}\)!=='已作废'/, 'student lesson records should ignore ledger rows from voided entitlements or purchases');
assert.match(source, /function studentEntitlementSummaryHtml[\s\S]*student-package-meta[\s\S]*应付\$\{fmt\(systemAmount\)\} · 实付\$\{fmt\(paidAmount\)\}/, 'student package records should keep compact middle-dot price text');
assert.match(source, /function studentEntitlementLedgerLineHtml\([\s\S]*studentEntitlementLedgerDeltaText\(row,ent,schedule\)[\s\S]*join\(' · '\)/, 'student package consume records should render one compact middle-dot line with signed lesson count');
assert.match(source, /function studentEntitlementLedgerTimeText\([\s\S]*\$\{date\} \$\{start\}-\$\{end\}/, 'student package consume records should show a lesson time range when available');
assert.match(source, /function findScheduleForEntitlementLedgerRow\([\s\S]*String\(s\.startTime\|\|''\)\.slice\(0,10\)!==date[\s\S]*function studentEntitlementLedgerLineHtml[\s\S]*studentEntitlementLedgerTimeText\(row,schedule\)/, 'student package consume records should use same-day schedule to fill missing start-end time');
assert.match(source, /function studentEntitlementLedgerSourceText\([\s\S]*sourceSheet[\s\S]*导入/, 'student package consume records should show the import source in the compact line');
assert.doesNotMatch(source, /function studentEntitlementLedgerHtml[\s\S]*扣减 \$\{lessonQty\(count\)\} 节[\s\S]*function classScheduleSummaryHtml/, 'student package consume records should not use the old two-line charge wording');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*当前状态[\s\S]*function studentOpsInfoHtml/, 'student detail should remove current status');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*当前班次[\s\S]*function studentOpsInfoHtml/, 'student detail should remove current class');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*班次进度[\s\S]*function studentOpsInfoHtml/, 'student detail should remove class progress');
assert.match(source, /上课记录/, 'student detail should provide lesson record history in plain language');
assert.match(source, /已购课包/, 'student detail should present purchased packages in plain language');
assert.match(source, /扣课记录/, 'student detail should expose lesson charge history in the student detail');
assert.match(source, /课包订单/, 'student detail should label package purchase records clearly');
assert.doesNotMatch(source, /课包消耗记录/, 'student detail should avoid a duplicate package consume record block');
assert.match(source, /关联订场账户在「订场\/会员」页面编辑用户时选择「关联学员」/, 'student detail should explain where to link booking accounts');
assert.doesNotMatch(source, /function openStudentModal[\s\S]*studentLinkedDetailHtml\(s\)/, 'student edit modal should not embed linked detail summary anymore');
assert.match(source, /function studentBasicInfoFormHtml[\s\S]*姓名 \*[\s\S]*手机号[\s\S]*负责教练[\s\S]*学员类型[\s\S]*来源[\s\S]*活动范围[\s\S]*所在校区[\s\S]*备注/, 'student edit modal should keep base profile fields and expose primary coach');
assert.doesNotMatch(source, /placeholder="13800138000"/, 'phone inputs should not show example numbers that look prefilled');
assert.match(source, /const campusOptions=studentCampusOptions\(\);/, 'student edit modal should build campus options through the shared student helper');
assert.match(source, /function studentCampusOptions\(/, 'student edit modal should expose all loaded campuses through a helper');
assert.match(source, /renderStandardDropdownHtml\('s_primaryCoach'/, 'student edit modal should provide a primary coach selector');
assert.match(source, /const data=\{name,phone,primaryCoach:/, 'student save should submit primary coach');
assert.match(source, /function openStudentModal[\s\S]*openStudentDrawer\(/, 'student edit modal should reuse the standard student drawer');
assert.doesNotMatch(source, /function openStudentModal[\s\S]*setCourtModalFrame\(/, 'student add and edit modals should not use legacy modal shell');
assert.match(source, /选择课包 \*[\s\S]*归属教练[\s\S]*支付日期[\s\S]*系统价格[\s\S]*实收金额[\s\S]*支付方式/, 'purchase modal should arrange package, owner, payment date, price and pay method in compact rows');
assert.match(source, /实际成交价与系统价格不一致时必填/, 'purchase modal should require an override reason when final price differs');
assert.match(source, /tms-readonly-text/, 'student detail long readonly fields should use padded readonly text blocks');
assert.match(source, /purchase-coach-picker[\s\S]*purchase-notes-row/, 'purchase allowed coach picker should reuse the student picker block style');
assert.match(source, /function purchaseAllowedCoachChecks[\s\S]*tms-checkbox-wrap[\s\S]*tms-checkbox/, 'purchase allowed coach options should use the standard checkbox row style');
assert.match(source, /\{key:'purchases'[\s\S]*columns:\[\{label:'支付日期',style:'width:100px;padding-left:20px'\},\{label:'学员',style:'width:80px'\},\{label:'课包',style:'width:110px'\},\{label:'实收',style:'width:90px'\},\{label:'余额',style:'width:105px'\},\{label:'状态',style:'width:80px'\},\{label:'归属教练',style:'width:95px'\},\{label:'支付方式',style:'width:90px'\}/, 'purchase record table should follow the narrowed column order');
assert.match(source, /pager:\{infoId:'purPagerInfo',pageSizeId:'purPageSize',buttonsId:'purPagerBtns'\}/, 'purchase record page should expose the standard pager');
assert.match(source, /function onPurchaseFilterChange\(\)[\s\S]*purPackageFilterValue=document\.getElementById\('purPackageFilter'\)\?\.value\|\|''[\s\S]*purPage=standardListFirstPage\(\)[\s\S]*renderPurchases\(\)/, 'purchase filters should store the selected package and reset pagination through the standard list flow');
assert.match(source, /function purchaseSelectedPackageFilter\(\)[\s\S]*purPackageFilterValue\|\|document\.getElementById\('purPackageFilter'\)\?\.value\|\|''/, 'purchase package filter should survive navigation before the dropdown is rendered');
assert.match(source, /function renderPurchasePagerControls\(/, 'purchase page should render compact pager controls');
assert.match(source, /pager\.style\.display=total>purPageSize\?'flex':'none'/, 'purchase pager should hide when the filtered result fits on one page');
assert.match(css, /#page-purchases \.tms-table-wrapper\{max-height:calc\(100vh - 210px\);overflow-x:auto;overflow-y:auto\}/, 'purchase table height should match the student standard table height');
assert.match(css, /\.tms-page-btn\{[^}]*min-width:24px[^}]*height:24px[^}]*font-weight:500[^}]*border-radius:6px/, 'purchase pager buttons should inherit the shared compact page button style');
assert.doesNotMatch(css, /\.tms-page-jump input/, 'purchase pager should not keep jump input styles');
assert.match(source, /function withStandardFilterCounts\(/, 'standard dropdown filters should support count labels for all pages');
assert.match(source, /function withLinkedFilterCounts\(/, 'standard dropdown filters should support linked count labels for all pages');
assert.match(source, /function renderStandardOptionLabel\(/, 'shared dropdown renderer should format option counts centrally');
assert.match(source, /renderStudentToolbarFilters[\s\S]*withLinkedFilterCounts\(\[[\s\S]*key:'type'[\s\S]*key:'source'[\s\S]*key:'coach'/, 'student toolbar filters should use linked count labels');
assert.match(source, /function renderPurchases[\s\S]*renderPurchasePagerControls\(total,pages\)/, 'purchase table should keep using the standard pager renderer');
assert.match(source, /purchaseEntitlementMiniBar\(ent\)/, 'purchase balance column should reuse the mini balance bar style');
assert.match(source, /entitlements\.filter\(e=>e\.studentId===stu\?\.id\)\.sort\(\(a,b\)=>String\(studentEntitlementPurchaseDate\(a,purchases\.find\(p=>p\.id===a\.purchaseId\)\|\|\{\}\)\)\.localeCompare\(String\(studentEntitlementPurchaseDate\(b,purchases\.find\(p=>p\.id===b\.purchaseId\)\|\|\{\}\)\)\)\)/, 'student package purchase records should sort older purchases first');
assert.match(source, /function sameCampusValue\(/, 'campus matching should use one helper so mabao and 顺义马坡 stay one campus');
assert.match(source, /sameCampusValue\(s\.campus,campus\)/, 'student page campus filter should treat mabao and 顺义马坡 as the same campus');
assert.match(source, /const purchaseDate=studentEntitlementPurchaseDate\(e,purchase\);/, 'student package purchase records should use a dedicated purchase date resolver');
assert.doesNotMatch(source, /const purchaseDate=e\.purchaseDate\|\|purchase\.purchaseDate\|\|String\(e\.createdAt\|\|purchase\.createdAt\|\|''\)\.slice\(0,10\);/, 'student package purchase date should not fall back to import createdAt');

console.log('student page view tests passed');
