const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: source } = require('./helpers/read-index-bundle');
const css = fs.readFileSync(path.join(__dirname, '../public/assets/styles/pages.css'), 'utf8');

assert.match(source, /function renderScheduleStudentSuggestions/, 'schedule modal should provide a dedicated student suggestion helper');
assert.match(source, /function scheduleSelectedStudentHomeCampusMeta/, 'schedule modal should derive the selected student home campus');
assert.match(source, /function scheduleStudentInlineMeta\([\s\S]*归属：[\s\S]*上次上课：/, 'schedule modal should show selected student home campus inline with the selected tag');
assert.doesNotMatch(source, /id="sch_homeCampusSummary"/, 'schedule modal should not show home campus as a separate row');
assert.match(source, /function syncScheduleHomeCampusFromStudents/, 'schedule modal should sync home campus after student selection changes');
assert.match(source, /function scheduleSelectedStudentCoachMeta/, 'schedule modal should derive the selected student primary coach');
assert.match(source, /function syncScheduleProfileFromStudents/, 'schedule modal should sync selected student coach and campus defaults');
assert.match(source, /setCourtDropdownValue\('sch_coach',meta\.coach,meta\.coach\)/, 'schedule modal should default coach from selected student profile');
assert.match(source, /上课校区 \*/, 'schedule own-location field should be labelled as lesson campus, not student home campus');
assert.match(source, /校区内[\s\S]*校区外/, 'schedule location type copy should separate in-campus and off-campus lessons');
assert.match(source, /id="sch_stuSearch"/, 'schedule modal should provide a searchable student input');
assert.match(source, /id="sch_selectedStudentTags"/, 'schedule modal should show selected students as removable tags');
assert.doesNotMatch(source, /id="sch_stuName"[^>]*placeholder="选班次自动填入"/, 'schedule modal should not use free text student input as the formal selector');
assert.match(source, /function getFilteredStudents\(/, 'student page should centralize filtered student list calculation');
assert.match(source, /function onStudentFilterChange\(\)\{stuPage=1;renderStudents\(\);\}/, 'student filters should reset pagination to first page');
assert.match(source, /oninput="onStudentFilterChange\(\)"/, 'student search should reset pagination before rendering');
assert.match(source, /function renderStudentToolbarFilters\(/, 'student filters should render through the booking-style dropdown helper');
assert.match(source, /stuTypeFilterHost[\s\S]*onStudentFilterChange/, 'student type filter should reset pagination before rendering');
assert.match(source, /stuSourceFilterHost[\s\S]*onStudentFilterChange/, 'student source filter should reset pagination before rendering');
assert.match(source, /stuCoachFilterHost[\s\S]*onStudentFilterChange/, 'student primary coach filter should reset pagination before rendering');
assert.match(source, /function getStudentDuplicateCandidates\(/, 'student save flow should detect possible duplicates before submit');
assert.match(source, /发现可能重复的学员：/, 'student save flow should warn operators about possible duplicates');
assert.match(source, /const d=getFilteredStudents\(\);[\s\S]*a\.download='FlowTennis_学员_'\+today\(\)\+'.csv'/, 'student csv export should use current filtered result set');
assert.match(source, /stuCoachFilterHost/, 'student page should include primary coach filter host');
assert.match(source, /label:'全部',emptyDisplay:'负责教练'[\s\S]*未分配/, 'student filters should expose responsible coach options with all as the reset item');
assert.match(source, /学员总数[\s\S]*今日课时[\s\S]*本周课时[\s\S]*本月课时[\s\S]*本月体验课转化率[\s\S]*待转化/, 'student top stats should use the all-coach workbench metric set');
assert.match(source, /function studentPageStats\(/, 'student page should centralize top stat calculation');
assert.match(source, /pendingConversion:base\.filter\(s=>studentNeedsConversion\(s\)\)\.length/, 'student stats should summarize pending conversion from trial-without-purchase students');
assert.match(source, /function studentStatusMeta\(/, 'student list should compute business status labels');
assert.match(source, /上课中[\s\S]*待转化[\s\S]*沉默30天[\s\S]*仅订场[\s\S]*无班次/, 'student status labels should cover the agreed business states');
assert.match(source, /function studentNoteSummary\(/, 'student list should compute compact ops-style note summary');
assert.match(source, /data-student-sort="lastLesson"[\s\S]*最近上课/, 'student table should sort by recent lesson');
assert.match(source, /data-student-sort="completedLessons"[\s\S]*累计上课/, 'student table should sort by cumulative lessons');
assert.match(source, /data-student-sort="packageLessons"[\s\S]*课时\/课包/, 'student table should sort by lesson/package balance');
assert.doesNotMatch(source, /<th[^>]*>当前班次<\/th>/, 'student table should hide the current class column');
assert.doesNotMatch(source, /<th[^>]*>订场\/会员<\/th>/, 'student table should hide the booking membership column');
assert.match(source, /<th style="width:94px">电话<\/th><th style="width:58px">类型<\/th><th style="width:105px">校区<\/th><th style="width:140px">/, 'student table should widen phone and type columns enough to show their full text');
assert.match(source, /id="stuPageSize"/, 'student pager should expose a page size selector host');
assert.match(source, /function setStudentPageSize\(/, 'student page should support 20, 50, and 100 row page sizes');
assert.match(source, /function renderStudentPagerControls\(/, 'student page should render compact pager controls');
assert.match(css, /#page-students \.tms-table-wrapper\{max-height:calc\(100vh - 210px\)\}/, 'student table should be taller on screen');
assert.match(css, /\.tms-stat-card\{[^}]*padding:12px 16px 16px 16px[^}]*min-height:86px/, 'top stat cards should be slightly shorter without squeezing the sub text');
assert.match(css, /#page-students \.tms-pagination\{padding:4px 12px;font-size:11px/, 'student pager should be shorter with smaller text');
assert.match(css, /#page-students \.tms-pagination \.tms-dropdown-display\{height:30px;padding:0 10px;font-size:11px;min-width:88px;font-weight:400/, 'student page size selector should be smaller and not bold');
assert.match(css, /#page-students \.tms-dropdown\.has-value \.tms-dropdown-display\{font-weight:400/, 'student selected pager dropdown should not be bold');
assert.match(css, /\.tms-dropdown\.has-value \.tms-dropdown-display/, 'selected filters should look different from the default all state');
assert.match(css, /#page-students \.tms-filters \.tms-dropdown\.has-value \.tms-dropdown-display\{color:#C06031;font-weight:400\}/, 'selected student filters should use the active dropdown item orange');
assert.match(css, /#page-students \.tms-sort-icon\{[^}]*width:7px[^}]*transform:translateY\(-1px\)/, 'student sort icon should be smaller and closer to the header text');
assert.match(source, /function cycleStudentSort\([\s\S]*stuSortDir='asc'[\s\S]*stuSortDir='desc'[\s\S]*stuSortKey='';stuSortDir='';/, 'student sortable headers should cycle asc, desc, and no sort');
assert.match(source, /function studentEmptyStateHtml\([\s\S]*没有匹配的学员[\s\S]*暂无学员[\s\S]*调整搜索或筛选后再试[\s\S]*点击右上角添加学员开始录入/, 'student empty state should distinguish filtered empty results from no data');
assert.match(source, /function renderStudentTableLoading\([\s\S]*tms-table-loading-state[\s\S]*学员数据加载中/, 'student loading state should use the standard table loading style');
assert.match(source, /function renderStudentTableError\([\s\S]*tms-table-error-state[\s\S]*加载失败[\s\S]*重新加载/, 'student load failure should render an inline retry state');
assert.match(source, /if\(pg==='students'\)renderStudentTableLoading\(\);/, 'student page should use the dedicated loading renderer');
assert.match(source, /if\(pg==='students'\)renderStudentTableError\(String\(e\.message\|\|e\)\);/, 'student page load failure should render the dedicated error state');
assert.match(css, /#page-students \.tms-empty-state\{[\s\S]*#page-students \.tms-state-action/, 'student empty, loading, and error states should have scoped standard styles');
assert.match(source, /function studentCompletedLessonCount\(/, 'student page should expose a cumulative completed lesson helper');
assert.match(source, /studentCompletedLessonCount\(s\)/, 'student list should render cumulative completed lessons');
assert.match(source, /function scheduleLessonUnits\(/, 'lesson stats should use schedule lesson units instead of row counts');
assert.match(source, /function studentPrimaryCoachText\(/, 'student list should render primary coach from the profile field');
assert.match(source, /studentPrimaryCoachText\(s\)/, 'student list coach column should use the profile primary coach');
assert.match(source, /未分配/, 'empty primary coach should display 未分配');
assert.match(source, /const SOURCES=\['转介绍','小红书','大众点评','视频号','抖音','播客','孙老师','其他'\]/, 'student source options should keep the unified ops order');
assert.match(source, /function renderCourtCellText[\s\S]*const muted=!raw\|\|raw==='-'\|\|raw==='—'\|\|raw==='未开卡'/, 'empty list values should always render with the muted dash style');
assert.match(source, /function renderCourtEmptyText[\s\S]*return raw&&raw!=='—'\?raw:'-'/, 'empty values should render with the short dash');
assert.doesNotMatch(source, /<th>最后订场<\/th>/, 'student table should remove last-court as a primary list column in phase 2');
assert.doesNotMatch(source, /<th>关联账户<\/th>/, 'student table should replace account wording with booking membership summary');
assert.match(source, /<th style="width:90px">[\s\S]*课时\/课包/, 'student package lesson column should be labelled lesson/package');
assert.match(source, /function studentPackageLessonMeta\(/, 'student package lesson summary should expose remaining and total lessons');
assert.match(source, /function studentPackageLessonMiniBar\(/, 'student package lesson column should render the same mini balance bar as booking accounts');
assert.match(source, /studentPackageLessonMiniBar\(s\)/, 'student list should render package lessons through the mini balance bar');
assert.match(source, /\$\{lessonQty\(remaining\)\}\/\$\{lessonQty\(total\)\}/, 'student package lesson text should use remaining over total lesson count without truncating half lessons');
assert.match(source, /function openStudentDetail\(/, 'student list should provide a dedicated view action');
assert.match(source, /openStudentDetail\('[^']+'\)[\s\S]*openStudentModal\('[^']+'\)/, 'student row should prioritize view before edit');
assert.match(source, /openStudentDetail\('[^']+'\)[\s\S]*openPurchaseModal\('[^']+'\)[\s\S]*openStudentModal\('[^']+'\)/, 'student row should expose a direct package purchase shortcut between view and edit');
assert.match(source, /function studentTeachingInfoHtml\(/, 'student detail should render teaching info block');
assert.match(source, /function studentOpsInfoHtml\(/, 'student detail should render operations info block');
assert.match(source, /function studentConsumptionInfoHtml\(/, 'student detail should render consumption relation block');
assert.match(source, /function studentLessonRecordHtml\(/, 'student detail should expose a dedicated lesson record helper');
assert.match(source, /function studentEntitlementLedgerHtml\(/, 'student detail should provide a dedicated lesson charge history helper');
assert.match(source, /function entitlementLedgerDisplayDate\(/, 'lesson charge history should display the real lesson or month date instead of import time');
assert.match(source, /function historicalImportedLedgerMonthKey\(/, 'lesson charge history should infer monthly import identity from sourceMonth or reason text');
assert.match(source, /reason\.match\(\s*\/\^历史导入\\s\*\(\\d\{1,2\}\)月消课\$\/\s*\)/, 'lesson charge history should fall back to parsing month from reason text when sourceMonth is missing');
assert.match(source, /dedupeEntitlementLedgerForDisplay/, 'lesson charge history should collapse duplicate ledger rows before display');
assert.match(source, /function historicalImportedLessonUnitsForStudent\(/, 'student page should expose a historical imported lesson helper');
assert.match(source, /aggregateHistoricalMonthlyLedgerRows/, 'student consume history should aggregate historical monthly rows before display');
assert.match(source, /studentCompletedLessonCount[\s\S]*historicalImportedLessonUnitsForStudent/, 'student cumulative lessons should include imported lesson consumption');
assert.match(source, /教学信息[\s\S]*运营信息[\s\S]*消费与关联信息/, 'student detail should follow the agreed information hierarchy');
assert.match(source, /function studentDetailFieldHtml\(/, 'student detail should render short readonly values without form inputs');
assert.match(source, /function studentDetailBlockHtml\(/, 'student detail should render long readonly content as information blocks');
assert.doesNotMatch(source, /function openStudentDetail[\s\S]*<input[\s\S]*function openStudentModal/, 'student detail modal should not use input controls for readonly values');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*<input[\s\S]*function studentOpsInfoHtml/, 'student teaching detail should not look editable');
assert.doesNotMatch(source, /function studentOpsInfoHtml[\s\S]*<input[\s\S]*function studentConsumptionInfoHtml/, 'student ops detail should not look editable');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*<input[\s\S]*function studentLinkedDetailHtml/, 'student consumption detail should not look editable');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*最近订场[\s\S]*function studentLinkedDetailHtml/, 'student consumption detail should remove duplicated recent booking field');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*关联说明[\s\S]*function studentLinkedDetailHtml/, 'student consumption detail should remove unclear duplicate linked account explanation');
assert.match(css, /\.modal\.modal-court \.tms-detail-grid[\s\S]*\.modal\.modal-court \.tms-detail-value[\s\S]*\.modal\.modal-court \.tms-detail-block/, 'student detail should use dedicated readonly display styles');
assert.match(source, /function studentDetailBlockHtml\(label,html,options=\{\}\)[\s\S]*options\.hideEmpty&&studentDetailIsEmptyHtml\(html\)/, 'student detail should hide empty long blocks when they add no information');
assert.match(css, /\.modal\.modal-court \.tms-detail-block\{[^}]*background:transparent[^}]*border:0[^}]*border-radius:0/, 'student detail long content should not look like input boxes');
assert.match(source, /const leadHtml=studentDetailBlockHtml\('线索摘要',studentLeadSummaryHtml\(s\),\{hideEmpty:true\}\);[\s\S]*leadHtml\?/, 'student detail should hide the linked lead section when there is no lead');
assert.match(source, /function studentDetailSectionHtml\(/, 'student detail should hide whole empty sections');
assert.doesNotMatch(source, /function studentOpsInfoHtml[\s\S]*最近活跃[\s\S]*function studentConsumptionInfoHtml/, 'student ops detail should remove duplicated recent active field');
assert.doesNotMatch(source, /function studentOpsInfoHtml[\s\S]*最近订场[\s\S]*function studentConsumptionInfoHtml/, 'student ops detail should remove recent booking from ops fields');
assert.match(source, /function studentConsumptionInfoHtml[\s\S]*const linkedFields=linkedCourts\.length\?[\s\S]*:\s*''/, 'student consumption detail should only show linked account fields when linked data exists');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*studentDetailFieldHtml\('订场 \/ 会员'/, 'student consumption detail should not show unlinked booking membership field');
assert.match(source, /function studentLessonRecordTimeText\([\s\S]*slice\(11,16\)[\s\S]*-\$\{end\}/, 'student lesson records should show start and end time');
assert.doesNotMatch(source, /function studentEntitlementSummaryHtml[\s\S]*badge b-amber[\s\S]*function studentEntitlementPurchaseDate/, 'student package records should render course type as normal text');
assert.match(source, /function studentEntitlementSummaryHtml[\s\S]*报名 \$\{esc\(renderCourtEmptyText\(purchaseDate\)\)\} · 归属/, 'student package records should use middle dots instead of semicolon separators');
assert.match(source, /function studentEntitlementLedgerLineHtml\([\s\S]*\$\{lessonQty\(Number\(row\.lessonDelta\)\|\|0\)\}节[\s\S]*join\(' · '\)/, 'student package consume records should render one compact middle-dot line with signed lesson count');
assert.match(source, /function studentEntitlementLedgerTimeText\([\s\S]*\$\{date\} \$\{start\}-\$\{end\}/, 'student package consume records should show a lesson time range when available');
assert.match(source, /function studentEntitlementLedgerSourceText\([\s\S]*sourceSheet[\s\S]*导入/, 'student package consume records should show the import source in the compact line');
assert.doesNotMatch(source, /function studentEntitlementLedgerHtml[\s\S]*扣减 \$\{lessonQty\(count\)\} 节[\s\S]*function classScheduleSummaryHtml/, 'student package consume records should not use the old two-line charge wording');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*当前状态[\s\S]*function studentOpsInfoHtml/, 'student detail should remove current status');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*当前班次[\s\S]*function studentOpsInfoHtml/, 'student detail should remove current class');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*班次进度[\s\S]*function studentOpsInfoHtml/, 'student detail should remove class progress');
assert.match(source, /上课记录/, 'student detail should provide lesson record history in plain language');
assert.match(source, /已购课包/, 'student detail should present purchased packages in plain language');
assert.match(source, /扣课记录/, 'student detail should expose lesson charge history in the student detail');
assert.match(source, /课包购买记录/, 'student detail should label package purchase records clearly');
assert.match(source, /课包消耗记录/, 'student detail should label package consume records clearly');
assert.match(source, /关联订场账户在「订场\/会员」页面编辑用户时选择「关联学员」/, 'student detail should explain where to link booking accounts');
assert.doesNotMatch(source, /function openStudentModal[\s\S]*studentLinkedDetailHtml\(s\)/, 'student edit modal should not embed linked detail summary anymore');
assert.match(source, /function openStudentModal[\s\S]*姓名 \*[\s\S]*手机号[\s\S]*负责教练[\s\S]*学员类型[\s\S]*来源[\s\S]*活动范围[\s\S]*所在校区[\s\S]*备注/, 'student edit modal should keep base profile fields and expose primary coach');
assert.match(source, /const campusOptions=studentCampusOptions\(\);/, 'student edit modal should build campus options through the shared student helper');
assert.match(source, /function studentCampusOptions\(/, 'student edit modal should expose all loaded campuses through a helper');
assert.match(source, /renderCourtDropdownHtml\('s_primaryCoach'/, 'student edit modal should provide a primary coach selector');
assert.match(source, /const data=\{name,phone,primaryCoach:/, 'student save should submit primary coach');
assert.match(source, /function openStudentModal[\s\S]*setCourtModalFrame\(/, 'student edit modal should reuse the booking-style modal shell');
assert.match(source, /选择课包 \*[\s\S]*主归属教练[\s\S]*支付日期[\s\S]*系统价格[\s\S]*实收金额[\s\S]*支付方式/, 'purchase modal should arrange package, owner, payment date, price and pay method in compact rows');
assert.match(source, /实际成交价与系统价格不一致时必填/, 'purchase modal should require an override reason when final price differs');
assert.match(source, /tms-readonly-text/, 'student detail long readonly fields should use padded readonly text blocks');
assert.match(source, /purchase-coach-picker[\s\S]*purchase-notes-row/, 'purchase allowed coach picker should reuse the student picker block style');
assert.match(source, /function purchaseAllowedCoachChecks[\s\S]*tms-checkbox-wrap[\s\S]*tms-checkbox/, 'purchase allowed coach options should use the standard checkbox row style');
assert.match(source, /购买日期<\/th><th style="width:120px">学员\/支付<\/th><th style="width:170px">课包\/课程<\/th><th style="width:90px">实收<\/th><th style="width:95px">余额<\/th><th style="width:135px">有效期<\/th><th style="width:80px">状态<\/th><th style="width:95px">归属教练<\/th>/, 'purchase record table should split validity and status into compact ordered columns');
assert.match(source, /entitlements\.filter\(e=>e\.studentId===stu\?\.id\)\.sort\(\(a,b\)=>String\(studentEntitlementPurchaseDate\(a,purchases\.find\(p=>p\.id===a\.purchaseId\)\|\|\{\}\)\)\.localeCompare\(String\(studentEntitlementPurchaseDate\(b,purchases\.find\(p=>p\.id===b\.purchaseId\)\|\|\{\}\)\)\)\)/, 'student package purchase records should sort older purchases first');
assert.match(source, /function sameCampusValue\(/, 'campus matching should use one helper so mabao and 顺义马坡 stay one campus');
assert.match(source, /sameCampusValue\(s\.campus,campus\)/, 'student page campus filter should treat mabao and 顺义马坡 as the same campus');
assert.match(source, /const purchaseDate=studentEntitlementPurchaseDate\(e,purchase\);/, 'student package purchase records should use a dedicated purchase date resolver');
assert.doesNotMatch(source, /const purchaseDate=e\.purchaseDate\|\|purchase\.purchaseDate\|\|String\(e\.createdAt\|\|purchase\.createdAt\|\|''\)\.slice\(0,10\);/, 'student package purchase date should not fall back to import createdAt');

console.log('student page view tests passed');
