const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: source } = require('./helpers/read-index-bundle');
const css = [
  'assets/styles/components/data-cards.css',
  'assets/styles/components/search.css',
  'assets/styles/components/buttons.css',
  'assets/styles/components/filters.css',
  'assets/styles/components/tables.css',
  'assets/styles/components/modals.css',
  'assets/styles/pages.css'
].filter(file=>fs.existsSync(path.join(__dirname, '../public', file))).map(file=>fs.readFileSync(path.join(__dirname, '../public', file), 'utf8')).join('\n');

function fnBody(name){
  const start = source.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = source.indexOf('\nfunction ', start + 1);
  const nextAsync = source.indexOf('\nasync function ', start + 1);
  const candidates = [nextFunction, nextAsync].filter(i => i !== -1);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return source.slice(start, next === -1 ? source.length : next);
}

assert.match(source, /function renderScheduleStudentSuggestions/, 'schedule modal should provide a dedicated student suggestion helper');
assert.match(fnBody('scheduleStudentRosterRows'), /students\.forEach[\s\S]*teachingStudentViews\?\.historicalStudents[\s\S]*teachingStudentViews\?\.activeStudents/, 'schedule student search should include the full student list before teaching view rows');
assert.match(source, /function scheduleSelectedStudentHomeCampusMeta/, 'schedule modal should derive the selected student home campus');
assert.match(source, /function scheduleStudentInlineMeta\([\s\S]*\$\{campus\}｜\$\{last\}\$\{last\.endsWith\('有课'\)\?'':'上课'\}/, 'schedule modal should show selected student home campus inline with the selected tag');
assert.doesNotMatch(source, /id="sch_homeCampusSummary"/, 'schedule modal should not show home campus as a separate row');
assert.match(source, /function syncScheduleHomeCampusFromStudents/, 'schedule modal should sync home campus after student selection changes');
assert.match(source, /function scheduleSelectedStudentCoachMeta/, 'schedule modal should derive the selected student primary coach');
assert.match(source, /function syncScheduleProfileFromStudents/, 'schedule modal should sync selected student coach and campus defaults');
assert.match(source, /setStandardDropdownValue\('sch_coach',selectedCoach,selectedCoach\)/, 'schedule modal should default coach from selected student profile');
assert.match(source, /上课校区/, 'schedule own-location field should be labelled as lesson campus, not student home campus');
assert.match(source, /校区内[\s\S]*校区外/, 'schedule location type copy should separate in-campus and off-campus lessons');
assert.match(source, /id="sch_stuSearch"/, 'schedule modal should provide a searchable student input');
assert.match(source, /id="sch_selectedStudentTags"/, 'schedule modal should show selected students as removable tags');
assert.doesNotMatch(source, /id="sch_stuName"[^>]*placeholder="选班次自动填入"/, 'schedule modal should not use free text student input as the formal selector');
assert.match(source, /id="ent_auth_student" value=""><input class="finput tms-form-control" id="ent_auth_student_search" placeholder="搜索姓名 \/ 手机号"/, 'authorization modal should start with an empty searchable input');
assert.match(source, /async function openEntitlementAuthorizationModal\([\s\S]*ensureStudentDetailData\(activeStudentId,\{force:true\}\)[\s\S]*studentDetailPackageRowForEntitlementId/, 'authorization modal should precisely reload one student before falling back to detail rows');
assert.match(fnBody('openEntitlementAuthorizationModal'), /data:\{studentDetailId:activeStudentId\|\|ent\.studentId\|\|''\}/, 'authorization modal should preserve the current student id for post-save refresh');
assert.match(source, /function renderEntitlementAuthorizationStudentSuggestions\([\s\S]*<strong>\$\{esc\(stu\.name\|\|stu\.id\|\|''\)\}<\/strong>[\s\S]*<span>\$\{esc\(entitlementAuthorizationStudentMeta\(stu\)\|\|'-'\)\}<\/span>/, 'authorization modal should render the same searchable suggestion style as schedule selection');
assert.match(source, /function entitlementAuthorizationSaveErrorText\([\s\S]*授权数据表还没准备好，请刷新页面后再试[\s\S]*return '授权保存失败，请稍后重试';/, 'authorization save errors should fall back to readable text');
assert.match(fnBody('saveEntitlementAuthorization'), /refreshStudentDetailDataAfterMutation\(currentStudentId\)[\s\S]*studentDetailActiveTab='orders'[\s\S]*openStudentDetail\(currentStudentId\)/, 'authorization save should refresh and reopen the current student package detail');
assert.match(fnBody('saveEntitlementAuthorization'), /refreshReadModelsInBackground\(\['packageCenterPage','customerCenterPage','purchasesPage'\]/, 'authorization save should refresh global package read models in the background');
assert.match(source, /function getFilteredStudents\(/, 'student page should centralize filtered student list calculation');
assert.match(fnBody('studentUnifiedViewRows'), /includeSearchIndex[\s\S]*teachingStudentViews\?\.searchableStudents/, 'student keyword search should use the lightweight full student search index instead of switching search tables');
assert.match(fnBody('studentUnifiedViewRows'), /studentHasNotes[\s\S]*const notes=studentHasNotes\?student\.notes/, 'student unified rows should preserve intentionally empty student notes instead of falling back to system notes');
assert.match(fnBody('studentSearchText'), /s\?\.searchText[\s\S]*s\?\.notes[\s\S]*s\?\.profileNote/, 'student keyword search must include backend searchText, notes, and profileNote');
assert.match(fnBody('searchHit'), /compactKeyword=keyword\.replace\(\//, 'global keyword search should build a compact keyword');
assert.match(fnBody('searchHit'), /text\.replace\(\//, 'global keyword search should compare against compact text');
assert.match(fnBody('searchHit'), /includes\(compactKeyword\)/, 'global keyword search should ignore spaces between names');
assert.match(source, /function onStudentFilterChange\(\)\{stuPage=standardListFirstPage\(\);renderStudents\(\);\}/, 'student filters should reset pagination through the standard list flow');
assert.match(source, /search:\{id:'stuSearch',oninput:'onStudentFilterChange\(\)'/, 'student search should reset pagination before rendering');
assert.match(source, /function renderStudentToolbarFilters\(/, 'student filters should render through the booking-style dropdown helper');
assert.match(source, /stuTypeFilterHost[\s\S]*onStudentFilterChange/, 'student type filter should reset pagination before rendering');
assert.match(source, /stuSourceFilterHost[\s\S]*onStudentFilterChange/, 'student source filter should reset pagination before rendering');
assert.match(source, /function studentSourceOptions\(\)[\s\S]*FlowTennisBusinessTaxonomy\.optionList\('leadSources'\)/, 'student source options should reuse the same source dictionary as leads');
assert.match(source, /function studentSourceText\(s\)[\s\S]*customerLifecycleSource\(s,s\?\.source\)/, 'student source display should use the shared lifecycle source accessor before legacy source values');
assert.match(source, /stuTagFilterHost[\s\S]*renderStudentTagCascader/, 'student tag filter should render through one cascader host');
assert.doesNotMatch(source, /stuPackageStatusFilterHost|stuPaymentModeFilterHost|stuActivityStatusFilterHost|stuLessonVolumeFilterHost|stuLifecycleStatusFilterHost/, 'student individual tag filter hosts should be replaced by the cascader host');
assert.match(source, /stuCoachFilterHost[\s\S]*onStudentFilterChange/, 'student primary coach filter should reset pagination before rendering');
assert.match(source, /const STUDENT_TAG_FILTER_GROUPS=\[[\s\S]*key:'packageStatus'[\s\S]*key:'paymentMode'[\s\S]*key:'activityStatus'[\s\S]*key:'lessonVolume'[\s\S]*key:'lifecycleStatus'/, 'student tag cascader should group package, payment, activity, lesson volume, and lifecycle labels');
assert.match(source, /function renderStudentTagCascader\(/, 'student tag cascader renderer should exist');
assert.match(source, /function toggleStudentTagFilter\(/, 'student tag cascader should support multi-select toggling');
assert.match(source, /function clearStudentTagFilters\(/, 'student tag cascader should support clearing all selected tags');
assert.match(source, /function removeStudentTagFilter\(/, 'student tag cascader should support removing one selected tag');
assert.match(source, /function studentTagFilterMatches\([\s\S]*STUDENT_TAG_FILTER_GROUPS\.every[\s\S]*!selected\.length\|\|selected\.includes\(group\.getter\(s\)\)/, 'student tag filters should use OR within one group and AND across groups');
assert.match(source, /let studentTagCascaderActiveGroupKey='packageStatus'/, 'student tag cascader should keep one active parent group');
assert.match(source, /function setStudentTagCascaderActiveGroup\(/, 'student tag cascader should switch second-level options from the first-level group');
assert.match(source, /filterHostIds:\['stuTypeFilterHost','stuSourceFilterHost','stuTagFilterHost','stuCoachFilterHost'\]/, 'student toolbar should expose type, source, tag cascader, and coach filters in order');
assert.match(fnBody('renderStudentToolbarFilters'), /match:\(s,value\)=>value==='__unassigned__'\?studentPrimaryCoachText\(s\)==='-':studentPrimaryCoachText\(s\)===value/, 'student coach filter should use the same visible responsible-coach口径 as the list');
assert.match(source, /function getStudentDuplicateCandidates\(/, 'student save flow should detect possible duplicates before submit');
assert.match(source, /function isHiddenStudentProfile\([\s\S]*'merged'[\s\S]*'archived'[\s\S]*deletedAt[\s\S]*archivedAt/, 'student hidden profile helper should cover merged, archived, deleted, and inactive profiles');
assert.match(fnBody('getStudentDuplicateCandidates'), /isHiddenStudentProfile\(s\)/, 'student duplicate warning should ignore hidden student profiles');
assert.match(source, /发现可能重复的学员：/, 'student save flow should warn operators about possible duplicates');
assert.match(fnBody('saveStudent'), /await appConfirm\(/, 'student duplicate warning should use the app modal instead of browser confirm');
assert.doesNotMatch(fnBody('saveStudent'), /confirm\(/, 'student duplicate warning should not use the browser confirm dialog');
assert.match(source, /const d=getFilteredStudents\(\);[\s\S]*a\.download='FlowTennis_学员_'\+today\(\)\+'.csv'/, 'student csv export should use current filtered result set');
assert.match(source, /stuCoachFilterHost/, 'student page should include primary coach filter host');
assert.match(source, /label:'全部',emptyDisplay:'负责教练'[\s\S]*未分配/, 'student filters should expose responsible coach options with all as the reset item');
assert.match(source, /function studentTopStatsCards\(stats\)/, 'student top stats should be built by page mode');
assert.match(source, /studentListViewMode\(\)==='trial'[\s\S]*历史学员[\s\S]*上过体验课[\s\S]*上过正式课[\s\S]*上过体验未上正式课[\s\S]*近30天正式课活跃/, 'historical student top stats should show schedule-fact cards');
assert.doesNotMatch(source, /当前列表课程成交/, 'trial student top stats must not show the old local course-deal card');
assert.match(source, /function studentStandardSummaryForMode\(/, 'student page should keep backend standard summary helper for top stats');
assert.match(fnBody('studentPageStats'), /studentStandardSummaryForMode\(\)/, 'student top stats must read the backend teaching summary');
assert.match(fnBody('studentPageStats'), /customerCenterPageReady\(\)/, 'student top stats must wait for the current lightweight customer center read model before showing numbers');
assert.doesNotMatch(fnBody('studentPageStats'), /FlowTennisPlatformDataStandards\.currentStudentSummary/, 'student top stats must not use frontend row summary');
assert.doesNotMatch(fnBody('studentPageStats'), /studentFinanceStatsForBase\(base\)|purchases\.filter|entitlements\.filter|amountPaid|finalAmount|recognizedRevenueDelta/, 'student top cards must not recalculate core metrics from frontend raw rows');
assert.match(fnBody('studentStandardSummaryForMode'), /historicalStudentCount[\s\S]*activeStudentCount/, 'student top stats should use historical and active student backend counts');
assert.doesNotMatch(fnBody('studentStandardSummaryForMode'), /historicalTagCounts[\s\S]*activeTagCounts/, 'student top cards should use explicit backend card fields instead of deriving from tag count maps');
assert.match(fnBody('studentStandardSummaryForMode'), /Number\.isFinite\(historicalSummaryCount\)\?historicalSummaryCount[\s\S]*Number\.isFinite\(activeSummaryCount\)\?activeSummaryCount/, 'student top stats should preserve explicit zero counts from the backend summary');
assert.doesNotMatch(fnBody('studentStandardSummaryForMode'), /studentStandardMetricValue\('courseChainStudents'\)|studentStandardMetricValue\('formalStudents'\)/, 'student top stats should not use old normal/formal metric counts as page totals');
assert.match(source, /在期学员[\s\S]*当前仍有运营价值[\s\S]*近30天正式课活跃[\s\S]*近90天正式课活跃[\s\S]*课包有余额[\s\S]*课包即将耗尽/, 'active student top stats should show active roster cards');
assert.match(source, /function currentStudentSummary\([\s\S]*historicalTrialAttendedCount[\s\S]*historicalFormalAttendedCount[\s\S]*historicalTrialWithoutFormalCount[\s\S]*historicalFormalLesson30Count[\s\S]*activeFormalLesson30Count[\s\S]*activeFormalLesson90Count[\s\S]*activePackageBalanceCount[\s\S]*activePackageLowCount/, 'shared current student summary should produce the agreed top card fields from unified rows');
assert.doesNotMatch(fnBody('studentPageStats'), /rows\.filter\(s=>student(ActivityStatusText|PackageStatusText|LifecycleStatusText)\(s\)===/, 'student top tag cards must not count labels by filtering frontend rows');
assert.match(fnBody('studentTopStatsCards'), /在期学员[\s\S]*近30天正式课活跃[\s\S]*近90天正式课活跃[\s\S]*课包有余额[\s\S]*课包即将耗尽/, 'active student top stats should show the agreed backend card order');
assert.match(fnBody('renderStudents'), /renderStandardDataCards\(studentTopStatsCards\(stats\)\)/, 'student renderer should choose top cards by current student page mode');
assert.match(source, /近30天正式课 \/ 在期学员[\s\S]*近90天正式课 \/ 在期学员/, 'student active cards should put 30-day and 90-day formal activity next to each other');
assert.match(source, /function studentPageStats\(/, 'student page should centralize top stat calculation');
assert.match(fnBody('renderStudents'), /const filteredStudents=getFilteredStudents\(\);[\s\S]*const stats=studentPageStats\(filteredStudents\)/, 'student top package finance stats should use the same filtered rows as the table list');
assert.doesNotMatch(fnBody('studentPageStats'), /studentStatsMatchesPackageCampus/, 'student top package income should not apply a second campus filter after the table list is filtered');
assert.doesNotMatch(source, /const validEntitlements=entitlements\.filter\(e=>studentIds\.has\(String\(e\.studentId\|\|''\)\)&&entitlementStatusText\(e\)!=='已作废'\)/, 'student top package stats must not drop package-campus rows when the student campus is empty');
assert.match(fnBody('studentPageStats'), /studentStandardSummaryForMode\(\)/, 'student stats should use backend unified schedule facts');
assert.doesNotMatch(fnBody('studentPageStats'), /standardSummary\.total\|\|base\.length/, 'student top stats must preserve unified zero values and not fall back to list length');
assert.match(source, /function studentUnifiedRecordForId\(/, 'student detail and edit flows should resolve the same unified student view row used by the list');
assert.match(fnBody('openStudentDetail'), /studentUnifiedRecordForId\(id\)/, 'student detail should use the unified student view row instead of raw students as the display source');
assert.match(fnBody('openStudentModal'), /studentUnifiedRecordForId\(id\)/, 'student edit default values should use the unified student view row instead of raw students');
assert.match(source, /let studentDetailRequestSeq=0/, 'student detail async loading should track the latest request');
assert.match(fnBody('ensureStudentDetailDatasets'), /const requestSeq=\+\+studentDetailRequestSeq[\s\S]*studentDetailRequestSeq!==requestSeq[\s\S]*studentDetailDrawerIsOpenFor\(id\)[\s\S]*studentDetailPageStillValid\(\)/, 'student detail async loading should not reopen after the drawer is closed or the page changes');
assert.match(fnBody('hydrateStudentDetailData'), /mergeTeachingStudentDetail\(data\.detailStudentView\)[\s\S]*renderStudentsIfVisible\(\)/, 'student detail hydration should refresh the visible list so cumulative lessons match the drawer immediately');
assert.doesNotMatch(fnBody('studentLastLessonDate'), /schedules\.filter/, 'student recent lesson must come from backend unified detail rows, not frontend schedule scanning');
assert.doesNotMatch(fnBody('studentCompletedLessonCount'), /studentCompletedLessonUnits/, 'student cumulative lesson count must come from backend unified completedLessons, not frontend schedule or ledger scanning');
assert.doesNotMatch(fnBody('studentCampusValuesForList'), /entitlements\.filter|purchases\.filter|packages\.filter|schedules\.filter/, 'student campus filter should read the unified student row campus fields instead of scanning raw business tables');
assert.doesNotMatch(source, /function studentFinanceRowsForBase\(|function studentFinanceRowIsCourse\(|function studentFinanceRowIsReceipt\(|function studentFinanceSum\(/, 'student page should not keep unused frontend finance summary calculators');
assert.match(fnBody('studentEntitlementSummaryHtml'), /detailPackageOrderRows/, 'student package detail should render from backend unified student detail rows');
assert.match(fnBody('studentLessonRecordRows'), /detailLessonRecordRows/, 'student lesson detail should render from backend unified student detail rows');
assert.match(fnBody('studentBenefitRows'), /detailBenefitRows/, 'student benefit summary should render from backend unified student detail rows');
assert.match(fnBody('studentBenefitLedgerRows'), /detailBenefitGrantRows|detailBenefitConsumeRows/, 'student benefit ledger detail should render from backend unified student detail rows');
assert.match(fnBody('saveStudentBenefit'), /refreshStudentDetailDataAfterMutation\(studentId\)[\s\S]*studentDetailActiveTab='benefits'[\s\S]*openStudentDetail\(studentId\)/, 'student benefit save should refresh the current student detail before reopening benefits');
assert.doesNotMatch(fnBody('saveStudentBenefit'), /await ensureDatasetsByName\(\['lifecycleMetricsPage'\],\{force:true\}\)/, 'student benefit save should not wait for lifecycle metrics');
assert.match(fnBody('saveStudentBenefit'), /refreshReadModelsInBackground\(\['packageCenterPage','customerCenterPage','lifecycleMetricsPage','financePage','purchasesPage'\]/, 'student benefit save should refresh global read models in the background');
assert.match(source, /function studentStatusMeta\(/, 'student list should compute business status labels');
assert.match(source, /上课中[\s\S]*待转化[\s\S]*沉默30天[\s\S]*仅订场[\s\S]*无班次/, 'student status labels should cover the agreed business states');
assert.match(source, /function studentNoteSummary\(/, 'student list should compute compact ops-style note summary');
assert.match(source, /function studentHumanText\(/, 'student list should clean system-import source and note text before display');
assert.match(source, /历史导入[\s\S]*马坡私教 CSV 导入自动创建[\s\S]*CSV 导入自动创建/, 'student human text should filter known non-human import labels');
assert.doesNotMatch(fnBody('studentTableColumns'), /packagePurchaseDate|课包购买时间|体验状态|成交路径|label:'课包'/, 'student table should remove old purchase-date, trial-status, deal-path and package columns');
assert.doesNotMatch(source, /<th[^>]*>当前班次<\/th>/, 'student table should hide the current class column');
assert.doesNotMatch(source, /<th[^>]*>订场\/会员<\/th>/, 'student table should hide the booking membership column');
assert.match(fnBody('studentTableColumns'), /label:'备注',style:'width:280px'/, 'normal student note column should use the wider lead-note width');
assert.match(source, /label:'活跃状态'/, 'student table should show activity status');
assert.match(source, /label:'付费方式'/, 'student table should show payment mode');
assert.match(source, /label:'课包状态'/, 'student table should show package status');
assert.match(source, /label:'课包余额'/, 'student table should show package balance');
assert.match(source, /html:studentSortHeader\('lastLesson','最近上课'\)/, 'student table should show sortable recent lesson');
assert.match(source, /html:studentSortHeader\('completedLessons','累计上课'\)/, 'student table should show sortable cumulative lessons');
assert.match(source, /label:'累计课程付费'/, 'student table should show cumulative course paid amount');
assert.match(source, /label:'学员状态'/, 'student table should show lifecycle status');
assert.doesNotMatch(fnBody('studentTableColumns'), /label:'历史课时'/, 'student table should not show lesson volume as a standalone column');
assert.match(fnBody('studentTableColumns'), /label:'姓名'[\s\S]*label:'来源'[\s\S]*label:'类型'[\s\S]*label:'校区'[\s\S]*label:'活跃状态'[\s\S]*label:'付费方式'[\s\S]*label:'课包状态'[\s\S]*studentSortHeader\('packageLessons','课包余额'\)[\s\S]*studentSortHeader\('lastLesson','最近上课'\)[\s\S]*studentSortHeader\('completedLessons','累计上课'\)[\s\S]*label:'累计课程付费'[\s\S]*label:'学员状态'[\s\S]*label:'负责教练'[\s\S]*label:'备注'/, 'student table should use the agreed student value column order');
const trialStudentColumns = fnBody('studentTableColumns').match(/if\(studentListViewMode\(\)==='trial'\)return \[([\s\S]*?)\];/)?.[1] || '';
assert.doesNotMatch(trialStudentColumns, /label:'电话'/, 'trial student table should not show phone column');
const officialStudentColumns = fnBody('studentTableColumns').match(/return \[\s*\n    \{label:'姓名'[\s\S]*?\n  \];\n\}/)?.[0] || '';
assert.doesNotMatch(officialStudentColumns, /label:'电话'|课时\/课包/, 'official student table should not show phone or the old lesson/package label');
assert.match(source, /function studentIsHistoricalRosterRow\(/, 'historical student list should use a dedicated historical roster rule');
assert.match(source, /function studentIsActiveRosterRow\(/, 'active student list should use a dedicated active roster rule');
assert.match(fnBody('getStudentBaseList'), /studentListViewMode\(\)==='trial'\?studentIsHistoricalRosterRow\(s\):studentIsActiveRosterRow\(s\)/, 'student base list should switch between historical and active roster rules');
assert.match(fnBody('getStudentBaseList'), /includeAllRoster[\s\S]*return true[\s\S]*studentListViewMode\(\)==='trial'\?studentIsHistoricalRosterRow\(s\):studentIsActiveRosterRow\(s\)/, 'student search should be able to find students across active and trial rosters');
assert.match(fnBody('getFilteredStudents'), /getStudentBaseList\(\{includeAllRoster:!!q\.trim\(\)\}\)/, 'student keyword search should broaden the base roster');
assert.match(fnBody('getStudentBaseList'), /studentUnifiedViewRows\(\{includeSearchIndex:includeAllRoster\}\)/, 'student keyword search should broaden through the stable lightweight search index');
assert.match(fnBody('getStudentBaseList'), /isHiddenStudentProfile\(s\)/, 'student base list should hide merged and archived student profiles');
assert.match(source, /pager:\{infoId:'stuPagerInfo',pageSizeId:'stuPageSize',buttonsId:'stuPagerBtns'\}/, 'student pager should expose a page size selector host');
assert.match(source, /function setStudentPageSize\(/, 'student page should support 15, 50, and 100 row page sizes');
assert.match(source, /function renderStudentPagerControls\(/, 'student page should render compact pager controls');
assert.doesNotMatch(css, /#page-students \.tms-table-wrapper\{max-height:/, 'student table should inherit the global standard table height');
assert.match(source, /function renderStandardDataCards\(/, 'top data cards should have a shared render helper');
assert.match(source, /assets\/styles\/components\/data-cards\.css/, 'index should load shared data card styles');
assert.match(source, /assets\/styles\/components\/search\.css/, 'index should load shared search styles');
assert.match(source, /assets\/styles\/components\/buttons\.css/, 'index should load shared button styles');
assert.match(source, /assets\/styles\/components\/filters\.css/, 'index should load shared filter dropdown styles');
assert.match(source, /assets\/styles\/components\/tables\.css/, 'index should load shared table styles');
assert.match(source, /assets\/styles\/components\/modals\.css/, 'index should load shared modal styles');
assert.match(css, /\.modal\.modal-court\{[^}]*background:#F5F2F0[^}]*border-radius:16px[^}]*box-shadow:0 24px 48px -12px rgba\(0,0,0,\.18\)/, 'shared modal shell should use the standard surface, radius, and shadow');
assert.match(css, /\.modal\.modal-court\.modal-standard\{width:min\(560px,95vw\)\}/, 'standard business modals should use the 560px width');
assert.match(css, /\.modal\.modal-court\.modal-view\{width:min\(720px,95vw\)\}/, 'detail and audit modals should use the 720px width');
assert.match(css, /\.modal\.modal-court\.modal-complex\{width:min\(800px,95vw\)\}/, 'complex workflow modals should use the 800px width');
assert.match(css, /\.modal\.modal-court \.mhead\{[^}]*padding:28px 32px 16px/, 'shared modal header should use the standard padding');
assert.match(css, /\.modal\.modal-court \.mbody\{[^}]*padding:8px 32px/, 'shared modal body should use the standard padding');
assert.match(css, /\.modal\.modal-court \.mactions\{[^}]*padding:16px 32px[^}]*gap:12px[^}]*justify-content:flex-end[^}]*background:#F5F2F0[^}]*border-top:1px solid rgba\(230,225,220,\.6\)/, 'shared modal footer should use the standard action bar');
assert.match(css, /\.modal\.modal-court \.mclose\{[^}]*width:32px[^}]*height:32px[^}]*border-radius:50%[^}]*background:#FFFFFF/, 'shared modal close button should use the standard circular style');
assert.match(css, /\.modal\.modal-court \.tms-form-control\{[^}]*height:40px[^}]*border:1px solid #E6E1DC[^}]*background:#FFFFFF[^}]*color:#2D241F[^}]*font-size:14px[^}]*border-radius:8px/, 'shared modal form controls should use the standard input style');
assert.match(css, /\.modal\.modal-court \.tms-form-control:focus\{[^}]*border-color:#D19356[^}]*box-shadow:0 0 0 3px rgba\(209,147,86,\.15\)/, 'shared modal form controls should use the primary focus ring');
assert.match(css, /\.modal\.modal-court \.tms-data-field[\s\S]*\.modal\.modal-court \.tms-data-label[\s\S]*\.modal\.modal-court \.tms-data-value/, 'shared modal readonly data fields should have component styles');
assert.match(css, /\.tms-stats-row\{[^}]*display:grid[^}]*grid-template-columns:repeat\(auto-fit,minmax\(200px,1fr\)\)/, 'top data card row should adapt from five to six cards using 200px minimum columns');
assert.match(css, /\.tms-stat-card\{[^}]*height:100px[^}]*background-color:#FBF7F4[^}]*border:1px solid #E8DFD5[^}]*border-radius:8px/, 'top data cards should match the shared 200 by 100 visual standard');
assert.match(css, /\.tms-stat-card\{[^}]*padding:18px 16px 14px 22px/, 'top data cards should keep 22px left content padding');
assert.match(css, /\.tms-stat-card\{[^}]*box-shadow:0 8px 20px rgba\(0,0,0,\.08\)/, 'top data cards should use the shared shadow');
assert.match(css, /\.tms-stat-label\{[^}]*font-size:12px[^}]*color:#887565[^}]*margin-bottom:10px[^}]*font-weight:700/, 'top data card titles should use the shared label style');
assert.match(css, /\.tms-stat-value\{[^}]*font-size:21px[^}]*font-weight:500[^}]*color:#3B3026/, 'top data card numbers should use the shared value style');
assert.match(css, /\.tms-stat-percent,\s*\.court-stat-percent\{[^}]*font-size:10px[^}]*color:#A19080/, 'top data card percentages should use the shared small metric style');
assert.match(css, /\.tms-stat-sub\{[^}]*font-size:10px[^}]*color:#A19080[^}]*margin-top:8px/, 'top data card explanations should use the shared caption style');
assert.match(css, /#page-courts \.court-split-value>span:not\(\.court-stat-slash\)\{[^}]*color:#3B3026[^}]*font-weight:500/, 'court top paired stat numbers should keep the shared dark number color');
assert.match(css, /#page-finance \.finance-ledger-stats \.finance-main-number\{[^}]*color:#3B3026[^}]*font-weight:500/, 'finance top main stat numbers should keep the shared dark number color');
assert.match(css, /\.tms-search-wrapper\{[^}]*width:300px/, 'shared search component should use the standard 300px width');
assert.match(css, /\.tms-search-input\{[^}]*height:36px[^}]*border:1px solid #E8DFD5[^}]*background-color:#FBF7F4[^}]*color:#5A4C41[^}]*font-size:13px[^}]*font-weight:400/, 'shared search input should use the standard field style');
assert.match(css, /\.tms-search-input::placeholder\{[^}]*color:#A08E7E[^}]*font-size:13px[^}]*font-weight:400/, 'shared search placeholder should use the standard muted text style');
assert.match(css, /\.tms-search-icon\{[^}]*width:16px[^}]*height:16px[^}]*color:#A08E7E/, 'shared search icon should use the standard size and color');
assert.match(css, /\.tms-search-icon\{[^}]*M5\.77924 3\.57289[^}]*M11\.1648 7\.01855/, 'shared search icon should use the complete provided svg');
assert.doesNotMatch(source, /<svg class="tms-search-icon"[\s\S]*?<circle cx="11" cy="11" r="8">/, 'search fields should not keep old inline circle icons');
assert.match(css, /\.tms-toolbar-right \.tms-btn-primary\{[^}]*min-width:104px[^}]*width:auto[^}]*height:36px[^}]*padding:0 16px[^}]*background-color:#D19356[^}]*border-radius:6px[^}]*color:#FFFFFF[^}]*font-size:13px[^}]*font-weight:400/, 'toolbar add buttons should keep 104px as the four-character default and grow with longer text');
assert.match(css, /\.tms-toolbar-right \.tms-btn-primary::before\{[^}]*width:10px[^}]*height:10px/, 'toolbar add buttons should use the shared plus icon size');
assert.match(css, /\.tms-export-action,.tms-import-action\{[^}]*display:inline-flex[^}]*margin-right:10px[^}]*color:#F1E9E2[^}]*font-size:13px[^}]*font-weight:400/, 'toolbar export and import actions should use the shared text action style');
assert.match(css, /\.tms-import-action::before\{[^}]*515\.2 823\.68[^}]*220\.8 542\.72/, 'toolbar import action should use the standard down-arrow tray icon');
assert.match(css, /\.tms-export-action::before\{[^}]*783\.36 404\.48[^}]*512 145\.92/, 'toolbar export action should use the standard up-arrow tray icon');
assert.doesNotMatch(css, /\.tms-export-action::before\{transform:rotate\(180deg\)\}/, 'toolbar export action should not rotate the import icon');
assert.doesNotMatch(source, /id="page-students"[\s\S]*openPurchaseEntryModal\(\)[\s\S]*id="stuTbody"/, 'student page should remove the global package purchase entry');
assert.match(source, /class="tms-export-action" onclick="exportStudentCSV\(\)"[\s\S]*>导出<\/span>[\s\S]*class="tms-btn tms-btn-primary" onclick="openStudentModal/, 'student export should sit immediately before the add button as a shared text action');
assert.match(css, /\.tms-dropdown-display\{[^}]*height:36px[^}]*min-width:0[^}]*width:auto[^}]*padding:0 10px 0 12px[^}]*background-color:#FBF7F4[^}]*border:1px solid #E8DFD5[^}]*border-radius:6px[^}]*color:#A08E7E[^}]*font-size:13px[^}]*font-weight:400/, 'shared filter dropdown should use an adaptive width instead of a fixed 90px width');
assert.match(css, /\.tms-dropdown-display\{[^}]*display:inline-flex[^}]*align-items:center[^}]*gap:8px[^}]*line-height:36px/, 'shared filter dropdown should keep text vertically centered');
assert.match(css, /\.tms-dropdown-display::after\{[^}]*width:16px[^}]*height:16px[^}]*margin-left:0[^}]*transform:translateY\(-1px\)[^}]*background:url/, 'shared filter dropdown should vertically center the svg arrow icon');
assert.match(css, /\.tms-filters \.tms-dropdown\.has-value \.tms-dropdown-display\{[^}]*color:#C06031[^}]*font-weight:400/, 'selected filters should use the shared active state');
assert.match(css, /\.course-package-showcase-filters \.tms-dropdown\.has-value \.tms-dropdown-display\{[^}]*color:#C06031[^}]*font-weight:400/, 'course package filters should reuse the shared active state');
assert.match(css, /\.tms-pagination\{[^}]*font-size:12px[^}]*line-height:16px[^}]*color:#78716C/, 'shared pager footer should use the new 12px stone standard');
assert.match(css, /\.pager-divider\{[^}]*width:1px[^}]*height:12px[^}]*background:#E7E5E4[^}]*margin:0 12px/, 'pager footer should use the standard vertical divider before the page-size dropdown');
assert.match(css, /\.tms-pagination \.tms-dropdown-display\{[^}]*padding:2px 6px[^}]*border-radius:4px[^}]*color:#44403C[^}]*font-weight:400[^}]*transition:all 150ms ease/, 'page-size trigger should use the global regular-weight pager standard');
assert.match(css, /\.tms-pagination \.tms-dropdown-menu\{[^}]*bottom:calc\(100% \+ 6px\)[^}]*width:72px[^}]*background:rgba\(242,242,247,\.95\)[^}]*backdrop-filter:blur\(24px\)[^}]*box-shadow:0 8px 24px rgba\(0,0,0,\.12\)/, 'page-size popover should match the apple-like floating panel standard');
assert.match(css, /\.tms-pagination \.tms-dropdown\.open \.tms-dropdown-menu\{[^}]*animation:tmsPagerMenuIn 100ms ease/, 'page-size popover should fade and zoom in');
assert.match(css, /\.tms-pagination \.tms-dropdown-item\{[^}]*padding:6px 8px[^}]*font-size:12px[^}]*color:#292524/, 'page-size menu items should use the compact menu item standard');
assert.match(css, /\.tms-pagination \.tms-dropdown-check svg\{[^}]*width:14px[^}]*height:14px[^}]*stroke-width:3/, 'selected page-size item should render the heavier checkmark svg');
assert.match(css, /\.tms-page-btn\{[^}]*min-width:24px[^}]*height:24px[^}]*font-weight:400[^}]*border-radius:6px[^}]*color:#57534E/, 'shared page buttons should use the global regular-weight page button standard');
assert.match(css, /\.tms-page-btn\.active\{[^}]*background-color:#8C6D53[^}]*color:#FFFFFF[^}]*box-shadow:0 1px 2px rgba\(0,0,0,\.08\)/, 'active page button should use the brand color and subtle shadow');
assert.match(source, /class="tms-dropdown-check"[\s\S]*stroke-width="3"/, 'custom dropdown should render the selected checkmark through the shared component');
assert.match(source, /function renderPagerInfoHtml\(total\)\{\s*return `共 \$\{Number\(total\)\|\|0\} 条`;\s*\}/, 'pager info should keep total number the same style as surrounding text');
assert.doesNotMatch(source, /pager-strong/, 'pager info should not emphasize total count');
assert.match(source, /function renderPageSizeSelectorHtml\(id,pageSize,onchange\)[\s\S]*pager-divider[\s\S]*每页[\s\S]*renderStandardDropdownHtml\(id,String\(pageSize\),\[\{value:'15',label:'15'\},\{value:'50',label:'50'\},\{value:'100',label:'100'\}\][\s\S]*条/, 'pager page-size control should render text around a numeric-only dropdown');
assert.match(css, /\.tms-page-chevron\{[^}]*width:14px[^}]*height:14px[^}]*mask:url\("data:image\/svg\+xml/, 'pager arrows should use the filter chevron glyph at 14px');
assert.match(css, /\.tms-page-chevron-prev\{transform:rotate\(90deg\)\}[\s\S]*\.tms-page-chevron-next\{transform:rotate\(-90deg\)\}/, 'pager arrows should rotate the filter chevron left and right');
assert.doesNotMatch(source, /跳至 <input/, 'pager should not render jump-to-page controls');
assert.match(css, /\.tms-pagination \.tms-dropdown\.has-value \.tms-dropdown-display\{[^}]*font-weight:400/, 'student selected pager dropdown should use the global regular trigger weight');
assert.match(css, /\.tms-dropdown\.has-value \.tms-dropdown-display/, 'selected filters should look different from the default all state');
assert.doesNotMatch(css, /#page-students \.tms-filters \.tms-dropdown\.has-value \.tms-dropdown-display\{color:#C06031;font-weight:400\}/, 'student filter active state should come from the shared filter component');
assert.match(css, /\.tms-table-card\{[^}]*background-color:#E7DFD6[^}]*border:1px solid #E8DFD5[^}]*border-radius:8px/, 'shared table shell should use the standard border and radius');
assert.match(css, /\.tms-table-wrapper\{[^}]*background:#FBF7F4/, 'shared table scroll wrapper should mask the old card background behind sticky headers');
assert.match(css, /\.tms-table thead\{[^}]*position:sticky[^}]*top:0[^}]*z-index:130[^}]*background:#F1E9E2/, 'shared table header should stick as a full header layer while scrolling');
assert.match(css, /\.tms-table th\{[^}]*height:42px[^}]*background-color:#F1E9E2[^}]*color:#887565[^}]*font-size:12px[^}]*font-weight:400/, 'shared table header should use the standard size and color');
assert.match(css, /\.tms-table td\{[^}]*height:42px[^}]*background-color:#FBF7F4[^}]*color:#887565[^}]*font-size:12px[^}]*font-weight:400/, 'shared table rows should use the standard size and color');
assert.match(css, /\.tms-table th,.tms-table td\{[^}]*border-bottom:0\.5px solid #E7DFD6/, 'shared table separators should use the standard 0.5px line');
assert.match(css, /\.tms-table tbody tr:hover td\{[^}]*background-color:#F6EFE8/, 'shared table hover should use the standard hover color');
assert.match(css, /\.tms-table tbody tr\.is-selected td\{[^}]*background-color:#EFE7E2/, 'shared table selected rows should use the standard selected color');
assert.match(css, /\.tms-action-cell \.tms-action-link\+\.tms-action-link\{margin-left:10px\}/, 'shared table action links should keep 10px spacing');
assert.match(css, /\.tms-mini-bar\{[^}]*width:80px[^}]*height:16px/, 'shared mini progress bar should use the standard size');
assert.match(css, /\.tms-mini-bar-fill\{[^}]*background-color:#DFBAA0[^}]*border-radius:3px 0 0 3px/, 'shared mini progress fill should use the standard color and left radius');
assert.match(css, /\.tms-sort-icon\{[^}]*width:14px[^}]*height:14px/, 'shared sort icon should use the standard 14px size');
assert.match(css, /\.tms-sort-icon \.tms-sort-up::before\{[^}]*M7\.19619 2\.9702[^}]*background-color:#BDAB9B/, 'shared sort icon should use the provided svg path');
assert.match(css, /\.tms-sort-header\.asc \.tms-sort-up::before\{background-color:#887565\}/, 'ascending sort should highlight only the upper half');
assert.match(css, /\.tms-sort-header\.desc \.tms-sort-down::before\{background-color:#887565\}/, 'descending sort should highlight only the lower half');
assert.doesNotMatch(css, /\.tms-sort-up[^{}]*\{[^}]*border-bottom:4px solid/, 'shared sort icon should not use the old css triangle');
assert.match(source, /function cycleStudentSort\([\s\S]*stuSortDir='asc'[\s\S]*stuSortDir='desc'[\s\S]*stuSortKey='';stuSortDir='';/, 'student sortable headers should cycle asc, desc, and no sort');
assert.match(source, /function studentEmptyStateHtml\([\s\S]*没有匹配的学员[\s\S]*暂无学员[\s\S]*调整搜索或筛选后再试[\s\S]*点击右上角添加学员开始录入/, 'student empty state should distinguish filtered empty results from no data');
assert.match(source, /function renderTableSkeletonLoading\(/, 'table loading should render through the shared full-table skeleton helper');
assert.match(source, /function renderStudentTableLoading\([\s\S]*renderTableSkeletonLoading\('stuTbody',15,'学员数据加载中\.\.\.'\)/, 'student loading state should use the shared full-table skeleton');
assert.match(css, /\.tms-table-skeleton-state\{[^}]*position:relative[^}]*width:100%[^}]*background:#FBF7F4/, 'shared table skeleton should follow the full horizontal table width');
assert.doesNotMatch(css, /\.tms-table-skeleton-head\{/, 'shared table skeleton should not render a second header below the real table header');
assert.match(css, /\.tms-table-skeleton-row\{[^}]*height:42px[^}]*background:#FBF7F4/, 'shared table skeleton rows should match the standard row height');
assert.match(source, /function renderStudentTableError\([\s\S]*tms-table-error-state[\s\S]*加载失败[\s\S]*重新加载/, 'student load failure should render an inline retry state');
assert.match(source, /if\(pg==='students'\)renderStudentTableLoading\(\);/, 'student page should use the dedicated loading renderer');
assert.match(source, /if\(pg==='students'\)renderStudentTableError\(String\(e\.message\|\|e\)\);/, 'student page load failure should render the dedicated error state');
assert.match(css, /#page-students \.tms-empty-state\{[\s\S]*#page-students \.tms-state-action/, 'student empty, loading, and error states should have scoped standard styles');
assert.match(source, /function studentCompletedLessonCount\(/, 'student page should expose a cumulative completed lesson helper');
assert.doesNotMatch(fnBody('renderStudents'), /studentLessonVolumeText\(s\)/, 'student list should not render lesson volume as a standalone column');
assert.match(source, /function studentRecentLessonText\(/, 'student page should expose a recent lesson display helper');
assert.match(source, /function scheduleLessonUnits\(/, 'lesson stats should use schedule lesson units instead of row counts');
assert.match(source, /stuSortKey='lastLesson',stuSortDir='desc'[\s\S]*function ensureStudentDefaultSort\(\)[\s\S]*stuSortKey='lastLesson';stuSortDir='desc'/, 'student lists should default to latest lesson date descending');
assert.match(fnBody('studentLastLessonDate'), /detailRecentLessonDate|detailLessonRecordRows/, 'student latest lesson date should read backend unified lesson detail fields');
assert.match(source, /function scheduleDurationLessonUnits[\s\S]*Math\.round\(\(mins\/60\)\*10\)\/10/, 'web lesson units should derive a precise duration fallback from start and end time');
assert.match(source, /function scheduleLessonUnits[\s\S]*Math\.max\(count,durationUnits\)/, 'web lesson units should not let a stale lower lessonCount override a longer real lesson duration');
assert.match(source, /function studentLedgerLessonUnits[\s\S]*Math\.max\(consumed,planned\)/, 'web student lesson totals should not let stale package ledger units undercount the linked schedule duration');
assert.match(source, /studentCompletedLessonUnits[\s\S]*studentLedgerLessonUnits\(row,schedule\)/, 'web student cumulative lesson count should normalize package ledger lesson units');
assert.match(source, /function studentLedgerConsumedText\([\s\S]*packageBalanceUnitLabel[\s\S]*studentLessonDurationText[\s\S]*join\(' · '\)/, 'student lesson records should show count-based package consumption as count plus real lesson duration');
assert.match(source, /function studentLessonRecordKey\(/, 'student cumulative lessons should share one lesson identity key');
assert.match(source, /function studentCompletedLessonUnits[\s\S]*const lessonMap=new Map\(\)[\s\S]*studentConcreteLessonLedgerItems\(stu\)[\s\S]*studentLessonRecordShouldIncludeSchedule[\s\S]*return \[\.\.\.lessonMap\.values\(\)\]\.reduce/, 'student cumulative lessons should merge schedule and package consume records by lesson identity');
assert.match(source, /function studentPrimaryCoachText\(/, 'student list should render primary coach from the platform coach list only');
assert.match(source, /studentPrimaryCoachText\(s\)/, 'student list coach column should use the profile primary coach');
assert.match(fnBody('studentPrimaryCoachText'), /const coach=\(Array\.isArray\(coaches\)\?coaches:\[\]\)\.find\(item=>item\?\.status==='active'&&coachName\(item\?\.name\)===coachName\(stu\?\.primaryCoach\)\)/, 'student primary coach should be accepted only when it exists in the active coach list');
assert.match(fnBody('studentPrimaryCoachText'), /return coach\?coachName\(coach\.name\):'-'/, 'missing or non-coach primary coach should display the short dash');
assert.match(source, /const SOURCES=BUSINESS_TAXONOMY\.SOURCES/, 'student source options should use the global source dictionary');
assert.match(source, /function renderStandardCellText[\s\S]*const muted=!raw\|\|raw==='-'\|\|raw==='—'\|\|raw==='未开卡'/, 'empty list values should always render with the muted dash style');
assert.match(source, /function renderStandardEmptyText[\s\S]*return raw&&raw!=='—'\?raw:'-'/, 'empty values should render with the short dash');
assert.doesNotMatch(source, /<th>最后订场<\/th>/, 'student table should remove last-court as a primary list column in phase 2');
assert.doesNotMatch(source, /<th>关联账户<\/th>/, 'student table should replace account wording with booking membership summary');
assert.match(source, /const STUDENT_PACKAGE_STATUS_OPTIONS=\['未买过课包','课包有余额','课包即将耗尽','课包已用完'\]/, 'student package status options should match the agreed labels');
assert.doesNotMatch(fnBody('studentHasFormalPackage'), /studentHasNonTrialPackage|studentLifecycleStage/, 'package status should not treat single-pay formal students as package students');
assert.match(fnBody('studentHasFormalPackage'), /coursePurchaseCount/, 'package status should still recognize students who bought packages that are now used up');
assert.match(source, /const STUDENT_PAYMENT_MODE_OPTIONS=\['课包学员','单次付费学员','课包\+单次付费'\]/, 'student payment mode options should match the agreed labels');
assert.match(source, /const STUDENT_ACTIVITY_STATUS_OPTIONS=\['近30天活跃','31-90天活跃','91-180天沉默','180天以上沉睡','从未正式上课'\]/, 'student activity status options should match the agreed labels');
assert.match(source, /const STUDENT_LESSON_VOLUME_OPTIONS=\['历史课时30\+','历史课时50\+','历史课时100\+'\]/, 'student lesson volume options should match the agreed labels');
assert.match(source, /const STUDENT_LIFECYCLE_STATUS_OPTIONS=\['课包活跃中','课包待续费','已转单次付费','稳定单次付费','有余额未活跃'\]/, 'student lifecycle status options should match the global student tag standard');
assert.match(source, /function studentLabelDisplayText\(/, 'student labels should use one shared display-name helper');
assert.match(fnBody('studentLabelDisplayText'), /'近30天活跃':'近30天'[\s\S]*'31-90天活跃':'31~90天'[\s\S]*'历史课时30\+':'30\+'[\s\S]*'课包活跃中':'课包活跃'[\s\S]*'课包待续费':'待续费'/, 'student label helper should map backend labels to compact table tags');
assert.match(fnBody('studentLabelDisplayText'), /'课包\+单次付费':'课包\+单次'/, 'student label helper should shorten mixed payment mode labels');
assert.match(source, /function studentLabelTagClass\(/, 'student labels should use one shared color-class helper');
assert.match(fnBody('studentLabelTagClass'), /'180天以上沉睡':'tms-tag-priority-p0'/, 'sleeping activity labels should use the red tag color');
assert.match(fnBody('studentLabelTagClass'), /'单次付费学员':'tms-tag-course-partner'/, 'single-pay labels should use the purple tag color');
assert.match(fnBody('studentLabelTagClass'), /'课包\+单次付费':'tms-tag-business-type-adult'/, 'mixed payment labels should use the teal tag color');
assert.match(source, /function renderStudentLabelTag\(/, 'student table labels should render through one shared tag helper');
assert.match(fnBody('renderStudentLabelTag'), /raw==='-'\|\|raw==='—'[\s\S]*renderStandardCellText\(raw,false\)[\s\S]*studentLabelDisplayText\(raw\)[\s\S]*studentLabelTagClass\(raw\)/, 'empty student labels should stay plain dashes while real labels become tags');
assert.match(fnBody('studentPackageStatusText'), /packageStatusLabel/, 'package status label must come from backend unified teaching view');
assert.doesNotMatch(fnBody('studentPackageStatusText'), /studentFormalPurchaseRows|studentFormalEntitlementRows|studentUnifiedPackageListRows|studentPackageRemainingLessons|purchases|entitlements/, 'frontend must not recalculate package status from raw package rows');
assert.match(fnBody('studentPaymentModeText'), /paymentModeLabel/, 'payment mode label must come from backend unified teaching view');
assert.doesNotMatch(fnBody('studentPaymentModeText'), /studentFormalLessonRows|studentDirectFormalLessonRows|settlementType|paymentType|payType|schedules/, 'frontend must not infer payment mode from schedule payment fields');
assert.match(fnBody('studentActivityStatusText'), /activityStatusLabel/, 'activity status label must come from backend unified teaching view');
assert.match(fnBody('studentActivityStatusText'), /未\.\*上课\|从未|未\.\*上课\|从未[\s\S]*studentCompletedLessonCount/, 'frontend should guard stale test summaries that say no lesson while unified rows still contain completed lessons');
assert.doesNotMatch(fnBody('studentActivityStatusText'), /studentFormalLastLessonDate|studentFormalLessonRows|schedules/, 'frontend must not recalculate activity status from schedules');
assert.match(fnBody('studentLastLessonDate'), /studentDateOnOrBeforeNow/, 'student latest lesson display should ignore future cached lesson dates');
assert.match(fnBody('studentLessonVolumeText'), /lessonVolumeLabel/, 'lesson volume label must come from backend unified teaching view');
assert.doesNotMatch(fnBody('studentLessonVolumeText'), /studentFormalLessonCountValue|studentFormalLessonRows|schedules/, 'frontend must not recalculate lesson volume from schedules');
assert.match(source, /function studentCumulativeCoursePaidText\([\s\S]*cumulativeCoursePaidText/, 'student cumulative course paid text must come from backend unified teaching view');
assert.doesNotMatch(fnBody('studentCumulativeCoursePaidText'), /purchases|entitlements|schedules|financeNormalizedRows|cashDelta|recognizedRevenueDelta|amountPaid|actualAmount|paidAmount/, 'frontend must not calculate cumulative course paid amount from raw rows');
assert.match(fnBody('studentLifecycleStatusText'), /studentStatusLabel/, 'student status label must come from backend unified teaching view');
assert.doesNotMatch(fnBody('studentLifecycleStatusText'), /studentRecentDirectFormalLessonCount|studentHasDirectAfterPackageUsedUp|studentPackageStatusText|studentActivityStatusText/, 'frontend must not recalculate student status from local labels');
assert.match(source, /function studentPackageLessonMeta\(/, 'student package lesson summary should expose remaining and total lessons');
assert.match(fnBody('studentPackageLessonMeta'), /packageBalanceRemaining[\s\S]*packageBalanceTotal[\s\S]*detailPackageOrderRows[\s\S]*activeRows[\s\S]*remainingLessons[\s\S]*totalLessons/, 'student detail package metric should use backend balance fields and fall back to backend detail package rows');
assert.match(source, /function studentActiveEntitlementRows\([\s\S]*includes\(entitlementStatusText\(e\)\)[\s\S]*lessonValue\(e\.totalLessons\)>0/, 'student lesson/package summary should keep normal packages even when balance is 0');
assert.match(source, /function studentPackageLessonSummary\([\s\S]*`\$\{lessonQty\(e\.remainingLessons\)\}\/\$\{lessonQty\(e\.totalLessons\)\}`[\s\S]*\|\|meta\.text/, 'student lesson/package summary should show only balance numbers, not package names');
assert.match(source, /function studentPackageListHtml\(/, 'student list should render each package on its own line');
assert.match(fnBody('studentPackageListHtml'), /studentActiveEntitlementRows\(stu\)[\s\S]*map\(e=>`<div>\$\{esc\(studentPackageLineText\(e\)\)\}<\/div>`\)[\s\S]*join\(''\)/, 'student package list should keep one package per line');
assert.match(source, /function studentUnifiedPackageListHtml\(/, 'student list should render package names from the backend unified teaching view');
assert.match(source, /function studentUnifiedPackageBalanceHtml\(/, 'student list should render package balance from the backend unified teaching view');
assert.match(source, /function studentUnifiedCompletedLessonCount\(/, 'student list should render completed lessons from the backend unified teaching view');
assert.doesNotMatch(fnBody('studentListPackagePurchaseDate'), /studentTrialPackagePurchaseDate|studentPackagePurchaseDate/, 'student table purchase date should not recalculate package dates in the frontend');
assert.doesNotMatch(fnBody('studentSortValue'), /studentCompletedLessonUnits\(stu\)|studentPackageLessonMeta\(stu\)/, 'student table sorting should use backend unified package and lesson fields');
assert.match(fnBody('renderStudents'), /renderStandardTooltipText\(noteText,'tms-text-remark tms-text-remark-1 student-note-cell'\)/, 'normal student notes should clamp to one line');
assert.match(fnBody('renderStudents'), /studentActivityStatusText\(s\)[\s\S]*studentPaymentModeText\(s\)[\s\S]*studentPackageStatusText\(s\)[\s\S]*studentUnifiedPackageBalanceHtml\(s\)[\s\S]*studentRecentLessonText\(s\)[\s\S]*studentCompletedLessonCount\(s\)[\s\S]*studentCumulativeCoursePaidText\(s\)[\s\S]*studentLifecycleStatusText\(s\)/, 'student table rows should render the agreed backend student value columns');
assert.doesNotMatch(fnBody('renderStudents'), /studentPackageListHtml\(s\)|studentPackageListTooltip\(s\)|studentPackageLessonMiniBar\(s\)|studentUnifiedPackageListHtml\(s\)|studentUnifiedCompletedLessonCount\(s\)|studentCompletedLessonUnits\(s\)/, 'student table rows should not render old package-name columns or frontend-calculated cumulative lessons');
assert.match(source, /function openStudentDetail\(/, 'student list should provide a dedicated view action');
assert.match(fnBody('renderStudents'), /openStudentDetail\('\$\{s\.id\}'\)[\s\S]*openPurchaseModal\('\$\{s\.id\}'\)/, 'student list should keep only view and package actions');
assert.doesNotMatch(fnBody('renderStudents'), /openStudentModal\('\$\{s\.id\}'\)/, 'student list should not expose inline edit action');
assert.match(source, /modalClass:'modal modal-court modal-schedule-drawer modal-student-drawer'/, 'student detail should use the standard drawer shell');
assert.match(source, /renderDetailDrawerHero\(/, 'student detail should use a clearer header layout');
assert.match(source, /student-detail-metrics/, 'student detail should use summary metric cards');
assert.match(source, /function studentBenefitRows\(/, 'student detail should derive student benefit rows separately from package lessons');
assert.match(source, /studentDrawerCardHtml\('权益列表',studentBenefitListTableHtml\(s\),'student-benefit-section'/, 'student detail should show current benefits in the benefits tab');
assert.match(source, /openStudentBenefitPickerModal\('\$\{s\.id\}','supplement'\)[\s\S]*openStudentBenefitPickerModal\('\$\{s\.id\}','consume'\)/, 'student detail benefits tab should expose supplement and consume benefit actions');
assert.match(source, /const STUDENT_BENEFIT_TYPES=\[[\s\S]*benefitCode:'courtBooking'[\s\S]*benefitCode:'ballMachine'[\s\S]*\]/, 'student benefit actions should only support booking and ball-machine benefits');
assert.match(source, /student-package-card/, 'student detail should render package purchases as cards');
assert.match(source, /student-package-icon-svg/, 'student detail should use a folder-style package icon');
assert.match(source, /student-lesson-timeline/, 'student detail should render lesson records as a timeline');
assert.match(source, /student-reminder-section/, 'student detail should render reminder preferences in a compact block');
assert.match(source, /titleHtml:`服务号提醒偏好<span class="tms-tag \$\{statusClass\}">/, 'student detail should keep the reminder title row compact');
assert.doesNotMatch(source, /studentDetailSectionBlockHtml\('服务号提醒偏好'/, 'student detail should not wrap the reminder block with an extra section title');
assert.doesNotMatch(source, /student-reminder-status/, 'student detail should not show a redundant reminder status line');
assert.match(source, /openStandardDetailDrawer\(/, 'student detail should use the standard detail drawer');
assert.match(source, /openStudentDrawer\(\{titleHtml:`\$\{studentDetailHeroHtml\(s\)\}\$\{studentDetailTabsHtml\(studentDetailActiveTab\)\}`/, 'student detail should keep the profile summary in the drawer header');
assert.match(source, /服务号上课提醒/, 'student detail should expose the official account lesson reminder block');
assert.match(source, /复制绑定链接/, 'student detail should let ops copy a student-specific binding link');
assert.match(source, /name="studentReminderMode"/, 'student detail reminder frequency should use single-choice controls instead of loose action buttons');
assert.match(source, /48小时 \+ 24小时[\s\S]*仅24小时[\s\S]*自定义[\s\S]*不提醒/, 'student detail should expose standard, custom and off reminder frequency modes');
assert.match(source, /studentReminderCustomHours/, 'student detail should let ops set custom reminder hours');
assert.match(source, /复制绑定链接/, 'student detail should make copy binding link the primary action');
assert.match(source, /generateStudentReminderBindLink/, 'student page should call the backend to generate a bind link');
assert.match(source, /updateStudentReminderMode/, 'student page should let ops update student reminder frequency');
assert.match(source, /unbindStudentReminder/, 'student page should let ops unbind a student service account recipient');
assert.match(source, /officialAccountSubscribed/, 'student reminder bind page should read the service account subscribe status');
assert.match(source, /qrcode_for_gh_4c6b1a2fe3a9_258\.jpg/, 'student reminder bind page should show the official account QR code when follow is still needed');
assert.match(source, /你已关注「网球兄弟」服务号/, 'student reminder bind page should tell subscribed users they can close the page');
assert.match(source, /关注后无需重新绑定/, 'student reminder bind page should tell unsubscribed users to follow without rebinding');
assert.match(source, /这条链接已经完成绑定/, 'student reminder bind page should explain reused links in user-facing language');
assert.match(fnBody('renderStudents'), /openStudentDetail\('\$\{s\.id\}'\)[\s\S]*openPurchaseModal\('\$\{s\.id\}'\)/, 'student row should prioritize view before package purchase');
assert.doesNotMatch(fnBody('renderStudents'), /openStudentModal\('\$\{s\.id\}'\)/, 'student row should not expose inline edit');
assert.match(source, /function studentTeachingInfoHtml\(/, 'student detail should render teaching info block');
assert.match(source, /function studentOpsInfoHtml\(/, 'student detail should render operations info block');
assert.match(source, /function studentConsumptionInfoHtml\(/, 'student detail should render consumption relation block');
assert.match(source, /function studentLessonRecordHtml\(/, 'student detail should expose a dedicated lesson record helper');
assert.match(source, /function studentEntitlementLedgerHtml\(/, 'student detail should provide a dedicated lesson charge history helper');
assert.match(source, /function entitlementLedgerDisplayDate\(/, 'lesson charge history should display the real lesson or month date instead of import time');
assert.match(source, /function historicalImportedLedgerMonthKey\(/, 'lesson charge history should infer monthly import identity from sourceMonth or reason text');
assert.match(source, /reason\.match\(\s*\/\^历史导入\\s\*\(\\d\{1,2\}\)月消课\$\/\s*\)/, 'lesson charge history should fall back to parsing month from reason text when sourceMonth is missing');
assert.match(source, /dedupeEntitlementLedgerForDisplay/, 'lesson charge history should collapse duplicate ledger rows before display');
assert.match(source, /function historicalImportedLessonUnitsForStudent\(/, 'student page should expose a historical imported lesson helper');
assert.match(source, /STUDENT_PAGE_DEFERRED_REQUIREMENTS=\[\]/, 'student list should not automatically load heavy detail datasets after first paint');
assert.match(source, /STUDENT_DETAIL_REQUIREMENTS=\[\]/, 'student detail should not block on static shared datasets');
assert.match(source, /function ensureStudentDetailDatasets\(/, 'student detail should own the lazy detail loader');
assert.match(source, /function studentDetailLocalRowsReady\([\s\S]*if\(tab==='orders'\)return false[\s\S]*detailBenefitRows/, 'student package tab should load precise single-student detail instead of trusting lightweight rows');
assert.match(fnBody('studentDetailDatasetsReady'), /studentDetailDataReady\(id,studentDetailActiveTab\)[\s\S]*detailReady\|\|studentDetailLocalRowsReady\(id,studentDetailActiveTab\)/, 'student detail loader should skip the per-student request only after precise detail is loaded or for safe local tabs');
assert.match(fnBody('ensureStudentDetailDatasets'), /openStudentDetail\('\$\{id\}'\)[\s\S]*重试[\s\S]*renderDetailDrawerCard\('加载失败'/, 'student detail loading failure should render a retry state instead of staying in loading');
assert.match(source, /ensureStudentDetailData\(id,\{force:studentDetailTabNeedsDatasets\(studentDetailActiveTab\)\}\)/, 'student detail should load heavy detail facts by student id instead of the full purchases aggregate');
assert.doesNotMatch(source, /function studentEntitlementLedgerHtml[\s\S]*aggregateHistoricalMonthlyLedgerRows[\s\S]*function classScheduleSummaryHtml/, 'student consume history should show imported lesson rows one by one instead of monthly aggregation');
assert.doesNotMatch(fnBody('studentCompletedLessonCount'), /historicalImportedLessonUnitsForStudent|studentConcreteLessonLedgerItems|schedules\.filter/, 'student cumulative lessons should only read backend unified completedLessons');
assert.doesNotMatch(fnBody('studentDetailBasicTabHtml'), /student-consumption-section|消费与关联/, 'student basic detail should not show the consumption relation card');
assert.doesNotMatch(fnBody('studentDetailBasicTabHtml'), /关联线索|student-lead-section/, 'student basic detail should not show the linked lead card');
assert.match(source, /function studentDetailFieldHtml\(/, 'student detail should render short readonly values without form inputs');
assert.match(source, /function studentDetailFieldHtml\(label,value\)\{[\s\S]*return renderDetailDrawerField\(label,value\)/, 'student detail readonly fields should use the shared detail drawer field helper');
assert.match(source, /function studentDetailBlockHtml\(/, 'student detail should render long readonly content as information blocks');
assert.match(source, /function studentDetailBlockHtml\(label,html,options=\{\}\)[\s\S]*return renderDetailDrawerBlock\(label,html\)/, 'student detail long readonly blocks should use the shared detail drawer block helper');
assert.doesNotMatch(source, /function openStudentDetail[\s\S]*<input[\s\S]*function openStudentModal/, 'student detail modal should not use input controls for readonly values');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*<input[\s\S]*function studentOpsInfoHtml/, 'student teaching detail should not look editable');
assert.doesNotMatch(source, /function studentOpsInfoHtml[\s\S]*<input[\s\S]*function studentConsumptionInfoHtml/, 'student ops detail should not look editable');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*<input[\s\S]*function studentLinkedDetailHtml/, 'student consumption detail should not look editable');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*最近订场[\s\S]*function studentLinkedDetailHtml/, 'student consumption detail should remove duplicated recent booking field');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*关联说明[\s\S]*function studentLinkedDetailHtml/, 'student consumption detail should remove unclear duplicate linked account explanation');
assert.match(css, /\.modal\.modal-court \.tms-detail-grid[\s\S]*\.modal\.modal-court \.tms-detail-value[\s\S]*\.modal\.modal-court \.tms-detail-block/, 'student detail should use dedicated readonly display styles');
assert.match(css, /\.modal\.modal-court\.modal-student-drawer \.student-detail-shell\{[^}]*display:flex[^}]*flex-direction:column/, 'student detail header should sit inside the standard drawer');
assert.match(css, /\.modal\.modal-court\.modal-student-drawer \.student-detail-tabs\{[^}]*display:flex/, 'student detail should render tabs in the drawer title area');
assert.match(css, /\.student-package-icon\{[^}]*background:transparent/, 'student detail package icon should be a bare folder glyph');
assert.match(css, /\.student-package-actions\{[^}]*font-size:13px/, 'student package first-line status and actions should use the same 13px size as the title');
assert.match(css, /\.student-package-action-link\{[^}]*font-size:13px/, 'student package action links should use 13px in the first line');
assert.match(css, /\.student-package-meta\{[^}]*font-size:12px/, 'student package second line should use 12px');
assert.match(css, /\.student-reminder-section \.student-reminder-options\{[^}]*max-width:none/, 'student reminder options should use the compact drawer layout');
assert.match(css, /\.student-reminder-section \.student-reminder-copy-btn span\{font-size:13px;font-weight:400/, 'student reminder copy button should use a smaller label');
assert.match(css, /\.student-lesson-title\{[^}]*font-size:12px/, 'student lesson title should stay compact at 12px');
assert.match(css, /\.student-lesson-charge strong\{[^}]*font-size:12px[^}]*background:transparent/, 'student lesson charge badge should stay compact and unboxed');
assert.match(source, /function studentDetailBlockHtml\(label,html,options=\{\}\)[\s\S]*options\.hideEmpty&&studentDetailIsEmptyHtml\(html\)/, 'student detail should hide empty long blocks when they add no information');
assert.match(css, /\.modal\.modal-court\.modal-schedule-drawer \.schedule-detail-block\{[^}]*background:#FBFCFE/, 'student detail long content should use the drawer detail block style');
assert.doesNotMatch(fnBody('studentDetailBasicTabHtml'), /studentLeadSummaryHtml\(s\)|studentLeadJumpActionHtml\(s\)/, 'student basic detail should not render lead summary or lead jump action');
assert.doesNotMatch(fnBody('studentDetailBasicTabHtml'), /studentDetailBlockHtml\('线索摘要'/, 'student linked lead card should not render a duplicate lead summary label');
assert.match(source, /function studentDetailSectionHtml\(/, 'student detail should hide whole empty sections');
assert.doesNotMatch(source, /function studentOpsInfoHtml[\s\S]*最近活跃[\s\S]*function studentConsumptionInfoHtml/, 'student ops detail should remove duplicated recent active field');
assert.doesNotMatch(source, /function studentOpsInfoHtml[\s\S]*最近订场[\s\S]*function studentConsumptionInfoHtml/, 'student ops detail should remove recent booking from ops fields');
assert.match(source, /function studentConsumptionInfoHtml[\s\S]*if\(!linkedCourts\.length\)return '<div class="student-detail-empty">暂无关联订场账户<\/div>'/, 'student consumption detail should show an empty state when there is no linked account');
assert.match(source, /function studentConsumptionInfoHtml[\s\S]*student-linked-summary-list/, 'student consumption detail should only render linked account summary cards when linked data exists');
assert.doesNotMatch(source, /function studentConsumptionInfoHtml[\s\S]*studentDetailFieldHtml\('订场 \/ 会员'/, 'student consumption detail should not show unlinked booking membership field');
assert.match(source, /function studentLessonRecordTimeText\([\s\S]*slice\(11,16\)[\s\S]*-\$\{end\}/, 'student lesson records should show start and end time');
assert.match(fnBody('studentLessonRecordRows'), /Array\.isArray\(stu\?\.detailLessonRecordRows\)[\s\S]*return stu\.detailLessonRecordRows[\s\S]*return \[\]/, 'student lesson records should only render backend unified detail rows');
assert.doesNotMatch(fnBody('studentLessonRecordRows'), /studentConcreteLessonLedgerItems|schedules\.filter|studentLessonRecordKey|studentLessonRecordMergeKey/, 'student lesson records must not rescan schedules or package ledgers in the frontend');
assert.match(source, /function studentLessonRecordDetailSectionText\([\s\S]*rows\.slice\(index\+1\)[\s\S]*studentLessonSectionMarker[\s\S]*return `\[第\$\{startText\}/, 'backend unified student lesson detail rows should show lesson section numbers for historical rows');
assert.match(fnBody('studentLessonRecordHtml'), /const sectionText=studentLessonRecordDetailSectionText\(rows,index\);[\s\S]*const detailText=\[item\.courseType,item\.className\|\|item\.packageName\][\s\S]*join\(' '\)/, 'backend unified student lesson detail titles should show section and course info without duplicating time');
assert.match(fnBody('studentLessonRecordHtml'), /const title=\[sectionText,item\.lessonRelationText,detailText\]\.filter\(Boolean\)\.join\(' '\)/, 'authorized package lesson records should show who used whose package in the drawer');
assert.match(source, /function studentLedgerBalanceAfter\([\s\S]*laterDelta[\s\S]*Number\(ent\.remainingLessons\)[\s\S]*packageBalanceUnitLabel[\s\S]*return `剩余 \$\{lessonQty\(balance\)\}\/\$\{lessonQty\(ent\.totalLessons\)\} \$\{unit\}`/, 'student lesson records should show the package balance after that specific lesson, not the final balance on every row');
assert.match(source, /function studentLedgerBalanceAfter\([\s\S]*currentTime=studentEntitlementLedgerTimeText[\s\S]*studentEntitlementLedgerTimeText\(item,findScheduleForEntitlementLedgerRow/, 'student lesson record balances should compare concrete lesson times so same-day lessons do not share one balance');
assert.match(source, /function studentLessonRecordPackageText\([\s\S]*standardPackageLabel[\s\S]*扣\$\{studentLedgerConsumedText\(row,ent,schedule\)\}[\s\S]*studentLedgerBalanceAfter\(row,ent\)/, 'student lesson record package rows should show deduct amount, real duration, per-lesson balance, and package name');
assert.match(source, /function studentLessonRecordSectionText\([\s\S]*studentLessonSectionMarker[\s\S]*packageBalanceUnitLabel[\s\S]*第\$\{startText\}\$\{startText===endText\?'':`-\$\{endText\}`\}\$\{unit\}/, 'student lesson record rows should show whole and half lesson section numbers with the package unit');
assert.match(source, /function studentLessonRecordChargeHtml\([\s\S]*免费送课[\s\S]*扣\$\{studentLedgerConsumedText\(row,ent,schedule\)\}/, 'student lesson records should show free lessons without deducting package balance');
assert.match(source, /function studentLessonRecordChargeHtml\([\s\S]*<strong>扣\$\{studentLedgerConsumedText\(row,ent,schedule\)\}（\$\{lessonQty\(balance\?\.remaining\)\}\/\$\{lessonQty\(balance\?\.total\)\}\$\{unit\}）<\/strong>/, 'student lesson record package rows should bold deduct lessons and balance');
assert.match(source, /function studentCumulativeLessonSectionText\([\s\S]*studentEntitlementLedgerRows\(\{id:studentId\}\)[\s\S]*Number\(item\.lessonDelta\)<0[\s\S]*earlierDelta[\s\S]*function studentLessonRecordSectionText\([\s\S]*studentCumulativeLessonSectionText\(row,ent\)/, 'student lesson record section numbers should continue across multiple packages for the same student');
assert.doesNotMatch(fnBody('studentLessonRecordRows'), /existing\?\.type==='ledger'|lessonDelta:\(Number\(existing\.row\.lessonDelta\)|studentLedgerPreferredDisplayEntitlement|studentLessonRecordMergeKey/, 'student lesson row merging should live in the backend unified read model, not the frontend drawer');
assert.match(source, /function studentEntitlementSummaryHtml\([\s\S]*detailPackageOrderRows[\s\S]*student-package-card[\s\S]*student-package-title[\s\S]*student-package-status[\s\S]*已上 \$\{lessonQty\(used\)\}\$\{unit\}[\s\S]*剩余 \$\{lessonQty\(remaining\)\}\$\{unit\}[\s\S]*报名[\s\S]*priceText[\s\S]*ownerCoach/, 'student package purchase records should show package, status, actions, used lessons, remaining lessons, signup date, paid amount, and owner coach in two lines');
assert.match(source, /function studentLessonRecordHtml\([\s\S]*studentLessonRecordRows\(stu\)[\s\S]*studentLessonRecordPackageHtml[\s\S]*student-lesson-row[\s\S]*rows\.length>10[\s\S]*收起[\s\S]*展开全部/, 'student lesson record list should use package-record style rows and support expand all');
assert.match(source, /function toggleStudentLessonRecordExpanded\(studentId\)[\s\S]*openStudentDetail\(studentId\)/, 'student lesson record expand toggle should refresh the open detail modal');
assert.doesNotMatch(source, /studentDetailBlockHtml\('课包消耗记录'/, 'student detail should not render a second package consume list');
assert.doesNotMatch(source, /function studentEntitlementSummaryHtml[\s\S]*badge b-amber[\s\S]*function studentEntitlementPurchaseDate/, 'student package records should render course type as normal text');
assert.match(source, /function studentEntitlementSummaryHtml\([\s\S]*detailPackageOrderRows[\s\S]*statusText=row\.statusText\|\|'正常'/, 'student purchase records should use backend unified detail rows with backend-owned voided status filtering');
assert.doesNotMatch(source, /function studentEntitlementSummaryHtml\([\s\S]*e\.studentId===stu\?\.id[\s\S]*function studentEntitlementPurchaseDate/, 'student package detail should not rescan raw entitlements for its display rows');
assert.doesNotMatch(source, /function studentEntitlementSummaryHtml\([\s\S]*purchaseStatusText\(purchases\.find\(p=>p\.id===e\.purchaseId\)\|\|\{\}\)!=='已作废'[\s\S]*function studentEntitlementPurchaseDate/, 'student package detail should not rescan linked raw purchases for its display rows');
assert.match(source, /function studentEntitlementLedgerRows\(stu\)\{[\s\S]*entitlementStatusText\(e\)!=='已作废'[\s\S]*purchaseStatusText\(purchases\.find\(p=>p\.id===e\.purchaseId\)\|\|\{\}\)!=='已作废'/, 'student lesson records should ignore ledger rows from voided entitlements or purchases');
assert.match(source, /const priceText=`实付 ¥\$\{fmt\(paidAmount\)\}`/, 'student package records should only show paid amount and hide payable amount');
assert.match(source, /function studentEntitlementLedgerLineHtml\([\s\S]*studentEntitlementLedgerDeltaText\(row,ent,schedule\)[\s\S]*join\(' · '\)/, 'student package consume records should render one compact middle-dot line with signed lesson count');
assert.match(source, /function studentEntitlementLedgerTimeText\([\s\S]*\$\{date\} \$\{start\}-\$\{end\}/, 'student package consume records should show a lesson time range when available');
assert.match(source, /function findScheduleForEntitlementLedgerRow\([\s\S]*String\(s\.startTime\|\|''\)\.slice\(0,10\)!==date[\s\S]*function studentEntitlementLedgerLineHtml[\s\S]*studentEntitlementLedgerTimeText\(row,schedule\)/, 'student package consume records should use same-day schedule to fill missing start-end time');
assert.match(source, /function studentEntitlementLedgerSourceText\([\s\S]*sourceSheet[\s\S]*导入/, 'student package consume records should show the import source in the compact line');
assert.doesNotMatch(source, /function studentEntitlementLedgerHtml[\s\S]*扣减 \$\{lessonQty\(count\)\} 节[\s\S]*function classScheduleSummaryHtml/, 'student package consume records should not use the old two-line charge wording');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*当前状态[\s\S]*function studentOpsInfoHtml/, 'student detail should remove current status');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*当前班次[\s\S]*function studentOpsInfoHtml/, 'student detail should remove current class');
assert.doesNotMatch(source, /function studentTeachingInfoHtml[\s\S]*班次进度[\s\S]*function studentOpsInfoHtml/, 'student detail should remove class progress');
assert.match(source, /上课记录/, 'student detail should provide lesson record history in plain language');
assert.match(source, /已购课包/, 'student detail should present purchased packages in plain language');
assert.match(source, /扣课记录/, 'student detail should expose lesson charge history in the student detail');
assert.match(source, /课包订单/, 'student detail should label package purchase records clearly');
assert.match(source, /confirmDel\('\$\{s\.id\}','\$\{esc\(s\.name\)\}','student'\)[\s\S]*删除学员/, 'student detail should expose a delete action behind the standard confirmation flow');
assert.match(source, /function studentDeleteCardHtml\(s\)[\s\S]*confirmDel\('\$\{s\.id\}','\$\{esc\(s\.name\)\}','student'\)[\s\S]*studentDrawerCardHtml\('删除学员'[\s\S]*function studentDetailBasicTabHtml\(s\)[\s\S]*studentReminderInfoHtml\(s\)\}\$\{studentDeleteCardHtml\(s\)\}/, 'student detail should show delete student as its own card below service account reminder');
assert.doesNotMatch(source, /openStudentDrawer\(\{titleHtml:`\$\{studentDetailHeroHtml\(s\)\}\$\{studentDetailTabsHtml\(studentDetailActiveTab\)\}\$\{studentDetailDeleteActionHtml\(s\)\}`/, 'student delete action should not sit in the drawer tab header');
assert.match(source, /DELETE_STUDENT_HISTORY/, 'student delete requests should carry the backend confirmation marker');
assert.match(source, /学员会隐藏归档；课包、上课、权益、财务和其他历史数据都会保留/, 'student delete confirmation should explain archive instead of destructive history deletion');
assert.doesNotMatch(source, /完全空白误录会删除/, 'student delete confirmation should not promise physical deletion from the management page');
assert.doesNotMatch(source, /及其课包订单、课包余额、扣课记录、单人排课、课后反馈和学员权益记录，并清理订场\/线索关联/, 'student delete confirmation must not promise destructive history deletion');
assert.match(fnBody('applyStudentCascadeDeleteResult'), /result\.archived&&result\.student[\s\S]*students=students\.map[\s\S]*return/, 'student archived delete result should only update the hidden student profile locally');
assert.doesNotMatch(source, /课包消耗记录/, 'student detail should avoid a duplicate package consume record block');
assert.match(source, /如需调整关联关系，请到「订场\/会员」页面编辑订场用户。/, 'student detail should explain where to adjust linked booking accounts');
assert.doesNotMatch(source, /function openStudentModal[\s\S]*studentLinkedDetailHtml\(s\)/, 'student edit modal should not embed linked detail summary anymore');
assert.match(source, /function studentBasicInfoFormHtml[\s\S]*姓名 \*[\s\S]*手机号[\s\S]*负责教练[\s\S]*学员类型[\s\S]*来源[\s\S]*所在校区[\s\S]*备注/, 'student edit modal should keep base profile fields and expose primary coach');
assert.doesNotMatch(fnBody('studentBasicInfoFormHtml'), /来源线索摘要|student-lead-summary-readonly|studentLeadSummaryHtml\(s\)|活动范围|s_range/, 'student edit modal should not show linked lead summary or activity range');
assert.doesNotMatch(fnBody('studentBasicInfoFormHtml'), /<label class="tms-form-label">线索来源<\/label><div class="finput tms-form-control tms-readonly-text">/, 'student edit lead summary should not look like an editable input');
assert.match(fnBody('studentDetailBasicTabHtml'), /const saveActions=`<div class="schedule-detail-card-actions"><button type="button" class="schedule-detail-action muted"[\s\S]*取消[\s\S]*保存[\s\S]*<\/div>`/, 'student drawer edit cancel and save should sit together as one action group');
assert.doesNotMatch(source, /placeholder="13800138000"/, 'phone inputs should not show example numbers that look prefilled');
assert.match(source, /const campusOptions=studentCampusOptions\(\);/, 'student edit modal should build campus options through the shared student helper');
assert.match(source, /function studentCampusOptions\(/, 'student edit modal should expose all loaded campuses through a helper');
assert.match(source, /renderStandardDropdownHtml\('s_primaryCoach'/, 'student edit modal should provide a primary coach selector');
assert.match(source, /const data=\{name,phone,primaryCoach:/, 'student save should submit primary coach');
assert.match(source, /function openStudentModal[\s\S]*openStudentDrawer\(/, 'student edit modal should reuse the standard student drawer');
assert.doesNotMatch(source, /function openStudentModal[\s\S]*setCourtModalFrame\(/, 'student add and edit modals should not use legacy modal shell');
assert.match(source, /选择课包 \*[\s\S]*归属教练[\s\S]*支付日期[\s\S]*系统价格[\s\S]*实收金额[\s\S]*支付方式/, 'purchase modal should arrange package, owner, payment date, price and pay method in compact rows');
assert.match(source, /实际成交价与系统价格不一致时必填/, 'purchase modal should require an override reason when final price differs');
assert.match(source, /tms-readonly-text/, 'student detail long readonly fields should use padded readonly text blocks');
assert.match(source, /purchase-coach-picker[\s\S]*purchase-notes-row/, 'purchase allowed coach picker should reuse the student picker block style');
assert.match(source, /function purchaseAllowedCoachChecks[\s\S]*tms-checkbox-wrap[\s\S]*tms-checkbox/, 'purchase allowed coach options should use the standard checkbox row style');
assert.match(source, /\{key:'purchases'[\s\S]*columns:\[\{label:'支付日期',style:'width:100px;padding-left:20px'\},\{label:'姓名',style:'width:80px'\},\{label:'课包',style:'width:260px'\},\{label:'应收',style:'width:70px'\},\{label:'实收',style:'width:70px'\},\{label:'差价',style:'width:70px'\},\{label:'余额',style:'width:80px'\},\{label:'状态',style:'width:64px'\},\{label:'归属教练',style:'width:78px'\},\{label:'支付方式',style:'width:78px'\}/, 'purchase record table should follow the current column order');
assert.match(source, /pager:\{infoId:'purPagerInfo',pageSizeId:'purPageSize',buttonsId:'purPagerBtns'\}/, 'purchase record page should expose the standard pager');
assert.match(source, /function onPurchaseFilterChange\(\)[\s\S]*purPackageFilterValue=document\.getElementById\('purPackageFilter'\)\?\.value\|\|''[\s\S]*purPage=standardListFirstPage\(\)[\s\S]*renderPurchases\(\)/, 'purchase filters should store the selected package and reset pagination through the standard list flow');
assert.match(source, /function purchaseSelectedPackageFilter\(\)[\s\S]*purPackageFilterValue\|\|document\.getElementById\('purPackageFilter'\)\?\.value\|\|''/, 'purchase package filter should survive navigation before the dropdown is rendered');
assert.match(source, /function renderPurchasePagerControls\(/, 'purchase page should render compact pager controls');
assert.match(source, /pager\.style\.display=isMobileList\?'none':\(total>purPageSize\?'flex':'none'\)/, 'purchase pager should hide on H5 and still hide on desktop when the filtered result fits on one page');
assert.doesNotMatch(css, /#page-purchases \.tms-table-wrapper\{max-height:/, 'purchase table should inherit the global standard table height');
assert.match(css, /\.tms-page-btn\{[^}]*min-width:24px[^}]*height:24px[^}]*font-weight:400[^}]*border-radius:6px/, 'purchase pager buttons should inherit the shared regular-weight page button style');
assert.doesNotMatch(css, /\.tms-page-jump input/, 'purchase pager should not keep jump input styles');
assert.match(source, /function withStandardFilterCounts\(/, 'standard dropdown filters should support count labels for all pages');
assert.match(source, /function withLinkedFilterCounts\(/, 'standard dropdown filters should support linked count labels for all pages');
assert.match(source, /function renderStandardOptionLabel\(/, 'shared dropdown renderer should format option counts centrally');
assert.match(source, /filterHostIds:\['stuTypeFilterHost','stuSourceFilterHost','stuTagFilterHost','stuCoachFilterHost'\]/, 'student toolbar should expose compact common filters plus one student tag cascader');
assert.match(source, /renderStudentToolbarFilters[\s\S]*withLinkedFilterCounts\(\[[\s\S]*key:'type'[\s\S]*key:'source'[\s\S]*key:'coach'/, 'student toolbar common filters should keep linked count labels');
assert.match(source, /renderStudentToolbarFilters[\s\S]*options:\[\{value:'',label:'全部',emptyDisplay:'来源'\},\.\.\.studentSourceOptions\(\)\][\s\S]*match:\(s,value\)=>studentSourceText\(s\)===value/, 'student source filter should use normalized source options and matching');
assert.doesNotMatch(source, /stuTrialStatusFilterHost|stuDealPathFilterHost|thirdFilterIsTrial/, 'student toolbar should not keep old trial-status or deal-path filter hosts');
assert.match(fnBody('getFilteredStudents'), /if\(!studentTagFilterMatches\(s\)\)return false/, 'student tag cascader selections should apply to the student list');
assert.match(source, /renderStandardGroupedFilterHtml\(studentTagGroupedFilterConfig\(baseRows\)\)/, 'student tag cascader should reuse the standard grouped filter component');
assert.match(fnBody('studentTagGroupedFilterConfig'), /label:studentLabelDisplayText\(value\)/, 'student tag cascader should display the same short labels as the table cells while keeping raw filter values');
assert.match(fnBody('renderStudents'), /if\(!options\.skipToolbar\)renderStudentToolbarFilters\(\)/, 'student tag cascader updates should avoid rebuilding the open dropdown');
assert.match(css, /\.tms-grouped-filter-menu\{[^}]*width:340px[^}]*max-width:calc\(100vw - 40px\)/, 'student tag cascader menu should use the shared bounded dropdown panel');
assert.match(css, /\.tms-grouped-filter-columns\{[^}]*grid-template-columns:132px minmax\(0,1fr\)/, 'student tag cascader should use the shared two-column grouped filter layout');
assert.match(css, /\.tms-grouped-filter-group\{[^}]*display:flex[^}]*justify-content:space-between/, 'student tag cascader first level should render group names through the shared style');
assert.match(css, /\.tms-grouped-filter-options\{[^}]*display:flex[^}]*flex-direction:column/, 'student tag cascader second level should render options through the shared style');
assert.match(css, /\.tms-grouped-filter-option\{[^}]*grid-template-columns:16px minmax\(0,1fr\)/, 'student tag cascader options should align checkbox and label through the shared style');
assert.match(fnBody('studentHasActiveSearchOrFilter'), /studentTagFilterCount\(\)/, 'student empty state should treat the student tag cascader selections as active filters');
assert.doesNotMatch(fnBody('renderStudents'), /renderStandardBusinessTag\(studentTrialPathStatusText\(s\),'stage'\)|studentDealPathText\(s\)/, 'student rows should not render old trial-status or deal-path fields');
assert.match(fnBody('renderStudents'), /renderStandardCellText\(studentSourceText\(s\),false\)[\s\S]*renderStudentLabelTag\(studentActivityStatusText\(s\)\)[\s\S]*renderStudentLabelTag\(studentPaymentModeText\(s\)\)[\s\S]*renderStudentLabelTag\(studentPackageStatusText\(s\)\)[\s\S]*renderStudentLabelTag\(studentLifecycleStatusText\(s\)\)/, 'student list should keep source as text and render student status fields as standardized tags');
assert.doesNotMatch(fnBody('renderStudents'), /renderStandardBusinessTag\(studentSourceText\(s\),'source'\)/, 'student source should not render as a tag in any student list');
assert.match(source, /function renderPurchases[\s\S]*renderPurchasePagerControls\(total,pages\)/, 'purchase table should keep using the standard pager renderer');
assert.match(source, /purchaseEntitlementMiniBar\(ent\)/, 'purchase balance column should reuse the mini balance bar style');
assert.match(source, /function studentEntitlementSummaryHtml\([\s\S]*detailPackageOrderRows/, 'student package purchase records should use backend unified order rows');
assert.match(source, /function sameCampusValue\(/, 'campus matching should use one helper so shunyi_mapo and 顺义马坡 stay one campus');
assert.match(source, /studentCampusValuesForList\(stu\)\.some\(value=>sameCampusValue\(value,campus\)/, 'student page campus filter should treat shunyi_mapo and 顺义马坡 as the same campus');
assert.match(source, /const purchaseDate=String\(row\.purchaseDate\|\|''\)\.slice\(0,10\);/, 'student package purchase records should use the backend unified purchase date');
assert.doesNotMatch(source, /const purchaseDate=e\.purchaseDate\|\|purchase\.purchaseDate\|\|String\(e\.createdAt\|\|purchase\.createdAt\|\|''\)\.slice\(0,10\);/, 'student package purchase date should not fall back to import createdAt');

console.log('student page view tests passed');
