const assert = require('assert');
const fs = require('fs');
const path = require('path');

const config = JSON.parse(fs.readFileSync(path.join(__dirname, '../vercel.json'), 'utf8'));
const apiSource = fs.readFileSync(path.join(__dirname, '../api/index.js'), 'utf8');
const feishuScheduleSyncSource = fs.readFileSync(path.join(__dirname, '../server/feishu-schedule-sync-routes.js'), 'utf8');
const feishuDailyWorkflow = fs.readFileSync(path.join(__dirname, '../.github/workflows/feishu-daily-report.yml'), 'utf8');
const officialRemindersWorkflow = fs.readFileSync(path.join(__dirname, '../.github/workflows/official-account-reminders.yml'), 'utf8');
const officialDigestsWorkflow = fs.readFileSync(path.join(__dirname, '../.github/workflows/official-account-daily-digests.yml'), 'utf8');
const feishuCoachDigestsWorkflow = fs.readFileSync(path.join(__dirname, '../.github/workflows/feishu-coach-daily-digests.yml'), 'utf8');
const feishuScheduleSyncWorkflow = fs.readFileSync(path.join(__dirname, '../.github/workflows/feishu-schedule-sync.yml'), 'utf8');
const operationsSnapshotWorkflow = fs.readFileSync(path.join(__dirname, '../.github/workflows/operations-snapshot-rebuild.yml'), 'utf8');
const matchKeepaliveWorkflowPath = path.join(__dirname, '../.github/workflows/match-supabase-keepalive.yml');

assert.strictEqual(config.crons, undefined, 'Vercel 不配置 Cron，定时任务统一走 GitHub Actions');
assert.strictEqual(fs.existsSync(matchKeepaliveWorkflowPath), true, '约球 Supabase 保活应由 GitHub Actions 定时触发，不使用 Vercel Cron');

assert.match(feishuDailyWorkflow, /workflow_dispatch:/, '飞书排课日报应保留手动触发入口');
assert.doesNotMatch(feishuDailyWorkflow, /cron:/, '飞书排课日报不应再使用 GitHub Actions 定时触发');
assert.match(officialRemindersWorkflow, /\/api\/cron\/official-account-coach-reminders/, '服务号教练课前提醒应由 GitHub Actions 单独触发');
assert.match(officialRemindersWorkflow, /\/api\/cron\/official-account-student-reminders/, '服务号学员课前提醒应由 GitHub Actions 单独触发');
assert.doesNotMatch(officialRemindersWorkflow, /\/api\/cron\/official-account-feedback-reminders/, '服务号课前提醒 workflow 不应被课后反馈提醒拖慢');
assert.match(officialDigestsWorkflow, /\/api\/cron\/official-account-daily-digests/, '服务号次日课表应由 GitHub Actions 触发');
assert.match(feishuCoachDigestsWorkflow, /cron: '0 12 \* \* \*'/, '飞书教练私发次日排课应每天北京时间 20:00 触发');
assert.match(feishuCoachDigestsWorkflow, /\/api\/cron\/feishu-coach-daily-digests/, '飞书教练私发次日排课应由 GitHub Actions 触发');
assert.match(feishuCoachDigestsWorkflow, /FEISHU_COACH_DIGEST_PHONE_OVERRIDES/, '飞书教练私发次日排课应支持用 GitHub Secret 覆盖缺失手机号');
assert.match(feishuCoachDigestsWorkflow, /FEISHU_COACH_DIGEST_OPEN_ID_OVERRIDES/, '飞书教练私发次日排课应支持用 GitHub Secret 覆盖 open_id');
assert.match(apiSource, /x-feishu-coach-digest-phone-overrides/, '飞书教练私发次日排课接口应读取安全请求头里的手机号覆盖配置');
assert.match(apiSource, /x-feishu-coach-digest-open-id-overrides/, '飞书教练私发次日排课接口应读取安全请求头里的 open_id 覆盖配置');
assert.match(feishuScheduleSyncWorkflow, /cron:\s*'0 0,10 \* \* \*'/, '飞书排课表同步应在北京时间 08:00、18:00 各触发一次');
assert.match(feishuScheduleSyncWorkflow, /\/api\/cron\/feishu-schedule-sync/, '飞书排课表同步应由 GitHub Actions 触发');
assert.match(operationsSnapshotWorkflow, /cron: '5,20,35,50 \* \* \* \*'/, '经营分析快照应由 GitHub Actions 高频重建');
assert.match(operationsSnapshotWorkflow, /node scripts\/rebuild-operations-snapshot\.js --write --view coach/, '经营分析教练人效快照 workflow 应优先重建轻量教练视图');
assert.doesNotMatch(operationsSnapshotWorkflow, /--process-queued/, '经营分析教练人效主刷新链路不应被历史队列拖慢');
assert.match(operationsSnapshotWorkflow, /DIAG_TOKEN:\s*\$\{\{\s*secrets\.DIAG_TOKEN\s*\|\|\s*secrets\.FLOWTENNIS_ADMIN_TOKEN\s*\}\}/, '经营分析快照 workflow should reuse FLOWTENNIS_ADMIN_TOKEN when DIAG_TOKEN is not configured');
const matchKeepaliveWorkflow = fs.readFileSync(matchKeepaliveWorkflowPath, 'utf8');
assert.match(matchKeepaliveWorkflow, /cron: '0 2 \* \* \*'/, '约球 Supabase 保活应每天北京时间 10:00 触发');
assert.match(matchKeepaliveWorkflow, /\/api\/match-diag/, '约球 Supabase 保活应访问会执行 SELECT 1 的 match-diag 接口');
assert.match(matchKeepaliveWorkflow, /"status":"ok"/, '约球 Supabase 保活应校验数据库探活成功');
assert.match(apiSource, /\/cron\/feishu-daily-report/, 'API 应提供排课日报入口');
assert.match(apiSource, /FEISHU_DAILY_REPORT_WEBHOOK/, '排课日报接口应读取飞书日报 webhook 环境变量');
assert.match(apiSource, /\/cron\/official-account-daily-digests/, 'API 应提供服务号次日排课入口');
assert.match(apiSource, /\/cron\/official-account-coach-reminders/, 'API 应提供服务号教练课前提醒入口');
assert.match(apiSource, /\/cron\/official-account-student-reminders/, 'API 应提供服务号学员课前提醒入口');
assert.match(apiSource, /\/cron\/official-account-feedback-reminders/, 'API 应提供服务号课后反馈提醒入口');
assert.match(apiSource, /\/cron\/official-account-reminders/, 'API 应保留服务号课前提醒兼容入口');
assert.match(apiSource, /\/cron\/feishu-coach-daily-digests/, 'API 应提供飞书教练私发次日排课入口');
assert.doesNotMatch(apiSource, /\/cron\/operations-snapshot\/rebuild/, 'API 不应提供会超时的经营分析快照重建入口');
assert.match(apiSource, /handleFeishuScheduleSyncRoutes/, 'API 应挂载飞书排课表同步路由');
assert.match(feishuScheduleSyncSource, /\/cron\/feishu-schedule-sync/, 'API 应提供飞书排课表同步入口');

console.log('vercel config tests passed');
